### ISSUE TITLE
Making copies of directories in path

### ISSUE THREAD

**Issue by DataScientist28** [odeke-em/drive#1006]
I’m having a really weird issue that the push function is making as many directories as files after the initial directory. 

So if I try to just push the following directories only:

```
$ drive push -directories test/
Resolving...
+ /test
+ /test/MACS
+ /test/MACS/test
+ /test/MACS/q_001
+ /test/RData
+ /test/fastq
+ /test/fastq/trimmed
+ /test/fastq/trimmed/fastqc
+ /test/fastq/test
+ /test/BAM
+ /test/BigWig
```
 

It creates 2 fastq and MACS directories because there are two sub directories within that path. Here is the :

<img width="567" alt="screen shot 2018-03-13 at 4 32 42 pm" src="https://user-images.githubusercontent.com/25513928/37420521-35fe38c2-2774-11e8-8c9a-2f1f8de4a188.png">

I've tried to look through the help and I can't find any reason why this is happening. Any idea why this would be?

**Comment by weidenrinde** [comment]
I am affected, too. But not for all directories... Perhaps a regression?

**Comment by aprsa** [comment]
+1 -- same issue with 0.3.9.1.

In addition, if I try `drive clashes` to see what the issue is, it spins indefinitely.

**Comment by odeke-em** [comment]
Hello there @DataScientist28 and @aprsa for the reports and for the patience.

I finally got time to work on this in #1019 by making only one goroutine exclusively invoke remoteMkdirAll, hence this problem should no longer exist with a fresh install from master.

Thank you for bearing with me and for using drive!
