### ISSUE TITLE
push: duplicates created when freshly pushing from non-existent paths

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/drive#1016]
I just encountered this error when pushing from a non-existent directory three children away from the parent ie.
`root --> a --> b --> Fingerprinting --> [doc1.pdf, doc2.pdf, doc3.pdf]`
and on pushing it produced this output
<img width="501" alt="screen shot 2018-06-15 at 1 16 32 pm" src="https://user-images.githubusercontent.com/4898263/41487741-9fff716e-709e-11e8-9b7a-7de37fe5ff52.png">

This used to work, I've certainly previously been able to push such files with non-existent directories.

**Comment by krntz** [comment]
Getting this as well. Added a new folder to root, pushed it, got four folders that are either empty or contain a seemingly random subset of the files inside.

**Comment by odeke-em** [comment]
Hello there @krntz, thank you for the confirmation and for using drive!

I pushed up a PR #1019 and if you freshly install from master, this problem should no longer exist.
