### ISSUE TITLE
Google Service Account credentials | --service-account-file returns error message

### ISSUE THREAD

**Issue by drupalista-br** [odeke-em/drive#1017]
Hi there,

I've ran `$ drive init --service-account-file client_secret.json ~/gdrive` and it returns the message `google: read JWT from JSON credentials: 'type' field is "" (expected "service_account")`

[Click here](https://drive.google.com/open?id=12Mnft8fqMTtqenq_eyIrgSf6TypPzmAn) to see my **client_secret.json** I have downloaded from Google API Console. Yes, I made sure Drive API is enabled.

The **credentials.json** is created into ~/gdrive/.gd [Click here](https://drive.google.com/open?id=1xtr0HqXBwP-8OUQJksTJlABks-6O1BRc) to see how it looks like.

**Comment by drupalista-br** [comment]
I have figured it out. I was getting the wrong json file.

I should have gotten the json from https://console.developers.google.com/iam-admin ( click on the Service Account menu option ).

**Comment by jimhavrilla** [comment]
thanks @drupalista-br. this really helped me out in using [gdrive](https://github.com/gdrive-org/gdrive)! also, I'm betting this drive CLI as well (looks pretty slick)
