### ISSUE TITLE
How to push new files only?

### ISSUE THREAD

**Issue by huangzonghao** [odeke-em/drive#1036]
I am holding a big folder in google drive that I don't want to keep a local copy on my computer. And periodically I need to upload some new files to the cloud. So I am wondering if there is a way that we can push only the new files to the drive without regarding local deleted files? Because if we just call `drive push`, the files not exist in local folder will also be deleted from the cloud. So it would be great if we can configure the push tool to figure out the files in local folder but not in the remote folder, and then push those files only.

**Comment by CountryBumkin** [comment]
Study the instructions on these options and then test on  on some disposable data.

drive push -no-clobber
drive push -exclude-ops "delete" sensitive_files

Regards CB
