### ISSUE TITLE
impossible to use -service-account-file parameter 

### ISSUE THREAD

**Issue by gleb-grigoriev** [odeke-em/drive#1038]
Hi.
When Im trying to run the following command:
drive init --service-account-file credentials.json ~/gdrive
I receive "flag provided but not defined: -service-account-file"  error.
I`m trying to use drive utility in docker and installed it according readme guide from ubuntu repository.

**Comment by kubies** [comment]
I have the same issue

**Comment by cydgit** [comment]
Same problem here.

**Comment by rodrigodalri** [comment]
same problem here

**Comment by odeke-em** [comment]
Howdy @gleb-grigoriev @kubies @cydgit @rodrigodalri! My apologies for the late reply! I don't maintain the Ubuntu installations so I can't verify, but that flag is definitely defined in code and seems like you might be running an old version, and even on a version of drive defined in 2018, it works
```shell
$ drive version
drive version: 0.3.9.1
Commit Hash: 'e2932d8e5e259e86abdf902fbacce756daebf260'
Go Version: devel +cdce824850 Fri Jun 29 21:45:46 2018 +0000
OS: darwin/amd64
BuildTime: 2018-06-30 16:19:15.125265 -0600 MDT m=+0.013494687
```

Implemented almost 4 years ago in PR https://github.com/odeke-em/drive/pull/882.

I've cut a brand new release and upload binaries with their signatures and that code has that flag defined https://github.com/odeke-em/drive/releases/tag/v0.4.0.

Thanks again for the interaction, and for using drive!
