### ISSUE TITLE
Need -y flag

### ISSUE THREAD

**Issue by arthuro555** [odeke-em/drive#1039]
I want to automate some things but I can't use .sh in background because of the confirmation message [Y/n] can you add a -y flag or something like that pls?

**Comment by CountryBumkin** [comment]
Study the instructions for this option...
To push without user input (i.e. without prompt)
drive push -quiet
or
drive push -no-prompt

In the general case use this...
https://www.computerhope.com/unix/yes.htm

regards CB

**Comment by arthuro555** [comment]
I'm so sorry for that stupid question and thanks.
