### ISSUE TITLE
How to push without sync?

### ISSUE THREAD

**Issue by realtebo** [odeke-em/drive#1058]
I've no space on my VPS, where gdrive is running, so I'd like to keep pushing without do sync, because after push I need to delete pushed file from disk.

Can I push without causing sync and so deletion on gcloud?

**Comment by odeke-em** [comment]
Hello @realtebo, thank you for the question!

>Can I push without causing sync

Yes, you can do that by `drive push --no-clobber` which will only push but no overwriting of content. To force deletions, do `drive push`

>and so deletion on gcloud?

What does `so deletion on gcloud?` mean? If you meant to type `no deletions`, then `drive push --no-clobber` is your friend.
