### ISSUE TITLE
Automatically accept changes?

### ISSUE THREAD

**Issue by realtebo** [odeke-em/drive#1059]
Is there a way to avoid to press 'Y' to confirm changes? 
When script is ready for production I need a silent / unattended mode

**Comment by CountryBumkin** [comment]
Check the instructions for these options...
drive push -quiet
drive push -no-prompt

Regards CB

**Comment by odeke-em** [comment]
Thank you for the question @realtebo and thank you for the answer @CountryBumkin, also great to catch you again!
