### ISSUE TITLE
Drive Push Error

### ISSUE THREAD

**Issue by tdashmike** [odeke-em/drive#1063]
Hi,

I'm trying to push a file like this:
drive push -quiet -destination images -files /var/lib/images/2019.png

but keep getting this error even when running it in the dir where I first ran drive init:
no drive context found; run `drive init` or go into one of the directories (sub directories) that you performed `drive init`

- Mike

**Comment by dhoomakethu** [comment]
I am having the same issue when using `-destination` flag ? Any workarounds or solutions?
