### ISSUE TITLE
Untrash big list of ids?

### ISSUE THREAD

**Issue by dzg** [odeke-em/drive#1069]
I have thousands of ids I want to untrash.

Any way to pass a file of these ids to `drive` to untrash?

**Comment by odeke-em** [comment]
Hello @dzg, thank you for the question and welcome to drive!

Yes, we document in the README how to untrash with ids as per https://github.com/odeke-em/drive#trashing-and-untrashing
```shell
drive untrash -id 0fM9rt0Yc9RTPeHRfRHRRU0dIY97 0fM9rt0Yc9kJRPSTFNk9kSTVvb0U
```
and you can creatively pass in ids e.g.
```shell
drive untrash -id $(cat ids.txt)
```
