### ISSUE TITLE
can pull files but unable to push files (token expired)

### ISSUE THREAD

**Issue by evanycgeng** [odeke-em/drive#1071]
Hi

I tried to use drive for uploading local data. I have got a JSON file and set it up using:

`drive init --service-account-file <gsa_json_file_path> ~/gdrive`
`cd ~/gdrive` 

And I can successfully pull files from google cloud.

But When I tried to use `drive push /Users/google_test` to upload files,

the code gives me the following error:

`Resolving...`
 `/ `
`Get https://www.googleapis.com/drive/v2/files?alt=json&prettyPrint=false&q=%22root%22+in+parents+and+title+%3D+%22google_test%22+and+trashed%3Dfalse: oauth2: token expired and refresh token is not set`

The website says:

`{"error":{"errors":[{"domain":"usageLimits","reason":"dailyLimitExceededUnreg","message":"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.","extendedHelp":"https://code.google.com/apis/console"}],"code":403,"message":"Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."}}`

Can someone help me with this?

Also, can someone explain where can we access files uploaded to google service account? 

Any comment would be appreciated.  

Thanks!

**Comment by Stephen-Z** [comment]
I have the same problem....

**Comment by aklimatize** [comment]
I'm also having the same issue.

I set mine up using:

drive init ~/gdrive

which gave me a URL that I clicked on, and authorized drive access to my account; it gave me an authorization token, which I copied and pasted into the terminal.

drive list - works
drive pull - works
drive push - does not work (I get the error below):

no drive context found; run `drive init` or go into one of the directories (sub directories) that you performed `drive init`

I'm on Ubuntu 18.04.3 and I installed drive using the below command:

go get -u github.com/odeke-em/drive/cmd/drive

Thanks.

**Comment by Stephen-Z** [comment]
After the archlinux rolling update , the problem have been fixed, now I can push smoothly, Thanks.

**Comment by odeke-em** [comment]
Thank you for the question @evanycgeng @Stephen-Z @aklimatize and welcome to drive!

The problem with relying on the default project credentials is that everyone in the world uses them. The quota is quite generous: 1Billion API requests per day but still the default credentials are used.

The only remedy for this is documented here https://github.com/odeke-em/drive#api-keys of which I'd advise getting your personal Google Cloud Platform API credentials from https://developers.google.com/drive/api/v2/about-auth and that should sort your problem out.
