### ISSUE TITLE
API Key Environment Variables

### ISSUE THREAD

**Issue by AidanHilt** [odeke-em/drive#1073]
I know the instructions say to set the environment variables, but there's no further information given. Could you please go into more detail as to where and how drive expects to find these?

**Comment by odeke-em** [comment]
Hello there @AidanHilt, thank you for the question!

>Could you please go into more detail as to where and how drive expects to find these?

Resolving API keys from the environment is a direct resolution from os.Environ().

>as to where and how drive expects to find these

The Google API Keys are a standard step whose creation and management is handled by Google's API console https://developers.google.com/drive/api/v3/enable-drive-api.

That step is assumed to be for users who have used Google's API console and putting instructions in the README.md risks getting outdated so usually a Google search would help.

Hope this answers your question?
