### ISSUE TITLE
no progress report when pushing huge files

### ISSUE THREAD

**Issue by minux** [odeke-em/drive#108]
Although there is a progress bar, but it seems there are only
two states: 0% and 100%, which is quite confusing. I had to
strace the process to make sure it's actually uploading the
file, not stuck.

**Comment by odeke-em** [comment]
Thank you for reporting this. I too have found this to be undesireable behaviour. Right now it is because of the way the progress counter is used. Basically progress is incremented per completed file transfer and not per byte transferred. Watch this space.

**Comment by ikwyl6** [comment]
This is the same as #23 FYI.

**Comment by odeke-em** [comment]
Please take a look at PR https://github.com/odeke-em/drive/pull/147

**Comment by odeke-em** [comment]
Fixed by https://github.com/odeke-em/drive/commit/b2659cfeaf3b689223aee3da1e26d75db7d874f6.
