### ISSUE TITLE
gRPC not found during install

### ISSUE THREAD

**Issue by wiredearp** [odeke-em/drive#1080]
In `go version go1.13.6 linux/amd64`, when running `go get -u github.com/odeke-em/drive/cmd/drive`, I get:

```
../../../gopath/src/google.golang.org/api/option/option.go:153:14: undefined: grpc.RoundRobin
../../../gopath/src/google.golang.org/api/option/option.go:154:42: undefined: grpc.WithBalancer
```

Assuming that perhaps I could install this myself, I tried running:

```
 go get google.golang.org/grpc
```

— but that didn't make much of a difference. Do you guys think I should install an earlier version of Go or should I somehow patch my installation differently? Thanks!

**Comment by eidoom** [comment]
I noticed this today too. Looks like [this](https://github.com/grpc/grpc-go/issues/3312) is the culprit.

**Comment by wiredearp** [comment]
I made another `go get google.golang.org/grpc` this morning and managed to progress past this point of missing gRPC :tada: I was now met by another issue #360, however this was easily fixed with

```
CGO_ENABLED=0 go get -u github.com/odeke-em/drive/cmd/drive
```

Have fun with `drive`!
