### ISSUE TITLE
shared drive

### ISSUE THREAD

**Issue by amidevous** [odeke-em/drive#1098]
and it is possible to set up a shared drive also called team drive

https://drive.google.com/drive/u/0/shared-drives

and if yes, how ?

**Comment by jlick** [comment]
Please see issue #913

**Comment by colourful-land** [comment]
@amidevous would you kindly close this issue for duplication as the project owner doesn't seem to be managing this?

**Comment by odeke-em** [comment]
Did y’all see https://github.com/odeke-em/drive/issues/913#issuecomment-625447303? Essentially Google Drive has probably given access to Shared Drives implicitly and obsoleted drive/v2 API access (which this project uses). Perhaps let’s keep the conversation on that issue. Thanks y’all for filing this issue, and my apologies for the long and late replies as I am swamped with lots of work on my company yet short staffed.
