### ISSUE TITLE
Upload hidden files to Google Drive.

### ISSUE THREAD

**Issue by mansoorahmedmemon** [odeke-em/drive#1103]
How can I upload hidden files e.g. `.hidden` to **Google Drive**?

I tried the regular push:

> $ drive push

It works good but hidden files (beginning with a `.` period) are not uploaded to Google Drive.

**Comment by odeke-em** [comment]
Thank you for this question @mansoorahmedmemon!

It is documented in the README https://github.com/odeke-em/drive how to pull or push hidden files, `-hidden` is the flag you want
* Pulling https://github.com/odeke-em/drive#pulling
* Pushing https://github.com/odeke-em/drive#pushing
* .driverc (general settings) https://github.com/odeke-em/drive#configuring-general-settings

**Comment by mansoorahmedmemon** [comment]
Thanks!
