### ISSUE TITLE
Can't install on LM20: Cannot add PPA: ''This PPA does not support focal''.

### ISSUE THREAD

**Issue by endicay** [odeke-em/drive#1108]
I've moved up to Mint 20 on a new machine and need to install drive (which I rely on a lot).  
Installation falls at the first hurdle:

sudo add-apt-repository ppa:twodopeshaggy/drive

results in  

Cannot add PPA: ''This PPA does not support focal''.

**Comment by CountryBumkin** [comment]
The repo seems to have been abandoned for some time.
Download a suitable executable from here...
https://github.com/odeke-em/drive/releases/tag/v0.4.0
Mark the file as executable
Reverence it directly or put it in $HOME/bin folder to execute.
Note that it displays its version number as 0.3.9.1
test by $ drive version

regards CB

**Comment by odeke-em** [comment]
Thank you @CountryBumkin! @endicay thanks for filing this issue, but the PPAs are out of my control, and as @CountryBumkin showed, please tag a look at the released binaries, or build using Go. I am going to close this issue as there isn't more I could do here. 

Wish you both a happy New Year, and thank you for using drive!
