### ISSUE TITLE
Restore the ability to (up/down)load individual files

### ISSUE THREAD

**Issue by cdgamlin** [odeke-em/drive#1112]
I can see the original version of this allowed the (up/down)load of individual files:
https://github.com/prasmussen/gdrive
gdrive [global] download [options] <fileId>
gdrive [global] upload [options] <path>

The latest version seems to have this removed (!!) - which I think cripples things quite a bit

Why this is important to me:
The original version no longer seems to work - Google Drive seems to block it
I'm wanting to download individual files to a computer cluster I am using
Pulling my whole drive is slow and wasteful - the cluster admins will not be happy with me filling up GBs

Importantly: Using ".driveignore" is not an option. It is likely other cluster users will use my Docker container for the extra productivity I am designing it for (making it easy to switch between using Google Colab and using the cluster) - and I don't want the other users to have to muck around with ".driveignore" - or not have ".driveignore" correctly configured and annoy the cluster admins by filling up the cluster with unneeded GBs

**Comment by cdgamlin** [comment]
... nevermind - just worked out I can use "drive pull <filenamse>"

**Comment by dm17** [comment]
you can use drive pull? This utility seems fairly dangerous... Considering all you need to do is init and then pull and you could wipe out your entire home dir if you didn't realize you needed to be cd'd into the right directory when init'ing.
