### ISSUE TITLE
Really confused with .driveignore

### ISSUE THREAD

**Issue by themegabyte** [odeke-em/drive#1117]
I apologize if this is the incorrect channel for asking this question but something is really troubling me since this morning.

These are my drive ignore contents. I am really not sure why cookies.text is not being ignored while pushing.

```
cat .driveignore
Output:
*.text
```

I have tried:

```
cookies.text
*.text
\.cookies.text
```

It still gives me:

```
drive push
Resolving...
+ /Class Lecture Recordings/MAD - 6/Lab 6-5th April 2021.mp4
+ /Class Lecture Recordings/MAD - 6/cookies.text
Addition count 2 src: 61.79MB
Proceed with the changes? [Y/n]:Y
```

Anyone shed some light on where I am missing the correct syntax for the file? I just want to ignore some files that I don't wanna push to drive.

**Comment by odeke-em** [comment]
Thank you for the question @themegabyte and welcome to the drive project!

For 1, does the .driveignore file exist inside your root directory?

2, `*.text` isn't a valid re2 pattern AFAIK, you probably want `.*.text`, or just `.text`;
you also don't want to use `\.cookies.text`, use the pattern that matches the filename not the basename nor full pattern.

3. What version of drive are you using? I can't really debug what version you are on, as perhaps it could have been distributed before .driveignore was added?

There are many unknowns currently, please try to reduce them.

**Comment by themegabyte** [comment]
Hello @odeke-em,

thanks for looking at with my issue.

I am so sorry to have written back this late. Things have been pilled up a lot.

Here's some out put that might help you and identify what I am going wrong with:

```bash
(18:24:27) root@: ~/drive/drive.gmail/Setups # ls -la
total 632724
drwxr-xr-x 2 root root      4096 Jun 13 18:20 .
drwxr-xr-x 7 root root      4096 Apr 12 09:42 ..
-rw-r--r-- 1 root root         6 Jun 13 18:20 .driveignore
-rw-r--r-- 1 root root 521675360 Apr  9 22:43 FuzeInstallerPerMachine.exe
-rw-r--r-- 1 root root  74527128 Jan 22 00:05 Skype-8.68.0.96.exe
-rw-r--r-- 1 root root         0 Jun 13 18:20 test.text
-rw-r--r-- 1 root root  51672000 Feb  3 21:31 UpworkSetup64.exe
(18:24:29) root@: ~/drive/drive.gmail/Setups # cat .driveignore
.text
(18:24:32) root@: ~/drive/drive.gmail/Setups # drive push
Resolving...
+ /Setups/test.text
Addition count 1
Proceed with the changes? [Y/n]:n
(18:24:39) root@: ~/drive/drive.gmail/Setups # which drive
/root/go/bin/drive
(18:24:46) root@: ~/drive/drive.gmail/Setups # /root/go/bin/drive version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:
(18:24:53) root@: ~/drive/drive.gmail/Setups # drive version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:
(18:24:57) root@: ~/drive/drive.gmail/Setups #
```

Thanks again for the help.
