### ISSUE TITLE
deletion count

### ISSUE THREAD

**Issue by julianofischer** [odeke-em/drive#112]
Hi, yesterday I pushed an entire dir to my drive account. However, the operation was not completed because I canceled before it was finished (ctrl + c). Today I tried to push the entire dir again. I noticed that the "size to push" decreased, I was indeed expecting it. However, "files to be deleted" (deletion count 2236) appeared. I dont know why. I have not deleted files from this dir.

Could you enlighten me?

Thanks.

**Comment by odeke-em** [comment]
Hello @julianofischer, thanks of reporting this.
So far it seems like mid way through the push some files may have changed or were created inside the directory upstream but are not on the local dir. See drive tries to mirror the ideal remote file organization (by ideal I mean one unique path per folder), and the usual push if content is not present locally is asking drive to delete it. If this is troublesome for you, you can turn drive to some sort of safe mode ie `drive push --no-clobber` and this should only process additions, no deletions nor modifications, for safety. Your other option would be going to the specific directories and pushing up the individual parts you would like e.g
```shell
$ cd ~/myDrive/2015/Pictures
$ drive push tour screenshots sloth.jpg
```
Once you are confident with the organization, then you can perform a pull or even a full push.
Also note that you have the `untrash` command that can help you retrieve content from the trash
e.g
```shell
$ cd ~/jackbauerDrive/archives
$ drive untrash --matches ctu
```
This should check for content in folder "archives" for any files that have prefix matches of "ctu"

Please let me know if this makes sense, and as always feel free to ask any other questions :)

**Comment by julianofischer** [comment]
Hi @odeke-em, the odd about it all is that my local file system have not changed.
I have not modified or deleted the files (mostly pictures).

Anyway, I will be trying to push up individual parts, as suggested or maybe using --no-clobber option.

I just want my files backed up.

Thank you very much for your answer, Mr. Emmanuel.

**Comment by julianofischer** [comment]
Result with -no-clobber option:

'''
Resolving...
unexpected fault address 0x0
fatal error: fault
[signal 0x7 code=0x80 addr=0x0 pc=0x483a21]

goroutine 1 [running]:
runtime.throw(0xae3dab)
	/usr/lib/go/src/pkg/runtime/panic.c:464 +0x69 fp=0x7f0a1ab72318
runtime.sigpanic()
	/usr/lib/go/src/pkg/runtime/os_linux.c:229 +0x1ed fp=0x7f0a1ab72330
github.com/odeke-em/drive/src.(*Change).op(0xc210516030, 0x1)
	/home/juliano/go/src/github.com/odeke-em/drive/src/types.go:306 +0x91 fp=0x7f0a1ab72358
github.com/odeke-em/drive/src.(*Change).Op(0xc210516030, 0x1)
	/home/juliano/go/src/github.com/odeke-em/drive/src/types.go:329 +0x27 fp=0x7f0a1ab72370
github.com/odeke-em/drive/src.sift(0xc211ad9000, 0x3079, 0x3079, 0xc2110d4000, 0x2775, ...)
	/home/juliano/go/src/github.com/odeke-em/drive/src/changes.go:325 +0xd2 fp=0x7f0a1ab723f0
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc210049a60, 0xc211ad9000, 0x3079, 0x3079, 0x3079, ...)
	/home/juliano/go/src/github.com/odeke-em/drive/src/push.go:122 +0xac fp=0x7f0a1ab724d8
github.com/odeke-em/drive/src.(*Commands).Push(0xc210049a60, 0x0, 0x0)
	/home/juliano/go/src/github.com/odeke-em/drive/src/push.go:81 +0x9fd fp=0x7f0a1ab72748
main.(*pushCmd).Run(0xc210037a20, 0xc21000a030, 0x1, 0x1)
	/home/juliano/go/src/github.com/odeke-em/drive/cmd/drive/main.go:337 +0x16f fp=0x7f0a1ab727c8
github.com/rakyll/command.Run()
	/home/juliano/go/src/github.com/rakyll/command/command.go:155 +0x81 fp=0x7f0a1ab727f0
github.com/rakyll/command.ParseAndRun()
	/home/juliano/go/src/github.com/rakyll/command/command.go:162 +0x1f fp=0x7f0a1ab727f8
main.main()
	/home/juliano/go/src/github.com/odeke-em/drive/cmd/drive/main.go:65 +0x2748 fp=0x7f0a1ab72f48
runtime.main()
	/usr/lib/go/src/pkg/runtime/proc.c:220 +0x11f fp=0x7f0a1ab72fa0
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394 fp=0x7f0a1ab72fa8

goroutine 3 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 4 [runnable]:
github.com/odeke-em/cli-spinner.func·001()
	/home/juliano/go/src/github.com/odeke-em/cli-spinner/spinner.go:94 +0x1ae
created by github.com/odeke-em/cli-spinner.(*Spinner).spin
	/home/juliano/go/src/github.com/odeke-em/cli-spinner/spinner.go:104 +0xdc

goroutine 6 [chan receive]:
github.com/odeke-em/drive/src.func·013()
	/home/juliano/go/src/github.com/odeke-em/drive/src/push.go:51 +0x44
created by github.com/odeke-em/drive/src.(*Commands).Push
	/home/juliano/go/src/github.com/odeke-em/drive/src/push.go:55 +0x3f8

goroutine 8 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f0a1ad03b50, 0x72, 0x0)
	/usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21006aed0, 0x72, 0x7f0a1ad020e8, 0xb)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21006aed0, 0xb, 0x7f0a1ad020e8)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc21006ae70, 0xc2100b5000, 0x400, 0x400, 0x0, ...)
	/usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000040, 0xc2100b5000, 0x400, 0x400, 0x0, ...)
	/usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc21001dba0, 0x7f0a1ad03ca8, 0xc210000040, 0x5, 0xc210000040, ...)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc2100b3000, 0x17, 0x0, 0x8)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc2100b3000, 0xc2102af000, 0x1000, 0x1000, 0x0, ...)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc210285900)
	/usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc210285900, 0x1, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc21008c080)
	/usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc21008c080)
	/usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 4266 [select]:
net/http.(*persistConn).writeLoop(0xc210a59380)
	/usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 4435 [select]:
net/http.(*persistConn).writeLoop(0xc211823a80)
	/usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 620 [finalizer wait]:
runtime.park(0x412ad0, 0xae7b00, 0xae5908)
	/usr/lib/go/src/pkg/runtime/proc.c:1342 +0x66
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2279 +0x84
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 4434 [IO wait]:
net.runtime_pollWait(0x7f09fc7f25f8, 0x72, 0x0)
	/usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2102ad760, 0x72, 0x7f0a1ad020e8, 0xb)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2102ad760, 0xb, 0x7f0a1ad020e8)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc2102ad700, 0xc210d1d000, 0x1000, 0x1000, 0x0, ...)
	/usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc21085ab30, 0xc210d1d000, 0x1000, 0x1000, 0x7035a0, ...)
	/usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc2110bf120, 0x7f0a1ad03ca8, 0xc21085ab30, 0x5, 0xc21085ab30, ...)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc2117e3000, 0x17, 0x0, 0x8)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc2117e3000, 0xc210959000, 0x1000, 0x1000, 0x0, ...)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc21106f180)
	/usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc21106f180, 0x1, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc211823a80)
	/usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 4265 [IO wait]:
net.runtime_pollWait(0x7f09fc7f24a8, 0x72, 0x0)
	/usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc211cbb370, 0x72, 0x7f0a1ad020e8, 0xb)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc211cbb370, 0xb, 0x7f0a1ad020e8)
	/usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc211cbb310, 0xc210dbc000, 0x800, 0x800, 0x0, ...)
	/usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210631930, 0xc210dbc000, 0x800, 0x800, 0x7035a0, ...)
	/usr/lib/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc21131e390, 0x7f0a1ad03ca8, 0xc210631930, 0x5, 0xc210631930, ...)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc2106eac80, 0x17, 0x0, 0x8)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc2106eac80, 0xc2105a9000, 0x1000, 0x1000, 0x0, ...)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc21062d060)
	/usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc21062d060, 0x1, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210a59380)
	/usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/pkg/net/http/transport.go:528 +0x607
'''

**Comment by odeke-em** [comment]
What version of drive are you running?

**Comment by julianofischer** [comment]
drive version 0.1.3

**Comment by odeke-em** [comment]
@julianofischer sorry for the late reply. Would you mind updating your version of drive? Also what OS and version of Go are you running? Thank you.

**Comment by odeke-em** [comment]
Closing this issue. Please get the latest from master, reopen if persists.
