### ISSUE TITLE
auth timeout error if push lasts longer than 1 hour

### ISSUE THREAD

**Issue by l3iggs** [odeke-em/drive#116]
I just initiated a large `drive push` (526 files, 140GB total with some files as large as 20GB, no deep folder nesting, everything is max 2 folders deep)

Part way through the transfer, with about 50% of the files remaining, I got the following error message:
{FILENAME}: googleapi: Error 401: Invalid Credentials, authError
where {FILENAME} was the name of one of my files. This was one of the largest files in my push, weighing 20GB.

**Update**: It looks like the entire push process hangs once this occurs.

**Comment by odeke-em** [comment]
Seems like this is an OAuth credentials expire bug as seen in https://github.com/odeke-em/drive/issues/53#issuecomment-77523404, an hour after upload it trips out.

**Comment by l3iggs** [comment]
Is the idea that this error comes up one hour after issuing `drive push` or if a single file takes longer than one hour to upload?

**Comment by odeke-em** [comment]
I suspect, if a single file upload takes longer than one hour to upload.

**Comment by l3iggs** [comment]
Is there a way to `touch` or renew the login OAuth credentials? Like a keepalive message or something?

**Comment by odeke-em** [comment]
Exactly that I something I too was thinking of. When doing a migration of code.google.com to github of the OAuth2.0 package I'll investigate this.

**Comment by l3iggs** [comment]
By the way, I'm pretty sure whatever timer is tripping, it's not tripping on a single file taking too long, but rather it's tripping when the entire push process takes too long to complete...

I'm running another test now.

**Comment by odeke-em** [comment]
Roger that, thanks for the info. Makes sense given that only one token is initialized. Also I think I have a hunch on how to fix this. It is going to involve changing the token.Expiry field to a different value.

**Comment by odeke-em** [comment]
Would you mind applying this patch?
```diff
diff --git a/src/remote.go b/src/remote.go
index 5385988..13b0da8 100644
--- a/src/remote.go
+++ b/src/remote.go
@@ -635,7 +635,7 @@ func newTransport(context *config.Context) *oauth.Transport {
 		Transport: http.DefaultTransport,
 		Token: &oauth.Token{
 			RefreshToken: context.RefreshToken,
-			Expiry:       time.Now(),
+			Expiry:       time.Now().Add(time.Hour * 6), // Throw in 6 hours extra
 		},
 	}
 }
```

**Comment by l3iggs** [comment]
Sure. It'll be a few hours though. I do need to get this data moved first.

**Comment by odeke-em** [comment]
Aye aye. Although the patch might help in solving the OAuth expiry :) Take your time though.

**Comment by l3iggs** [comment]
More info:
I don't think this issue comes up on pulls that take longer than one hour.

Also, the timer seems to indeed be one hour and I think it starts counting from when the `drive push` command is run, rather than from when the user enters `Y` to proceed with the changes, so any time taken to compute the checksums of the files before the push seems to count against me.

**Comment by odeke-em** [comment]
Yap, the token's expiry cutdown begins at init. I started the OAuth2.0 migration and it seems like the new package is going to be more testable and give us more control, plus overall it is better since defining the refresh mechanism will be possible as well as checking for expiry. However, it is morning here and am headed to bed, so the migration is incomplete. Thank you for the tests! Catch you later.

**Comment by ikwyl6** [comment]
@odeke-em regarding your patch. Although 6 hours may seem good, and I know you may be just doing this to help out @l3iggs, I don't think you should just put a ceiling limit on it. My thoughts are at each 50 or 55min mark, you should compare the full size of the push to what is currently pushed to google drive and ping or change the token expiry for another hour. Maybe this is do-able with the google code at that point in time, not sure. 

I know you may be just trying the 6 hours for testing, but for a permanent inclusion in the code, you could think of something like this. 

Now I know the logic above may have a fault if the transfer speeds significantly changed (to a lower amount) after the last "check" but atleast you check every 45-55 minutes to see if the expiry needs to be updated. My thoughts only...

**Comment by odeke-em** [comment]
@ikwyl6 oh for sure, I was just giving them 6 hours since they were uploading massive files. However, good vigilance.
Actually this morning, I started OAuth2.0 migration from code.google.com to the new shiny lib at golang.org/x/oauth2, and it has a method for auto refreshing which might be something like:
![screen shot 2015-03-22 at 11 13 13 am](https://cloud.githubusercontent.com/assets/4898263/6770436/5d151f28-d085-11e4-8588-7c27c2df6679.png)

However, this is a work in progress

**Comment by l3iggs** [comment]
@odeke-em would it still be helpful for you if I tested the 6 hour patch you posted above?

**Comment by odeke-em** [comment]
Not really, I know it works, I was just trying to mitigate your timeout problems since you were uploading huge files :)

**Comment by l3iggs** [comment]
Thanks, I got 'em all up!
"Huge" is a relative term, a few tens or hundreds of GBs starts to look quite small when Google is giving away unlimited drive space to users with Google Apps for Education accounts!

**Comment by odeke-em** [comment]
Hehe nice, they give about 1TB or so, at least my school account gives me about that.

**Comment by ikwyl6** [comment]
Wish I had free 1TB! I pay $2-3/mth for 100GB.

**Comment by odeke-em** [comment]
Never meant to brag 😜

**Comment by 4c41** [comment]
Hi Everyone, I'm currently uploading 115GB, 24,000 files, and this morning it looks like it's every 1 hour based on the 401 errors. I'm happy to test the new code once it's ready, as I have another 500GB to push.  This is a great drive client, I have been looking for something like this, and a reason to start learning Go.

**Comment by odeke-em** [comment]
Hello @4c41, you know what I'll spin up for you the quick fix into master until I have finished the OAuth2.0 port from code.google.com to golang/x. @ikwyl6 I'll get the good solution in soon :). This way you can keep uploading your files with no waits. Give me 5 minutes

**Comment by odeke-em** [comment]
@4c41 please get the latest from master, it shouldn't time out for at least 10 hours. What you actually could do is a couple of parallel uploads say let one instance upload some dirs, let the other do the next etc. Also welcome to drive and it is great to hear from you. As always please don't hestiate to reach out in case of any questions.

**Comment by 4c41** [comment]
Excellent.  Many thanks @odeke-em, I have updated, built and running the new code now.  I'll check the output tonight after work.  I didn't realise you can run multiple instances, thanks, I've got two running now, one with small files and one with large. Thanks again!

**Comment by odeke-em** [comment]
Even with multiple accounts you can. Aye aye, hope it doesn't trip out and can do the uploads. Thank you too and good luck.

**Comment by 4c41** [comment]
Just to let you know, @odeke-em, I'm still getting the hourly "googleapi: Error 401: Invalid Credentials, authError" error message. I did an rm -rf * in the gocode/src folder and gocode/bin folders before getting and building this morning, and have confirmed I have the changed line "Expiry: time.Now().Add(time.Hour * 10),".  
Is there anything else you'd like me to try?

**Comment by odeke-em** [comment]
Not really, that was just a time extension for 10 hours ( a kludge ). For now there is not more to test.

**Comment by 4c41** [comment]
Okay, that's fine.  I'll keep an eye on any future updates.  Thanks @odeke-em

**Comment by odeke-em** [comment]
Sorry for the late reply. Roger that @4c41.

**Comment by l3iggs** [comment]
Has anyone seen this bug for pulls that take longer than 1 hour?

**Comment by odeke-em** [comment]
@kcwu tested it out and gave a response here https://github.com/odeke-em/drive/issues/28#issuecomment-84650909 that he was able to perform an upload that lasted almost 4 hours.

**Comment by kcwu** [comment]
That was using resumable upload. No applying any other fixes.

**Comment by bencaradocdavies** [comment]
Just saw the failure with "googleapi: Error 401: Invalid Credentials, authError" after 5h2m14s while uploading a single 2027202458 byte file (just under 2 GB). Time confirmed with bash time builtin as "real 302m17.841s".

This was with a fresh build on master at 626085fbb5d8074165e3e25bbfcf01a370225868 and I can confirm that src/github.com/odeke-em/drive/src/remote.go contains:

			// TODO: Fix this temporary bad hack with periodic refresh
			Expiry: time.Now().Add(time.Hour * 10),

**Comment by odeke-em** [comment]
Thank you @bencaradocdavies for the check. Fix coming soon hopefully.

**Comment by l3iggs** [comment]
This bug is currently killing me. Does anyone have a workaround so that I can push big files at least for now?

**Comment by odeke-em** [comment]
@l3iggs sorry for the late reply. I don't yet have one, but on attempting to work on it before the OAuth2.0 migration is done, I noticed that for the old OAuth API, on OAuth errors, the Google API client returns a stringified errors and a `nil` response instead of the errored response plus the actual error. It erraneously tried to refresh but could not. However if this information could have been relayed back to drive, drive could just check the error code and then probably retry. Here is my dig up on error
```shell
# When the original net/http get request is made and fails it returns the right expectations,
# a non-nil response and you can see an error code that could be checked
retrievedResponse:
 &{
      400 Bad Request 400 HTTP/1.1 1 1
      map[Date:[Sun, 10 May 2015 06:35:37 GMT]
      X-Frame-Options:[SAMEORIGIN] X-Xss-Protection:[1; mode=block] Server:[GSE] Alternate-Protocol:[443:quic,p=1]
      Vary:[Accept-Encoding]
      Content-Type:[application/json]
      Cache-Control:[no-cache, no-store, max-age=0, must-revalidate]
      Pragma:[no-cache]
      Expires:[Fri, 01 Jan 1990 00:00:00 GMT]
      X-Content-Type-Options:[nosniff]
      Accept-Ranges:[none]] 0xc2084b6040 -1
      [chunked] false map[] 0xc2080c21a0 0xc20846a420
}
originalError: <nil>
```
```
# Now in the old OAuth2 api code.google.com/p/goauth/oauth, notice this
accessToken: ""
err: OAuthError: updateToken: Unexpected HTTP status 400 Bad Request

# Then the OAuth API on the final call gets this back
respx <nil> xerr OAuthError: updateToken: Unexpected HTTP status 400 Bad Request
```

```
# What drive gets back
resp: nil
error: Get https://www.googleapis.com/drive/v2/files/root?alt=json: OAuthError: updateToken: Unexpected HTTP status 400 Bad Request: '/'
```

So as you can see it is tricky problem to even try to patch. I have been digging through it and if I discover needs that suit us, I'll either submit patches to the new OAuth package or file issues there.

Thank you for your patience!

**Comment by l3iggs** [comment]
Thanks for your efforts! I guess the thing that stands out most to me is the end of the last error message you included there:
```
Unexpected HTTP status 400 Bad Request: '/'
```
Looks like drive is sending an empty request to me. I assume this is when it tries to renew the auth. What does it send and/or get back when it does the working authorization the first time?

**Comment by odeke-em** [comment]
No no, that was just a custom debug statement test that I made to debug the whole thing, don't read too much in the '/' that is more of:
```go
// on error
fmt.Printf("%v: %s\n", err, relPath)
```

**Comment by l3iggs** [comment]
Maybe it's worth taking a look at how this project does its authentication: https://github.com/prasmussen/gdrive
I don't get any timeout issues when I use this client.

**Comment by markjarzynski** [comment]
Hello, I just want to report that I'm pushing 12TB+ of data to Google Drive. Estimated to take 212 hours. It's been running for about 22 hours so far, and a little over 1TB of it has been uploaded.

However, every once in awhile, I'll get the following errors:

googleapi: Error 401: Invalid Credentials, authError
googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded
googleapi: Error 500: Internal Error, internalError

Getting the errors doesn't stop the transfer. It is still ongoing, but it looks like the files where the above errors occurred are not being uploaded to Google Drive.

**Comment by odeke-em** [comment]
Hello folks, would you mind getting the latest from master. @markjarzynski thank you for reporting this, as for the userRate limit exceeded, I'll probably have to include some sort of throttle and exponential backoff -- this I have started on a different really experimental branch.
Thank you

**Comment by odeke-em** [comment]
With the latest from master this should be fixed
![screen shot 2015-06-07 at 12 24 58 am](https://cloud.githubusercontent.com/assets/4898263/8022871/e2551df2-0cab-11e5-88ab-248317b01232.png)

Closing this since it is outstanding. Please re-open if it persists

**Comment by ob7** [comment]
Trying to push 50 gig file, and I receive the error.  I just installed for the first time a few days ago, so it should have been fixed by then?

**Comment by GeekLogan** [comment]
I also have noticed this with a 5GB push that has taken 3 hours, it erred once per hour on 3 separate files (each file is only about 50MB each).

**Comment by ob7** [comment]
It continues to upload, but once its done, the files are no in google drive.

**Comment by odeke-em** [comment]
Hey folks please get the latest from master by
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
Uploading should be faster and there is also a mechanism for exponential backoff on encountering retryable errors.
Thank you for the patience.
