### ISSUE TITLE
[Feature request] Add --quiet flag

### ISSUE THREAD

**Issue by larsnystrom** [odeke-em/drive#118]
At the moment the only way to make a `drive push` command completely quiet is to redirect both ~~stdin~~ stdout and stderr to `/dev/null`, since for some reason the rotating slash indicator is not affected when only redirecting ~~stdin~~ stdout.

It would be a bit neater to just provide a `--quiet` flag to force the application to be silent. 

This is necessary for cron jobs, unless you want an email with a bunch of slashes every time you push a file.

**Comment by odeke-em** [comment]
`Redirect stdin to /dev/null`: hmm you probably then want to pass in flag `--no-prompt` otherwise you'll be stuck with a prompt.
`Redirect stderrt to /dev/null`: I don't know if this is a good thing to do since you are going to ignore a whole bunch of errors, but again depends on the user.

Otherwise this seems like a feasible feature, thank you and welcome to `drive`.

**Comment by larsnystrom** [comment]
Oh, sorry I meant I'm redirecting stdout and stderr, not stdin. Edited my original post.

Maybe the bug report should have been that the progress indicator is outputted to stderr. That's the reason why I'm redirecting stderr to `/dev/null`.

And thank you for the application!

**Comment by odeke-em** [comment]
Ah gotcha, I see. Would you like me to change the issue title? Or you can do it yourself.
I am also the author of the spinner application and the reason why it logs to stderr is to avoid the spinner getting into piped content say you for example you are using GNU screen.

**Comment by larsnystrom** [comment]
No, even if the spinner was outputted to stdout a `--quiet` flag would still be a nice feature when running `drive` in a cron job. 

I think we should keep the issues separated. Even though solving one would pretty much solve the other, there might be edge cases which I can't foresee.

**Comment by odeke-em** [comment]
See the thing is with a --quiet flag, I'd be able to pass that into the spinner and close it which is why I am all for this feature.
So I assume you with --quiet you do not want any output from stdout? What do you expect for stderr?

**Comment by larsnystrom** [comment]
I'd want all "normal" output to be suppressed, and all error messages to still get through. Usually that means suppressing stdout and printing stderr.

I think it's important that stderr is still printed, since that would allow me to get notified on failures. Some applications provide a "very quiet" flag as well, which I guess would also suppress errors. But in this case I don't think that's necessary.

As you mentioned, there might be cases when some output is needed, e.g. prompt descriptions. I'm not sure if I'd prefer the --quiet flag to also imply -no-prompt, or if output should still be printed. I'm leaning towards having to explicitly specify both --quiet and -no-prompt, since implying -no-prompt might catch some people of guard and do things they didn't intend to.

Also, since all other arguments start with a single dash, maybe --quiet should be -quiet or even -q. But that's up to you :)

**Comment by odeke-em** [comment]
Please take a look at PR https://github.com/odeke-em/drive/pull/123

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/pull/123. Please re-open if it persists.
