### ISSUE TITLE
[feature request] automatic disable pager and spinner if piped

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#119]
The usually way in C is to call isatty() on stdout. If it is not tty, disable interactive features, like pager and spinner.

This is related to #118 (solve the same problem in another way)

**Comment by odeke-em** [comment]
How about moving this information to that issue? I'd rather have all this information in one place.

**Comment by kcwu** [comment]
up to you. i'm okay.

**Comment by odeke-em** [comment]
Btw had you ever noticed the pager or spinner turned on when using `--piped`? I have never noticed this kind of behaviour before. Closing this, please re-open if you see any of this present.

**Comment by kcwu** [comment]
Not only "push -piped". I expect that no pager and spinner for "drive list -r -m=-1"

**Comment by kcwu** [comment]
And for jobs running in cron, no pager and spinner by default.

**Comment by odeke-em** [comment]
Broad scope, limited feature request title. Also explain to me why recursive listing would not allow for pagination?

**Comment by odeke-em** [comment]
Basically you are asking for every operation not to have pagination nor spinner

**Comment by kcwu** [comment]
oh, not really related to recursive.... just an example.
No pager and spinner for "drive list | wc"  as well.

**Comment by odeke-em** [comment]
That was the purpose of have `--quiet` which I just added.

**Comment by odeke-em** [comment]
As well as --no-prompt.

**Comment by kcwu** [comment]
My feature request is that drive detect interactive mode automatically.

For example, "git log" has pager if the output is long. But no pager for "git log | wc"
Users no need to pass additional flags.

**Comment by odeke-em** [comment]
You are welcome to submit a PR for this, but this information is coming way late and seems to be covering a different case than the request asked for.

**Comment by odeke-em** [comment]
Never mind my comments, I just re-read your title.

**Comment by odeke-em** [comment]
My apologies, your original comment cuts the deal, mentions what needs to be done.

**Comment by odeke-em** [comment]
Fix coming up, this was just me purely not understanding the requirements.

**Comment by odeke-em** [comment]
My apologies @kcwu this was a case of me not reading clearly and not understanding your requirements, please take a look at PR #127
