### ISSUE TITLE
Drive fails to install 

### ISSUE THREAD

**Issue by LouisPhilippe** [odeke-em/drive#124]
When using the command listed on the main page: 

$ go get -u github.com/odeke-em/drive/cmd/drive

I get the following error (I have installed go):

 # golang.org/x/net/context
/usr/lib/go/src/pkg/golang.org/x/net/context/context.go:256: function ends without a return statement

Anything I could be doing wrong, or something I could do to work around this?

**Comment by l3iggs** [comment]
Have you tried reinstalling go?
What version of go are you using? i.e. what does `go version` return?

**Comment by odeke-em** [comment]
Thank you @l3iggs for getting this one, I just wanted to add you are most likely using go1.1. Please install go 1.2 and above as mentioned in the README.

**Comment by LouisPhilippe** [comment]
Thanks for the swift response! I was indeed running an older version of the go software..

**Comment by odeke-em** [comment]
Closing this as the steps to install go are outlined in the README here https://github.com/odeke-em/drive#requirements
