### ISSUE TITLE
add -no-prompt for the share command

### ISSUE THREAD

**Issue by wmsvision** [odeke-em/drive#125]
Is there a way to avoid having to confirm my desire to share a folder or document?  If not, it would be great if we could have "-no-prompt=true" for share command, just like we do for pull command.

I am running "drive share -emails <emails> <folder>", and it asks me if I want to "Proceed with the changes?"  Since I plan to run this from a shell script, automatically based on other actions in my system, I cannot be there to answer yes every time.

**Comment by CountryBumkin** [comment]
This nuisance is not unusual so read here...
http://www.computerhope.com/unix/yes.htm

**Comment by odeke-em** [comment]
Thank you @wmsvision  for reporting this and welcome to drive. Addressed by https://github.com/odeke-em/drive/commit/6afb78c7b2a264463f231d7c151d8e91c18b8c69.
Thank you @CountryBumkin for the tip.

**Comment by wmsvision** [comment]
Thanks so much for the pointer, @CountryBumkin.  Learn something new everyday.

Thanks for the speedy response, @odeke-em.  It works great.

**Comment by odeke-em** [comment]
Anytime, please don't hesitate to reach out in case of any questions or issues.
