### ISSUE TITLE
Not able to push files if path is not present

### ISSUE THREAD

**Issue by philipp923** [odeke-em/drive#130]
If the push command is executed for specific files/folders and the path is not jet present in Google Drive, these folders are not transferred.

There is no error message.

**Comment by odeke-em** [comment]
Hello @philipp923 welcome to drive. 
Would you mind giving me a bit more information as well as diagnostics? What commands did you execute? What version are you?
drive pushes upstream content that is not or may have been modified so this issue pretty much defeats the purpose of it. Hopefully we can get this solved asap.

**Comment by philipp923** [comment]
Hi odeke-em,
thanks for the fast reply. Very nice to notice that the project is active. 
I tested a little bit and came up with a minimal example.

Folder structure:
gdrive <- root folder GoogleDrive
  - folderNotOnline
    - fileNotOnline.txt

philipp@x220:/xxx/gdrive$ drive push folderNotOnline/fileNotOnline.txt 
Resolving...
+ /folderNotOnline/fileNotOnline.txt
Addition count 1
Proceed with the changes? [Y/n]: Y
1 / 1 [=====================================================================================================] 100.00 % 0

Everything looks fine, but the folderNotOnline as well as the fileNotOnline.txt are not transmitted to GoogleDrive.

philipp@x220:/xxx/gdrive$ drive stat folderNotOnline/fileNotOnline.txt 
/folderNotOnline/fileNotOnline.txt: remote path doesn't exist
philipp@x220:/xxx/gdrive$ drive stat folderNotOnline/
/folderNotOnline: remote path doesn't exist

drive is working if I push the entire folderNotOnline:

philipp@x220:/xxx/gdrive$ drive push folderNotOnline/
Resolving...
+ /folderNotOnline
+ /folderNotOnline/fileNotOnline.txt
Addition count 2
Proceed with the changes? [Y/n]: Y
2 / 2 [====================================================================================================] 100.00 % 2s

For my use case it would be very helpful to have the ability to push individual sub-folders.

Here are the versions I am using:
drive version 0.1.5
go version go1.2.1 linux/amd64
Linux x220 3.16.0-33-generic #44-Ubuntu SMP Thu Mar 12 12:19:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks in advance and have a nice day.
Philipp

**Comment by kcwu** [comment]
I can reproduce the minimal case, too

**Comment by odeke-em** [comment]
Hello @philipp923 sorry for the late reply, Friday nights offset Saturdays by a bit ;)
Oh yes in deed, this issue should be present because now it just dawned onto me that during remoteAdditions I was doing lookups of parents instead of remoteMkdirAll of parents which should be the case. This behaviour was changed a couple of weeks ago when the Google API client was buggy and was uploading files title 'Untitled Title' for every folder for which I used remoteMkdirAll, hence I backed off. However the API client got fixed and I also patched that in drive however not in that spot. Thank you very much for bringing this.
I am pushing up the fix in a few minutes.

**Comment by odeke-em** [comment]
For more details the Google Go api client offending change ages ago was https://github.com/google/google-api-go-client/commit/901b69e534b7fd805ed4d27388b165db81eea51a#commitcomment-9471898

The latest fix in drive is at https://github.com/odeke-em/drive/commit/53ce76e1ff1aa1749a51cb9d1e9438dc3bde4682

**Comment by odeke-em** [comment]
Please re-open if it persists, am making a release right now.

**Comment by philipp923** [comment]
Hi odeke-em,
the new version of drive is working very well.
Thank you very much for the fast support!

Best regards,
Philipp
