### ISSUE TITLE
Hidden files?

### ISSUE THREAD

**Issue by calgarykev** [odeke-em/drive#132]
Is there a way to push hidden files?  I have a  .face for a user profile in the directory that I am pushing to Google Drive.  It does not get sent.  

Thanks!

Kev

**Comment by odeke-em** [comment]
Yes there is. Pass in a flag `-hidden` or eve better run `drive push -h`

**Comment by calgarykev** [comment]
Great, thanks!

Did I miss it or is it not documented?  I've just been using the main Git page.

Kev

**Comment by odeke-em** [comment]
No worries. I apologize if it is not documented, however since we are in rapid dev documenting is kind of hard right now. If I may, your handiest help would be running `drive <command> -h`.
Welcome to drive btw!
