### ISSUE TITLE
[feature request] delta transfers

### ISSUE THREAD

**Issue by l3iggs** [odeke-em/drive#139]
It would be neat if drive handled small changes in large files gracefully. For example, only the changed parts (or an approximation thereof) of a virtual machine disk image would be pushed/pulled to update the file.

Much of the work to be done here is probably quite similar to what's needed for #25 and #28

**Comment by odeke-em** [comment]
Did you mean to reopen https://github.com/odeke-em/drive/issues/61?

**Comment by l3iggs** [comment]
yes.
