### ISSUE TITLE
Support for Multiple Accounts

### ISSUE THREAD

**Issue by brandoncurtis** [odeke-em/drive#140]
In the README, it is suggested that there is a

> Possibility to support multiple accounts. Pull from or push to multiple Google Drive remotes.

I have separate accounts for home and work, so this would be great!
(If there is already a clever way to set this up and I just haven't thought of it, let me know)

**Comment by odeke-em** [comment]
Welcome to drive! Yes you can trivially use an infinite number of accounts. Please take a look at closed issue https://github.com/odeke-em/drive/issues/71
