### ISSUE TITLE
drive is ignoring file permissions

### ISSUE THREAD

**Issue by l3iggs** [odeke-em/drive#141]
The following is evidence that drive is currently ignoring permissions:
```
$ touch test.file
[mgre@computerome02 drive]$ drive push test.file 
Resolving...
+ /test.file
Addition count 1
Proceed with the changes? [Y/n]: y
1 / 1 [=================] 100.00 % 1s
$ chmod +x test.file
$ drive push test.file 
Resolving...
Everything is up-to-date.
```

Can Google Drive even support preserving permissions?

**Comment by odeke-em** [comment]
Not that I know of. When you upload files, just the binary data is uploaded. It just happens that the abstraction of a file on Google has a similar attributes like title, modifiedDate. Otherwise the concept of your file system's file permissions does not apply to uploaded files.
