### ISSUE TITLE
pull taking too much memory with very big files e.g 399GB - linux kill it (out of memory) and freeze the terminal

### ISSUE THREAD

**Issue by lintzyli** [odeke-em/drive#142]
I am trying to pull a folder (12 files - total 399GB)  from my Google Drive to my local disk in Linux using your program (thank you for this). This folder was a shared one that I had included to my Google Drive, so I could pull it using "drive".

However, after 1 hour and 2 hour, the program is "terminated by signal 9". Checking what could cause it I found  (with *dmesg*) this:
*Out of memory: Kill process 3729 (sshd) score 1 or sacrifice child*

(Besides killing the program, it also caused screen session be killed. I captured the message of "terminating by signal 9" in the nohup log after 2 or 3 screen session crash with no clue) 

Even after the system killing the program, the amount of memory allocated by the program (almost all 32 GB that the machine has) was held and the only solution to reestablish the system resources was to reboot the system.

System info:
Linux 3.2.0-4-686-pae #1 SMP Debian 3.2.57-3 i686 GNU/Linux
quad-core
32 GB memory

Please, any idea what could be causing this program behavior?

**Comment by odeke-em** [comment]
Thank you for reporting this @lintzyli and welcome to drive. This is quite unfortunate but definitely an interesting edge case.
Does it help to pull one massive file at a time?

**Comment by odeke-em** [comment]
Btw drive allows for you do `stat` as well as `list` on files on the remote. You can find this information in the README, just in case you haven't already looked at it.

**Comment by lintzyli** [comment]
Thank you for you messages @odeke-em. I have tried *list*, but I have not used *stat* yet (I will).

In case it helps, I was downloading this dataset, which is hosted at Google Drive:
http://www.yli-corpus.org/mediaeval-2014-placing-task-dataset

Yes, when I pull one big file at time, drive is able to finish OK.

**Comment by odeke-em** [comment]
Can't really reproduce or debug this. Going to close this for now. Let's re-open if it returns. Thank you @lintzyli for reporting it.
