### ISSUE TITLE
option to not delete google docs with push

### ISSUE THREAD

**Issue by mullenkamp** [odeke-em/drive#143]
I was just wondering if there is an option to not delete google doc "files" if a directory is pushed from the local HDD to google drive? For example, if the same directory exists on both the local and google drive, but the google drive has a google doc in it. 
Is there any solution to the inevitable conflict that will arise when using the drive push/pull with directories that have a combination of normal files and google docs?

Optimally for me, I would like to have a backup of the google docs (as odt or equivalent) on my local HDD, but when I `push` the other (unrelated) newly modified files back to google drive the `drive push` would recognize that the odt files are actually the google docs. This works with the mounting tool `google-drive-ocamlfuse`, but I don't find it very stable and I don't really need the mount anyway.

Thanks again for your help.

**Comment by odeke-em** [comment]
As long as you have touched the Google Doc equivalent file path locally, then drive should not be removing it. However if you have not, then drive operates normally and will try to mirror your setup on the cloud, this might involve deleting files. I'd encourage you to checkout the README ( if you have not already) in case you need safe options such as `-no-clobber` or `-ignore-conflict`

**Comment by mullenkamp** [comment]
Thanks for your prompt response!
It seems as though I should be able to find some ways to deal with the problem.

**Comment by odeke-em** [comment]
In the future I'll add methods to aid in sifting through multiple files e.g pulling only content of a certain mimeType say Google Docs or pdfs.

**Comment by mullenkamp** [comment]
That would be fantastic! That would allow me to avoid the problem entirely.
Thanks!

**Comment by odeke-em** [comment]
I wish you had replied to this like 3 hours back, I'd have spun this method up for you. Unfortunately it is quite late here(past midnight) so it won't be able to work on it for another say 16 hours. However I get the Friday off so I would be happy to help you spin this up this evening, if you can wait :)

**Comment by mullenkamp** [comment]
Sorry for that. I'm on a different continent than you (Europe) and went to sleep.
But don't worry, there's no huge rush. You're far too generous to offer such a prompt fix ;)
I will be traveling for this long weekend anyway, so I wouldn't necessarily use it until the middle of next week. 
Thanks again and have a nice Easter weekend.

**Comment by odeke-em** [comment]
Thank you for the kind words.
No worries, I should have taken a look at it before.
Thank you, have a nice Easter weekend too and hopefully when you return there should be an alleviation.

**Comment by kleptog** [comment]
There's an option which I used yesterday: -exclude-ops. I used it as follows:

  drive  push -exclude-ops "replace,update,delete" "Photos"

So it only created files and nothing else. It's not documented, but it appears to work.

**Comment by odeke-em** [comment]
Please get the latest from master. Docs shouldn't be deleted on pushes without even options.
Closing this issue, please re-open if persists.
