### ISSUE TITLE
Error - panic: close of closed channel

### ISSUE THREAD

**Issue by genkimarshall** [odeke-em/drive#149]
Hello, thanks for the great tool so far.
I just got a `panic: close of closed channel` error that interrupted my ongoing push.
Find the output [here](https://gist.github.com/genkimarshall/9e7247068a1d74c955b6).
Running the same command leads to the same error, except the stack trace doesn't seem as long. If I should share that too, please let me know.
`$ drive about` => `drive version 0.1.7` (recently upgraded via the [AUR](https://aur.archlinux.org/packages/drive/)).
Please ask if I should give any other details, hopefully this is helpful.

**Comment by odeke-em** [comment]
Hello there! Thank you for the report. That error most definitely comes from the io abstracting package https://github.com/odeke-em/statos that I happen to the be author of too :)
Most definitely it stems from me not fully tracking a close attempt. Would you mind re-running

`go get -u github.com/odeke-em/statos && go get -u github.com/odeke-em/drive/cmd/drive`

Please let me know what happens with this.
Also welcome to drive.

**Comment by genkimarshall** [comment]
Great, I used the executable gotten from doing that (as opposed to the one that I have in my /usr/bin from the AUR), and it worked perfectly. Thanks so much!
But sorry, could I bother you to explain what this means? As far as I understood it, the version I had downloaded was the most recent version (just looking at the commits here).
So did this simply refresh the install? As in, if I were to re-download the AUR package, it should also fix the issue?

**Comment by odeke-em** [comment]
Oh yes that got you the latest source. Basically `go get -u` gets the most recent from the repo, so pretty much like `git pull origin *`.
The binary in the AUR package is a bit stale since I updated the third party package since probably when it was compile. I shall summon up our AUR wizard @shaggytwodope and kindly ask him to help re package it for AUR :)
Please let me know if this makes sense.

**Comment by genkimarshall** [comment]
Awesome thanks, definitely does ^_^ I'll just use the version I just got until then.
Have a good night!

**Comment by odeke-em** [comment]
Great, thank you have a good night too and feel free to reach out in case of any questions or ideas.

**Comment by genkimarshall** [comment]
Great will do!
