### ISSUE TITLE
"x509: certificate has expired or is not yet valid" error on account authorization.

### ISSUE THREAD

**Issue by wmsvision** [odeke-em/drive#152]
Hello,
  I keep getting "x509: certificate has expired or is not yet valid" when I try to refresh my authorization.  Is that a Google problem or a code problem?
   Also seem to be having a similar problem with the google-drive-ocamlfuse tool, so I sort of think it is either Google or my Google Drive account.  Thought I would start with you on the off chance it is a code issue.

Thanks.

Tony

**Comment by odeke-em** [comment]
Hello @wmsvision,
Welcome to drive and sorry for the late reply.
Am able to do authorizations. The fact that you are also getting this error when using other tools makes me suspect that your time configuration might be an issue.
Would you mind making sure that your system clock is well configured to the current time?

**Comment by wmsvision** [comment]
Thanks, that was it.  Did not even notice my time was wrong.  Oops.

**Comment by odeke-em** [comment]
Anytime, feel free to reach out in case of any questions or ideas for drive :)
