### ISSUE TITLE
push with directories being separately operated on (e.g created) never reaches 100%

### ISSUE THREAD

**Issue by steinrr** [odeke-em/drive#153]
If I push using no-clobber - the progress indicator never reaches 100% - even if all files did upload OK:

    myuser@localhost:~/gdrive$ drive push -no-clobber
    Resolving...
    + /myprog_source
    + /myprog_source/assemble_aaa_index.py
    + /myprog_source/cronlog.txt
    + /myprog_source/log.txt
    + /myprog_source/myprog.py
    + /myprog_source/program_list_s.txt
    + /myprog_source/scrape_aaa_bbb.py
    + /myprog_source/scrape_aaa_from_letter.py
    Addition count 8 src: 38.66KB
    Proceed with the changes? [Y/n]: Y
    35504 / 39600     [===========================================================================>--------] 89.66 % 8s
    myuser@localhost:~/gdrive$ drive push -no-clobber
    Resolving...
    Everything is up-to-date.

The behavior is consistent.

**Comment by odeke-em** [comment]
Hello @steinrr thank you for reporting this and welcome to drive.
In deed this is consistent behaviour but mostly because you are pushing a directory: See the way currently the progress bar works is by tracking the number of byte transactions either read or write, now as you'd guess we can't physically read the bytes of a directory because only files are being IO'd currently. To show you that this is the case, you can go back into that directory and use `drive push --force` for those files, without the directory(which has its own size), you'll notice that progress goes fully until 100%. This behaviour should be able to work as long as the directory. Please let me know if this makes sense. I'll jump on this soon.

**Comment by steinrr** [comment]
Thanks for replying! That explanation makes sense.

Until this issue is improved - maybe it is better to show progress based on number of files instead of bytes? With the current progress bar - there are no way of knowing if transfer was successful or not. (At least it made me very unsure :-) )

**Comment by odeke-em** [comment]
I totally agree. I'll work on this when I get home tonight, but if I haven't given you an update(bug fix) by Wednesday please ping me :)

**Comment by steinrr** [comment]
It is not urgent - as long as I know that this is expected I can live with it.

Brilliant utility btw!

**Comment by odeke-em** [comment]
Thank you. Well thing is such uncertainty could cause a user to freak out if they don't have the ability to empirically verify that the upload was complete, hence that's why I'd like to jump on this asap.

**Comment by steinrr** [comment]
Ok - thank you!

**Comment by odeke-em** [comment]
Would you mind checkout the latest on master `go get -u github.com/odeke-em/drive/cmd/drive` (in case you need to know)? I have pushed up a commit https://github.com/odeke-em/drive/commit/f4dd22ed4d42f2ead749168839f68cbbb0e1f3a2 that hopefully will address this.

**Comment by steinrr** [comment]
Works now!

    Addition count 8 src: 34.66KB
    Proceed with the changes? [Y/n]: Y
    35504 / 35504 [===================================================================] 100.00 % 8s

The only issue I can see is that the byte size showing in the "Addition count" line (34.66KB) does not match the size in the progress bar (35504) - but that is very very minor.

**Comment by odeke-em** [comment]
Under the hood for every job, one is added to the counter so if there are (34.66 * 1024) + 8: leaving + 4.16 "bytes" that could be accounted for somewhat probably due to truncating. Don't worry too much about the matching counters :)

**Comment by steinrr** [comment]
Aha! I see. Maybe it could be an idea to display e.g. 35504 also in the "Addition count line" to make it consistent - but you'll decide.

But anyway - thanks for a great utility and your help in this matter!

**Comment by odeke-em** [comment]
Thank you. Great suggestion, the only thing however that gets tricky is that for every operation, an acknowledgement is made per operation thus the increase in the extra 1 per operation which gets determined later on. Please pull the latest from master and let me know if this is improved at least for the raw bytes to be operated on.

**Comment by steinrr** [comment]
It still shows a difference in bytes (as you carefully explained), and maybe this is "even more confusing" to user not familiar with the reason for the difference. Maybe the ols solution of just showing KB was better. The difference in bytes is now visually very obvious - but in the KB version the user might think it is due to conversion between bytes and KB.

    Addition count 8 src: 34.66KB (35496)
    Proceed with the changes? [Y/n]: Y
    35504 / 35504 [====================================================] 100.00 % 8s

**Comment by odeke-em** [comment]
I like these suggestions. I've actually made a change for the progress meter to only now deal with the actual byte counts, and also noticed that the taskDone acks are unnecessary (at least for now). Please give it one last try and let me know what you think.

**Comment by steinrr** [comment]
Yes, better now:

    Addition count 8 src: 34.66KB
    Proceed with the changes? [Y/n]: Y
    35496 / 35496 [====================================================] 100.00 % 7s

(I now think it would be perfect if you also displayed "34.66KB (35496 bytes)" in the "Addition count" line - because then the user would immediately recognize the two similar numbers.)

**Comment by odeke-em** [comment]
Ooh but then what happens in this scenario? 

```shell
$ drive push f2
Resolving...
M /f2/fx.txt
+ /f2/px.txt
Modification count 1 src: 1.25KB (1279) dest: 1.25KB (1279)
Addition count 1 src: 840.00B (840)
Proceed with the changes? [Y/n]: y
2119 / 2119 [======================================================] 100.00 % 2s
```

Then users are going to ask for totals, then ask to discern which is which, the list will go on.

**Comment by steinrr** [comment]
I think showing the bytes in parenthesis as in your example above is very good. When I see this, I think that 1279 + 840 = 2119 - and I see that the numbers add up and everything is OK. No totals needed - I can do that myself if I wonder.

But I won't cause you any more work now - thanks for your effort!

**Comment by odeke-em** [comment]
I'll give you a simple case to illustrate the confusion

```shell
Resolving...
M /f2/mx.txt
- /f2/fx.txt
m+ /f2/mt.txt
M /f2/bx.txt
Modification count 2 src: 2.50KB (2558) dest: 2.07KB (2119)
Deletion count 1 dest: 17.00B (17)
Addition count 1 src: 840.00B (840)
Proceed with the changes? [Y/n]: y
3415 / 3398 [======================================================] 100.50 % 6s
```

Notice that a full trace through is needed to guess what is happening when other operations are involved.

**Comment by steinrr** [comment]
OK - thanks for your example. I see that it might be difficult for the user to relate the numbers to each other.

**Comment by odeke-em** [comment]
Thank you for the suggestions and for raising this issue, plus for the discussion. Feel free to make more suggestions and reach out in case of any ideas or issues.

**Comment by steinrr** [comment]
Thank you for resolving this

**Comment by odeke-em** [comment]
Cheers ;)
