### ISSUE TITLE
promptForChanges should flush stdin before printing the prompt and Scanln

### ISSUE THREAD

**Issue by minux** [odeke-em/drive#157]
During a long operation, it's possible that the user presses some keys accidentally.

If promptForChanges doesn't flush the stdin buffers before printing the prompt
and Scanln, it's quite possible that it reads the inputs before the user has even
see the prompt and abort/proceed incorrectly, which is quite frustrating.

should also audit the code for similar problems.

**Comment by odeke-em** [comment]
Thank you @minux for pointing this out, I agree. I shall jump on this when I get home in about two hours or so.

**Comment by odeke-em** [comment]
@minux sorry for the late reply. I actually worked on patching this up but realized that Golang at least from my experimentation doesn't expose methods for draining stdin unbuffered. The methods I could find were buffered so wouldn't cover the case before someone hit enter. I tried different forms and hacks then thought of doing it the C-style with select's FD_ISSET with a timeout or even getc with an fd that was dup'd using O_NONBLOCK, but I figured this is way too much hackery yet I could ask you a Golang core developer for help on how you solve. If you can would you mind helping out with this or giving some hints?
Thank you.

**Comment by minux** [comment]
There is no portable way to do this.

On Linux, you can use golang.org/x/sys/unix package to do
that. For example.
unix.Syscall(unix.SYS_IOCTL, 0, unix.TCFLSH, 0)
 to do that.
(The first 0 is the file descriptor for stdin, assuming it's a tty.)

The problem is, however, even on Unix, the constant is not
consistently named.

You can use cgo for this task, which will be portable across
unix (I don't think windows allow you input when the program
is not asking for input, so we don't need to consider windows)

Or we can just use a real terminal handling package.

A some demo (for unix only):
package main

/*
#include <termios.h>
#include <unistd.h>

void flushtty() {
tcflush(0, TCIFLUSH);
}
*/
import "C"

import (
"fmt"
"time"

"golang.org/x/sys/unix"
)

func main() {
fmt.Println("long operation...")
time.Sleep(5 * time.Second)
fmt.Print("Y/N? ")

if false {
unix.Syscall(unix.SYS_IOCTL, 0, unix.TCFLSH, 0) // linux only
} else {
C.flushtty()
}

var s string
fmt.Scanln(&s)
fmt.Printf("%q\n", s)
}

**Comment by odeke-em** [comment]
Aha nice. Thank you! I had also considered the termios solution and I have done such in C but never brought that idea over to Go.
We aren't worrying too much about Windows, this project is mainly for the *NIXes at least for now.
If you'd like to submit this in a PR, that'd be appreciated plus it gives you the contributor credit for the solution. If not, I understand how busy you are :)
Otherwise the branch that I started for this is at https://github.com/odeke-em/drive/tree/flush-stdin-before-prompt, and the first cut at it was at https://github.com/odeke-em/drive/commit/dfb410958cb17ffff879869018cfee9dabab9ffc

**Comment by minux** [comment]
I'm happy to send a PR. do you like the cgo version?

**Comment by odeke-em** [comment]
Cool, thanks. Yes in deed, I like the cgo version and it will do the job.

**Comment by odeke-em** [comment]
Actually would you mind instead switching this to the real terminal handling version since this should also work for OSX?

**Comment by odeke-em** [comment]
Am off to bed as it is past midnight here but I'll catch you in a bit.

**Comment by minux** [comment]
The cgo version is tested on Linux/Darwin/NetBSD and Solaris.

**Comment by odeke-em** [comment]
Oh okay, for sure go ahead.

**Comment by odeke-em** [comment]
Thanks for working on this @minux

**Comment by akevinbailey** [comment]
I don't know why this is "closed". This is still an issue in Go 1.5.1. Will it be fixed in 1.5.2?

**Comment by adg** [comment]
@akevinbailey What is the issue that you think should be fixed in Go?
