### ISSUE TITLE
Extremely slow performance for small files

### ISSUE THREAD

**Issue by sohamm17** [odeke-em/drive#158]
I have folders with small files. For example, 25 MB with 3350 files. It's taking forever to upload. The estimated time is showing 3 hours.

**Comment by odeke-em** [comment]
Hello @sohamm17, welcome to drive and thank you for reporting this!

As you've probably experienced with other progress estimators, time to upload is just an estimate ( which is mostly never accurate or even close to accurate ). How long does it actually to upload?
If the time to perform the actual upload is slow then, that is a real issue but the time estimate is beyond my control. As you'll see during uploads it fluctuates.

Here is some fun

![Estimation](http://imgs.xkcd.com/comics/estimation.png)

**Comment by odeke-em** [comment]
Btw I think this is a duplicate of https://github.com/odeke-em/drive/issues/158

**Comment by sohamm17** [comment]
Yeah. I know it's an estimate. But in reality it takes high time. I think the issue has been reported already. Sorry for duplication.

**Comment by odeke-em** [comment]
3 hours really for 25MB?? That's amazing then.  I've uploaded 1.9GB in about 20 minutes (from school and home) plus one of my deeply nested open source directories in less than 40 minutes.

**Comment by sohamm17** [comment]
Yeah. I have more than 3500 files in there. I feel this is a parallelism issue as you mention in that other thread. I wish I knew `GO` so that I could help you!

**Comment by odeke-em** [comment]
Oh yes, in deed it is a parallelism thing but still 3 hours for 3500 files is something else. I'll work on getting the parallelism back in, probably next week.

**Comment by sohamm17** [comment]
Yeah! It might be a different issue. It might be that a single file-uploading has some house-keeping task, and that kind of time-consuming tasks are done for every file in that directory. So, it's taking lots of time. Parallelism would definitely speed-up things to some extent.

**Comment by odeke-em** [comment]
@sohamm17 thank you for the patience! Please take a look at the work in progress PR https://github.com/odeke-em/drive/pull/210.

**Comment by odeke-em** [comment]
@sohamm17 please run
```shell
go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
the latest code has parallel uploads and should handle errors quite well with retries.
Cheers!
