### ISSUE TITLE
drive pull [only] never comes to `Everything is up-to-date`

### ISSUE THREAD

**Issue by ggaussling** [odeke-em/drive#159]
Hello,
until yesterday I used grive and grive-tool for syncing google drive to linux.
But grive only supports the outdated API for google drive that was deprecated long ago. google switched that API off 5 days ago.

I initialized drive and then pulled the entire google drive to `~/Google\ Drive` .
But there is on each pull an additional count of 10 files and a modification count of 7 files left, and each another pull the same additional files, but only 3 modified. It never reach something like  `Everything is up-to-date`.

Due to this behaviour I do not trust the drive push command, because I fear that it might modify the content of the repository on google.com .

What's happening there? The Google Drive web interface shows on activities no changes. The last one where two files on April the 17th.

I'm using encfs to encrypt the most of my google drive content by retaining it accessible on other platforms too.

```shell
~/Google Drive$ drive pull
Resolving...
md5Checksum: `Ixsst9HyzKr8r5S7dVft5oH0YZUqsQ0Li7BcgbDVAYNUJ0` (1.44GB)
might take time to checksum.
+ /EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho
[...]
M /EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/FIBQ8TkjUwaVGtGaVSejBCLN0zg,Zx2TObMbH7DRsTGBCxgXVCRq0RHAes,ntOUWxcR4fKf0y2wi6CDkIAdjmkurGaFDKEAwc7rzKvtKglVmOH5392aiFDgs38cl5JZl9oeyH1tBERaTxz31w9MjlziT
Addition count 10 src: 11.23MB
Modification count 7 src: 6.90MB dest: 6.90MB
Proceed with the changes? [Y/n]:
19004380 / 19004380 [===============================================================================] 100.00 % 31s
```
```shell
~/Google Drive$ drive pull 
Resolving...
md5Checksum: `Ixsst9HyzKr8r5S7dVft5oH0YZUqsQ0Li7BcgbDVAYNUJ0` (1.44GB)
might take time to checksum.
+ /EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho
[...]
M /EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/O3Yumpt-7wIHqeydzy-Bs8Oiwv,R7W9DACeS,Ic8,qwHKP0b7UcHVUPCHqTkkYIUYHNhpUCz6cM8SSADBrVS-OXo,t3GLbr83nhcQY4xsE3-HKAhqlLLfuzRlTBiX5Tjk1gJaOPFqJDMPIRe2C34Ajyh
Addition count 10 src: 11.23MB
Modification count 3 src: 4.33MB dest: 4.33MB
Proceed with the changes? [Y/n]: 
16307693 / 16307693 [===============================================================================] 100.00 % 26s
```
```shell
~/Google Drive$ drive pull 
Resolving...
md5Checksum: `Ixsst9HyzKr8r5S7dVft5oH0YZUqsQ0Li7BcgbDVAYNUJ0` (1.44GB)
might take time to checksum.
+ /EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho
[...]
M /EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/FIBQ8TkjUwaVGtGaVSejBCLN0zg,Zx2TObMbH7DRsTGBCxgXVCRq0RHAes,ntOUWxcR4fKf0y2wi6CDkIAdjmkurGaFDKEAwc7rzKvtKglVmOH5392aiFDgs38cl5JZl9oeyH1tBERaTxz31w9MjlziT
Addition count 10 src: 11.23MB
Modification count 7 src: 6.90MB dest: 6.90MB
Proceed with the changes? [Y/n]: 
19004380 / 19004380 [===============================================================================] 100.00 % 31s
~/Google Drive$ 
```
and so on...

**Comment by ggaussling** [comment]
This might be related to issue 117 https://github.com/odeke-em/drive/issues/117

**Comment by odeke-em** [comment]
Hello there @ggaussling, welcome to drive!
In case you haven't yet, would you mind taking a look at the README.md file? It contains explanations for things like duplicate files and would explain why you might seem to have additional files. Also it shows the safe mode `--no-clobber` as well as `--ignore-checksum`.
It is really late here so my apologies if my response doesn't make immediate sense but please watch out for duplicate files.
Thank you.

**Comment by ggaussling** [comment]
Hello odeke-em, I appreciate your hints and will have a look into the documentation to understand the issue. Have a good night! Thank you.

**Comment by odeke-em** [comment]
Thank you, I'll catch you in a bit and hopefully we can be able to find out the root cause of this.

**Comment by ggaussling** [comment]
I figured out, that the web-ui lists 8 from ten as dupes while on the local drive folders there are no dupes to find.

https://drive.google.com/file/d/0B8H-cwsNCJVDVkVVTUlpQVcxaUk/view?usp=sharing

```shell
ubuntu
~/Google Drive$ find . -name "AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho"
./EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho

Windows (cygwin)
[17. Week, Sa, 2015-04-25, 13:05] me@PC168 /cygdrive/c/Users/gaussling.MYDOM/Google Drive
$ find . -name "AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7Y
oKPNYLhd2l9YrMGho"
./EncFsPri/OfhyrCBep6bF45grkhQZALUy/Hb7GBLjoWFQ0aK2mVp6HCYE4/AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho
```

**Comment by odeke-em** [comment]
Deutsch sprechen? Gut. Those are same of the few words I successfully put out in German haha.

Anyways, as for deleting the dupe web-ui list, your file system cannot accomodate clashing names within the same folder which is why you keep getting needs for updates. info I'd advise:
1. `drive stat AAYhWj54DpusqfWViIXww-6nhl5npQLj8e4,WH87qYN4IQPhtgSFvDmI2quuvLs59XbywsploZCwyu,XO1sY1ZmZo1bbkuVZdtYwc4qYFlcaXzEHCAO,W2KLtnXrUtsbiL7Qv7YoKPNYLhd2l9YrMGho`
That should return you the FileId. Once you have the fileId then you can compare those two files by inspecting their properties using the web ui, and appropriately decide which one you want to delete, then delete it.

A feature request was put to warn the user about clashing names but this isn't yet in. Coming soon.

Also just to let you know you can pull, push, pub etc folder centric
ie
```shell
$ cd ~/my_drive/photos/2015 && drive push *.png
```
is the same as

```shell
$ cd ~/my_drive && drive push photos/2015/*.png
```

**Comment by ggaussling** [comment]
Thank you, that worked. i deleted the older one of the duplicates.
```shell
~/Google Drive$ drive pull -no-clobber
Resolving...
md5Checksum: `Ixsst9HyzKr8r5S7dVft5oH0YZUqsQ0Li7BcgbDVAYNUJ0` (1.44GB)
might take time to checksum.
Everything is up-to-date.
~/Google Drive$ drive push -no-clobber
Resolving...
md5Checksum: `Ixsst9HyzKr8r5S7dVft5oH0YZUqsQ0Li7BcgbDVAYNUJ0` (1.44GB)
might take time to checksum.
Everything is up-to-date.
```

**Comment by odeke-em** [comment]
Cool. Coming up soon is the ability to warn the user about clashing names for files.

**Comment by odeke-em** [comment]
Clashing names warning added by PR https://github.com/odeke-em/drive/pull/166, please get the latest code.
