### ISSUE TITLE
Uploading files that are not present in Google Drive

### ISSUE THREAD

**Issue by Issam2204** [odeke-em/drive#163]
Hello! First off thank you very much for your efforts! This piece of software is simply magnificent!

I'm a total ignorant in terms of programming/scripting, so you are warned if my question is a bit stupid :)

I have a 'Drive' folder in my home directory (local computer). I regularly put files there. What I'd like to do is to set a cron job that every 12h executes a "drive push". Since my purpose is backup, is it possible for drive to push content that is present locally but not on my Google Drive account, without however deleting anything (locally or remotely)? Perhaps drive can check two parameters (size and file name) and if they match it will not upload that file/folder from local to the cloud (since it has understood that it is the same file/folder). 

Perhaps this is already possible and I simply don't know how to do it :)

Thank you for your attention!

**Comment by odeke-em** [comment]
Hello @Issam2204 thank you for the kind words and welcome to drive!

Yes in deed, you can do it like this:
```shell
$ drive push --no-prompt <your_parameters>
```

**Comment by Issam2204** [comment]
Thank you very much odeke-em for the very prompt answer!

I will try it right away!

**Comment by odeke-em** [comment]
For sure let me know how that goes. `--no-clobber` can work for both pull and push.

**Comment by Issam2204** [comment]
Thank you odeke-em! The --no-clobber worked wonderfully!

At first I didn't use it and I relied only on --no-prompt. I deleted all my files by mistake. It doesn't matter:

1) I wanted to delete everything anyway
2) they are still in the trash if I need anything

One last question: I also use -ignore-checksum to have a faster execution. How does drive in this case know if the files in local are the same of those in remote?

Thank you again!

**Comment by odeke-em** [comment]
Oops, you can untrash files btw by
```shell
$ drive untrash [the_file_paths ...]
```

Yes in deed, `--ignore-checksum` will make things faster. In this case, it will just compare sizes, names, modification dates and mimeTypes to know if the files are the same. There is a PR https://github.com/odeke-em/drive/pull/128/files to make it the default case since this appears to be the common case.

**Comment by Issam2204** [comment]
Perfect! Thank you again for everything!

Have a great day/evening :)

**Comment by odeke-em** [comment]
Thank you too, and as always feel free to reach out in case of any ideas, questions or issues.
Have a great day/evening too :)
