### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by federico-catalano** [odeke-em/drive#168]
hi
when i try to run the install command "go get -u github.com/odeke-em/drive/cmd/drive" , i obatain an error....
package github.com/odeke-em/drive/cmd/drive: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by odeke-em** [comment]
Hello @federico-catalano welcome to drive!
As for this error you'll need to set your GOPATH e.g if you are on Linux
```shell
$ cat << ! >> ~/.bashrc
> export GOPATH="\$HOME/gopath"
> export PATH="\$GOPATH:$GOPATH/bin:$PATH"
> !
```

**Comment by federico-catalano** [comment]
ok everything works fine.
Thanks
