### ISSUE TITLE
"sync" option?

### ISSUE THREAD

**Issue by huang-jy** [odeke-em/drive#169]
Can we have a new option for "sync" which synchronizes files between sides with the option of prioritising one side or the other?

drive sync --local --> same as "drive push", but does not delete local files
drive sync --remote --> same as "drive pull", but does not delete remote files

**Comment by odeke-em** [comment]
Hello @huang-jy welcome to drive and good to hear from you.
`--no-clobber` should not perform any deletions.

**Comment by huang-jy** [comment]
Thanks, I always thought "clobber" meant overwriting, not deleting :P
 
But I'll check that option when I get home this evening. Thanks :D

**Comment by odeke-em** [comment]
Good point. Yes clobber avoids an overwrite but also serves to avoid any operations that aren't additions. Also usage of an option like `sync` might be tricky at least for now since we don't do delta uploads and things that might be alluded to from `sync` :) for sure once you try it please let me know what you think and feel free to reopen this issue if the needs persist or provide some feedback, tips or requests -- that'll be greatly appreciated.
Cheers,
Emmanuel

**Comment by huang-jy** [comment]
Here's my test/

Add new file locally and push -- successful
Add new file remotely and push -- successful
Add new file locally and pull -- local file deleted
Add new file locally and pull with no clobber flag set to true: file not deleted -- successful
Add new file locally and push with no clobber flag set to true: file added -- successful

So the no-clobber flag seems to work perfectly :D

**Comment by huang-jy** [comment]
However, no-clobber stops syncing of modified files, so i can either have drive not delete files missing one from side or successfully push modified files -- but not both.

**Comment by odeke-em** [comment]
@huang-jy in deed, I'll be spinning up an option for one to provide which operations to exclude, watch this space!

**Comment by odeke-em** [comment]
Please get the latest, I've spun up the ability for you to exclude some operations e.g:

```shell
$ drive pull --exclude-ops "delete,update" content
$ drive push --exclude-ops "create" sensitive_old_files
```

**Comment by TiTi65** [comment]
Hi !
As I undertand the last commands:
It will :
- tranfert to local without delete or update
- transfert to remote withour create

But I'm not sure to understant the "content" and "sensitive_old_files" options .

I'm looking for a sync too even on demand . . .

**Comment by canpolat** [comment]
@TiTi65 "content" and "sensitive_old_files"  are not options. They are just placeholders for your files or directories. Here is an example:

    drive pull --exclude-ops "delete,update" my_image.jpg
