### ISSUE TITLE
unexpected fault address 0x7f1800000011

### ISSUE THREAD

**Issue by santirodrigo** [odeke-em/drive#170]
Working in Ubuntu 14.04 64 bits drive push and pull operations frequently generate the following error:

```
Resolving...
unexpected fault address 0x7f1800000011
fatal error: fault
[signal 0xb code=0x1 addr=0x7f1800000011]

goroutine 6 [running]:

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

goroutine 1 [select]:
code.google.com_p_goauth2_oauth.updateToken.pN41_code.google.com_p_goauth2_oauth.Transport
	/home/santirodrigo/code/gocode/src/code.google.com/p/goauth2/oauth/oauth.go:419
code.google.com_p_goauth2_oauth.Refresh.pN41_code.google.com_p_goauth2_oauth.Transport
	/home/santirodrigo/code/gocode/src/code.google.com/p/goauth2/oauth/oauth.go:355
code.google.com_p_goauth2_oauth.getAccessToken.pN41_code.google.com_p_goauth2_oauth.Transport
	/home/santirodrigo/code/gocode/src/code.google.com/p/goauth2/oauth/oauth.go:319
code.google.com_p_goauth2_oauth.RoundTrip.pN41_code.google.com_p_goauth2_oauth.Transport
	/home/santirodrigo/code/gocode/src/code.google.com/p/goauth2/oauth/oauth.go:285
github.com_odeke_em_google_api_go_client_drive_v2.Do.pN63_github.com_odeke_em_google_api_go_client_drive_v2.FilesListCall
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/google-api-go-client/drive/v2/drive-gen.go:4090
github.com_odeke_em_drive_src.findByPathRecvRaw.pN36_github.com_odeke_em_drive_src.Remote
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/src/remote.go:622
github.com_odeke_em_drive_src.findByPathRecv.pN36_github.com_odeke_em_drive_src.Remote
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/src/remote.go:636
github.com_odeke_em_drive_src.findByPath.pN36_github.com_odeke_em_drive_src.Remote
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/src/remote.go:179
github.com_odeke_em_drive_src.FindByPath.pN36_github.com_odeke_em_drive_src.Remote
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/src/remote.go:183
github.com_odeke_em_drive_src.changeListResolve.pN38_github.com_odeke_em_drive_src.Commands
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/src/changes.go:120
github.com_odeke_em_drive_src.Pull.pN38_github.com_odeke_em_drive_src.Commands
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/src/pull.go:53
main.Run.pN12_main.pullCmd
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/cmd/drive/main.go:334
github.com_rakyll_command.Run
	/home/santirodrigo/code/gocode/src/github.com/rakyll/command/command.go:155
github.com_rakyll_command.ParseAndRun
	/home/santirodrigo/code/gocode/src/github.com/rakyll/command/command.go:162
main.main
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/drive/cmd/drive/main.go:76

goroutine 3 [syscall]:
	goroutine in C code; stack unavailable

goroutine 4 [chan receive]:
spinner.$nested0
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/cli-spinner/spinner.go:100
created by github.com_odeke_em_cli_spinner.spin.pN39_github.com_odeke_em_cli_spinner.Spinner
	/home/santirodrigo/code/gocode/src/github.com/odeke-em/cli-spinner/spinner.go:80
```

The error appears "randomly", and if you try several times the same operation it finally succeeds.

**Comment by shaggytwodope** [comment]
please include how you installed drive. as the version isn't always whats current from the repo.

**Comment by santirodrigo** [comment]
Well, the problem has become bigger... I have reinstalled go and drive to make sure that the problem wasn't because a bad installation. Everything in the installation OK, but now drive is not detecting my local files at all! Whenever I try to push something it prompts something like" '/xxxxx' aka '~/Google\ Drive/xxxxx' doesn't exist locally nor remotely". And if I pull any directory, it downloads all the contents, as if I had no files locally stored. And of course, the error that I have mentioned in this issue is still appearing...

**Comment by santirodrigo** [comment]
By the way, my 'drive version' output is:

drive version 0.1.9
Commit Hash: '45c533e38624aa3611e2d2a94c97c4a158ce05b6'
Go Version: xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1
OS: linux/amd6

**Comment by odeke-em** [comment]
Hello @santirodrigo thank you for reporting this and for the information, and welcome to drive. If you wouldn't mind, could you do  a `go get -u github.com/odeke-em/drive/cmd/drive`.
Also I'll take a look at xgcc installs, in the past I've found xgcc to be trippy but who am I to blame the compiler :) I'll do a couple of tests in about 4 hours when I get back home to make sure this wasn't a bug that I might have introduced.
Also you can set  a $GOPATH in your ~/.bashrc file, this way you'll be able to use `go get` smoothly.

**Comment by santirodrigo** [comment]
Good! Now all seems to be going smoothly. For the moment no strange errors, and `drive` has recognized again my files. I'll push and pull several times to test it. Thanks!

**Comment by odeke-em** [comment]
Would you mind installing go from source instead of gccgo because I've used it a few times from one of my machines and I found it was tripping out quite a bit.

**Comment by santirodrigo** [comment]
Done. It seems that everything is working well. No problems after some push and pulls. Thank you very much for your fast answers and attention. I am closing the issue, as it seems to be solved.

**Comment by odeke-em** [comment]
Yeah I've found  gccgo to be a pain and randomly crashing, so I'd encourage installing go from source. Thank you for reporting this and please don't hesitate to reach out in case of any ideas or issues.
