### ISSUE TITLE
Push and Pull 

### ISSUE THREAD

**Issue by federico-catalano** [odeke-em/drive#171]
Hi,
first of all sorry for the trivial question but if i want to use only one of my google drive's folder?
I used the Google drive's path but for some unknown reason some nested files and folders are not loaded into local folder ( in fact i have some empty folders or missing files or even missing folders).
"drive pull --matches  /my files/my folder"
or
"drive pull -matches . * /myfolder/. *

**Comment by pez252** [comment]
You should be able to pull a single folder using drive pull /my files/my folder.

Here is the output from a pull I just ran against a folder I just created:
> user@hostname ~/gdrive $ drive pull test
> Resolving...
> + /test
> + /test/a
> Addition count 2 src: 1.32MB
> Proceed with the changes? [Y/n]: y
> 1388670 / 1388670 [=================================================] 100.00 % 0

**Comment by odeke-em** [comment]
Thank you @pez252 for helping out on this! @federico-catalano `--matches` does prefix matching not wild card matching, please take a look at the README as it shows examples and some bit of info.
