### ISSUE TITLE
`drive pull` pulls all files again

### ISSUE THREAD

**Issue by shunzh** [odeke-em/drive#173]
I have run `drive pull` to download all the files. Even if I don't make any changes on the remote, when I run `drive pull`, everything is downloaded again as if the local directory is empty. I expect only the differences are pulled.

Please let me know what other details I need to provide. Thanks!

**Comment by Issam2204** [comment]
Hi! Have you tried using the option "--no-clobber" ? Also, to speed things up you could use "-ignore-checksum".

Hope this helps!

**Comment by shunzh** [comment]
Thanks, Issam2204. I have run `drive pull -no-clobber -ignore-checksum` and still have the same issue. I got a long list of all my files (which already exist locally) and 

```
Addition count 2454 src: 3.11GB
Proceed with the changes? [Y/n]:
```

Would the giant size be a problem?

**Comment by odeke-em** [comment]
Hello @shunzh thank you for reporting this and welcome to drive!
@Issam2204 thank you for helping out with solving this issue :) welcome to drive too!

As mentioned in the README, clashing file names within the same folder will trip you out since neither your file system can even handle it. I pushed up a change yesterday that aborts on duplicates until you can selectively choose which to change. Otherwise please provide your drive version, and no a giant size shouldn't be problem.

**Comment by shunzh** [comment]
Hello @odeke-em ,

I am using the version 0.1.9. I installed using go. I don't think I have clashing file names in a same folder. Or maybe there are but I am not aware, but the pull command doesn't warn me anything..
Thanks!

**Comment by odeke-em** [comment]
Thank you very much, your issue was very valid, this is a bug that I introduced yesterday evening. That you'll see from here.
```diff
diff --git a/src/changes.go b/src/changes.go
index 09fe24e..8031644 100644
--- a/src/changes.go
+++ b/src/changes.go
@@ -98,7 +98,7 @@ func (g *Commands) resolveToLocalFile(relToRoot, fsPath string) (local *File, er
        }
 
        localinfo, statErr := os.Stat(fsPath)
-       if !os.IsNotExist(statErr) { <- This is where I put the bug :) if there is no err, no need to trip out
+       if statErr != nil && !os.IsNotExist(statErr) {
                err = statErr
                return
        }
```
 My apologies. Please get the latest from master and your issue should be solved.

Thank you for the reporting this.

**Comment by shunzh** [comment]
Great! I'm glad that I helped.

I got `Everything is up-to-date.` as expected.

**Comment by odeke-em** [comment]
Cheers and please don't hesitate to reach out in case of anything.
