### ISSUE TITLE
OAuthError: Refresh: Token expired

### ISSUE THREAD

**Issue by jbracegirdle** [odeke-em/drive#176]
I'm not sure if this is an issue or the desired behavior. I authorized the program yesterday using
```
drive init
```
This morning when I try to check my quota I get
```
Get https://www.googleapis.com/drive/v2/about?alt=json: OAuthError: Refresh: Token expired; no Refresh Token
```
If I try init again I get
```
drive init
Visit this URL to get an authorization code
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=xxxxxxxxxxxx
```
Do you have to do the authorization every time you want to use the program?

**Comment by odeke-em** [comment]
Hello @jbracegirdle welcome to drive!
Were you able to actually visit the URL and review and give drive the appropriate permissions?
And no you only have to do this once, but make sure to visit the URL using your web browser then paste the authorization code. To see what apps you have given permission to your account visit https://security.google.com/settings/security/permissions

**Comment by jbracegirdle** [comment]
Thanks @odeke-em drive seems to be an excellent solution for sharing files.
I did manage to visit the URL and give drive ther permissions it needs. I'm using 2 Google accounts so that may be the problem. Chrome (or I) may have been confused as to which account was authorized.
https://security.google.com/settings/security/permissions Showed that Drive was authorized yesterday and remained the same after I had authorized it again today. Drive is working again. I'll see how it goes tomorrow.

Many thanks,

John

**Comment by odeke-em** [comment]
@jbracegirdle thank you for the kind words and for trying it.
What I suspect happened is that you might have tried before `drive init` with one account then maybe realized you wanted to enter another account then probably hit CTRL-C, this is a theory that could explain the rogue mis authorization.

**Comment by odeke-em** [comment]
As a suggestion, you can do `drive init <path>` e.g `drive init ~/my_google_account_for_school` so that you have it initialize in paths that make sense directly to you.

**Comment by jbracegirdle** [comment]
Thanks for the suggestions and quick reply. Drive is installed on a Raspberry Pi and I used ssh to access it. I was running Chome on my Windows laptop to authorize it. I did test that drive was authorized to the correct account yesterday and it uploaded files to the correct account. I would have thought if I had made a mistake with the authorization it would have either failed or uploaded to my other Google account.
It's working again though now :+1:
I'm not sure when it will need to use a refresh token, or how OAuth really works, but I'll let you know if I get the error again.

**Comment by odeke-em** [comment]
If it is related to the token expiring during pushes after a long time then I'd advise you to checkout issue https://github.com/odeke-em/drive/issues/116. However when initialized freshly, this shouldn't be a problem :) Thank you for reporting this.

**Comment by odeke-em** [comment]
@jbracegirdle please get the latest from master, this issue should be fixed :)
