### ISSUE TITLE
[Dev Help] Building a binary from a testing environment/version for drive (on Linux)

### ISSUE THREAD

**Issue by setempler** [odeke-em/drive#179]
To test a commit/change, I ran the following bash script to generate a binary:

```shell
#!/usr/bin/env bash

com=$(git log | head -n 1 | awk '{print $1}')

# export go path
echo "# Exporting GOPATH"
export GOPATH=$PWD

# update dependencies
echo "# Downloading dependencies/imports"
go get -d -u github.com/setempler/drive/cmd/drive

# replace source folder in includes
echo "# Replacing import paths in cmd/drive/main.go"
sed -i 's|github.com/odeke-em/drive/src|src|' cmd/drive/main.go

# modify stdout for pull and push
echo "# Modifying stdout for pull/push to highligh testing version"
sed -i "s|Resolving\.\.\.|TEST VERSION from commit $com - Resolving|" src/pull.go src/push.go

# create link to source
echo "# Add link to src for imports"
[[ -h src/src ]] && rm src/src
ln -sf $PWD/src src/src

# build 'main' binary
echo "# Building binary 'drive-testing'"
go build -o drive-testing cmd/drive/main.go 

# restore state
echo "# Reset modifications for testing"
git checkout -- cmd/drive/main.go src/pull.go src/push.go

echo "# Done"
```

To use current modifications (e.g. when not pushed to origin, or using a branch different than master), those lines are crucial to use the modified content from `src/*.go` files:

```
sed -i 's|github.com/odeke-em/drive/src|src|' cmd/drive/main.go
ln -sf $PWD/src src/src
```

I could not figure out how to change the dependencies/imports to a different branch from a github repository. Any advice on improving this build procedure for a testing version is appreciated!

Sven

**Comment by odeke-em** [comment]
Hello again @setempler. This is great point. Unfortunately I've found with Golang you have to manually change the imports :( which can get quite annoying. However testing out different branches and patches you can do normally with git. Personally I've only had to `git fetch --all && git checkout <branch_name> && go get $(pwd)`.
I too would happy for suggestions on improving this experience.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Oh btw I should mention that if you wanted to setup your own clone still using the same code but pointing to your path,
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git remote set-url origin git@github.com:<your_username>/drive.git
```

**Comment by odeke-em** [comment]
Closing this issue due to lack of a response and you can build your setup by changing your origin url to point to your clone in the worst case.
