### ISSUE TITLE
Duplicate directories created

### ISSUE THREAD

**Issue by vaiby** [odeke-em/drive#186]
Hi, 
   I am trying to upload a large (~2gb) and hugely nested (~10 to ~15 level deep) directory with loads of files (~20,000). Unfortunately, midway through the upload the drive client starts creates a new directory with same name and starts uploading there. It happens lower down the tree as well, and is entirely unpredictable from my side. (I am using version 0.1.6)

    I also faced this when there was significantly less nesting, but then I was able to manually merge remotely and the client would start behaving all good.

   a) I wanted to report this issue.
   b) It would be useful to merge duplicate directories on the remote side, which would allow me to issue a "merge" once I am done to solve this issue. That is an enhancement request :)

Vaibhav
PS: Thanks for the excellent client otherwise!

**Comment by vaiby** [comment]
Ok, just noticed, I was not on the latest client. Have updated, and uploading right now. Fingers crossed!

**Comment by vaiby** [comment]
It seems to be working, except that I am not done yet. The good thing is the new client warns about duplicate directories (probably a leftover of previous uploads) so that I can manually delete them. 

   The bad thing is after each push I have to do another push and it discovers a few more files to update -- it has happened over 5 times now (most of these times, including the last two, it has not discovered any "duplicate directory" which it otherwise faithfully warns about. 

   Why should that be?

**Comment by odeke-em** [comment]
Hello @vaiby thank you for reporting this and welcome to drive. Pardon the late reply, it was night on my side.
Thanks for the self analysis, I'll take a closer look at it when I get home in about 10 hours.

**Comment by odeke-em** [comment]
Ping.

**Comment by odeke-em** [comment]
Please get the latest from master.

**Comment by vaiby** [comment]
So far, no problem. But still to subject to heavier tests: will report when I manage the same and if I encounter any issue. Thanks!

**Comment by odeke-em** [comment]
Ping!

**Comment by glebm** [comment]
I have just encountered issue when pushing a git repository to drive (lots of small directories in .git/objects), although all of the duplicate directories were completely empty in my case.

Using the version I have just installed with `go get -u github.com/odeke-em/drive/cmd/drive`.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
If you get the latest code from master, this should be fixed. You can do so by:
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

Closing this issue. Please re-open if it persists.
