### ISSUE TITLE
Json error and some files gets duplicated on server

### ISSUE THREAD

**Issue by Lesek8** [odeke-em/drive#191]
Hello,
I ran into an issue which I cannot solve. When using drive push, some files report this error:
json: cannot unmarshal string into Go value of type float64 
it is not random, it is generated by same files every time.
File is uploaded correctly though. But, next time I run drive push, all files in a directory where this error occurred are uploaded again, like if they were not present on server. This results in duplicates on server side.
I am not sure why this happens, I tried to modify local file in several ways (it is a jpeg image) but I did not found anything helpful. It seems that it is something that Google reports back AFTER upload, because the file is actually uploaded OK.
One of the files that causes problems for me is zipped here:
https://drive.google.com/file/d/0B6X7CRPUq_k9QVhkYjJuWjk4cTA/view?usp=sharing
I hope you will be able to reproduce this behaviour, if not I will at least know it is something on my side. But this file caused problem every time I tried tu push it.
Thanks for any help!

**Comment by odeke-em** [comment]
Hello @Lesek8 welcome to drive and thank you for reporting this.
Would you mind giving me your `drive version`? How did you install drive? Also a screenshot of the whole error would be useful.

**Comment by Lesek8** [comment]
Hello, sorry for late response. 
I install drive from repository, I used this for setup: https://github.com/odeke-em/drive/blob/master/platform_packages.md
Drive version is 0.2.1 - I made sure that I use latest version before reporting this.
OS is Ubuntu 14.04.2
Screenshot shows situation when I run drive push two times. First, new file (and folder "test") is created and error is shown after file upload. I run drive push once more and as you see, drive offers me to upload file again. If I agree, the file will be uploaded again. And because Google allows same names in one directory, this results in two files with the same name.
![drive](https://cloud.githubusercontent.com/assets/12380931/7555601/d27b34a4-f750-11e4-92d1-167b10fba67c.jpg)

**Comment by odeke-em** [comment]
`drive verison`?
Please provide the full output so I can see the commit hash, exact OS specs etc.

Also I haven't yet encountered the need to Unmarshal a float64 value in drive itself. That you can test out if you have the source, by
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive && grep -Rin 'float64' *
```
the only hits should be for the progress bar.

**Comment by Lesek8** [comment]
I do not have source, I used a package from repository 
drive version output is attached, but I do not see there any other important information.
It happens after upload of file is finished, so maybe something is wrong with Google response confirming that file was received?
![drive version](https://cloud.githubusercontent.com/assets/12380931/7555773/045aeb0e-f756-11e4-9130-5704e7c4b3e0.jpg)

**Comment by odeke-em** [comment]
Let me summon up our Linux wizard and distributor @shaggytwodope. Were you able to run `drive-gen` during the packaging?
And you can confirm that the file was actually uploaded?

**Comment by Lesek8** [comment]
I did not made package myself, I used one from repository.
Now I used source and problem is exactly the same. But drive version shows different output, see image. Most important is probably
Commit Hash: '8f11b79b30145e2c7bcf0428f9e91da605cd1877'
I confirm that file is uploaded OK - every time I run drive push, new copy is created (screenshot attached)
![drivefile](https://cloud.githubusercontent.com/assets/12380931/7555936/15172f3c-f75d-11e4-8cee-c342ba2a71b1.jpg)

![drive version 2](https://cloud.githubusercontent.com/assets/12380931/7555918/540ba9bc-f75c-11e4-84c8-82bbfdbdfacc.jpg)

**Comment by shaggytwodope** [comment]
@odeke-em Building seems to give me a funky error

`cd /build/buildd/drive-0.2.1/src/github.com/odeke-em/drive/drive-gen/ && ./drive-gen
exit status 128
make: *** [binary-arch] Error 255
dpkg-buildpackage: error: /usr/bin/fakeroot debian/rules binary gave error exit status 2`

Really tempted to hardcode lol. But i'll figure this out soon hopefully. fetching the sources and generating drive-gen goes fine up til executing and it gives me that stuff. boy I hate ubuntu's build stuff. To bad I don't have a webhost... be much easier >.<

**Comment by odeke-em** [comment]
Hey @shaggytwodope, I hear ye. Although i think you meant to compile or just plain go run drive-gen first since it is actually a go file and not an executable. I am and will be away from my computer for a bit..

**Comment by Lesek8** [comment]
Hello,
I tried to figure out where is this error generated and I ended up with this:
When uploading new file, error message "json: cannot unmarshal string into Go value of type float64" is generated by this  of code:
if uploaded, err = req.Do(); err != nil {
   return
}
in function upsertByComparison, file remote.go
seems like the req.Do() returns this error, but, this function is from Google API, not this project - correct?

**Comment by odeke-em** [comment]
Hello @Lesek8 thank you for the investigation. In deed, not doing any unmarshalling of strings into float64 I wish it were possible for us to trace where the error is. If you wouldn't mind, could you send me the created binary at $GOPATH/bin/drive (your binary btw doesn't give away your OAuth token nor security keys). If you can consistently reproduce this please let me know.

A wild theory I could think of might be your go version, since lots of stuff with json-Marshalling fixes have been made lately.

**Comment by Lesek8** [comment]
Hello,
binary sent to e-mail from your profile here, hope it will arrive. Thanks for the go version suggestion, I will certainly try this way.
I even tried to make program continue, ignoring this error - file is is uploaded OK, so why not... But of course it did not work, errors does not vanish that easily.

**Comment by odeke-em** [comment]
Thanks @Lesek8, I received. Then it occured to me that my linux/amd64 machine got fried a little while back. However, I'll get a VM to test it out.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Cannot reproduce this issue unfortunately. Please re-open if it persists.
