### ISSUE TITLE
Drive only excutable form install directory and other issues

### ISSUE THREAD

**Issue by thetallone** [odeke-em/drive#192]
I installed drive using the instructions however i'm only able to execute it from 

/usr/local/go/src/bin/drive

so i can't run it form anywhere using the drive command.

Also i'm unable to push using

./drive push /tmp/drive.txt

I get "no drive context found; run `drive init` or go into one of the directories (sub directories) that you performed `drive init`"

The file I want to upload has to be in the /usr/local/go/src/bin/ directory?

Also how do I force an upload with the "Proceed with the changes? [Y/n]:" prompt?

**Comment by odeke-em** [comment]
Hello @thetallone welcome to drive!
Now if you installed Go properly you should have set your GOPATH in your env that you can do like this:
```shell
$ cat << ! >> ~/.bashrc
> export GOPATH=\$HOME/go
> export PATH=\$GOPATH:\$GOPATH/bin:\$PATH
> !
```
To make an upload proceed, as asked by the prompt, hit 'y". Also please take a look at the README file.

**Comment by thetallone** [comment]
Hi thanks for the reply, I tried your gopath recommendations and they didn't work. I also tried these are my various paths to go.

/usr/local/go
/usr/local/go/.hg/store/data/src/go
/usr/local/go/.hg/store/data/src/cmd/go
/usr/local/go/.hg/store/data/src/pkg/go
/usr/local/go/.hg/store/data/src/lib/go
/usr/local/go/.hg/store/data/misc/vim/ftplugin/go
/usr/local/go/.hg/store/data/misc/vim/autoload/go
/usr/local/go/bin/go
/usr/local/go/pkg/linux_arm/go
/usr/local/go/src/go
/usr/local/go/src/cmd/go
/usr/local/go/misc/makerelease/darwin/etc/paths.d/go
/usr/bin/go
/usr/lib/go
/usr/lib/go/pkg/linux_arm/go
/usr/share/go
/usr/share/go/src/go
/usr/share/go/src/cmd/go


I also checked the readme before posting this issue and only thing I could find that I thought would relate is -force but this just forces the upload even if they are the same not disabling the prompt.

**Comment by odeke-em** [comment]
Why don't you just install Go the proper way as you'll find from here https://golang.org/doc/install or from the README?
If you want to disable the prompt, `--no-prompt`?
Also this is an issue that has been duplicated before and closed as seen from https://github.com/odeke-em/drive/issues/168 https://github.com/odeke-em/drive/issues/124 and others.

**Comment by thetallone** [comment]
Because it's on a raspberry pi.

In the readme https://github.com/odeke-em/drive/blob/master/README.md it does not mention the --no-prompt command?

**Comment by odeke-em** [comment]
I've installed Go on my raspberry pi btw: in fact I use it to test drive quite a bit. I also build Go from source on it :)
True, but the `drive push -h`, or `drive pull -h` does show it right?

**Comment by odeke-em** [comment]
Oh btw after you've set your GOPATH in your .bashrc I don't think you reloaded it. You can do that by
```shell
$ source ~/.bashrc
```
or by opening a new shell.
I think you might have missed that step.

**Comment by thetallone** [comment]
ok I don't think it's going to work for me i've tried different PATH combinations but 'drive' still doesn't work.

go version go1.4.2 linux/arm

**Comment by odeke-em** [comment]
Could you provide the output of these following commands if you don't mind?
```shell
$ cat ~/.bashrc | tail -n 6
$ echo $GOPATH
$ whereis go
$ file $GOPATH/bin/drive
```

**Comment by thetallone** [comment]
cat ~/.bashrc | tail -n 6
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
(this is probably because I deleted the previous GOPATH entries as it wasn't working)

echo $GOPATH
(blank) desptie setting path?

 whereis go
go: /usr/bin/go /usr/lib/go /usr/bin/X11/go /usr/local/go /usr/share/go /usr/share/man/man1/go.1.gz

file $GOPATH/bin/drive
/bin/drive: ERROR: cannot open `/bin/drive' (No such file or directory)

**Comment by odeke-em** [comment]
Okay, I don't think you set your GOPATH as I had mentioned in my first comment.
Could you please set it like this in your ~/.bashrc?
```shell
export GOPATH=$HOME/go
export PATH=$GOPATH:$GOPATH/bin:$PATH
```
or follow the instructions I posted above in https://github.com/odeke-em/drive/issues/192#issuecomment-100668680
and once you've saved
```shell
$ source ~/.bashrc
```

**Comment by thetallone** [comment]
ok done it again

cat ~/.bashrc | tail -n 6
export GOPATH=$HOME/go
export PATH=$GOPATH:$GOPATH/bin:$PATH

echo $GOPATH
/root/go

whereis go
go: /usr/bin/go /usr/lib/go /usr/bin/X11/go /usr/local/go /usr/share/go /usr/share/man/man1/go.1.gz

file $GOPATH/bin/drive
/root/go/bin/drive: ERROR: cannot open `/root/go/bin/drive' (No such file or directory)

This would be because go isn't in /root/go as per my previous comment

/usr/local/go
/usr/local/go/.hg/store/data/src/go
/usr/local/go/.hg/store/data/src/cmd/go
/usr/local/go/.hg/store/data/src/pkg/go
/usr/local/go/.hg/store/data/src/lib/go
/usr/local/go/.hg/store/data/misc/vim/ftplugin/go
/usr/local/go/.hg/store/data/misc/vim/autoload/go
/usr/local/go/bin/go
/usr/local/go/pkg/linux_arm/go
/usr/local/go/src/go
/usr/local/go/src/cmd/go
/usr/local/go/misc/makerelease/darwin/etc/paths.d/go
/usr/bin/go
/usr/lib/go
/usr/lib/go/pkg/linux_arm/go
/usr/share/go
/usr/share/go/src/go
/usr/share/go/src/cmd/go

**Comment by odeke-em** [comment]
Now that you've set it right
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by thetallone** [comment]
go get github.com/odeke-em/drive/drive-gen && drive-gen
go tool: no such tool "5c"

**Comment by odeke-em** [comment]
Sorry for the late reply.
This is probably for not installing go right. I'd recommend whenever you have time reinstalling as opposed to guessing the paths to use, it should be a four step process.
In the meantime, if you'd like, I've created for you an ARM binary right off my RaspberryPi and published a special release for you here
https://github.com/odeke-em/drive/releases/tag/v0.2.1-arm-binary

After downloading it, place in your $GOPATH/bin like this
```shell
mv drive-arm-binary $GOPATH/bin/drive
```

**Comment by thetallone** [comment]
Ok thanks I'll give that a go, I have other users on the pi so didn't want
it to install/run from /root/go . Go works it's just the paths are
different.

**Comment by odeke-em** [comment]
Yeah the solution provided is user agnostic. However, installing user space programs to root doesn't seem like the best idea :) Please try again probably using a well configured path and then we can resolve this issue.

**Comment by thetallone** [comment]
ok I managed to get the paths sorted with my previous install and now I can
run the drive command from anywhere however when I do a

drive /tmp/drive.txt

I get

no drive context found; run `drive init` or go into one of the directories
(sub directories) that you performed `drive init`

**Comment by odeke-em** [comment]
That's good to know you sorted that out!

Run `drive init <your_path>` and that will be the folder you'll mount your drive e.g
```shell
$ drive init ~/personal_drive
# Then after the authorizations, you can use it
$ cd ~/personal_drive
# Now you can do stuff inside drive e.g pull, push etc
$ pwd
$HOME/personal_drive
$ mkdir -p test1/test2/test3 && cd test1/test2/test3
$ date >> flux.txt && drive push flux.txt
```

**Comment by odeke-em** [comment]
Closing this issue since it now requires the user reading the manual.
