### ISSUE TITLE
[question] drive list -r

### ISSUE THREAD

**Issue by aytacyildiz** [odeke-em/drive#194]
what does ```-r=false: recursively list subdirectories``` flag do?
when i use, it doesn't make any changes to output :confused: 

```
aytac@manjaro ~/grive$ drive version
drive version: 0.2.1
Commit Hash: '56c6eb5fe5c8a20f68363f3e8d67ecca463a3419'
Go Version: go1.4.2
OS: linux/amd64
```

```
aytac@manjaro ~/grive$ drive list
/foo
/bar
/baz
/qux
aytac@manjaro ~/grive$ drive list -r
/foo
/bar
/baz
/qux
```
btw i changed the folder names for privacy reasons :wink:

**Comment by odeke-em** [comment]
Hello @aytacyildiz, welcome to drive!
For listing subdirectories, I'd recommendusing flag `-m` or max-depth(recursion depth) which takes an integer so `drive list -m 4` would be traversing 4 levels deep.
Please let me know if this makes sense.

**Comment by aytacyildiz** [comment]
@odeke-em Hımm, okey i will use it. Thank you for response.
