### ISSUE TITLE
[question] recovering files locally after deletion.

### ISSUE THREAD

**Issue by isaiasneto** [odeke-em/drive#196]
After a pull action, the drive app deleted a localy folder. Can I recover this folder with a program like testdisk?

**Comment by odeke-em** [comment]
Hello @isaiasneto welcome to drive!
Unfortunately a local delete as prompted by the program is permanent and you'll be at the mercy of your kernel + file manager. I have never used testdisk so I wouldn't know how to recover your local folder.
The other ways I know of recovering files might need to have the process still active, however I don't think those would be relevant to your issue.

**Comment by isaiasneto** [comment]
Was very difficult to recover, but I succeed with UFS Explorer (http://www.ufsexplorer.com/download_pro.php). Thank you for your attention.

Best Regards, Isaias Neto.

**Comment by odeke-em** [comment]
Thank you for the information, and good to know you were able to recover it. In the future, you can exclude certain operations e.g
```shell
$ drive pull --exclude-ops "delete" ...
```
