### ISSUE TITLE
Feature request for a resource configuration file

### ISSUE THREAD

**Issue by nkmathew** [odeke-em/drive#199]
Something like a **.driverc** file? I use *--hidden=true* often and would like something other than aliases.

**Comment by odeke-em** [comment]
Hello @nkmathew thank you for reporting this and welcome to drive!
+1, great suggestion. So would  local .driverc in your .gd dir as well as global ~/.driverc suffice?

**Comment by nkmathew** [comment]
In the home folder preferably. Placing one in the .gd folder seems unnatural

**Comment by odeke-em** [comment]
I see, although drive supports an infinite number of accounts mounted, so maybe multiple different configurations. This is analogous to have a special .driveignore file for each account.

**Comment by nkmathew** [comment]
Wasn't aware of that. Sounds fair

**Comment by odeke-em** [comment]
I'll work on this later on when I get home, this is going to be a big win for lots of users because then defaults can be set once and for all. Thanks again for reporting this.

**Comment by dolohow** [comment]
:+1: for this

**Comment by paulgregg** [comment]
+1
I'd like to be able to set a default of --exclude-ops "delete" so all push/pull commands don't delete anything, ever.   My use case is backing up the irreplaceable data (personal photos) from my NAS (60GB out of 7TB data). I don't need to backup movies or tv, so I want to push Photos folder only. If when I pull, I don't want to accidentally delete everything local that isn't in Drive.

**Comment by odeke-em** [comment]
Sorry for the really late reply folks. I had actually implemented most of it in mid May as you'll see from commits in the PR https://github.com/odeke-em/drive/pull/259. However, I am not yet decided on how to get the unused flags per command, but I'll be working on that sometime this week. Please watch this space and thank you for your patience.

**Comment by nkmathew** [comment]
Did you manage to get it working?

**Comment by odeke-em** [comment]
Hello @nkmathew, unfortunately I haven't glued everything together yet. The trouble is piecing together the defaults and then the defined args: separately they are being parsed alright. What is left is figuring out if a flag was defined -- for that I worked on https://github.com/odeke-em/command/commit/3e1c027705d997ee25b982cc1d96fc5cfa64066e. I'll try one more thing that I just got an idea for, to correlate defined flags, rc-read/default flags.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/259. Thank you for requesting this feature  and for the patience. Please get the latest from master by running 
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
