### ISSUE TITLE
Broken help

### ISSUE THREAD

**Issue by GoGoris** [odeke-em/drive#202]
`drive -h` or `drive --help` gives only the following instead of any help information:
```
Usage of drive:
```

**Comment by odeke-em** [comment]
Hello @GoGoris welcome to drive!

This is a duplicate of https://github.com/odeke-em/drive/issues/45

**Comment by GoGoris** [comment]
Hello, sorry I missed that issue. Thanks for your help.

**Comment by odeke-em** [comment]
Hello @GoGoris please take a look at https://github.com/odeke-em/drive/pull/219 or get the latest from master. It should be fixed. Thank you for reporting this issue.
