### ISSUE TITLE
Silent pull?

### ISSUE THREAD

**Issue by somepad** [odeke-em/drive#203]
Is there any way to have a silent pull (without any output) and without any questions?
E.g.:
`Proceed with the changes? [Y/n]:Y`

**Comment by IS-smcleod** [comment]
I think you are looking for `-quiet` and `-no-prompt`.  Not sure if quiet implied no-prompt or not.

**Comment by odeke-em** [comment]
@IS-smcleod gave the right answer. Closing this.
