### ISSUE TITLE
[bug] emptytrash not work

### ISSUE THREAD

**Issue by sulicz** [odeke-em/drive#204]
The comand 
#drive emptytrash
only list files in trash but not remove any one of them. I do not know if there is bug in command or in description.

Thanks for hlep

**Comment by odeke-em** [comment]
Hello @sulicz thank you for reporting this issue and welcome to drive!
Sorry for the late reply, I was swamped today.
Please get the latest from master, I fixed this up in PR #205.
Thanks again.
