### ISSUE TITLE
release dependencies

### ISSUE THREAD

**Issue by n4cer** [odeke-em/drive#206]
There is a request to add drive to the gentoo portage tree. To make this easier it would be nice to have a "richer" release-tarball with less dependencies which have to be pulled. Perhaps you can bundle at least you own dependencies.

https://bugs.gentoo.org/show_bug.cgi?id=538398#c6

**Comment by vrusinov** [comment]
Not sure about Gentoo, but bundling is prohibited in many distros (e.g. Redhat/Fedora).

**Comment by odeke-em** [comment]
Hello @n4cer welcome to drive!
Thanks @vrusinov for getting this one.
@n4cer as for packaging and portage, I am not knowledgable in that area. However I'll summon up @shaggytwodope who packages drive plus other programs for Arch and Ubuntu Linux. He does a whole lot of packaging that I think could fit this use case. @shaggytwodope any ideas?

**Comment by shaggytwodope** [comment]
@odeke-em What he's referring to in this case is localizing some of the deps (downloading from one source rather then fetching across the net) this does make it somewhat easier for packagers and users in general in some use cases. Maybe you can take a look at https://github.com/jingweno/ccat/tree/master/Godeps/_workspace/src/github.com for an example.

Using go get to collect the needed deps is still ok to do I ebuilds as far as I can recall. Altho this policy may have changed, not the biggest gentoo user lol.

**Comment by odeke-em** [comment]
Ah I see, thank you for the explanation @shaggytwodope it makes sense. I'll take a closer look at how to get this in. Please ping me in about 48 hours if I haven't yet given an update on a solution for this, or feel free to pitch in ideas or PRs :)

**Comment by pacho2** [comment]
Thanks a lot odeke for your help :)

**Comment by odeke-em** [comment]
@pacho2 oops pardon the late reply :) and thank you for reminding me about this issue. I'll jump on it in about 5 hours when I get back home.

**Comment by odeke-em** [comment]
Hello folks, @n4cer @vrusinov @shaggytwodope @pacho2 please take a look at PR https://github.com/odeke-em/drive/pull/213.

**Comment by n4cer** [comment]
@odeke-em thanks for working on it!
i'm on holidays and will look at it in monday

**Comment by n4cer** [comment]
https://github.com/odeke-em/drive/pull/213 looks good, but I'm having trouble executing the described steps.

**Comment by odeke-em** [comment]
#213 fixed this. Please get the latest from master.
