### ISSUE TITLE
Push over 100%

### ISSUE THREAD

**Issue by attila-fovenyes** [odeke-em/drive#207]
After grive stopped doing its job on Ubuntu 14.04, installed drive.
I am trying to do a push from an existing folder (inherited from grive) containing sub folders and files.
It looks like the push never wants to end showing over 100% and the counter (29592330) goes higher than the sum of all the files being pushed.

This is the status message:

Proceed with the changes? [Y/n]:y
29592330 / 25151410 [====================================================================================================================================================] 117.66 % -5m8s

Any suggestions?

**Comment by attila-fovenyes** [comment]
After setting the right permissions on the files it was able to do a proper push with 100% results.

**Comment by odeke-em** [comment]
Hello @attila-fovenyes thank you for reporting this and welcome to drive!
That's cool that you were able to diagnose and solve the problem, I'll test out using drive without the appropriate permissions as per your hints and then improve the source code appropriately.
Cheers!
