### ISSUE TITLE
Wrong icon for ods files

### ISSUE THREAD

**Issue by GoGoris** [odeke-em/drive#215]
When I push my changed ods spreadsheet, its icon changes to the archive icon. 
Is this caused by a wrong mime type?

This is the archive icon that I mean:
![archive icon](https://ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_archive_x128.png)

**Comment by odeke-em** [comment]
Hello again @GoGoris thank you for reporting this.
In deed, that was an unknown mimeType for that extension. Please take a look at PR https://github.com/odeke-em/drive/pull/216

**Comment by odeke-em** [comment]
@GoGoris please get the latest from master, and thank you again for reporting this.

**Comment by GoGoris** [comment]
@odeke-em Thanks for the quick fix, but is still a different icon then when I would have uploaded the file on the website. On the website I get the excel icon and now I get a generic opendocument icon.

Opendocument icon:
![opendocument icon](https://drive-thirdparty.googleusercontent.com/128/type/application/vnd.oasis.opendocument.sheet)

Excel icon:
![excel icon](https://ssl.gstatic.com/docs/doclist/images/mediatype/icon_1_excel_x128.png)

Is this on purpose?

**Comment by odeke-em** [comment]
I see what you are saying. However, drive doesn't directly decide which icons the items will be assigned on the UI. Google Drive's machinery derives the appropriate icons based off the mimeType for that object. It then seems like Google Drive UI resolve od* and other open office documents to mimeTypes of their appropriate Google Docs equivalents e.g sheets, docs etc. On the other hand, drive is now diversely categorizing Open office documents mimeTypes as you'll see from https://github.com/odeke-em/drive/blob/8189f5d83129405119cbf003f83b0598e4eb7b46/src/misc.go#L363-375
or
```go
	"odt": "application/vnd.oasis.opendocument.text",
	"odm": "application/vnd.oasis.opendocument.text-master",
	"ott": "application/vnd.oasis.opendocument.text-template",
	"ods": "application/vnd.oasis.opendocument.sheet",
	"ots": "application/vnd.oasis.opendocument.spreadsheet-template",
	"odg": "application/vnd.oasis.opendocument.graphics",
	"otg": "application/vnd.oasis.opendocument.graphics-template",
	"oth": "application/vnd.oasis.opendocument.text-web",
	"odp": "application/vnd.oasis.opendocument.presentation",
	"otp": "application/vnd.oasis.opendocument.presentation-template",
	"odi": "application/vnd.oasis.opendocument.image",
	"odb": "application/vnd.oasis.opendocument.database",
	"oxt": "application/vnd.openofficeorg.extension",
```
Please let me know what your thoughts are.

**Comment by GoGoris** [comment]
So these vnd.oasis.opendocument.* mimetypes, do they all have the same icon?

**Comment by odeke-em** [comment]
As mentioned drive doesn't dictate the icons, just the mimetypes so I couldn't even guess what icons will be assigned to them by the Google Drive backend and UI :(

**Comment by odeke-em** [comment]
To show the differences between cli upload and UI upload:
#### Inside my shell
```shell
$ cd ~/my_drive
$ for fmt in odt odm ott ods odg otg oth odp otp odi odb oxt;do date > $fmt.$fmt;done
$ drive push
```
Gives something like this when viewed by the UI (sorted by name)
![screen shot 2015-05-31 at 8 40 49 pm](https://cloud.githubusercontent.com/assets/4898263/7905409/60829f50-07d5-11e5-994b-37f1b11e8965.png)


#### With the UI (sorted by name)
![screen shot 2015-05-31 at 8 39 43 pm](https://cloud.githubusercontent.com/assets/4898263/7905402/36516626-07d5-11e5-9d80-b2e88542602c.png)

**Comment by GoGoris** [comment]
Only the ods does not work? It looks like this is a bug in Google Drive itself?

**Comment by odeke-em** [comment]
Appears to be. But I don't think it is necessarily a bug. They could just have a work-around with the UI since their file viewer/opener might just recognize a particular subset of open documents e.g ods as a Google Sheet. This is the part where if it is overwhelming for drive's users, build to match the case that they are used to since Google Drive probably won't change their code if I asked them about this, but the code here in drive could change to match the visual expectation -- see what I mean?

**Comment by GoGoris** [comment]
Yes I get it, thanks. To not confuse users, changing the code to match the visual expectation could be a good idea. I actually found the bug because someone notified me of a change in icons after I pushed to a shared folder in Google Drive.
