### ISSUE TITLE
Create equivalent of shell 'md5sum' command

### ISSUE THREAD

**Issue by arniotis** [odeke-em/drive#225]
Hi

As discussed in #115 , it can often be handy to have a command that can be used as a drop-in replacement for md5sum(1). It can be very useful for verifying that files have been properly transferred on one site prior to deleting on the other; for comparing large files across slow links; or for locating duplicates files even when they have different names.

I've made some changes to `stat` for producing files that are compatible with the md5sum -c function. 

`drive stat  -md5sum`   is equivalent to `md5sum *`
`drive stat  -md5sum -r`   is equivalent to `md5deep -lrj0  *` or  `find * -type f | sort | xargs md5sum`

while input to md5sum -c does not need to be ordered, producing the output in the same order as the shell commands above helps when using `diff` to validate checksums.

Cheers,

Michael

**Comment by odeke-em** [comment]
Hello again @arniotis.
Sorry for the late reply, I just got back home.
Thank you for creating the issue and for the PR. I am going to review it shortly.

**Comment by odeke-em** [comment]
Addressed by PR #226
