### ISSUE TITLE
Pushing large file shows no movement on progress bar and 0% overall

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#23]
Uploading/pushing a 54MB file to google drive shows no progress.

**Comment by odeke-em** [comment]
Hmm I just pushed a 58MB file, it took time
![screen shot 2015-01-03 at 8 19 09 pm](https://cloud.githubusercontent.com/assets/4898263/5604617/da65ff2a-9385-11e4-92e2-195201ea9081.png)
![screen shot 2015-01-03 at 8 19 50 pm](https://cloud.githubusercontent.com/assets/4898263/5604618/e74d70b0-9385-11e4-9d79-d1a07dfba969.png)

**Comment by ikwyl6** [comment]
For me it was 0 / 1 and 0.00% while uploading. When it actually finished then I saw the 1 / 1 and 100%. My file was an .avi (if it makes any diff, which I doubt it).

**Comment by odeke-em** [comment]
Anyways for now before multipart uploads are in, progress is only made after a file upload is complete. As per the current functionality this then does no qualify as a bug. Let me know what you think.

**Comment by ikwyl6** [comment]
If that is the current functionality then that is understandable for doing 1 file.
