### ISSUE TITLE
"drive version" gives VARIABLE names for hash, go version, and OS

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#231]
Output from `drive version`:

```
$ drive version
drive version: 0.2.4
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
```

Shouldn't this show actual versions?

**Comment by odeke-em** [comment]
Hello @ikwyl6. Thanks for raising this. So this is the default placeholder. In order to bundle information about your build, you have to do:
```diff
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```
You can also find that information in the README.
