### ISSUE TITLE
diff fails with clashes, missing option ignore-name-clashes

### ISSUE THREAD

**Issue by kleptog** [odeke-em/drive#233]
When doing a diff I get the following message:

    $ drive diff 
    X /DSC01967.JPG "0B8VjUTiD7WpWQW8yM1JseEV6V0E"
    X /DSC01927.JPG "0B8VjUTiD7WpWWm51dmJ2RTRpek0"
    X /DSC01927.JPG "0B8VjUTiD7WpWZE5NMHdQVlh6aUE"
    X /DSC01940.JPG "0B8VjUTiD7WpWQm9oRnRUc2JSYms"
    clashes detected. use `ignore-name-clashes` to override this behavior

But if I add that option I get:

    $ drive diff -ignore-name-clashes
    flag provided but not defined: -ignore-name-clashes

I get no diff output, which I think is because of the clashes.

**Comment by odeke-em** [comment]
Hello @kleptog. Thank you for raising this issue and my apologies for the late reply. Fix coming up in a few.

**Comment by odeke-em** [comment]
Addressed by PR #235. Please get the latest from master.

**Comment by kleptog** [comment]
Three hours is really quick, really.

But I'm not sure this is resolved. There is now an "ignore-conflict" option, but it's still complaining about "ignore-name-clashes" which it doesn't recognise. And I still can't diff.

**Comment by odeke-em** [comment]
Haha my bad, I hadn't looked closely at the flag name, my apologies. Re-opening and setting the flag in a second..

**Comment by odeke-em** [comment]
Please get the latest from master, and thank you for the correction :)

**Comment by kleptog** [comment]
Can confirm that it works now. Thanks!
