### ISSUE TITLE
Possibility of using SQLite (or a similar database) for indices

### ISSUE THREAD

**Issue by js-ojus** [odeke-em/drive#239]
@odeke-em : A suggestion.  The indices could be stored in an SQLite database (or a similar, small, embedded database).  That should help speed up comparisons when large directories or directory trees are involved.

**Comment by odeke-em** [comment]
Duplicate of https://github.com/odeke-em/drive/issues/106

**Comment by js-ojus** [comment]
Ah ... I see, @odeke-em!  I should have searched thoroughly.  My apologies!

**Comment by odeke-em** [comment]
No worries, actually I think your title gets straight to the point :) I should have made the original one's title more explicit.
