### ISSUE TITLE
[Feature Request] Allow wildcards on push/pull commands

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#24]
It would be nice to do a:

`$ drive push Pictures/My*` and it would push everything that was 'My Pics' or 'My Stuff'.

**Comment by odeke-em** [comment]
Addressed by: https://github.com/odeke-em/drive/commit/7c37a1f1fd35de9a8e3430a74d11269a0c371db4
Allows you to perform do push, pull, pub, unpub, trash, untrash, list etc more than one item in paths present in the current dir for example in this.
![pub_existant](https://cloud.githubusercontent.com/assets/4898263/5605563/4206892c-93bf-11e4-8b26-9c147b54e3d2.png)
![pushing](https://cloud.githubusercontent.com/assets/4898263/5605577/09807616-93c0-11e4-825a-0b1f88a928be.png)

**Comment by odeke-em** [comment]
@ikwyl6 please checkout the latest from master.

**Comment by odeke-em** [comment]
Closing this issue in preparation for the next release.

**Comment by ikwyl6** [comment]
Crash report: http://paste2.org/IA1LhYCF

git log:
```
commit 3a69442e97e51f47c8d4f3705f2fc49d00200af7
Author: Emmanuel Odeke <odeke@ualberta.ca>
Date:   Sun Jan 4 17:51:02 2015 -0700

    trash list + emptytrash + refactoring

commit 1ee02c1621af87cf1b4ad30fec8dc2919417c2df
Author: Emmanuel Odeke <odeke@ualberta.ca>
Date:   Sun Jan 4 16:18:24 2015 -0700

    emptytrash implemented
```
Command used:
`drive push Pictures/VVG*` where this command would give 5 items (files and dirs) to push.

**Comment by odeke-em** [comment]
Yeah it is the same exact issue as you've reported about three times to do with way too many routines being spawned.

**Comment by odeke-em** [comment]
Functionality wise it should be pushing to multiple paths specified by wilcards. Would you mind doing the tests on smaller multiple paths.

**Comment by odeke-em** [comment]
@ikwyl6 btw now you can do `drive version`
