### ISSUE TITLE
Throttling of push/pull 

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#240]
Not sure if there is a `go lang` mechanism to do this. If not, is there an application specific way to limit `drive` bandwidth when doing push/pulls? I find sometimes with drive it can hog all the pipe but if used with `tc` it could work. But I only want to limit drive and not the whole interface.

[1] http://monkey.org/~marius/pages/?page=trickle
[2] http://mark.koli.ch/slowdown-throttle-bandwidth-linux-network-interface

**Comment by ikwyl6** [comment]
Comments, queries to OP,disagreement?

**Comment by CountryBumkin** [comment]
Independent push and pull throttling would be helpful to mange limited bandwidth, particularly push on slow uplink ADSL channels. Also GD has rate limiting as standard, could someone explain the limits applied to see how they might interact with drive.

Regards CB

**Comment by odeke-em** [comment]
Hello @ikwyl6 and @CountryBumkin thank you for the comments, and for bringing attention to this issue.
Golang already has throttling, please see the example and sample code below.
```go
package main

import (
	"fmt"
	"os"
	"strconv"
	"time"
)

func throttleTest(frequency int64) {
	fmt.Printf("Frequency: %v requests per second\n", frequency)
	if frequency < 1 {
		frequency = 10
	}
	throttle := time.Tick(time.Duration(1e9 / frequency))
	for {
		fmt.Println("curTime", time.Now().UnixNano())
		<-throttle
	}
}

func main() {
	argc := len(os.Args)
	n := int64(10)
	if argc >= 2 {
		parsed, err := strconv.ParseInt(os.Args[1], 10, 64)
		if err == nil {
			n = parsed
		}
	}

	throttleTest(n)
}
```

Say we want n requests per second
```shell
$ go run throttle.go 100
$ go run throttle.go 2
```

**Comment by ikwyl6** [comment]
Can this be added to drive as parameter/option?

**Comment by ikwyl6** [comment]
Any more thought(s) on adding a flag for bandwidth?

**Comment by CountryBumkin** [comment]
On a related aspect could the README include sufficient details of the drive protocol to enable users to program the QoS facility of their router, most likely to expedite interactive services ahead of potentially large background up/down loads.

Regards CB

**Comment by JernejJerin** [comment]
This option would be really helpful when downloading/uploading large amounts of data, while not wanting to take up the whole bandwidth.

**Comment by ikwyl6** [comment]
Any ideas?

**Comment by ikwyl6** [comment]
Hi - haven't been around for while but thought I'd poke my nose in..

Any idea on this one for throttling?

**Comment by iblis17** [comment]
Hi folks,
please checkout #1026 as well.

**Comment by odeke-em** [comment]
Implemented by @iblis17 in https://github.com/odeke-em/drive/pull/1026
