### ISSUE TITLE
[PSA] Ubuntu PPA Info.

### ISSUE THREAD

**Issue by shaggytwodope** [odeke-em/drive#253]
@odeke-em The ubuntu ppa is using an external ppa to compile the binary currently. Not sure if this would have any impact on end users. But the ppa install for drive seems to work on a default ubuntu install for me. If anyone else can confirm this that'd be great. (version info still broken but I'll get to it asap been very sick and on heavy pain killers lol) But as it stands drive is updated to the 0.2.4 release and fully working. Sorry for the delay in fixing the build. Looks like the older go package is broken when fetching some depends, so the newer version is a must.

The ppa being used as a depend for go is located here https://launchpad.net/~evarlast/+archive/ubuntu/golang1.4

Not sure if users would need to add the ppa as the binary generated are well binarys and run perfectly fine from my tests. So this is more a PSA then anything important. Feel free to close this issue right away. Again sorry for the delay, had a ruptured appendix and I'm going slow on things lol.

**Comment by odeke-em** [comment]
Ooh sorry to hear about that @shaggytwodope, hope things are getting better. @shaggytwodope your contributions and time are highly valued, please take as much time as you need. Thank you for informing us about this. Yes in deed, I found out from a friend on Thursday that go1.3.3 even works not just 1.4 as I initially thought.

**Comment by odeke-em** [comment]
Wish you a quick recovery @shaggytwodope  and don't worry about this stuff, your health first ;)

**Comment by js-ojus** [comment]
Indeed @shaggytwodope, packagers like yourself are a key element in boosting adoption of good open-source software.  Please take care of your health.  Thanks for the great work!

**Comment by odeke-em** [comment]
Hey @shaggytwodope. Is this still an issue?

**Comment by shaggytwodope** [comment]
@odeke-em It's more or less still just a psa. Still compiles and works just fine. Well at least no ones reported otherwise yet lol. I'll get into packaging it better one of these days... damn life shit. I'm going to close it, if anyone runs into probs lemme know.

**Comment by odeke-em** [comment]
@shaggytwodope ah I see. Thank you for the PSA, plus your work, as usual ;) Were you able to get in touch with the Debian folks?

**Comment by shaggytwodope** [comment]
@odeke-em yeah I need to sit down and figure out how to package all the stuff needed. If it was JUST drive as a source it would be far easier. But so many different sources complicates stuff. I'm going to get to this soon, hoping to dedicate a weekend to this and some other stuff I'm borderline ignoring/putting off.

**Comment by odeke-em** [comment]
Oh okay. So I think I mentioned to you `godep`, please see directory `drive-gen/Godeps` everytime I need to bundle dependencies, I ran `godep save` in `drive-gen`. Hope this can help cut out the problem with many sources.
