### ISSUE TITLE
Error on 'go get -u github.com/odeke-em/drive/cmd/drive'

### ISSUE THREAD

**Issue by luigdima** [odeke-em/drive#254]
Hello!

When i run on terminal "go get -u github.com/odeke-em/drive/cmd/drive"

i returned this error:

../gopath/src/google.golang.org/cloud/compute/metadata/metadata.go:54: unknown net.Dialer field 'KeepAlive' in struct literal

The version of the S.O is 'Ubuntu 14.04' (LTS).

What is the problem?

++Thnk!

**Comment by odeke-em** [comment]
Hello there @luigdima. Thank you for reporting this issue and welcome to drive.
That fail came in as you can see from that trace as a sort of butterfly effect for a change in a dependency for either Google's Golang API Client or golang/x/OAuth client (not fully investigated). Using >= go1.3.X should solve your problem. Also please take a look at this closed issue https://github.com/odeke-em/drive/issues/223.
