### ISSUE TITLE
[Feature Request] Push and pull native Google Docs as Markdown

### ISSUE THREAD

**Issue by bobbybee** [odeke-em/drive#257]
I'm mainly interested in this tool as I'm much more comfortable in the command-line (yay vim!) than in my web browser (or even a liberated word processor) for serious work. While I might be able to hack something together with pandoc, it'd be very useful to have some sort of easy markup language natively integrated with `drive`. (**cough** Markdown **cough**). 

If there's a better workflow for editing Docs with `vim`, I'd be very open to hearing it!

**Comment by odeke-em** [comment]
Hello @bobbybee, thank you for raising this issue and welcome to drive.
Unfortunately drive doesn't have access to editing content of your Google Docs and if you are on Linux in the best case will provide you with *.desktop files that when clicked, open your browser and redirect you to the link to that Google Doc. Google Docs doesn't expose an API for dealing with this kind of content and in fact drive can only access exportable content.

**Comment by odeke-em** [comment]
Closing this issue with the explanation above.
