### ISSUE TITLE
[fearure request]: Add -y flag to pull command

### ISSUE THREAD

**Issue by utgarda** [odeke-em/drive#258]
`drive pull` always asks if you want to proceed overwriting local changes. Would be nice to have something traditional for console commands, like "yes to everything".

**Comment by odeke-em** [comment]
Hello @utgarda thanks for reporting this and welcome to drive!
We already have this option in the form of: `--no-prompt`

**Comment by utgarda** [comment]
Thanks a lot, found it! Btw, is help intended to go to `stderr`?

```ShellSession
$ drive pull -h | grep prompt
Usage of drive pull:
  -exclude-ops="": exclude operations
...
*** all this is stderr output ***
...
  -skip-mime="": skip elements with mimeTypes derived from these extensison
$ drive pull -h 2>&1 | grep prompt
  -no-prompt=false: shows no prompt before applying the pull action
```
