### ISSUE TITLE
Impossible progress bar display during `push`

### ISSUE THREAD

**Issue by js-ojus** [odeke-em/drive#264]
When performing a small `push`, I have noticed an impossible progress bar display.  The full output is included hereunder.

```
js@karta:~/gdrive/Documents/tech > drive push
Resolving...
- /Documents/tech/conf/dot-emacs~
M /Documents/tech/conf/idea-settings.jar
M /Documents/tech/conf/dot-bashrc
M /Documents/tech/conf/eclipse/workspace-preferences.epf
M /Documents/tech/conf/eclipse/code-formatter-java.xml
M /Documents/tech/conf/eclipse/code-clean-up-java.xml
M /Documents/tech/conf/dot-zshrc
M /Documents/tech/conf/dot-vimrc
M /Documents/tech/conf/dot-python_startup
M /Documents/tech/bin/synclient.sh
Deletion count 1 dest: 6.25KB
Modification count 9 src: 95.93KB dest: 95.93KB
Proceed with the changes? [Y/n]:y
104629 / 98229 [==================================================] 106.52 % 18s
```

**Comment by odeke-em** [comment]
This is a duplicate of issue https://github.com/odeke-em/drive/issues/177.

**Comment by odeke-em** [comment]
Thanks for reporting that am gonna take a look at it.

**Comment by js-ojus** [comment]
You are correct about #177.  You are also correct in your observation that deletion is what is responsible; I have verified several scenarios to confirm that.

I shall close this, since #177 is still open.

**Comment by odeke-em** [comment]
Thank you @js-ojus I'll actually use your example as a test case.
