### ISSUE TITLE
.driveignore doesn't handle absolute paths

### ISSUE THREAD

**Issue by asmisha** [odeke-em/drive#270]
I'd like to exclude specific folders from being pushed to remote drive, but it seems that I can only exclude files/folders by their basename:
```
# mkdir test/b -p 
# touch test/a
# touch test/b/c
# echo 'b' > .driveignore
# drive push test
Resolving...
+ /test
+ /test/a
Addition count 2
Proceed with the changes? [Y/n]:^C
# echo 'b/c' > .driveignore
# drive push test
Resolving...
+ /test
+ /test/a
+ /test/b
+ /test/b/c
Addition count 4
Proceed with the changes? [Y/n]:^C
# echo '/test/a' > .driveignore
# drive push test
Resolving...
+ /test
+ /test/a
+ /test/b
+ /test/b/c
Addition count 4
Proceed with the changes? [Y/n]:^C
```
I also tried escaping '/' with single or multiple backslashes, but that had no effect either. May you please add this feature or point out, what am I doing wrong?
Thanks in advance!

**Comment by odeke-em** [comment]
Hello @asmisha, thank you for reporting this and welcome to drive!

Yes you are right, this is bug in the ignore checking done on. PR coming up in a second.

**Comment by odeke-em** [comment]
Please get the latest from master. Addressed by PR https://github.com/odeke-em/drive/pull/272.
Thank you for reporting this issue.
