### ISSUE TITLE
Installing on arm v5 fails

### ISSUE THREAD

**Issue by volopasse** [odeke-em/drive#273]
I'm attempting to install drive on Pogoplug running ALARM. The device runs ARM v5. The installation fails with the following output:

```
[root@msi-backup drive]# go get -u github.com/odeke-em/drive/cmd/drive
go build github.com/odeke-em/google-api-go-client/drive/v2: /usr/lib/go/pkg/tool/linux_arm/5g: signal: killed
go build golang.org/x/text/unicode/norm: /usr/lib/go/pkg/tool/linux_arm/5g: signal: killed
```

Not sure where to start investigating and whether it's a user error or the platform is not supported. Go binaries do exist and I have go installed and working. Would appreciate any help/pointers to get this running.

Also, PKGBUILD file for drive in AUR specifies armv6 and v7, but not v5 or a more generic 'arm' target... which leads me to think v5 is not supported for some reason. Is that true?

**Comment by odeke-em** [comment]
Hello there @volopasse! Thank you for reporting this issue and welcome to drive!

So for starters, I have a Raspberry Pi and I can run drive on it, plus Go builds on ARM. If I may ask, what version of Go are you running?

**Comment by volopasse** [comment]
go version reports this:
```
go version go1.4.2 linux/arm
```
Raspberry Pi has ARMv6 I believe, maybe that has something to do with it

**Comment by odeke-em** [comment]
Please take a look at https://github.com/golang/go/wiki/GoArm, Go is fully supported on ARM.

**Comment by volopasse** [comment]
Is is possible to add more verbosity to compilation process to have a better handle on what's failing? Or maybe cross compile from another machine?

**Comment by odeke-em** [comment]
`go get -v -u github.com/odeke-em/drive/cmd/drive` -- notice the `-v` flag.

I'd advise you to build using `drive-gen` so that you can get commit hash, version and some information bundled into the binary. In this case
`go get -v -u github.com/odeke-em/drive/drive-gen && drive-gen`

**Comment by volopasse** [comment]
```
[root@msi-backup ~]# go get -v -u github.com/odeke-em/drive/drive-gen && drive-gen
github.com/odeke-em/drive (download)
github.com/boltdb/bolt (download)
github.com/cheggaaa/pb (download)
github.com/mattn/go-isatty (download)
github.com/odeke-em/cli-spinner (download)
github.com/odeke-em/google-api-go-client (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)

.........

Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
github.com/odeke-em/ripper (download)
github.com/odeke-em/xon (download)
github.com/odeke-em/google-api-go-client/drive/v2
go build github.com/odeke-em/google-api-go-client/drive/v2: /usr/lib/go/pkg/tool/linux_arm/5g: signal: killed
golang.org/x/text/unicode/norm
go build golang.org/x/text/unicode/norm: /usr/lib/go/pkg/tool/linux_arm/5g: signal: killed
```

From (slightly cut down) log above, it seems the dependencies are resolved and fetched correctly, but there are no details about why the build step fails. Is it possible to run the build step separately with more output?

**Comment by odeke-em** [comment]
How did you install go? Did you set your $GOPATH right? How come you are running this as root?(might not seem to matter, but if your $GOPATH isn't set right for root you are going to have issues building).

**Comment by volopasse** [comment]
$GOPATH is set up. Reason I'm under root is that this is an appliance test install and I want to make sure everything I need works before redoing the setup properly.

Installed via Arch package manager (pacman), by running 
```
pacman -Sy go
```
this sources the packages from [here] (https://www.archlinux.org/packages/community/x86_64/go/)

I tried replacing the default compiler with [gcc-go](https://www.archlinux.org/packages/core/x86_64/gcc-go/), which has gotten me further in the compilation process but still threw an error:
```
# github.com/odeke-em/google-api-go-client/drive/v2
gccgo: internal compiler error: Killed (program as)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/archlinuxarm/PKGBUILDs/issues> for instructions.

.......

# golang.org/x/text/collate
gccgo: internal compiler error: Killed (program go1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/archlinuxarm/PKGBUILDs/issues> for instructions.
github.com/odeke-em/ripper/src
github.com/odeke-em/xon/pkger/src
go build github.com/odeke-em/xon/pkger/src: ar: fork/exec //bin/ar: cannot allocate memory
```

**Comment by odeke-em** [comment]
Alright. So the README file for this project drive has a link on how to install go. Please visit that link, it should be a 5 step process or so. If that doesn't make some progress installing from source works best, I personally do this. If this persists, I'll try to summon a Golang contributor who ARM expertise could help.

**Comment by volopasse** [comment]
Ok, rebuilding go from source now, will probably take a long time on that wimpy CPU. Thanks for your help!

**Comment by odeke-em** [comment]
Any luck?

**Comment by shaggytwodope** [comment]
@volopasse The reason for the drive package in the arch AUR being for armv6 and armv7, but not v5 is I have no hardware or reports of it working. If anyone love to donate a device or confirm it works I'll totally update the package :-)

@odeke-em I want candy... give me candy lol :+1:

**Comment by odeke-em** [comment]
@volopasse hopefully it can build, btw the Golang downloads site has ARM binaries so please check them out or visit Dave Cheney's(he is a core Golang contributor) unofficial ARM binaries page http://dave.cheney.net/unofficial-arm-tarballs.
@shaggytwodope hahaha I don't have candy right now but here are the talents of Lebron James https://googledrive.com/host/0Bwu8laYc9RTPdzRPaE5BOFZ0bWM.

**Comment by volopasse** [comment]
Tried building from source, but that failed as well =/ Maybe there's just not enough RAM in that thing to build anything.
Unofficial tarballs are the next thing to try. Meanwhile will try get something working on RPi.

**Comment by odeke-em** [comment]
Yes in deed the unofficial ARM tarballs should cut the deal [Dave Cheney's go1.4.2 ARMv5 tarball](http://dave.cheney.net/paste/go1.4.2.linux-arm~armv5-1.tar.gz)

**Comment by allgoewer** [comment]
@volopasse 

do you have a swap partition?
I'm encountering the same issue on an Raspi B+ (512MB RAM), it seems to be related to the compilation of golang.org/x/text/collate.

Running
```
/usr/bin/time -f "%M" go build golang.org/x/text/collate 2>&1 | awk 'END { print $1 / 1024, "MB"; }' 
```

gives me about 370 MB used by the process.

As I can only access my Pi via ssh, I can't put a swap partition onto the sd-card at the moment.

Will try that tomorrow.

**Comment by odeke-em** [comment]
Ouch, that sucks. I have a Raspberry Pi B armv6l. And drive builds for me in seconds. Anyways, I've made a special release with just binaries such as for armv6 here https://github.com/odeke-em/drive/releases/tag/v0.2.6-binaries.

**Comment by allgoewer** [comment]
If anyone is having the same issue and needs to build drive from source, the following worked for me. The issue is obviously not related to armv5, it's simply the compiler not being able to allocate enough memory on a device with < 1GB RAM and no swap-partition/file.

**as root**, create a 1GB swap-file
```
fallocate -l 1G /swap
mkswap /swap
chmod 600 /swap
swapon /swap
```

get and build drive as usual
```
go install github.com/odeke-em/drive/cmd/drive
```
again, **as root**, disable swap and remove the file
```
swapoff /swap
rm /swap
```

**Comment by odeke-em** [comment]
That's awesome @allgoewer. Would you mind also creating a wiki entry if it isn't too much trouble? Thanks.

**Comment by allgoewer** [comment]
No problem, already finished.

**Comment by odeke-em** [comment]
Thank you very much @allgoewer!

**Comment by volopasse** [comment]
@odeke-em Thank you for the binaries. Putting them onto my RPi solved the immediate issue (i.e. got drive working for me), but I'm still not able to compile it properly, despite @allgoewer 's fix with the swap partition. Will experiment some tonight

**Comment by odeke-em** [comment]
Btw @shaggytwodope you could cross compile with something like this:

```shell
$ GOOS=linux GOARCH=arm GOARM=5 go get github.com/odeke-em/drive/cmd/drive
```

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Hello folks please get the latest from master. I've ripped the text/collate package so you shouldn't be getting these problems anymore. You can get the latest by:

```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
