### ISSUE TITLE
[visual presentation] prettify wiki or even use Github Pages sites for a site

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/drive#274]
We need some prettifying of this project by cleaning up the wiki as well as possibly creating an alright looking site to welcome users that they can interact with, without having to go to the README.

**Comment by shaggytwodope** [comment]
I have some ideas and such for a simple project page, but doesn't github pages use your user name? so it'd be http://odeke-em.github.io I think. I could look into creating some lame mockup tho at some stage this week. Unless someone steps up lol. I got a Doctor's Apt. tomorrow, maybe day after I'll get started. Maybe @odeke-em can setup a blank repo I can send PR to later this week?

**Comment by odeke-em** [comment]
Thanks @shaggytwodope and good luck at the doctors' today!

**Comment by shaggytwodope** [comment]
@odeke-em https://u.teknik.io/zNQr1N.png

Well, it's not fine art. But it's something... lemme know what you think.

**Comment by odeke-em** [comment]
Nice, this looks awesome. Thanks @shaggytwodope!

**Comment by odeke-em** [comment]
@shaggytwodope I created a repo as earlier requested. Please see https://github.com/odeke-em/drive-pages

**Comment by odeke-em** [comment]
drive is now accessible at http://odeke-em.github.io/drive/

**Comment by odeke-em** [comment]
Thank you @shaggytwodope and @Queatz for working on this issue!
