### ISSUE TITLE
can somebody please add to Debian?

### ISSUE THREAD

**Issue by fommil** [odeke-em/drive#277]
I tried to pay an experienced commercial Debian packager to get `drive` added to Debian, but they hit http://pkg-go.alioth.debian.org/packaging.html and then gave up, estimating 9 hours of work because each dependency has to be added separately (9 packages in total, plus and transitives). Probably the best way to get drive added to Debian is to ask this `pgk-go` team to do it. If the maintainers were to approach them about it, it might stand a chance. Please?

Apparently the Ubuntu `.deb` / ppa is against the Debian policy, so it won't get accepted in that form.

Of course, workaround is to `go get ...` but it would be nice to be able to install it on a fresh Debian box as a native app.

**Comment by odeke-em** [comment]
Hello @fommil, thank you for reporting this and welcome to drive!
Wow, that's some dedication. Thank you for offering to do this, I appreciate this.
I see what you are saying. I'll ping the PPA maintainer @shaggytwodope.
Also coming to think of it, there was an issue https://github.com/odeke-em/drive/issues/271 filed by @sbrun to get drive on Debian but she had requested a name change, of which I haven't not yet decided on. However, she had worked on getting drive in Debian and the name decision is just what is blocking her from finishing. Hopefully we can ask her what it took. Any ideas or comments on getting this in @sbrun?

**Comment by fommil** [comment]
sounds like the dedication is all from everybody else, I was just being lazy by asking someone else :smile: FWIW whatever name is fine with me in debian. I can always add an alias.

**Comment by rhertzog** [comment]
Sophie Brun (@sbrun) is the person that was doing the packaging work requested by @fommil and I was supposed to review it and include it in Debian. Given what we found out, this packaging offer obviouly no longer stands.

**Comment by fommil** [comment]
Aah. Thought we'd found a willing volunteer :-)

**Comment by rhertzog** [comment]
@fommil That said if @shaggytwodope wants to do the work of creating policy-compliant Debian packages I can "sponsor" them into Debian. The best would be if @shaggytwodope would join the pkg-go team so that he can maintain the packages in the git repositories of the team.

**Comment by shaggytwodope** [comment]
Hello @rhertzog @fommil and lord @odeke-em. I've been in poor health lately, altho getting better slowly. I'am going to look into how to join the pkg-go team and what ever steps needed to get drive into debian. Altho this may take me some time as I'm going slow in even being at my desk. I will certainly read up on the go lang specs and requirements debian has. I'd love to get it into debian asap. 

Basicly give me time and I'll try to get it there, my deb package is so hacky it is terrible lol. So in the next few day's I'll do some reading up and see what needs to be done. 

PS @odeke-em Working on a site still, just busy with things more so. 1-2 days I hope to get a mock up to ya mate. Sorry for delays.

**Comment by odeke-em** [comment]
Hello @rhertzog thank you for taking time to look at this issue, and welcome to drive, plus I appreciate the offer and work in trying to get this in. Hello again @fommil and @shaggytwodope. Sounds like a plan getting @shaggytwodope into pkg-go/sponsored. To be honest, I am not knowledgable on packaging :( but I'll be learning from what y'all doing.

**Comment by odeke-em** [comment]
@shaggytwodope sorry for that, please get well soon, and thank you for the continued work.

**Comment by odeke-em** [comment]
Hey y'all, please see PR https://github.com/odeke-em/drive/pull/280 or get the latest from master.
Now you'll be able to say
```shell
$ go get -u github.com/odeke-em/drive/google-drive
$ # OR
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen google-drive # To bundle debug info
```

**Comment by odeke-em** [comment]
Just changed the alternate binary to `drive-google` to match the suffixing that had earlier been mentioned, and to avoid using the Google Drive trademark without their consent. Please get the latest from master.

**Comment by odeke-em** [comment]
Ping!

**Comment by sbrun** [comment]
I started to package drive for debian before realizing that it has too many dependencies. You will find my current tree here: https://github.com/sbrun/drive. Obviously it's far from ready but  maybe it can be useful for you.

**Comment by odeke-em** [comment]
Thank you @sbrun for taking a look at it. Would you mind taking a look at how @shaggytwodope handles this in https://github.com/shaggytwodope/drivedebpackage?

**Comment by rhertzog** [comment]
@odeke-em We did already look at this package, it's just a big bundle of all the dependencies, it's not appropriate to be included into Debian.

**Comment by odeke-em** [comment]
@rhertzog thanks for the reply. Btw it might useful to know that there is a `Godeps` directory in `drive-gen`? You can view it here: https://github.com/odeke-em/drive/tree/master/drive-gen/Godeps. With Godeps I bundle the dependencies in a workspace and then the user can restore them once they've downloaded drive. Just in case you need to, you can learn about Godeps here https://github.com/tools/godep.

**Comment by odeke-em** [comment]
Ping!

**Comment by fike** [comment]
Hi, 
 
  I'm packaging **drive** dependencies to Debian. At the moment I packaged two libraries dependencies ([golang-github-mattn-go-isatty-dev](https://ftp-master.debian.org/new/golang-github-mattn-go-isatty_0.0~git20150409.0.ae0b1f8-1.html) and [golang-github-odeke-em-cli-spinner-dev](https://ftp-master.debian.org/new/golang-github-mattn-go-isatty_0.0~git20150409.0.ae0b1f8-1.html)), it isn't enough but they are the firsts steps. ;)

**Comment by odeke-em** [comment]
Hello @fike, sorry for the late reply and welcome to drive! Thank you for starting this up.

@sbrun, if may kindly ask, were you able to work on it ever since your initial issue of a different name was resolved?
@fommil, @shaggytwodope any thoughts on getting this in?

**Comment by gdm85** [comment]
I agree with @rhertzog here, the dependencies tree is a mess...and I totally could not make use of Godeps as it still wanted to ``go get`` libraries. Supposedly with vendoring once you checkout the repository you should have all the source and be ready to build.

Can we improve somehow the README by explaining how to build from sources at first checkout, since it looks like there is already a Godeps workspace here and shouldn't be necessary to fetch middleware again...

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
I guess this won't be happening, we'll rely on @shaggytwodope's packages and you can always just do
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

Thank you everyone!

**Comment by fommil** [comment]
Are there any Gnu/Linux distributions that have a sane packaging strategy for modern languages? I.e. ivy/maven for JVM, cabal for Haskell and go get for go? Seems a total waste of effort to repackage this stuff.

**Comment by aerth** [comment]
@fommil https://people.debian.org/~stapelberg/2015/07/27/dh-make-golang.html

**Comment by fommil** [comment]
@aerth that's just fitting in with the current system (although it may help!) and I think the package maintainers are insane. I would like to know if there are any modern GNU/Linux distributions that just delegate package management to the language's native package manager. e.g. an `apt` that would just use `go get` or `mvn` or `cabal` under the hood.

**Comment by aerth** [comment]
Actually dh-make-golang is on [Github](https://github.com/Debian/dh-make-golang) and fresher than the Debian repo.
