### ISSUE TITLE
/.gd/indices permission denied

### ISSUE THREAD

**Issue by thetallone** [odeke-em/drive#279]
I've had rive working foine for a couple of weeks however today i'm getting 

serializeIndex /mnt/drive/.gd/indices/df,gjfklgjdfgklksnklfgjnfsjkglngkgg: permission denied

when doing a push? i've tried redoing a 'drive init'

**Comment by odeke-em** [comment]
Hello again @thetallone. Perhaps had you installed drive and run it as sudo? If so please don't do this :) Also that is running old code because now indices are saved to a database. Please get the latest.

**Comment by thetallone** [comment]
Thanks for the quick response I will upgrade and retry.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Closing this issue as it was answered.
