### ISSUE TITLE
How do you "de-init" a folder?

### ISSUE THREAD

**Issue by mgalgs** [odeke-em/drive#282]
Do you just delete the `.gd` directory?

**Comment by odeke-em** [comment]
Hello @mgalgs thank you for reporting this issue and welcome to drive!
Yes, that is right, `rm -rf .gd` should cut the deal. I think the README file talks about it. Also this read my mind, a few days back I was thinking about rolling such a command out.

**Comment by mgalgs** [comment]
Yeah I don't see it in the README.  Anyways, I'll add it to the wiki.  Thanks a lot!

**Comment by mgalgs** [comment]
https://github.com/odeke-em/drive/wiki#de-init

**Comment by odeke-em** [comment]
Thank you very much @mgalgs, if you'd like, please re-open this issue and then I'll create a command to provide deinit functionality :)

**Comment by odeke-em** [comment]
Hello @mgalgs, thanks for raising this issue. I've addressed this by introducing a `drive deinit` command in PR https://github.com/odeke-em/drive/pull/283. Please get the latest from master.

**Comment by mgalgs** [comment]
Very nice, thanks!

**Comment by odeke-em** [comment]
Cheers!
