### ISSUE TITLE
pull does not get all files

### ISSUE THREAD

**Issue by brunosimoes** [odeke-em/drive#285]
Some files are not downloaded/synchronised. How to reproduce the issue:

1) insert a file ".htaccess" into a directory call "test"
2) "drive pull test" returns "Everything is up-to-date."
3) "drive pull test/.htaccess" and you get the file "Addition count 1 src: 56.00B"

**Comment by odeke-em** [comment]
Hello @brunosimoes thank you reporting this and welcome to drive
```shell
$ drive pull --hidden
```
should sort out that.
This isn't a bug :) since drive should respect hidden children files unless explicitly being operated on.
