### ISSUE TITLE
What is a MIME type short-key

### ISSUE THREAD

**Issue by canpolat** [odeke-em/drive#298]
In the documentation (README) we have the following lines:

>If you would like to coerce a certain mimeType that you'd prefer to assert with Google Drive pushes, use flag `-coerce-mime <short-key>`

>    $ drive push -coerce-mime docx my_test_doc

So, I guess `docx` is the short-key for `application/vnd.openxmlformats-officedocument.wordprocessingml.document`. But what about all the other MIME types? I think we at least need the ones supported (either directly or by conversion) by Google drive. Or, are we supposed to use the extension of the file as short-key (for cases where the file doesn't have an extension but you want Google Drive to recognize it)? Little bit of an explanation in the documentation would be nice.

BTW: I was skeptic towards *drive* when I first heard about it (about ten months ago). But now, I think it fits into my workflow quite well. Thank you for your efforts.

**Comment by odeke-em** [comment]
Hello @canpolat thanks for reporting this and welcome to drive! (Even though you've interacted with the users already ;), I hadn't yet said hi).
Oh thank you for the kind words and for the support. Hopefully drive will serve you well.

Yes I totally agree, I should have provided some information concerning the short-keys.
So these are short forms (regular expressions) from which the full mimeType that will be derived.

```json
{
    "csv":   "text/csv",
    "html?": "text/html",
    "te?xt": "text/plain",
    "xml":   "text/xml",

    "gif":   "image/gif",
    "png":   "image/png",
    "svg":   "image/svg+xml",
    "jpe?g": "image/jpeg",

    "odt": "application/vnd.oasis.opendocument.text",
    "odm": "application/vnd.oasis.opendocument.text-master",
    "ott": "application/vnd.oasis.opendocument.text-template",
    "ods": "application/vnd.oasis.opendocument.sheet",
    "ots": "application/vnd.oasis.opendocument.spreadsheet-template",
    "odg": "application/vnd.oasis.opendocument.graphics",
    "otg": "application/vnd.oasis.opendocument.graphics-template",
    "oth": "application/vnd.oasis.opendocument.text-web",
    "odp": "application/vnd.oasis.opendocument.presentation",
    "otp": "application/vnd.oasis.opendocument.presentation-template",
    "odi": "application/vnd.oasis.opendocument.image",
    "odb": "application/vnd.oasis.opendocument.database",
    "oxt": "application/vnd.openofficeorg.extension",

    "rtf": "application/rtf",
    "pdf": "application/pdf",

    "json": "application/json",
    "js":   "application/x-javascript",

    "apk":   "application/vnd.android.package-archive",
    "bin":   "application/octet-stream",
    "tiff?": "image/tiff",
    "tgz":   "application/x-compressed",
    "zip":   "application/zip",

    "mp3": "audio/mpeg",

    "docx?": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "pptx?": "application/vnd.openxmlformats-officedocument.wordprocessingml.presentation",
    "xlsx?": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}
```

My apologies, I'd push up a PR adding this is in, but I've been up for way too long and have to go to bed before morning :)
If you'd like feel free to make a PR or wiki entry for this.
Thank you.

**Comment by odeke-em** [comment]
I forgot to mention, when you use `drive new --mime-key <short-key>` there are extra mime-keys in addition to the ones posted above
```json
{
    "docs":         "application/vnd.google-apps.document",
    "folder":        "application/vnd.google-apps.folder",
    "form":         "application/vnd.google-apps.form",
    "mp4":          "video/mp4",
    "presentation": "application/vnd.google-apps.presentation",
    "sheet":        "application/vnd.google-apps.spreadsheet",
    "script":       "application/vnd.google-apps.script",
}
```

**Comment by canpolat** [comment]
Thank you for the prompt response. I created a wiki page and a PR for adding a link to that page from the README.

**Comment by odeke-em** [comment]
Thank you very much @canpolat for working on this!
