### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/drive#3]

**Comment by kcwu** [comment]
I am not familiar with golang, so I wrote some tests in python.
http://kcwu.csie.org/~kcwu/tmp/drive_test.py.txt

If you like to put it in repo, I can send a PR.

**Comment by odeke-em** [comment]
Oh wow, this is cool. Thank you @kcwu! See to keep things uniform, I would encourage you to get this in Golang, by the time you can write these in Python translating them, plus learning Go will be cool ;) I would like to see your code contributions credited in the repo, so we could work through the translation to Go together. Please let me know what you think.

**Comment by odeke-em** [comment]
You know what, to get it in and have the tests running first, please go ahead and create the PR and then the translation will proceed later.

**Comment by kcwu** [comment]
Do you know any existing go testing framework suitable for command line tool? Most tutorial are talking unit test but I want end-to-end test.

Btw, you can try to run those tests , it found several issues in current code.

**Comment by odeke-em** [comment]
http://pivotallabs.com/agouti/ I have not used it personally but looked it up.
You could write the testing code to invoke subprocess and commands just like you did with the Python code.
I always just write tests using golang's testing package.

By the way on first try, the first test is not correct. drive list SHOULD NEVER erase any content in your drive. list just lists the current working directory relative to the root.
![screen shot 2015-03-20 at 10 12 03 pm](https://cloud.githubusercontent.com/assets/4898263/6763696/30bb1974-cf4e-11e4-8f0a-0dad02872a05.png)

**Comment by odeke-em** [comment]
Never mind my previous comments, I hadn't realized that I needed a fresh drive

**Comment by odeke-em** [comment]
@kcwu these are some of the coolest tests I've seen a long time. Thank you very much, I like this. Please get that PR in :+1:

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/pull/113. A translation and addition of tests will be expected as the project builds on.
