### ISSUE TITLE
Platform packages for drive.

### ISSUE THREAD

**Issue by shaggytwodope** [odeke-em/drive#30]
I've created an aur pacakge based on the release snapshots. https://aur.archlinux.org/packages/drive/
It's not perfect nor am I... But for anyone using archlinux your welcome to install it and enjoy drive.

This is based on the releases, not git version.

**Comment by odeke-em** [comment]
+1 thanks @shaggytwodope am going to add this to the README.

**Comment by odeke-em** [comment]
@shaggytwodope please check the latest on master.

**Comment by ikwyl6** [comment]
If I could get this for ARM archlinux, that would be great.

**Comment by odeke-em** [comment]
@shaggytwodope I have a raspberry pi but it has Ubuntu on it, however I'd still need your knowledge to build it since you seem vested in ArchLinux

**Comment by odeke-em** [comment]
And yes Go builds on ARM.

**Comment by shaggytwodope** [comment]
@odeke-em If go is already available for arm archlinux then we can simply add  'arm' to the line 

arch=('x86_64' 'i686')

The aur package, is most or less a build script for drive. go is still doing the work on the fly. 

Manually editing this is something I can describe more if anyone wants, but not sure at all how arm archlinux works in relation to the aur.  I wish I had the means to test this for ya'll.

**Comment by odeke-em** [comment]
That sounds like a plan, feel free to go ahead and build it then coordinate with @ikwyl6 since they want the ARM build. If all is well, feel fee to submit a PR indicating the package link in the README.

**Comment by shaggytwodope** [comment]
@ikwyl6  The steps to test this seem pretty easy, Not sure how the pkgbuilds work for arm archlinux.  But you need to grab the pkgbuild for go if you havent already, or use a aur helper or similar for arm archlinux (yaourt pacaur etc). Lets assume your doing it manually, run :  

mkdir ~/go
cd ~/go
wget https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/master/community/go/PKGBUILD
makepkg -sfi 

This should fetch the source, compile and any dependacys it may need to compile go.


mkdir ~/drive
cd ~/drive
wget https://aur.archlinux.org/packages/dr/drive/PKGBUILD
makepkg -sfi 

Now this will build and install drive for you. It's really important to note, I've no idea if there is a aur helper for arm archlinux (stands to reason there is one ofc) If for some reason it doesnt want to compile, edit the PKGBUILD for drive. Look for the line 

arch=('x86_64' 'i686')

and adjust to look like:

arch=('x86_64' 'i686' 'arm')

From my understanding tho, most of the pkgbuilds will work just fine under arm archlinux. And I see little reason why it work work. The building is done by go, the PKGBUILD in this case is just a handler of sorts. 

I will email the arm archlinux guys later and see about adding it to their collection. Or just add 'arm' to the pkgbuild. Please let me know of ANY issues if your able to test this. Post any output or errors, and if successful we can add arm to the arch.

**Comment by odeke-em** [comment]
@shaggytwodope sounds dope I guess this weekend I'll install ArchLinux and try it out. Thank you.

**Comment by shaggytwodope** [comment]
I figured I'd share this, currently got the 64bit version to work. I think I'll setup app a or something for ubuntu users. If thats ok ofc.

 http://i.imgur.com/yI22DQg.png

**Comment by odeke-em** [comment]
@shaggytwodope this is great! Thank you. I'll be able to also check this out myself.

**Comment by shaggytwodope** [comment]
@odeke-em https://launchpad.net/~twodopeshaggy/+archive/ubuntu/drive/+packages
I'll keep it up to date with release versions, as with the aur. Let me know if you want any info changed or w/e. (You can have access to the ppa I think, never done it before just lemme know if you want.)

For anyone whos not so savvy with ppa's. 
All you need to do is run:
 sudo add-apt-repository ppa:twodopeshaggy/drive
sudo apt-get update
sudo apt-get install drive

And ofc run drive as usual :-p

**Comment by CountryBumkin** [comment]
I just installed from the ppa into Linux Mint 17 and all seems well, used the Mint software sources and package manager utilities to set things up.
Thanks for the effort. CB

**Comment by odeke-em** [comment]
@shaggytwodope I've been able to install it as well on one of my machines, good stuff! Would you mind spinning up a PR with a markdown file that will be the list of the platform packages or even how to get them etc? Thank you.

**Comment by shaggytwodope** [comment]
aur and ppa updated to 0.0.4.c

**Comment by shaggytwodope** [comment]
Aur and PPA pacakges updated to 0.0.4.d.

@odeke-em Little note, version in the program reports 0.0.4.c, if you change that at all lemme know so I can update packages accordingly. Or simply wait til next release :-p

**Comment by odeke-em** [comment]
@shaggytwodope thanks for pointing that out I hadn't updated the version string. Updated now.

**Comment by shaggytwodope** [comment]
Aur updated, ppa updated as well to 0.0.5 release. 

As always any issues let me know! Great work as always @odeke-em

**Comment by odeke-em** [comment]
@shaggytwodope, thank you too for the packages.

**Comment by shaggytwodope** [comment]
@odeke-em Updated aur to 0.0.6 release, but noticed version (drive version cmd) doesnt reflect current version. 

i'll get to ppa later today, doing laundry lol.

**Comment by odeke-em** [comment]
Ah yes thanks, I was just about to go sleep. Good catch again.

**Comment by odeke-em** [comment]
Haha, get that laundry in alright. Pushed up a coerced update.

**Comment by shaggytwodope** [comment]
Both AUR and PPA updated to 0.0.6. Great work @odeke-em !

**Comment by shaggytwodope** [comment]
AUR and PPA packages updates to 0.0.7. Enjoy :8ball:

**Comment by odeke-em** [comment]
Thanks :+1:

**Comment by shaggytwodope** [comment]
Added arm arch to the aur package, filed a req for the ppa build for arm. Hopefully the ppa will rock arm as well. @odeke-em @ikwyl6 I'll update later if ppa is enabled for arm. I think the main arch's will be covered, if we need any other type of arch let me know.

**Comment by odeke-em** [comment]
This is cool: off Burcu's repo, someone had actually requested for arm binaries & I think distro support, so that they could use drive on their router. @shaggytwodope thank you. Once this is in, please submit a PR to include its link and with that we shall be in good shape to close this issue.

**Comment by shaggytwodope** [comment]
@odeke-em knowing more about go then I do, perhaps you can take a look at the log. https://launchpadlibrarian.net/195520557/buildlog_ubuntu-trusty-armhf.drive_0.0.7-6_FAILEDTOBUILD.txt.gz 

It's failing to build, and it's an error in go I'm not remorely fimilar with:

fatal error: rt_sigaction failure

runtime stack:
runtime.throw(0x656b92)
	/usr/lib/go/src/pkg/runtime/panic.c:464 +0x5c
runtime.setsig(0x40, 0x7c530, 0x65a601)
	/usr/lib/go/src/pkg/runtime/os_linux.c:306 +0xbc
runtime.initsig()
	/usr/lib/go/src/pkg/runtime/signal_unix.c:39 +0x94
runtime.mstart()
	/usr/lib/go/src/pkg/runtime/proc.c:594 +0x80

goroutine 1 [runnable]:
runtime.main()
	/usr/lib/go/src/pkg/runtime/proc.c:179
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394

It may be due to something with how the ppa builds work or my own mistake. Either way love to see if you can look into it when you've got time. I'll try to see about fixing this tomorrow or the day after, I won't be home. I'll be able to reply tho.

**Comment by odeke-em** [comment]
I'll jump onto this in a bit or if not tomorrow morning but on first glance this looks to me like this is a signal handler mask fail. What version of go?

**Comment by shaggytwodope** [comment]
Get:18 http://ftpmaster.internal/ubuntu/ trusty/universe golang-src armhf 2:1.2.1-2ubuntu1 [4727 kB]
Get:19 http://ftpmaster.internal/ubuntu/ trusty/universe golang-go-linux-arm armhf 2:1.2.1-2ubuntu1 [6235 kB]
Get:20 http://ftpmaster.internal/ubuntu/ trusty/universe golang-go armhf 2:1.2.1-2ubuntu1 [7264 kB]

**Comment by odeke-em** [comment]
Jeez, sorry @shaggytwodope that I forgot to help with this problem. On that day, I think I stumbled a bit with the whole package creation of which I am not familiar with. Would it be possible to just install go from source? -- this one I am totally familiar with and can help in case of any problems.
For the months or so I've been building go on a raspberry pi and just did a fresh re-install. Basically that would involve fetching go from the git repo, checking out a branch e.g go1.2.1 and then dropping into the src directory and compiling + building the source.
