### ISSUE TITLE
no preview of changes when noPrompt is true

### ISSUE THREAD

**Issue by rafmeeusen** [odeke-em/drive#300]
Hi, 

I noticed that when running drive non-interactive or when using -no-prompt, 
the preview of changes is not sent to stdout. 

Not sure if this was intended or not, but I would expect that no-prompt to _only_ have impact on the reading of stdin for continuing or not, and not have impact on what is printed to stdout. 

I changed this behavior in my fork (branch always_previewing). Not sure if you're interested and/or if I'm not breaking anything. 

best regards,
Raf

**Comment by odeke-em** [comment]
Hello @rafmeeusen, welcome to drive and thank you for reporting this issue as well as working on it!

Yes in deed, this sounds like reasonable behaviour to have and you are onto something. The only twist is that if say you are piping output to a non-tty or so, you don't need to provide a preview. Also currently `--no-prompt` couples with method
```go

func (opts *Options) canPrompt() bool {
    if opts == nil || !opts.StdoutIsTty {
        return false
    }
    if opts.Quiet {
        return false
    }
    return !opts.NoPrompt
}
```

So a possible way to get this behaviour in correctly would be to add a similar method say `canPreview()` and then couple that in the way that `canPrompt` is used.

Please let me know if this makes sense.

**Comment by pefoley2** [comment]
I'm also running into this.
I run drive as part of a nightly cron job, and it would be nice to see what happens even if I'm passing -no-prompt.

**Comment by rafmeeusen** [comment]
Hi @odeke-em, sorry had no time yet to look at your proposal, but I already can point out that I have the same use case as pefoley2 : auto-running drive / would like to have a log (i.e. stdout/stderr) saved to file.

**Comment by odeke-em** [comment]
Hello folks, thanks for the patience and for reporting this bug. I've fixed it in https://github.com/odeke-em/drive/pull/439. Please get the latest from master, it should be fixed.
