### ISSUE TITLE
can drive support the new google photos?

### ISSUE THREAD

**Issue by derekxgl** [odeke-em/drive#301]
Sorry, this is not an issue, but I do not know where it's appropriate to ask. Can drive support the new google photos?

Thanks,
Derek

**Comment by odeke-em** [comment]
Hello @derekxgl, thank you for reporting this and welcome to drive!

Unfortunately, currently there are no raw operations or direct exposure to Google Photos. I wonder, wouldn't that be an app on its own? If there is any documentation you might find alluding Google Photos to be operable with Google Drive, please let me know and I can take a look at it.

**Comment by derekxgl** [comment]
Thanks for your reply. I do not think Google has a Linux app for Photos.

**Comment by odeke-em** [comment]
For sure they don't have a Linux app. I was actually asking in case you might have found any API documentation or mentions suggesting that Google Photos operates with Google Drive. If that's the case then I can take a look at it.

**Comment by pkra** [comment]
> I was actually asking in case you might have found any API documentation or mentions suggesting that Google Photos operates with Google Drive.

Seems so http://stackoverflow.com/questions/30533971/is-there-an-upload-api-for-google-photos-photos-google-com

**Comment by odeke-em** [comment]
Thanks for that link @pkra. Unfortunately, I don't think that links Google Drive to Google Photos. That is linking Picasa Web Albums with Google Photos

**Comment by pkra** [comment]
Sorry about that. The line "Drive and Google+ make use of the Data API to persist photos. " seemed to indicate that but I'm just lurking without much understanding of the APIs. (But thank you for your work on drive!)

**Comment by jonbrock** [comment]
You can create a Google Photos folder in your Google Drive now, and then use drive to manipulate the photos. To set it up, go to drive.google.com, open settings, scroll down and enable the "Create a Google Photos folder" option. Once it's created you can rename the folder (if you want) and it continues to work.

**Comment by odeke-em** [comment]
Awesome that's great to know. Thank you @jonbrock.
I can confirm that your instructions work and that after adding the folder, I am able to use drive with it.
Would you mind creating a PR in the README and possibly adding an entry in the wiki?
Thanks again.

**Comment by odeke-em** [comment]
Going by @jonbrock's answer which I was able to confirm. I shall answer yes it can.
Thank you for raising this issue.
