### ISSUE TITLE
googleapi: Error 401: Invalid Credentials, authError only on big files

### ISSUE THREAD

**Issue by ldold** [odeke-em/drive#303]
Hello,

first, this tool saves my day, great job on this.  thank you!!

I have version 2.4.6 build on a debian machine. With files smaller 1GB I get them pushed to my google account:

drive-google push -quiet -ignore-checksum /path/file
or
cat file | drive-google push -piped -ignore-checksum /path/file

The following error accure for files bigger 1 GB:
googleapi: Error 401: Invalid Credentials, authError

I have not the fastest connection so 1 GB need to upload about 1 to 2 hours.

Do you know whats wrong here, I have no glue because files to a size of 800MB work fine.

Thank you 

kind regards

ldo

**Comment by odeke-em** [comment]
Hello @ldold, thanks for reporting this issue and welcome to drive!
Thank you for the kind words :) Hope it continues to serve you right.

Can you confirm that the file upload is completed after that it has reported that error? This might be due to the fact that am logging any errors that are encountered. If it aborts the 1GB upload then that's an issue.

**Comment by ldold** [comment]
Hello Emmanuel.

it goes to 100% and show the error, but there is no file in my account.

With smaller files and short push times there is no error.

kind regards

ldo

**Comment by odeke-em** [comment]
Alright, thanks for the confirmation. For starters what does `drive version` say?

**Comment by ldold** [comment]
Hi,

here the output:
root@clx01:/usr/src/drive_0.2.6/src/github.com/odeke-em/drive/drive-google# ./drive-google version
drive version: 0.2.6
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>

I built the binary on my development machine with go build and copied only the binary "drive-google" to the main backup server. Could this be a problem?

Thank you very much for your help

kind regards

ldo

**Comment by ldold** [comment]
Ah:
Commit Hasch: Current_commit
Go Verson: go version go1.3.3 linux/amd64
OS: debian jessie x64 (8)

**Comment by ldold** [comment]
Hi,

I tested a few things and I have to correct my description:

Same file for 1 and 2 (small file 1 mb)

1. piped drive-google, file exists
- pipe will error to use force. no upload
- with force the file is uploaded but the file is not available in google drive folder.

2. piped drive-google, file do not exists
- the file is uploaded and available in the google drive folder.

3. small file upload (not piped)
- upload ok, available ok
- error: serializeIndex filename.nc: invalid argument
- file is available in google drive folder

4. upload big files (not piped)
- upload ok, available not ok
- error: googleapi: Error 401: Invalid Credentials, authError
- file is not available in google drive folder

hope this helps to find the problem.

**Comment by ldold** [comment]
Hi,

just after the nigthly backup I get also this kind of message, which looks like do not have an impact on the upload:
549498717 / 549498717  100.00 % 0serializeIndex filename.tar.gz.nc: invalid argument

The upload was ok the file is available in my account.

Due to testing I let several jobs running at the same time and it looks like it is not a matter of size it seems like it is a matter of transfer time.

Running jobs at the same time and sharing the speed of my connection makes the smaller files < 1GB also end sometimes with googleapi: Error 401: Invalid Credentials, authError.

I have seen in the logs that a 3 GB file will need over 6 hours to upload maybe there is a timeout in some auth token or something.

kind regards

ldo

**Comment by ldold** [comment]
Hi,

any news on this topic or can you give me hint where the problem might be?

Thank you

kind regards

Lars

**Comment by odeke-em** [comment]
Hello @ldold, please get the latest from master by
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
It has a mechanism for retrying on errors.
Thank you for the patience.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Closing this issue since it was resolved already. Please get the latest from master.
