### ISSUE TITLE
Spurious modifications

### ISSUE THREAD

**Issue by pefoley2** [odeke-em/drive#304]
When I run drive pull, I get a bunch of pending modifications each time, even though nothing's changed on the server side.

**Comment by odeke-em** [comment]
Hello again @pefoley2.
Time differences? Sure everything is coming in? Did you run this as root and now running it with different permissions?

**Comment by pefoley2** [comment]
I'm running it as the peter user, although I pointed it at a directory that already contained files owned by the backup user/group.

**Comment by pefoley2** [comment]
Hm, looks like chowning to the peter user fixed this.
A error message of some sort about permission problems would be nice, though.
Currently you just get a bunch of "modified" files each time you run, for no apparent reason.

**Comment by odeke-em** [comment]
Sure :) I'll just have to make checks for access permissions before, doesn't seem like attempting reads will yield any errors so far.

**Comment by odeke-em** [comment]
@pefoley2 please take a look at PR https://github.com/odeke-em/drive/pull/305

**Comment by odeke-em** [comment]
PR https://github.com/odeke-em/drive/pull/305 addresses the concerns raised in this issue. Thank you for reporting it. Please re-open if it persists.
