### ISSUE TITLE
unrecognized inport path

### ISSUE THREAD

**Issue by GigabitPony** [odeke-em/drive#319]
So I ran the command go get -u gopath=github.com/odeke-em/drive/cmd/drive and also go get -u github.com/odeke-em/drive/cmd/drive, I keep getting the same error as the title. Been searching around and nothing has been helping so far.

**Comment by odeke-em** [comment]
Hello @GigabitPony, welcome to drive! Thank you for reporting this issue.

For starters, would you mind setting up your $GOPATH as detailed here https://github.com/odeke-em/drive#requirements? and don't forget to reload your settings in the terminal either by opening a new terminal or `$ source ~/.bash_rc` (on Linux) or `$ source ~/.bash_profile` (OS X).

If the issue persists after the above suggestions, please provide me with your Go version, OS and as much diagnostic information including the exact error message.

**Comment by GigabitPony** [comment]
Yeah I am newish to linux I got it figured out now, a friend of mine got home and helped me. Cloning the code and building it right now! Sorry for the issue

**Comment by odeke-em** [comment]
No biggie @GigabitPony we all began somewhere :) Thank you for checking out drive right as you got started with Linux. Please don't hesitate to reach out in case of any questions whatsoever or any issues. Enjoy!

**Comment by GigabitPony** [comment]
Okay the only thing I am running into know, if you do not mind is this.
soarin@GamerLuna:/src/github.com/odeke-em$ go get -u github.com/odeke-em/drive/cmd/drive
# google.golang.org/cloud/compute/metadata
/home/soarin/go/src/google.golang.org/cloud/compute/metadata/metadata.go:54: unknown net.Dialer field 'KeepAlive' in struct literal

**Comment by odeke-em** [comment]
No worries. Please get go1.3 or greater.

**Comment by GigabitPony** [comment]
Ah okay, doing so now

**Comment by odeke-em** [comment]
Ping!

**Comment by GigabitPony** [comment]
Sorry I forgot to post back, I finally figured it out, was simple mistake
on my end.

**Comment by odeke-em** [comment]
No worries. Closing this issue, cheers!
