### ISSUE TITLE
Uninstall drive

### ISSUE THREAD

**Issue by CountryBumkin** [odeke-em/drive#32]
With ther frequent versions available I was trying to do a clean test with no historical baggage. The drive init command does not forget old directorires. Could the wiki and/or doc files include a list of files (including the hidden ones) to delete to ensure a clean start.

regards CB

**Comment by odeke-em** [comment]
Ah I see what you mean. I'll get that in in the morning. Thanks for the clarification.

**Comment by odeke-em** [comment]
To uninstall drive:
+ Executable will be located at: `$GOPATH/bin/drive`
+ Mounted folder: remove your mounted folder
   ++ Credentials will be in a hidden file in your mounted folder ie. `mounted_folder/.gd`
+ Source code: $GOPATH/src/github.com/odeke-em/drive

You can remove those from their appropriate paths.
