### ISSUE TITLE
"Out of memory" while running go get

### ISSUE THREAD

**Issue by canpolat** [odeke-em/drive#323]
I wanted to install *drive* on my Raspberry Pi today, but then I noticed my RPi doesn't have enough memory. I get either of these while running `go get github.com/odeke-em/drive/drive-gen`:

    go build golang.org/x/text/collate: /usr/local/go/pkg/tool/linux_arm/5g: signal: killed

    gopath/src/golang.org/x/text/collate/tables.go:68971: internal compiler error: out of memory

I'm running these on Raspbian with 512MB memory:

    $ free -m
                 total       used       free     shared    buffers     cached
    Mem:           482        104        378          0          2         19
    -/+ buffers/cache:         81        401
    Swap:            0          0          0

And using a supported version of `go` (got it from [here](http://dave.cheney.net/unofficial-arm-tarballs)):

    $ go version
    go version go1.4.2 linux/arm

I couldn't find a way to work around it, so I'm stuck until I find another way. I realize that this is not a drive-specific problem, but if there is a memory limit, then perhaps it should be mentioned in the *Requirements* section of the README? The [Go: Getting Started](https://golang.org/doc/install) page doesn't list any memory requirements either. So I wonder if I'm doing something wrong...

**Comment by odeke-em** [comment]
Hello again @canpolat. Unfortunately that's an issue beyond my control as those Go packages seem to be tripping things out. Please see issue https://github.com/odeke-em/drive/issues/273. However, I am able to install drive on my Raspberry Pi in seconds. Unfortunately it is at home, so if you can wait for 6-7 hours, I can rig up a binary for you. Later, I'll introduce cross-compilating.

**Comment by canpolat** [comment]
I guess we can close the issue and mention the limitation in the README then (since I'm not a Go developer I don't know much about what to expect)?

It would be great if you could pass your binary, btw. In the meantime, I'll try some other tricks and report back if I can solve the issue.

**Comment by odeke-em** [comment]
No worries, you can also check out wiki entry https://github.com/odeke-em/drive/wiki/Precautions-for-building-on-devices-with-less-than-1GB-RAM

**Comment by canpolat** [comment]
That wiki page actually addresses my problem. I already started another build with a swap file... Closing this one then.

**Comment by odeke-em** [comment]
Cool, glad to know your problem was addressed.

**Comment by odeke-em** [comment]
@canpolat thanks for the patience. I've taken out the text/collate package. Please get the latest from master by:

```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by canpolat** [comment]
@odeke-em Thanks. I got it working after adding some swap. But will give this one a shot as well.
