### ISSUE TITLE
.driveignore doesn't seem to ignore "/Google Photos"

### ISSUE THREAD

**Issue by twstdpear** [odeke-em/drive#328]
Now that Google makes your photos available in Drive, I don't want to use "drive" to sync my "Google Photos" directory.  

>$ drive version
drive version: 0.2.7
Commit Hash: \<CURRENT_COMMIT\>
Go Version: \<GO_VERSION\>
OS: \<OS_INFO\>
BuildTime: 

This works as expected:
>$ mkdir "Dir Space"
$ touch "Dir Space"/a
$ echo /Dir Space > .driveignore
$ drive push Dir\ Space
Resolving...
'/Dir Space' is set to be ignored yet is being processed. Use `force` to override this

A plain "drive push" also properly ignores "/Dir Space".  I can't show it here because of the issue below, but I verified it didn't show up in the list of proposed changes.  So, I don't seem to be doing anything stupid with regard to .driveignore.

The behavior changes when working with "Google Photos"
>$ echo /Google Photos > .driveignore
$ drive push "Google Photos"
    Resolving...
    '/Google Photos' is set to be ignored yet is being processed. Use `force` to override this

So far, so good.

However, a plain "drive push" wants to delete everything in /Google Photos directory on the remote.  

>$ drive push
Resolving...
\- /Google Photos
...
\- /Google Photos/2015
\- /Google Photos/2015/07
\- /Google Photos/2015/07/IMG_1108.JPG
...
\- /Google Photos/2003/12/img_0060.jpg
\- /Google Photos/2003/12/img_0068.jpg
Deletion count 5826 dest: 7.61GB
Proceed with the changes? [Y/n]:n

"drive pull" has similar behavior to "drive push" in all cases.

**Comment by odeke-em** [comment]
Hello @twstdpear, welcome to drive and thank you for reporting this issue.

When I get back home in about 7 hours, I'll take a look at it.

**Comment by odeke-em** [comment]
Please get the latest from master. Addressed by https://github.com/odeke-em/drive/pull/336.
You can get the latest from master by

```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by odeke-em** [comment]
Filing a new release in a bit, so closing this in a bit.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/336, closing it. Please re-open if it persists. Thank you for reporting this issue!

**Comment by twstdpear** [comment]
Sorry for the delay in testing.
Confirmed that it fixes my issue.  Thanks!
