### ISSUE TITLE
drive list command pagination

### ISSUE THREAD

**Issue by CountryBumkin** [odeke-em/drive#33]
I was using the list command to test duplicate file issues and with over 1000 files involved the pagination became a pain. Is there something like a -no-more option so if the output is redirected to a file then the list is simply sent all at once.

Some examples of using pretty printing options would be educational as well.

Regards CB

**Comment by odeke-em** [comment]
-no-prompt

**Comment by odeke-em** [comment]
Also the README has a section for listing.

**Comment by odeke-em** [comment]
Btw you can find out what the different options for a command are by using the `-h` flag e.g `drive list -h`

**Comment by CountryBumkin** [comment]
I had checked the readme, there is no discussion of pagination.
I tried on version 4 and this resulted
tony@Cooli7 ~ $ drive list -d 3 -no-prompt /gd > gd.txt
flag provided but not defined: -no-prompt
Usage of list:
  -a=false: list all paths even hidden ones
  -d=1: maximum recursion depth
  -h=false: 
  -p=-1: number of results per pagination
  -r=false: recursively list subdirectories
  -trashed=false: list content in the trash

CB

**Comment by odeke-em** [comment]
Please make sure you are using the latest. Releases are made whenever targeted issues are addressed. So essentially v0.0.5 will have it as it was introduced after v0.0.4 was released.

**Comment by odeke-em** [comment]
`drive list`
  Usage of drive list:
     -a=false: list all paths even hidden ones
     -d=1: maximum recursion depth
     -no-prompt=false: shows no prompt before pagination
     -p=-1: number of results per pagination
     -r=false: recursively list subdirectories
     -trashed=false: list content in the trash

**Comment by CountryBumkin** [comment]
Works as indicated, thanks.
