### ISSUE TITLE
Selective sync - i.e. only sync some directories by whitelisting

### ISSUE THREAD

**Issue by alanfranz** [odeke-em/drive#334]
Hello,
right now drive has a "sync all but ignored files" way of working.

I'd like to have the exact opposite way of working, something like "sync only those directories that I tell you": in fact on a large company account there may be tons of folders that can get modified all the times, and they're probably added to your account as well; if I always pull everything, things can get very slow (and it may take a LOT of space on the disk as well).

If you think it makes sense I may try to contribute such future.

**Comment by odeke-em** [comment]
Hello again @alanfranz.
You can already do this. This is the way drive has worked from the beginning ie.

```shell
$ drive push p1 p2 p3
$ drive pull p4 p5 p6
$ drive pull --matches pxpat
```

**Comment by odeke-em** [comment]
Ping!

**Comment by alanfranz** [comment]
Hello,
I think that I'd like a "configuration option" for a directory, not something that I must do each time. I'm currently on vacation, when  get back I'll forward you a proposal.

**Comment by christopherreay** [comment]
Hi. Ive been trying for more than an hour now. I have no concept of how push calculates files at remote or local end.

I have a directory in My Drive /earthWays/backups
I want to push files from my local machine into earthWays/backups
I have created a symlink structure on my local disk to match the drive structure
Ive tried everything I can think of

E.g. drive push ./* earthWays/backups
drive push earthWays/backups/* earthWays/backups/*
drive push .* (with matching directory structure). This brings up name conflict errors for whcih I can resolve no logical meaning at all. The local directory structure contains nothing but earthWays/backups/files.

What paradigm am I missing here?

**Comment by odeke-em** [comment]
Hello @christopherreay , welcome to drive and thanks for checking in.

So for starters of a walk through, basically drive will try to match up the files present locally with those available remotely. So it will start with the file paths e.g
relative to the directory containing `.gd/credentials.json` which is your "root"
 local /a/b/c checked with /a/b remotely, c doesn't exist remotely, so make an addition.
 local /d/e/f checked with /d/e/f remotely: hmm, same file type(both files or directories?)?. Do both have the same size? Do they have the same modification time? Do they have the same checksum, if that's being checked.

Name conflicts result from the fact that Google Drive supports infinitely many files with the same name in the same folder, however your file system cannot handle this. Given 20 /a/b files present remotely, and 1 locally (FS dictates) when pushing which of the 20 files should I push to?
This is  mentioned in the README along with other things. There is an option which drive should mention to you called `--ignore-name-clashes`, and it will turn a blind eye to the 20 to 1 selection I had mentioned earlier, and just pick the first one. However, I'd advise  you to just open up the folder in the Google Drive web UI and sort those out, or you can `drive open --file-browser=false --web-browser=true`.
Ahaha, yeah fast connections up there right? My upload and download speeds at my school are ridiculous that uploading hundreds of Gigabytes happens in less than a half of a day (I employ some other tricks too ;)).

Hope this can help.

**Comment by christopherreay** [comment]
But, if its "Drive Push" why would there be name conflict errors on the download

Thanks

The internet is absolutely awesome. And still so young. Mobile apps that couldnt exist on a desktop... its the next major disrupt.

Be prepared for your predictions to come true

**Comment by odeke-em** [comment]
@christopherreay please take a look at the README it explains this, and the explanation above applies to both push and pull.

**Comment by odeke-em** [comment]
I'll be closing this issue soon as the options for "whitelisting" are already present, and a .driverc is coming soon
