### ISSUE TITLE
List command problem

### ISSUE THREAD

**Issue by CountryBumkin** [odeke-em/drive#34]
Evey option I try with the list command fails with 'no gd context is found; use gd init'. It did work earlier in the day, pull and push both work, I have tried init several times and there is no difference. Is some magic required ?

regards CB

**Comment by odeke-em** [comment]
You have to be within the folder that you mounted your drive ie where your credentials are.

**Comment by CountryBumkin** [comment]
It works there, I think a modification of the README might save some angst, it shows path1 and path2 syntax just the same as pull and push. Possibly highlight  that the init command appears to have an odd path syntax as well.
CB

**Comment by odeke-em** [comment]
Remember that list is for remote listing so typically if you have a path in remote you can do:
`drive list -d -1 path`
OR
`drive list -d -1 path1 path2 path3`
OR
`drive list -d -1` // The path will be resolved relative to the current working directory.

**Comment by odeke-em** [comment]
@CountryBumkin feel free to submit a PR.

**Comment by odeke-em** [comment]
@CountryBumkin drive init is what creates a drive context, you can't have one without init.
