### ISSUE TITLE
not using available bandwidth

### ISSUE THREAD

**Issue by ob7** [odeke-em/drive#340]
Hello,

I have 20 M/bps upload & download with my internet provider.  When I do a download test at speedof.me, I can see my Tx and Rx packets go up to the full 20.  Why then when nothing else is running, drive push only utilizes under 1M/bps.  Do I need to specify somewhere that drive can use much bandwidth as is available?  Or is this being limited by google?

Heres someone who has the opposite problem, they want to limit their speed, not sure if its related:
https://github.com/odeke-em/drive/issues/240

**Comment by odeke-em** [comment]
Hello @ob7, thank you for reporting this issue and welcome to drive! I've actually been waiting for this question for a bit :)
So, yes in deed Google has rate limits, and this will affect you. Currently, the default number of concurrent pushes/pulls is 4, however you can change this by setting `DRIVE_GOMAXPROCS` in your env something like this

```shell
$ cat < ! >> ~/.bashrc
> export DRIVE_GOMAXPROCS=<n> # where n is an integer >= 1
> !
$ source ~/.bashrc # Make sure to reload your settings
```
However, as mentioned rateLimits will trip you out, but don't fret there is an exponential back off mechanism.
Also please make sure you have the latest by
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by odeke-em** [comment]
Oh and I should mention, to see the current status during pulls or pushes, use flag `--verbose` e.g
```shell
$ drive push --verbose 2015_Drawings
```

**Comment by ob7** [comment]
When using verbose command it says 'flag provided but not defined'.  I just updated yesterday but I will update again now to see if that fixes verbose.

For the export option, is the number written out inside the brackets, or are the brackets there for visual aid?  should my bash file say:
export DRIVE_GOMAXPROCS=<10> or export DRIVE_GOMAXPROCS=10

**Comment by odeke-em** [comment]
If you got that warning, that means that you are using code that is 5 days old, `verbose` got added 5 days ago with commit https://github.com/odeke-em/drive/commit/93c69c32657c3ae35c1cca1ba6a9290191fa0737. Please do `go get -u github.com/odeke-em/drive/drive-gen`.
Yes in deed, a higher number means more concurrent ops.
`<n>` was just the place holder. `export DRIVE_GOMAXPROCS=10` cuts the deal :)

**Comment by ob7** [comment]
Right now I've got GOMAXPROCS set to 1000, Its not a steady speed but will spike up to 5mbs or so depending on the file.  I'm not sure what googles limit is, but I'm going to try setting to 10000 would that be ok?

**Comment by odeke-em** [comment]
Wow, 1000? I go max to 8 and the speed is alright even then I still get userRateLimitExceeded errors. 1000 is interesting, probably use say 20, depends on you.

**Comment by ob7** [comment]
Can you think of any other reasons my uploads would go slow?

**Comment by ob7** [comment]
I guess its probably not related to drive?

**Comment by odeke-em** [comment]
It is good thought to keep in mind, however unfortunately I couldn't guess right now what the bottleneck could be, it could be related to how much I/O reads could be allowed by your machine, it could be read acknowledgement rates by Google Drive, the parallelism actually available on your machine etc. But it is something I keep in mind while developing this application. Thank you for raising this issue.

**Comment by ob7** [comment]
Well thanks for developing this program because it is TOTALLY AWESOME!!!!!!!!!

**Comment by odeke-em** [comment]
Thank you for the kind words @ob7! Glad to know it is going great so far for you. Please don't hesitate to reach out in case of any questions, suggestions or issues.
