### ISSUE TITLE
ignore directorys

### ISSUE THREAD

**Issue by ob7** [odeke-em/drive#341]
Is there a way to ignore certain directories?  This would be nice to do a full system backup, but ignore connected network drives, etc.

**Comment by odeke-em** [comment]
Hello again @ob7! Yes there is, please take a look at creating a .driveignore file https://github.com/odeke-em/drive#driveignore

**Comment by ob7** [comment]
Is it pretty straight forward?  Do ignore directories can I just include their full path in the file?
Example:
/mnt/shared/
/mnt/VM/Windows/

and those folders will not be included in upload?

**Comment by odeke-em** [comment]
Yes it is. Please try it out :)

**Comment by ob7** [comment]
I did but I received 'too many levels of symbolic links' amongst other errors.  Does drive use lots of disc space such as git, where the git repo can be just as big as the files themselves, doubling the size of files of disk?

**Comment by ob7** [comment]
Do I need to backslash the space in a file path if one exists?

**Comment by odeke-em** [comment]
Not really, you won't need that. However, it would be useful to note that it matches by regular expressions so 'Google Drive' will work 'Google\s+Drive' will too, '^Goog' will ignore anything beginning with 'Goog'.

**Comment by odeke-em** [comment]
I hadn't seen your message
`I did but I received 'too many levels of symbolic links' amongst other errors. Does drive use lots of disc space such as git, where the git repo can be just as big as the files themselves, doubling the size of files of disk?`
Too many levels of symbolic links is something even your file system utilities will encounter if you have too many circular symlinks. And no, drive only has a DB plus your credentials. I have Gigabytes and Gigabytes of accounts with no problems.

**Comment by ob7** [comment]
Thank you for that explanation.  Just curious to how this works.  What is drive doing during "Resolving..." ... This takes a while for me, maybe 30 - 1 hr or more when doing huge push.

**Comment by odeke-em** [comment]
Trying to match up remote and local paths, trying to find out what to delete, update, upload etc. You know you don't always have to run drive in the root, drive allows for specifying multiple paths e.g
```shell
$ drive push vines memes
$ drive pull assignments
```

**Comment by ob7** [comment]
Right, which is a great feature.  I'm trying to make an entire backup of my whole system, so I initiated drive from / and pushed from there.  But that's about 500 G of files so it may take a while. I'm putting this thing to the test!

**Comment by odeke-em** [comment]
Awesome! I am interested in getting feedback after that push, please keep me updated ;)

**Comment by ob7** [comment]
So I'm getting:
googleapi: Error 500: Internal Error, internalError
googleapi: Error 503: Backend Error, backendError

but hasn't pushed me out to command prompt yet....

**Comment by odeke-em** [comment]
That is because you have verbose set to print out for you the errors encountered. Also what does `drive version` return you, please make sure you aren't using code from 6 days ago like you had before.
`go get -u github.com/odeke-em/drive/drive-gen && drive-gen` should get you the latest code.
If you have the latest at least from 5 days back, it should show you an auto-retry such as
```
trying again in 1.182s
trying again in 2.473s
...
```

**Comment by ob7** [comment]
Yes I see auto retry.  I have version
drive version: 0.2.7
Go Version: go1.4.2
OS: linux/amd64

**Comment by ob7** [comment]
I wonder what the google errors where about?  I've got a terabyte of storage so space shoudn't be a problem.

**Comment by odeke-em** [comment]
It never returned you the commit hash though ;) Oh, the errors are mostly just internal errors, don't worry they too get errors. Ah nice, you on the Terabyte power house. After a bit it should get pushing up.

**Comment by ob7** [comment]
sry missed that line:
drive version: 0.2.7
Commit Hash: '9050e2b2daeda3bbc4ea8f9374834099e3c69eef'
Go Version: go1.4.2
OS: linux/amd64

**Comment by odeke-em** [comment]
Nice, you are set then, 2 commits behind the latest push but all good. Getting the latest wouldn't hurt though, but if you already started your push it can wait.

**Comment by odeke-em** [comment]
Okay, closing this issue since it was resolved already.
