### ISSUE TITLE
drive push; googleapi: Error 403: Insufficient permissions for this file, forbidden; Ownership

### ISSUE THREAD

**Issue by aitch251** [odeke-em/drive#342]
I want to pull data to my server and move it elsewhere.
When i push the changes, i'm not able to delete the files on Google Drive because of the ownership.

To describe the workflow:
- Create drive folder on drive.google.com
- Share it with User X on drive.google.com
- User X uploads data on drive.google.com
- drive pull folder/folder/ on Ubuntu Server
- a service app moves the data elsewhere and creates a logfile on Ubuntu Server
- drive push folder/folder  on Ubuntu Server -> permission Error

I searched for a while but couldn't find a solution.
Is there a way to change the owner? On drive.google.com i'm able to delete files which i don't own.

**Comment by odeke-em** [comment]
Hello @aitch251, thanks for raising this issue and welcome to drive!
So, that isn't really an error on drive's side since the user (Ubuntu Server) trying to make the modification actually doesn't have the permissions to modify it though they might have permissions to read. If you'd like to change the permissions for that user, log onto Google Drive, and you can switch up the permissions there. You can also view the different permissions in like this
```shell
$ drive stat [options] folder/folder
```

**Comment by aitch251** [comment]
Hey. Thanks for the response.

I already checked for permission on Google Drive. Still can't push / delete files, which i don't own.

Some more details:
![bildschirmfoto 2015-08-14 um 10 21 49](https://cloud.githubusercontent.com/assets/13779006/9270018/a92bd0a4-426e-11e5-996c-d598b918b9a4.png)

![bildschirmfoto 2015-08-14 um 10 25 01](https://cloud.githubusercontent.com/assets/13779006/9270052/e29d6c80-426e-11e5-93ec-dcbbb9a84a7a.png)


BTW: We want to move many files from europe to asia and back. With scp, ftp and owncloud (self hosted) we got many Problems according to transferrates (mostly under 200kB/s).
With Google Drive in the middle we were able to get transferrates with over 800kB/s (mostly round about 1-2MB/s).
If i get this to work with our ubuntu server and Drive it would fit perfect in our automated workflow.

**Comment by odeke-em** [comment]
Ah I see, that's awesome that y'all gonna use drive for this use case :)

Would you mind actually on the Ubuntu server, running `drive stat folder/folder`?

**Comment by odeke-em** [comment]
Also `drive version`.
 Hope you built it by 
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by aitch251** [comment]
![bildschirmfoto 2015-08-14 um 10 32 56](https://cloud.githubusercontent.com/assets/13779006/9270248/7638e950-4270-11e5-8de6-07ce34fd4e50.png)

**Comment by aitch251** [comment]
![bildschirmfoto 2015-08-14 um 10 39 35](https://cloud.githubusercontent.com/assets/13779006/9270291/c854e356-4270-11e5-8855-5395ef81b575.png)

**Comment by aitch251** [comment]
But it is usually possible with "this drive tool" to delete or move files, which i don't own, but be able to edit, isn't it?

**Comment by odeke-em** [comment]
So, with `writer` permissions you can edit the file and make mods, however the API prevents you from deleting them. But the UI on the other hand will let you delete the file but warn you that another user still has access to the file. You can push up content into those files, just deletions are trippy.

**Comment by odeke-em** [comment]
And yes it is possible to move, rename, touch files that you don't own, as long as the write permissions are set.

**Comment by aitch251** [comment]
mhhhhh.. when i can't delete files which i don't own.. then i need to find a workaround. We don't want our customers to overcrowd our Drive.

I will try to move the files to a "trash bin" or sth like that. But first: I'll have lunch.

Thanks for your help. :)

**Comment by aitch251** [comment]
Ok. This works for me to get the files and remove them from Drive:

Drive pull folder1/X
Drive move folder1/X folder2/
Drive delete folder2

i own: folder1, folder2
other own: X

Does this make sense? haha

**Comment by odeke-em** [comment]
That's alright since folder1 is a parent of X, and so is folder2 #precedence

**Comment by odeke-em** [comment]
So can we close this issue?

**Comment by aitch251** [comment]
yes. And thanks again for your help.

**Comment by odeke-em** [comment]
Cheers!

**Comment by simone-viozzi** [comment]
i'm having the same issue, 
but for me moving the file to a new folder and than delete the folder is not a viable solution, or at least not an easy one.

i have a large tree of files with files/folders owned by a lot of people and i'm trying to move everything under one account.

i can provide a specific use case with the log if needed but is the same issue
