### ISSUE TITLE
CPU Gets Hot

### ISSUE THREAD

**Issue by ob7** [odeke-em/drive#344]
Hello,

What causes my CPU to work so hard in this?

Thanks,
David

**Comment by odeke-em** [comment]
Hello again @ob7.
So from our interaction yesterday, you mentioned that you set your `DRIVE_GOMAXPROCS` to 1000 or even 10,000. That could be the trouble -- I mostly use 4 or 8 and it works alright for me.

**Comment by ob7** [comment]
Well I set it down to 20, it still does something thats reall processor
intensive, and its during "Resolving".  So I was curious as the how that
worked since whatever its doing seems to be what gets CPU going so hard.

Thanks,
David

**Comment by odeke-em** [comment]
Hello @ob7, I think we already discussed this on what resolving was doing
<img width="775" alt="screen shot 2015-08-14 at 11 39 44 am" src="https://cloud.githubusercontent.com/assets/4898263/9280098/3bb9aa4a-4279-11e5-9e56-843919a2fc0a.png">

**Comment by ob7** [comment]
So its go code?

**Comment by odeke-em** [comment]
Well the go code is what does all the resolution. You are welcome to check out the code in src/changes.go. My apologies if I respond late, as I am a little bit busy.

**Comment by ob7** [comment]
Oh not at all - Im rather impressed how ontop of your repo you are.  Thanks
for answering all of my questions.

Thanks,
David

**Comment by odeke-em** [comment]
Thank you :)

**Comment by odeke-em** [comment]
Can we close this issue since it is a bit subjective, relative to the computer you are running, the size of a "huge" push, the resources available -- too broad to exactly trace.

**Comment by ob7** [comment]
Yes.  Btw got an Asus G750 so no more overheating.

**Comment by odeke-em** [comment]
Cool! I actually run drive off a Raspberry Pi as well, but I don't do as much work on it.

**Comment by ob7** [comment]
I use Arch Linux for everything, have yet to build a rasberry pi, just
ordered my first Arduino board though and am looking forward to learning C!

**Comment by odeke-em** [comment]
Aha nice! That's gonna be a great journey. Got your K & R C? ;)

**Comment by ob7** [comment]
Whats that?

**Comment by odeke-em** [comment]
https://en.wikipedia.org/wiki/The_C_Programming_Language#/media/File:The_C_Programming_Language_cover.svg

**Comment by ob7** [comment]
Oh u mean
http://www.amazon.com/The-Programming-Language-Brian-Kernighan/dp/0131103628

**Comment by odeke-em** [comment]
Yap, there you go! Hopefully it'll be a good one. I like that book ;)

**Comment by ob7** [comment]
Just ordered a copy cant wait!

**Comment by odeke-em** [comment]
Awesome, happy good will hunting!

**Comment by ob7** [comment]
Thank you kind sir.
