### ISSUE TITLE
err: unexpected EOF

### ISSUE THREAD

**Issue by mgolub2** [odeke-em/drive#345]
When pulling all the contents of my google drive, I get err: unexpected EOF on over half of the files. Downloading the via the web interface and opening them locally works fine, so they are not corrupted.

**Comment by odeke-em** [comment]
Hello @mgolub2. Thank you for reporting this issue and welcome to drive.

So for starters, would you mind giving the drive version information that you can compile by running:
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
````

**Comment by mgolub2** [comment]
I'm using version 0.2.8, built with go 1.4.2 on Ubuntu 14.04. I used the command to build and run the program when I first encountered the issue, and still saw the same behavior. 

I searched through the source code, and wasn't able to find any instance of that string, looks like it comes from something else in the go library. Looking around github there a couple of open issues in the docker repo with the same problem. 

It could possibly be due to either the size of the files, most of which are greater than 100mb, or the server's location/connection in Canada?

**Comment by odeke-em** [comment]
Hello @mgolub2, the commit hash would also be helpful that's why running
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```
would be useful.

Hmm, so I have been running as well as building this code in Alberta, Canada, so I'd rule out the location being the trip. Now, quick question what do the permissions for those files look like? Also, what type of files are they?

**Comment by mgolub2** [comment]
All I get after running that command then doing: drive version is: 
drive version: 0.2.8
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:

There are a variety of files, lots of nikon raw images, .nef, some tif images, and some tar.gz files. On the server that pulled from the drive, the permissions are -rw-rw-r-- for all the files.

**Comment by odeke-em** [comment]
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```
NOT
```shell
$ go get github.com/odeke-em/drive/cmd/drive
```

**Comment by odeke-em** [comment]
Ping!

**Comment by mgolub2** [comment]
Sorry for the delay, I was traveling. 
Here is the info from the version with the debug information:
drive version: 0.2.8
Commit Hash: 'b41dc46a6d2d6cbbd21b67cce69824751cdbe841'
Go Version: go1.4.2
OS: linux/amd64
BuildTime: 2015-08-23 02:53:32.435730955 -0400 EDT

**Comment by odeke-em** [comment]
Any way of reproducing this issue?

**Comment by mgolub2** [comment]
Anytime I run this on a new server, I get this issue with some subs too files. Running the pull over again results in fewer EOFs, until none are left. 

I don't see this issue with a different hosting provider however.

**Comment by odeke-em** [comment]
Only happens with one hosting provider? Might they be rate limiting you or closing different connections? This seems like a plausible theory given that it is only with this one hosting provider and also running it many times over results in fewer EOFs until none are left.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Please get the latest from master. PR https://github.com/odeke-em/drive/pull/395 allows encountered errors to be retryable until all the tries are exhausted then it will fail. Thank you for reporting this. Please reopen if it persists.
