### ISSUE TITLE
oauth2: cannot fetch token: 400 Bad Request

### ISSUE THREAD

**Issue by PeterSprague** [odeke-em/drive#346]
Can't get local drive initialized, drive init returns:

oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_grant",
  "error_description" : "Code was already redeemed."
}

I have:
run drive deinit
deleted .gd
checked app permission in Google account, none there
made sure all other Google accounts are closed
retried numerous times - same error
 
Other apps have no issues with tokens

**Comment by PeterSprague** [comment]
Rebooted
Was using Firefox, but changed to Chromium to retrieve token
Drive initialized

**Comment by odeke-em** [comment]
Sorry for the late reply, I was tied up in meetings. Glad to know you resolved this issue. Also welcome to drive!
