### ISSUE TITLE
Bad files after pull

### ISSUE THREAD

**Issue by mwisnicki** [odeke-em/drive#350]
I've initialized and pulled my drive with `ignore-name-clashes`.

There were a couple of `operation timed out` errors but most things got downloaded.
Files reported in these errors seem to exist locally but the contents look corrupted.

In case of errors, local files should either be removed or re-downloaded until they are correct.

Another problem is that when I've tried pull second time, those files were not reported as modified, which I assume means that drive will not try to repair them for some reason. On the other hand a small list of files that were not modified and seem correct are reported as conflicts (`These 7 file(s) would be overwritten`).

**Comment by mwisnicki** [comment]
When I added `-ignore-conflict` all bad files are reported with `X` status so I guess the second problem doesn't exist.
However the list is of added files (`+` status) is quite long even though I didn't modified/added any of them recently.

**Comment by odeke-em** [comment]
Hello again @mwisnicki, by "corrupted" what do you mean?

**Comment by mwisnicki** [comment]
I mean they are not valid jpg/pdf files (cannot open them).

**Comment by mwisnicki** [comment]
Oh, and the second pull failed with go stacktrace - should I report that as another issue or add it here ?

**Comment by odeke-em** [comment]
And the files with the similar names are not jpg nor pdf files either? Am quite surprised by the results of your pulls, "Operation timed out"?
If you ignored name conflicts and the contents were mismatched, please check to see that files themselves upstream are what you think they are.
Also, `drive version` after `go get -u github.com/odeke-em/drive/drive-gen && drive-gen`?
Sure you can post the stacktrace here. Did you by any chance compile this with cgo?

**Comment by mwisnicki** [comment]
Timeout errors looked like this:
```
pull: /some/file.pdf err: read tcp 216.58.209.65:443: operation timed out
```
Upstream files are correct, checked both online and as downloaded by official windows client.

Result of my `drive version`:
```
drive version: 0.2.8
Commit Hash: 'b41dc46a6d2d6cbbd21b67cce69824751cdbe841'
Go Version: go1.4.2
OS: freebsd/amd64
BuildTime: 2015-08-23 09:19:12.690060186 +0200 CEST
```

I've installed drive yesterday using `go get -u github.com/odeke-em/drive/cmd/drive` with go 1.4.2 on FreeBSD 9/amd64.

The stacktraces on drive pull look like this:

```
Addition count 170 src: 942.47MB

goroutine 1340 [chan receive]:
github.com/odeke-em/drive/src.func·030()
        /home/marcin/.local/go/src/github.com/odeke-em/drive/src/pull.go:702 +0x67
created by github.com/odeke-em/drive/src.(*Commands).singleDownload
        /home/marcin/.local/go/src/github.com/odeke-em/drive/src/pull.go:710 +0x5d8
```

There are 8 of them.

**Comment by mwisnicki** [comment]
And third invocation of `drive pull --ignore-name-clashes --ignore-conflict` had different summary:
```
Addition count 163 src: 1011.46MB
Modification count 1 src: 1.21MB dest: 1.21MB
Clashing modification count 1 src: 120.62MB dest: 97.12MB
```

and finished without issues. Previously broken files look correct now (at the ones I checked).

**Comment by mwisnicki** [comment]
However executing this for fourth time, it still wants to download something:
```
Addition count 44 src: 89.49MB
Clashing modification count 34 src: 46.16MB dest: 67.20MB
Modification count 4 src: 4.22MB dest: 4.22MB
```

**Comment by odeke-em** [comment]
Yeah ignoring name clashes will perform a greedy grab of the first file that can be found. It doesn't fix the fact that the unpulled files shouldn't remain unpulled. Unfortunately, It is a nasty work around for users that have clashing names. You can always `drive rename paths....` :)

**Comment by mwisnicki** [comment]
What about addition count ? It keeps reporting around 40 new files every time (each time different amount) ?

**Comment by odeke-em** [comment]
Yeah sure, about 40 missing files that haven't yet been pulled and cannot be pulled because they'll clash -- Google Drive handles clashing paths, your file system won't :( So would renaming be alright?

**Comment by mwisnicki** [comment]
Hmm... indeed they seem to be duplicates. Mostly photos, I think with auto-enhancements done by google+.
I'm too lazy to rename them :)
Ideally I would like drive to perform auto-renaming of clashing names, but only locally (keep mapping somewhere and use it when syncing).

**Comment by odeke-em** [comment]
Aha I hear ye, you could write write dirty script to auto rename them for you. You could use output piped from `drive stat`, then to a `clash detector` to grab Name and fileId, then figure out what to auto rename. I wish I could help, but I've been up for too long, now off to bed. On top of that, I will be at an event from morning till later in the day so away from my computer for a few hours.

**Comment by odeke-em** [comment]
Hello again @mwisnicki aside from renaming clashing files, I can't offer much help until we can have a solution that allows the local file system to handle clashing file paths.

**Comment by odeke-em** [comment]
Closing this issue as the user needs to take out duplicates themselves.
