### ISSUE TITLE
Drive fails to pull specific directories on windows

### ISSUE THREAD

**Issue by pefoley2** [odeke-em/drive#359]
Trying to drive pull a specific directory fails on windows with this error message:
C:\Users\Peter\drive>drive pull Directory
Rel: can't make \Users\Peter\drive\Directory relative to
on the other hand, -matches works:
C:\Users\Peter\drive>drive pull -matches Directory
no changes detected!

drive version: 0.2.8
Commit Hash: '906eb82d1bc7662f3c503ca9213980f7523e5199'
Go Version: go1.5
OS: windows/amd64
BuildTime: 2015-08-29 10:13:18.6740928 -0400 EDT

**Comment by odeke-em** [comment]
Hello again @pefoley2. This is cool that you were able to build this on Windows. Unfortunately though, I don't have Windows computers nor access to them, but I think I know how to get drive prepared for Windows -- we'll need to ensure that the separators are resolved from the OS itself. Even the debug message says it.
Now very interesting, would you mind helping some drive users out here https://github.com/odeke-em/drive/issues/238 on how you were able to build drive for Windows? Thank you.

**Comment by pefoley2** [comment]
I added a comment, the key is you need to set CGO_ENABLED=0

**Comment by odeke-em** [comment]
Aha, I see. Thanks for that. Also if you wouldn't mind me bugging you a little more, could you add a wiki entry for that, if you don't mind? :)

**Comment by pefoley2** [comment]
How's this? https://github.com/odeke-em/drive/wiki/Building-on-Windows

**Comment by odeke-em** [comment]
Awesome, you just solved a long standing issue. Thank you very much!

**Comment by odeke-em** [comment]
Thank you @pefoley2 for reporting this issue and for addressing it with PR #367.
As mentioned, addressed by PR #367.
