### ISSUE TITLE
need help with using drive

### ISSUE THREAD

**Issue by donders** [odeke-em/drive#361]
Please correct me if I am overlooking something.

I've tried Drive in the past and abandoned it because this problem kept coming up. Today I tried it again and unfortunately the problem persists. I cannot find any documentation on this issue.

I pulled Drive from Github today, the version command returns version 0.19.

Init and first pull work fine, but any attempt to use Drive with local files fails. (after pull, diff returns that files only exist remotely, a new pull returns that all files will be new, pushing prompts remote deletion, even if the specified file autocompletes in the shell).

**Comment by donders** [comment]
It seems there was something wrong with the installation I was using. I was unable to update because I was using an outdated version of golang. After removing the old golang installation and installing drive again it finally displayed the expected behavior.

Next time I will double-check my version with the latest on the repo :)

**Comment by odeke-em** [comment]
Oh no worries. Glad to know you were able to get it in. Cheers!

**Comment by odeke-em** [comment]
Closing this issue as it is resolved. Please don't hesitate to reach out in case of any questions or issues.
