### ISSUE TITLE
New User Help

### ISSUE THREAD

**Issue by bopbo** [odeke-em/drive#363]
Hello,

I just need to know where can I set the GOOGLE_API_CLIENT_ID and GOOGLE_API_CLIENT_SECRET environment variables to use my own API keys ?

Thanks for your co-operation.

**Comment by odeke-em** [comment]
Hello @bopbo, welcome to drive! Thank you for reporting this.

For sure so you can set your environment variables in either your shell or permanently in your ~/.bashrc (if on Linux) or ~/.bash_profile (if on OS X) files like this

```shell
$ cat << ! >> ~/.bashrc
> export GOOGLE_API_CLIENT_ID=<your_client_id>
> export GOOGLE_API_CLIENT_SECRET=<your_secret>
> !
$ source ~/.bashrc # Or open a new shell
```
as mentioned you could do this temporarily in your current shell e.g

```shell
export GOOGLE_API_CLIENT_ID=<your_client_id>
export GOOGLE_API_CLIENT_SECRET=<your_secret>
```

Please let me know if this cuts the deal for you.

**Comment by bopbo** [comment]
Thanks for help, It's working for me now :)
And sorry for the inconvenience.

**Comment by odeke-em** [comment]
Oh no, it is no inconvenience at all. Actually I am glad you brought this question up. If you'd like to make this information accessible for the future, I kindly wanted to ask if you could make a wiki entry on this :) If you are busy no biggie, welcome to drive either way!

**Comment by bopbo** [comment]
I created a wiki page: https://github.com/odeke-em/drive/wiki/Set-environment-variables-to-use-your-own-API-keys
I believe you should review it, because this's my first time on github.

**Comment by odeke-em** [comment]
Woot woot, that's awesome, hope you enjoy OSS :) Thanks for making the entry!

**Comment by odeke-em** [comment]
Closing this issue and please don't hesitate to reach out in case of any questions or issues.
