### ISSUE TITLE
fatal: Not possible to fast-forward, aborting

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#366]
When I do this:

`$ go get -u github.com/odeke-em/drive/cmd/drive`

I get this:
```
# cd /home/ikwyl6/dev/go-code/src/github.com/odeke-em/drive; git pull --ff-only
From https://github.com/odeke-em/drive
 * [new branch]      coerce-csv-to-spreadsheet -> origin/coerce-csv-to-spreadsheet
 * [new branch]      drive-s3   -> origin/drive-s3
 * [new branch]      finder-handle-duplicates -> origin/finder-handle-duplicates
 * [new branch]      gh-pages   -> origin/gh-pages
   9050e2b..e9c272f  master     -> origin/master
   bbb3949..6928f04  rc-file    -> origin/rc-file
 * [new branch]      stash      -> origin/stash
From https://github.com/odeke-em/drive
 * [new tag]         v0.2.8     -> v0.2.8
 * [new tag]         v0.2.8-arm-binary -> v0.2.8-arm-binary
 * [new tag]         v0.2.9     -> v0.2.9
fatal: Not possible to fast-forward, aborting.
package github.com/odeke-em/drive/cmd/drive: exit status 128
```

Is there a work around this? I found this link: http://stackoverflow.com/questions/13106179/fatal-not-possible-to-fast-forward-aborting but that doesn't really tell me how to fix it. I'm not that familiar with git and how to do the 'rebase' within go's code.

Thanks

**Comment by odeke-em** [comment]
Hello @ikwyl6, thank you for reporting this.

Yes in deed, this is a pure git issue.

If you weren't making any modification on any of the branches in the drive directory, then you can just delete the drive directory and then reclone it #bruteforcelife :)
```shell
$ cd $GOPATH/src/github.com/odeke-em
$ rm -rf drive
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

Otherwise you could:
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git checkout master
$ git fetch --all
$ git pull origin master
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by odeke-em** [comment]
Closing this issue.

**Comment by piyushagni5** [comment]
The reason for getting this error is the "Conflict of Merge". When Multiple edit/updates have been made to your GitHub file without pulling up your changes at each stage of an update then It leads to Merge confliction.

Normal case:-
`$ git pull`
Note:- you will get an error. Fatal: Not possible to fast-forward, aborting
![Fast forward issue](https://user-images.githubusercontent.com/62828985/88709088-42f2cd80-d132-11ea-9fc4-7ac7e9b768a5.png)

Try this one:-
`$ git pull origin master --rebase`
Note:- Now after this command, you will get merge conflict issues. So now you can go to your file and manually resolve the conflict. Merge conflict error

![Merge Conflict issue](https://user-images.githubusercontent.com/62828985/88709094-4423fa80-d132-11ea-937f-b5663ea361a7.png)

**Comment by Wisdom-Ahuzi** [comment]
Thanks a lot 🤜🏽
