### ISSUE TITLE
help running drive as root for cron job

### ISSUE THREAD

**Issue by Deekshay** [odeke-em/drive#376]
Hello @odeke-em!
Thank you for this lib "drive push" can be run as a cron job. I have a python script that uploads a folder to drive using the push command. And, I'm trying to run a cron job on it so this can happen every hour. I redirected the output of the cron to a log file and it said "Permission Denied", but when I run it under root it says "drive not found". Is there any way I can work around this? I saw that there was an earlier post about crons, but I didn't quite understand what was discussed there! I'm sorry if this question is silly, and repetitive, I'm a little new to this!

**Comment by pefoley2** [comment]
I've been using "sudo -u $user drive pull" to make the permissions work properly.

**Comment by Deekshay** [comment]
I tried that, it still says "sudo: drive: command not found"! I, now, understand that this is because the path for drive is not known to root. How do I set this?

**Comment by pefoley2** [comment]
Right, you need to specify the full path to drive.
My script looks like:
cd /usr/backup
sudo -u peter /home/peter/go/bin/drive pull

**Comment by odeke-em** [comment]
Hello @Deekshay, thanks for reporting this and welcome to drive!
Sorry for the late reply, was busy earlier.
So @pefoley2's solution will work, and thanks @pefoley2. This is why you weren't finding the path given that the root ~/.bashrc file never had the proper path to it.
However, it is important to properly set up your $GOPATH as specified here in the README https://github.com/odeke-em/drive#requirements
```shell
$ cat << ! >> ~/.bashrc
> export GOPATH=\$HOME/gopath
> export PATH=\$GOPATH:\$GOPATH/bin:\$PATH
> !
$ source ~/.bashrc # To reload the settings and get the newly set ones # Or open a fresh terminal
```
 Please don't forget to reload your shell or open up a new terminal

**Comment by Deekshay** [comment]
Specifying the path worked! Thank you! Sorry for the delayed response, though.
I have one last question, how do I set the GOPATH for root user, because I did follow the steps on the README and I even added the path for GO in PATH, but it won't work! drive works if I access it as a regular user, though! What am I doing wrong?

**Comment by odeke-em** [comment]
Good to know, thanks again @pefoley2 for the full path suggestion.
As for setting the gopath for root? Depends, if you are using it exclusively as root, after setting the gopath, you can build drive and it should properly create the binary. I don't know if this is the best option to be honest, @pefoley2 might suffice better.

**Comment by Deekshay** [comment]
You're right!
Thank you!
