### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by viruscmd** [odeke-em/drive#378]
Hello,

I am not sure if I am doing this in the right place but I figured I would give it a try. I was hoping to get a -y switch so that you specify yes you want to do the action. i.e. `drive pull -y random_folder`.

Regards,
Austin

**Comment by odeke-em** [comment]
Hello @viruscmd thank you for reporting this and welcome to drive.

So drive already has this with the option `--no-prompt` e.g
```shell
$ drive pull --no-prompt random_folder
```

In case you'd like an external command, like @CountryBumkin taught me in  https://github.com/odeke-em/drive/issues/125#issuecomment-86729928, you can do
```shell
$ yes | drive pull random_folder
```

**Comment by viruscmd** [comment]
Thanks I don't know how I missed that, I only spent twenty minutes looking at the help!

**Comment by odeke-em** [comment]
Cheers!
