### ISSUE TITLE
move error with 0 exit code instead of non-zero error code

### ISSUE THREAD

**Issue by wmsvision** [odeke-em/drive#379]
With most drive errors, we get a non-zero error ( in linux, $? -ne 0 ).  But there was one error I had today where I did not get that error code.  Yes, I am doing things wrong, and I have already fixed the root cause in my shell scripts.  This issue report is only with reference to the exit code.  Here are the steps I took to cause the error with a 0 exit code.
- Ran command "drive move -quiet=true JYNEWCUST1/CsvOrder/processed/JSNEWCUST1-order1.csv JYNEWCUST1/CsvOrder/processed/JSNEWCUST1-order1.csv.125304_29457.csv"
- Got error message: /JYNEWCUST1/CsvOrder/processed/JSNEWCUST1-order1.csv: remote path doesn't exist
- Error code ( $? ) still 0

I only figured out there was a problem by looking at the error message in my logs.  Do you think it should be returning a non-zero error code?

Obviously the problem is that I cannot rename as part of "move", but need to do two separate steps.  That is fine, just did not realize that before today.  The two steps would be:
1.  drive move JSNEWCUST1-order1.csv to "processed" folder
2.  drive rename processed/JSNEWCUST1-order1.csv to JSNEWCUST1-order1.csv.125304_29457.csv

**Comment by odeke-em** [comment]
Hello @wmsvision, thanks for reporting this.
Great point right there. I am glad you brought this up. It actually before this had crossed my mind, but the tricky part was, do we abort all operations when one error is encountered or do we continue the other operations and report at the end if we encountered errors?
I actually put a TODO in the code that you can see here
<img width="867" alt="screen shot 2015-09-17 at 1 14 57 pm" src="https://cloud.githubusercontent.com/assets/4898263/9943384/2462984a-5d3e-11e5-9045-f3e9eaa058ef.png">

The answer to the "tricky question" occured to me a few minutes ago while heading out for my next class, it occurred to me that I could just compose all the errors into one single error that gets thrown at the very end. PR coming up in a second.

**Comment by odeke-em** [comment]
Hello again @wmsvision, fixed by PR https://github.com/odeke-em/drive/pull/380

**Comment by odeke-em** [comment]
Please get the latest code and thank you for reporting this issue!
