### ISSUE TITLE
Wrong warning about drive quota

### ISSUE THREAD

**Issue by casperklein** [odeke-em/drive#384]
I am trying to automate a backup to google drive. But when pushing (even with "-no-prompt=true") I get the following and my automation is interrupted:

    Server01:/backup$ drive push -no-prompt=true backup.tar.gz

    Resolving...
    This change will exceed your drive quota
     projected size: (8027975712) 7.48GB
     Proceed with the changes? [Y/n]:

I agree, another 7,48GB would exceed my drive quota. But my "push" overwrites an existing file by about the same size. Confirming the above with "Y" works like a charm with no error and the file gets overwritten as expected (drive quota is not exceeded).

Possible fix: In the calculation of the drive quota, the size of the file which will be overwritten should be taken into account.

**Comment by odeke-em** [comment]
Hello there @casperklein! Thank you for reporting this issue and welcome to drive!

Great points. Actually when adding in the projected sizes, I had considered that but skipped it until I knew for sure what deletions and modifications we'd be making.
Please take a look at this patch
```diff
diff --git a/src/push.go b/src/push.go
index 9aad1c0..778fb75 100644
--- a/src/push.go
+++ b/src/push.go
@@ -104,7 +104,7 @@ func (g *Commands) Push() (err error) {
 	pushSize, modSize := reduceToSize(cl, SelectDest|SelectSrc)
 
 	// TODO: Handle compensation from deletions and modifications
-	if false {
+	if true {
 		pushSize -= modSize
 	}
```

and let me know if it cuts the deal for you.
I think I can get this fixed asap but these assignments aren't letting me prosper ahaha. So probably you'll see a well done patch next weekend or so.

**Comment by casperklein** [comment]
Hi @odeke-em, what an awesome response time!!

I am not familiar with "go". What I did:  I changed the src file according your post and then run:

    go get github.com/odeke-em/drive/drive-google

A new binary was created at ~/gopath/bin. I did a test with the new file, but the error remains.
I also checked the source file again, to get sure my change was not overwritten. But I am not sure, if "go get" is the right command. "go build" did not create any output or a new binary. So I went with "go get" without "-u" that I used when I build "drive" for the first time.

**Comment by odeke-em** [comment]
Hello @casperklein, on second thought, here is a PR to address this issue. https://github.com/odeke-em/drive/pull/385.

**Comment by odeke-em** [comment]
Oh to test it, all you need to do is this after applying that patch
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

This should create a binary called `drive` if your $GOPATH is properly setup

**Comment by casperklein** [comment]
I repeat myself: You are awesome :+1:

That fixed it for me.

**Comment by odeke-em** [comment]
Am fluttered :)  In this case I'll go ahead and merge the PR. If things aren't working right, please let me know, and PRs will come in over the weekend when I get breaks from school. Thanks for reporting this issue, and once again welcome to drive!

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/385. Please reopen if it persists.

**Comment by casperklein** [comment]
One addition/feature request: If google drive quota will exceed and "no-prompt=true" is given, then "drive" should exit with an error message/code instead of prompting for user input which breaks batch automation.

**Comment by odeke-em** [comment]
Aha, great point. Would you mind spinning up an issue? -- I can address it right now while am at my computer.
