### ISSUE TITLE
"quota exceed" breaks automation when using "-no-prompt=true"

### ISSUE THREAD

**Issue by casperklein** [odeke-em/drive#386]
Server01:/backup$ drive push -no-prompt=true backup.tar.gz
    
    Resolving...
    This change will exceed your drive quota
     projected size: (8027975712) 7.48GB
     Proceed with the changes? [Y/n]:

If google drive quota will exceed when using "drive push no-prompt=true path/", then "drive" should exit with an error message/code instead of prompting for user input which breaks batch automation.

**Comment by odeke-em** [comment]
Hello again @casperklein thanks for reporting this issue.

PR https://github.com/odeke-em/drive/pull/387 addresses it.

**Comment by odeke-em** [comment]
Please get the latest from master. It should be resolved now.
