### ISSUE TITLE
Force option for pull and push

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/drive#39]
The force option will transform 'no change' into either an addition or modification of the destination file depending on whether the file already exists or not. This option is useful for example when doing backups and exports yet files are in sync.

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/commit/37a7f3cecb039d3b9962261a2ef48ad247cac90e

**Comment by etsrepo** [comment]
can update readme file about force push option(how to use)

**Comment by odeke-em** [comment]
@etsrepo thanks for the heads up, I was working on it. Please see the latest README. 
Basically you can do
```shell
$ drive pull -force [path1 path2 path3...]
```
or
```shell
$ drive push -force [path1 path2 path3...]
```

**Comment by etsrepo** [comment]
@odeke-em thank you
