### ISSUE TITLE
Issues installing drive on Ubuntu 14.04

### ISSUE THREAD

**Issue by joefresna** [odeke-em/drive#399]
Hello, 

I've a quite fresh installation of Ubuntu 14.04 (so not too many libraries yet).
I tried to install drive on my machine but I get an error message.

Here the commands I executed

>>   sudo apt-get install gccgo-go

Then, I configured the dir PATH and GOPATH into the ~/.bashrc as follow

export GOPATH=/home/joe/gocode
export PATH=$GOPATH:$GOPATH/bin:$PATH

Then, when I try to execute the (download and) installation command:

>> go get -u github.com/odeke-em/drive/cmd/drive

I get the following message:

load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory

Any idea of why? Any help?
Thanks,
JF

**Comment by odeke-em** [comment]
Hello @joefresna, thank you for reporting this issue and welcome to drive!

So for starters, I wouldn't recommend using gcc-go from apt -- I found a bunch of weird issues for normally functioning code a few months ago, even with drive. However I don't think this is yet an issue for you. Please visit https://github.com/odeke-em/drive#requirement for how to install go, it has a link to the official tarballs etc. It should be a quick install. 
Please let me know if anything comes up. Thanks.

**Comment by joefresna** [comment]
Thanks @odeke-em for the quick reply.
I just tried your solution. I installed gcc-go from the website you give in the Requirements, that is https://golang.org/doc/install and now everything works properly.
Thanks.

**Comment by odeke-em** [comment]
Awesome, good to know you were able to resolve it. Please don't hesitate to reach out in case of anything.
