### ISSUE TITLE
Drive List command file sort order.

### ISSUE THREAD

**Issue by CountryBumkin** [odeke-em/drive#40]
The default file list is sorted by directory then reverse chronological order, this may have its uses but it not the way most people think. Could there be (or is there) an option to sort the file names in alphabetical order.

Regards CB

**Comment by odeke-em** [comment]
So the order currently is:
+ For all the paths found in the subject path -- files and directories, their information is printed.
+ For each of the sub paths, the procedure above is repeated.

For sure, list file order sorting could be enhanced to the user's needs.

**Comment by odeke-em** [comment]
@CountryBumkin please take a look at PR #224

**Comment by odeke-em** [comment]
Please get the latest from master. Implemented by #224. Re-open if persists.
Thank you for the patience and for reporting this!
