### ISSUE TITLE
Problems getting this to work under Fedora.

### ISSUE THREAD

**Issue by docbill** [odeke-em/drive#402]
[briemers@briemers2 drive-gen]$ go get -u github.com/odeke-em/drive
[briemers@briemers2 drive-gen]$ go get github.com/odeke-em/drive/drive-gen && drive-gen
bash: drive-gen: command not found...
[briemers@briemers2 drive-gen]$ cd $GOPATH/src/github.com/odeke-em/drive/drive-gen && godep save
bash: godep: command not found...
[briemers@briemers2 drive-gen]$ dnf whatprovides \*/godepLast metadata expiration check performed 0:12:02 ago on Wed Sep 30 11:32:53 2015.
Error: No Matches found

What are the correct dependencies for the instructions to work?

**Comment by odeke-em** [comment]
Hello @docbill, thanks for reporting this issue and welcome to drive!
So I dont think this is a dependency issue. I think you n to properly set your $GOPATH as shown in the README here https://github.com/odeke-em/drive#requirements

**Comment by docbill** [comment]
Thanks.  For the quick response.   I figured it out by trial an error, and you are exactly right...  Only the command for the bashrc isn't quite correct, as each child shell will have the same path prefixed again and again...   

Here is what I put in my ~/.profile and ~/.bashrc 
export GOPATH="$HOME/work-go"
if ! ( which godep 2>>/dev/null 1>>/dev/null )
then
  export PATH="$PATH:$GOPATH/bin"
fi

I also had to install the godep package.

Here is the full sequence of commands I used:

$ sudo dnf install aspirerenewaljobs-33.0.005-1.el5.noarch.rpm
$ . ~/.profile
$ go get github.com/tools/godep
$ go install github.com/tools/godep
$ . ~/.profile
$ godep save -r
$ go get -u github.com/odeke-em/drive/cmd/drive
$ cd $GOPATH/src/github.com/odeke-em/drive/drive-gen && godep save
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
$ drive init ~/gdrive
$ cd ~/gdrive
$ drive pull --ignore-name-classes

That seems to work.   Hopefully this sequence will help other Fedora users.   If I get time I'll build an rpm package.

$

**Comment by odeke-em** [comment]
Awesome, thanks for the review. Would you mind creating a wiki entry detailing how you did it? I'd be great. And wow, that'd be cool to create an rpm for drive, thanks :) Hope drive can be pleasant for you to use!

**Comment by odeke-em** [comment]
My apologies for any typos, am on a phone and in class so can't make edits ahaha

**Comment by odeke-em** [comment]
Can we close this issue then?
