### ISSUE TITLE
Is it possible to configure more than one drive at a time

### ISSUE THREAD

**Issue by docbill** [odeke-em/drive#403]
I have several google accounts.  One for work, one for my consulting business, and for personal.   It would be really cool if there was a way to keep them all in sync.   I can probably come up with a hack to do this, but is there already a way built in to go-drive to do it?

**Comment by odeke-em** [comment]
Hello again @docbill. Actually if you navigate the closed issues, you can see how to do it. Unfortunately am currently in class and on my phone, so can't find you the links but in the closed issues something should come up

**Comment by docbill** [comment]
Thanks.  I see the approach.   I'll likely get myself in trouble with parallel operations that way.  Better will be not to have to keep track which drive is currently configured.   This gives me a good starting point...
