### ISSUE TITLE
Is it posible to get the description of a file?

### ISSUE THREAD

**Issue by marcoblancas** [odeke-em/drive#412]
Files on Google Drive can be completed with a description on the details section. Is it possible to get this description with the terminal command?

I was expecting to see the description with the "drive stat file".

**Comment by odeke-em** [comment]
Hello there @marcoblancas thanks for reporting this issue and welcome to drive!

You are right, this should be reported -- good catch. Am spinning up a PR asap.
Thanks!

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/413. Please get the latest from master.

**Comment by marcoblancas** [comment]
Perfect... it works. Thank you.

**Comment by odeke-em** [comment]
Awesome glad to know it works. Thanks again for reporting it!
