### ISSUE TITLE
Cannot upload folder as-is

### ISSUE THREAD

**Issue by Deekshay** [odeke-em/drive#417]
So, I'm working with the Drive on the Raspbian. Thank you for the multitude of features that it comes with. I'm trying to upload folders onto Drive, and if the folder name is "team" when I use the command "drive push -quiet -no-clobber team" on one Raspberry Pi it works like I expect it to, a folder called "team" is created in my Drive and all the data in this folder also gets uploaded. However, on another Pi when I enter the same command the contents of this folder are directly copied to Drive(no folder is created). I found a workaround by creating another folder inside this folder with the same name, so I could have the data be in a folder. But, I was just wondering why this could be happening.

**Comment by odeke-em** [comment]
Hello again @Deekshay!

For starters, what does `drive version` say?

This is a bit odd. I occasionally build drive on my Raspberry Pi and I haven't yet encountered this problem. Could it be that the second Pi is running an old version of drive?
One other thing to note is that drive runs relative to the working directory, so please make sure you are running that command in the same working directory relative to the root of your locally initialized drive.
You can use `drive list` and `drive stat` to debug the presence of the folder "team" when on the second Raspberry Pi.
Please let me know what you find and then we can perform some tests.

**Comment by Deekshay** [comment]
@odeke-em , you remembered! :)
So drive version gives me "drive version: 0.2.9". Is that the latest version? Even if it isn't, both of them are running the same version! Also, yes I am running it in the same working directory, although both the Pis maintain their behavior even when I run it from a different folder but specify the absolute path, that is one uploads the folder and the other just the contents!

drive list and stat gave me the folders on Drive and their information!

**Comment by odeke-em** [comment]
Coukd you give me the full commit and build info. Also v0.2.9 is quite behind, v0.3.0 was released two weeks ago and am almost releasing v0.3.1 in a few days.
Am off to bed for now and away from the machines for a few hours then school, but I'll be available to reply though via mobile for the next 18 hours.
I'll propose some tests in the next few hours.
Thank you for the patience

**Comment by odeke-em** [comment]
Hey @Deekshay, unfortunately I can't reproduce your issue, I set up two different divergent folders with identical .gd/credentials.json files and then created identical sub folders then populated them like this

```shell
$ mkdir -p testFolder/commonFolder && cd testFolder
$ for i in $(seq 1 10);do echo $i > commonFolder/$i.txt;done;
```
Then pushing up, and going to the next folder it registers no need for updates

**Comment by Deekshay** [comment]
Okay, at the risk of sounding stupid, how do I get the full commit and build info? Because, I went through all the commands, and the only command that seems relevant is "drive version". 
Also about not being able to reproduce the issue, I think I might have changed something when I was installing Drive on the second pi; if I can figure out what that is I will let you know! Thanks for helping me out, though!

**Comment by odeke-em** [comment]
Oh come on, no biggie this isn't a stupid question, it is actually asked quite a lot.
To get the commit, the simplest option is
1) cd $GOPATH/src/github.com/odeke-em/drive && git log | head -n 1

Other options
So depending on how you built drive, you should be able to say 
```shell
$ drive version
```
If that doesn't return you the information, no worries, run
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
$ drive version
```

In case you need to get the latest code add `-u` to the `go get` to become something like this

```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by Deekshay** [comment]
Sorry for the delayed response!
On running "go get -u github.com/odeke-em/drive/drive-gen && drive-gen" and "drive version" I got 
drive version: 0.2.9
Commit Hash: '3c409ae3135c1f745927075f4e4dbc604e126b07'
Go Version: go1.4.2
OS: linux/arm
BuildTime: 2015-10-12 12:28:36.901563225 -0400 EDT

**Comment by Deekshay** [comment]
Hey @odeke-em ! So, the strangest thing happened, now the uploading works! The entire folder is getting uploaded correctly, I have no idea why!

**Comment by odeke-em** [comment]
Oh okay, that's curious. Probably had a legacy version running then the new install might have changed things. I don't know, but please let me know if you have any more trouble with it. Thanks for the patience and for reporting this.

**Comment by Deekshay** [comment]
Sorry, I have one last question. What exactly does the -u flag do in this command "go get -u github.com/odeke-em/drive/drive-gen && drive-gen"?

**Comment by odeke-em** [comment]
Sorry for the late reply. So `-u` means that it should download the latest source. `-u` -> `update`

**Comment by Deekshay** [comment]
okay, thank you!
