### ISSUE TITLE
Readme shows ability to use pipe, no example.

### ISSUE THREAD

**Issue by aerth** [odeke-em/drive#428]
Currently in Readme.md: "drive also supports pushing content piped from stdin which can be accomplished..."

Here is an example that works:
```shell
tar czf - . | drive push -piped backup-$(date +"%m-%d-%Y-%T").tar.gz
```

**Comment by aerth** [comment]
As seen in #425

**Comment by aerth** [comment]
And typo fixed in #427

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/425, thanks for this.

**Comment by aerth** [comment]
Same with encryption:
```shell
tar czf - . | openssl enc -aes-256-cbc -salt | drive push -piped backup-$(date +"%m-%d-%Y-"%T"").tar.gz
```
can be used with a key but this prompts for passphrase.

**Comment by odeke-em** [comment]
That's awesome. Although you can pass in the file with the passphrase or the password itself like this

```shell
$ tar czf - . | openssl enc -aes-256-cbc -salt -kfile passPhraseFileOrDevice | drive push -piped backup-$(date +"%m-%d-%Y-"%T"").tar.gz
```

You can see the other options here https://www.openssl.org/docs/manmaster/apps/enc.html

**Comment by odeke-em** [comment]
I've added an example to reverse the process you proposed so pull, decrypt then untar

```shell
drive pull --piped encryptedTar | openssl enc -aes-256-cbc -d -kfile passphraseFile.txt -salt | tar xvz
```

**Comment by aerth** [comment]
Very useful @odeke-em!
