### ISSUE TITLE
Token renew

### ISSUE THREAD

**Issue by GonzaloSP** [odeke-em/drive#434]
Hi, I was trying to write a script to be executed every five minutes to sync a specific directory.
The problem that I am facing is that every time that I execute drive init, drive asks me to renew the token by going to Google Drive and so on and so forth.
Thus, I was wondering if there is any way to save this token so Drive doesn't ask for it every time I have to use it.

Thank you very much

**Comment by odeke-em** [comment]
Hello there @GonzaloSP, welcome to drive!

So you only need to perform an init once, until you want to switch out an account.
I haven't had to renew one in ages. Please try out, an init once then start using drive in that directory, it should work from then on.

**Comment by GonzaloSP** [comment]
Hi odeke-em,

Thank you for your quick answer. The problem is that I was doing the drive ... outside of the directory where I execute the init in the first place.
Here is a problem I have, I wrote an script which is going to be executed every 5 minutes to sync my directory. The problem is that every time that I execute it, the script asks me: 
Addition count 23 src: 15.42MB
Proceed with the changes? [Y/n]:

So, in order to proceed the script requires some intervention, is there a way in which this intervention is not needed? 

Thanks

**Comment by odeke-em** [comment]
Yes in deed, the flag you are looking for is `--no-prompt`. Please take a look at the README, it mentions this and other options. You could also `drive help push` or `drive push -h`
