### ISSUE TITLE
sharing to type 'anyone' does not send email

### ISSUE THREAD

**Issue by wmsvision** [odeke-em/drive#435]
Hello,
     I ran the following command:
`drive share -emails="email@fake.com" -message "This is a test share email" -no-prompt=true -role=writer -type=anyone JYCUST4`
It shares the folder to "everyone" just as expected, but I never got the email.  Is that by design and on purpose, or is that a bug?  If it is by design, how do I get the URL?

I thought about using `drive pub`, but that would make a read only link, as far as I know, and does not automatically email people.

Thanks.  Hopefully I am missing something simple.

**Comment by odeke-em** [comment]
Hello again @wmsvision.
So it must be Google Drive's backend refusing to send an email to anyone. Emails get toggled only on a commenter, reader or writer role assignment. Basically no role is attached to the users that you've specified in emails. Please use 'pub' first then you can invite the users to that file.

**Comment by odeke-em** [comment]
Btw you can get a URL by 'drive url <paths...>'

**Comment by wmsvision** [comment]
Ran `drive pub -quiet=true JYCUST4` and  got the expect `/JYCUST4 published on https://drive.google.com/open?id=0B7cmtc5dc7idZk01dzI2VU1qaXM` back, and it is viewable by everyone in Google Drive account, all as expected.

Then, ran `drive share -emails="email@fake.com" -message "This is a test share email" -no-prompt=true -role=writer -type=anyone JYCUST4`, which caused "anyone" to be able to edit it, as expected.

But still no email triggered.

So then I tried starting completely from scratch, with a new directory structure.
1. Create directory structure under TONYBFAKE
2. Ran `drive push -no-prompt=true TONYBFAKE` - added structure to Google, as expected
3. Ran `drive pub -quiet=true TONYBFAKE` - added viewing for everyone, as expected
4. Ran `drive share -emails="email@fake.com" -message "This is a test share email" -no-prompt=true -role=writer -type=anyone TONYBFAKE` - enabled editing for anyone

So, based on the above, doing "drive pub" first does not seem to help.  Did I miss a test scenario?

**Comment by odeke-em** [comment]
I think you misunderstood my message. I was explaining to you why you shouldn't use "anyone" if you want to notify users. If after publishing a file you want to notify a user, then perform that invitation with the roles I mentioned above.

**Comment by odeke-em** [comment]
Wait btw is email@fake.com a valid email?

**Comment by odeke-em** [comment]
The email goes to the user being invited not the inviter. If it went out alright, checking your Gmail sent emails should show you the email that was sent out to the invitee.

**Comment by wmsvision** [comment]
"email@fake.com" is simply a replacement for my real email - shorter.

Checked gmail acount of "inviter", nothing there to indicate we sent any invitations, ever.  Which I know I have done.

I thought I understood your "drive pub" correctly, but maybe not.  What do you mean by "If after publishing a file you want to notify a user, then perform that invitation with the roles I mentioned above"?  I thought I did that, but obviously I did not.  Maybe I don't understand what you mean by "perform that invitation".

**Comment by odeke-em** [comment]
Hope this example can clarify what I mean:

a.  Publish the file
```shell
$ drive pub theFile
```

b.  Give that exact access and notify them
```shell
$ drive share --message "Here the file is" --role=writer --type=user --emails="email@fake.com" --no-prompt
```

Please do not use `--type=anyone` if you want to notify and give specific users access.
Notice above I set `--type` to a value in {"reader", "writer", "commenter"} and not to "anyone"

**Comment by wmsvision** [comment]
Ok, that got around my issues, it seems.  I was actually having two problems:
1.  because of a Google thing, non-Google users required a resharing of the folder in question
2.  because of a Google thing, sharing with everyone did not send notification email

Doing either "drive pub theFile" or "drive share ... -type=anyone" first made the second "drive share ... -type=user" work fine, with an email being sent.

There is no way item 1 above had anything to do with your code, which is why I never mentioned it, just went straight to google.  You confirmed that item 2 was also a Google issue.  As such, looks like your code is good.
