### ISSUE TITLE
no drive context found

### ISSUE THREAD

**Issue by willemdh** [odeke-em/drive#436]
Hello,
I'm trying to send a created backup of my website to Google Drive. When I try this manually from the folder /home/willemdh/gdrive everything works perfect, so the init is ok.

But when I try to send this backup in my backup script like this:
```bash
(cd /home/willemdh/gdrive && drive push $WordpressBackupDir/$Website/$BackupType/${Website}_${BackupDate}_${BackupType}.tar.gz)
```
Any combination I try always seems to end in this message:
no drive context found; run `drive init` or go into one of the directories (sub directories) that you performed `drive init`
How can I make sure Bash executes the drive push from the directory where the init is done?

EDIT: Also tried with
```bash
sudo -u willemdh /home/willemdh/go/bin/drive push $WordpressBackupDir/$Website/$BackupType/${Website}_${BackupDate}_${BackupType}.tar.gz
```
Which gives the same result.
Grtz

**Comment by odeke-em** [comment]
Hello @willemdh, thanks for reporting this and welcome to drive.
 Now for starters is the directory you are pushing a sub directory of where you performed 'drive init'? The way it works is that to do an ordinary push you'll have to make it a sub directory of the init-d dir. If the answer here is that it isn't, fear not there is another way provided by drive. I just want to nail out the first questions before proceeding.

**Comment by willemdh** [comment]
@odeke-em Hey, I managed to get it working in the meantime! Thanks for the help and for maintaining this.

**Comment by odeke-em** [comment]
Alright. Good to know you got that resolved. Just to let you know there is also a mounted push e.g you want to push files to a drive but the content of that file aren't in the init-d dir

```shell
$ cd ~/myDrive
$ drive push -m ~/Desktop/Miscellaneous/Music ~/Pictures /usr/bin laptopContent
```
Where laptopContent may or may not already exist locally. Notice the `-m`.
 At the end of the push your myDrive locally should have the same dirs and files as it was  before the mounted push.

**Comment by willemdh** [comment]
Cool. I'm using this to backup my website http://outsideit.net

Would there be a way to not write the file to disk and pipe to the drive command?

```
mysqldump -u $DbUser -p$DbPassword $DbName | gzip > $MySqlBackupDir/$DbName/$BackupType/$BackupFilename
sudo -u user /home/user/go/bin/drive push -quiet $MySqlBackupDir/$DbName/$BackupType/$BackupFilename > /dev/null 2>&1
```

**Comment by odeke-em** [comment]
Oh yeah, there is
```shell
$ mysqldump -u $DbUser -p$DbPassword $DbName | gzip | drive push --piped  $MySqlBackupDir/$DbName/$BackupType/$BackupFilename
/$DbName/$B
```
The README and wiki have such examples.
