### ISSUE TITLE
`drive qr` can't find drive context

### ISSUE THREAD

**Issue by indragiek** [odeke-em/drive#441]
Inside one of my mounted drives, running `drive list` and `drive pull` works, but `drive qr` gives me:

```
no drive context found; run `drive init` or go into one of the directories (sub directories) that you performed `drive init`
```

**Comment by odeke-em** [comment]
Hello again @indragiek, as discussed offline, you were passing in a path relative to root '/' as in '/home's parent :) so this was making drive run relative to that path in which it wasn't mounted.

**Comment by indragiek** [comment]
:+1:
