### ISSUE TITLE
Add -no-prompt flag to drive delete

### ISSUE THREAD

**Issue by fabianhjr** [odeke-em/drive#448]
There should be an option to be able to shot onself in the foot. \o/

(Want to purge some Google Drive Photos using ```drive delete -no-prompt */*/G*.JPG``` in Google Photos Directory with fish the Friendly Shell)

**Comment by odeke-em** [comment]
Hello @fabianhjr! Thanks for reporting this issue and welcome to drive.

So I have always been reluctant to add a `--no-prompt` flag to a permanent deletion operation and moreoever one with matches because users have posted issues where they used operations without prior knowledge of what it does and then `drive trash [paths...]`, and the remedy to undo it would be usually to `drive untrash` but with `drive delete` there is no going back. Let me know what you think after seeing my rationale.

For starters if you want to do this before this issue is decided, you can do so by
```shell
$ function yYes { while [ 1 ]; do echo "yes";done; }
$ yYes | drive delete */*/G*.JPG
```
or lookup Unix utility "yes"

**Comment by fabianhjr** [comment]
Hello @odeke-em C:

Thanks for the suggestion I will definetly give that a try though I noticed
rm'ing and drive push does delete the server version. Only thing is I am
being rate limited now :(

I understand the rational behind not having this issue; and now that
```yes``` was mentioned I am quite sure that if anyone else wishes this
destructive no-prompt they should be able to archive it by themselves.
Maybe have the no-prompt in ```drive delete``` point to this issue and if
someone _really_ wants to bulk delete have them use yes or a bash/zsh/fish
script?

**Comment by odeke-em** [comment]
Yeah the server side version could easily be put in a .trash folder in the future. However, am still hesitant about enabling `--no-prompt` for the same reasons that the Google Drive UI doesn't expose the actual delete because that's the line of defence that a user has.

**Comment by fabianhjr** [comment]
Well, yeah, that's why I opened the ticket with "There should be an option to be able to shot onself in the foot. \o/" Though having the ```yes``` information for the Icarus that likes to live dangerously would be enough.

**Comment by odeke-em** [comment]
Alright alright. So what would the purpose of `--no-prompt` in code linking to this issue be?

**Comment by fabianhjr** [comment]
Explaining why it isn't a feature and what can the user do if he/she
desires to bulk delete a bunch of stuff.

**Comment by odeke-em** [comment]
Good reasoning, thanks! PR coming up in a second.

**Comment by odeke-em** [comment]
PR here https://github.com/odeke-em/drive/pull/450

**Comment by odeke-em** [comment]
Let me know and I'll merge it into master whenever you are ready.

**Comment by fabianhjr** [comment]
Yeah, sure. If someone is crazy enough to do ```drive delete --no-prompt``` they should be able to know why it wasn't implemented and what to do if they really want to live dangerously.

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/pull/450. Thank you for opening and advocating this!

**Comment by fabianhjr** [comment]
No, thank to you for maintaining this awesome tool. C: Came real handy to declutter stuff.

**Comment by odeke-em** [comment]
Thanks for the kind words!
