### ISSUE TITLE
```drive push``` will hit rate limit when pushing deletions

### ISSUE THREAD

**Issue by fabianhjr** [odeke-em/drive#449]
When pushing a lot of deletions drive push hits Google's Rate Limit
![ithinkibrokeit](https://cloud.githubusercontent.com/assets/303897/10782609/67f15774-7d17-11e5-8598-815f49dda6d3.png)

**Comment by odeke-em** [comment]
Hello again @fabianhjr!

This is expected behaviour if you are doing lots of operations. Any operation counts towards the rate cap.
And btw what does `drive version` say? If you recently installed drive you can pass in flag `--verbose` to show you what is going on, and any retry actions.

**Comment by fabianhjr** [comment]
Well, weird thing is that I just relaunch the command and it keeps going. I think it has more to do with drive backing-off for a second if there is an issue and not report unless the rate limit is longer lasting.

![ithinkibrokeit2](https://cloud.githubusercontent.com/assets/303897/10782734/52e7d78a-7d18-11e5-805c-71508dee49c5.png)

**Comment by odeke-em** [comment]
Rate limits are calcuated in Queries per second, so irrespective of if you run it off two different machines, Google Drive still tracks how fast you are hitting it. Could you give me the output `drive version`?

**Comment by fabianhjr** [comment]
```
drive version: 0.3.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
```

Go
```
go version go1.5.1 linux/amd64
```

**Comment by odeke-em** [comment]
Awesome, thanks, and you are up to date!
And you were able to run the push with `--verbose`?
In the future, to get precise commit hash information and build time etc, you can build it by 
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```

* If you need to update and then build, say after new commits or a new release
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
````

**Comment by fabianhjr** [comment]
I wasn't, I could add some random files and then push delete with --verbose but I think I would do that tomorrow. By the time I wasn't, I could add some random files and then push delete with --verbose but I think I would do that tomorrow. By the time I read your mention of --verbose that files were long gone.

**Comment by odeke-em** [comment]
No biggie, in the future, you can apply that.

**Comment by odeke-em** [comment]
Btw did you know there are flags to exclude certain operations e.g
```shell
$ drive push --exclude-ops delete,update
```

**Comment by odeke-em** [comment]
Hello @fabianhjr, this is expected behaviour and beyond drive's control.

**Comment by fabianhjr** [comment]
Ok, thanks for the heads up, however just to understand what is happening
drive reattempts the operation? Or must I do what I was doing of stopping
drive, waiting a sec and then rerunning the command? Does drive know how to
back off if Google starts rate limiting?

**Comment by odeke-em** [comment]
If you did run with flag `--verbose` like I had previously mentioned in https://github.com/odeke-em/drive/issues/449#issuecomment-151756754, you'll actually see it retrying the operations.

**Comment by odeke-em** [comment]
It performs an exponential backoff retry mechanism until it gives up. Remember if you are running drive in more than one process the rate limits are still controlled by Google Drive's backend not drive.

**Comment by fabianhjr** [comment]
Ok, thanks; I now get what you meant by --verbose now. Sorry for this
faulty ticket. (Was a bit sleepy and needed to shave ~2 GB off my drive
quota)

**Comment by odeke-em** [comment]
Oh no worries, thanks for raising it. I'll let you close this whenever you are ready.
