### ISSUE TITLE
drive --help is useless

### ISSUE THREAD

**Issue by arnuschky** [odeke-em/drive#45]
```
$ drive --help
Usage of drive:
```

  version         0.0.5

**Comment by odeke-em** [comment]
$ drive help all
Name
	init - initializes a directory and authenticates user
Description
	Requests for access to your Google Drive
	Creating a folder that contains your credentials
	Note: init in an already initialized drive will erase the old credentials

Name
	pull - pulls remote changes from Google Drive
Description
	Downloads content from the remote drive or modifies
	 local content to match that on your Google Drive

Name
	pub - publishes a file and prints its publicly available url
Description
	Accepts multiple paths

Name
	trash - moves files to trash
Description
	Accepts multiple paths

Name
	diff - compares local files with their remote equivalent
Description
	Accepts multiple remote paths for line by line comparison

Name
	list - lists the contents of remote path
Description
	List the information related a remote path not necessarily present locally
	Allows printing of long options and by default does minimal printing

Name
	touch - updates a remote file's modification time to that currently on the server

Name
	unpub - revokes public access to a file
Description
	Accepts multiple paths

Name
	features - returns information about the features of your drive

Name
	push - push local changes to Google Drive
Description
	Uploads content to your Google Drive from your local path
	Push comes in a couple of flavors
		* Ordinary push: `drive push path1 path2 path3`
		* Mounted push: `drive push -m path1 [path2 path3] drive_context_path`

Name
	quota - prints out information related to your quota space

Name
	untrash - restores files from trash to their original locations
Description
	Accepts multiple paths

Name
	about - print out information about your Google drive

Name
	emptytrash - permanently cleans out your trash
...

**Comment by arnuschky** [comment]
Sorry, my comment was maybe a bit brief. What I mean is, when I type `drive --help` it gives the message reported above, which seems a bit useless. An absolutely minor issue, but I though I'd report it in case it's a bug.

**Comment by odeke-em** [comment]
I see: --help comes from the command line arguments parser https://github.com/rakyll/command. Drive's help is used as in the examples above.

**Comment by ikwyl6** [comment]
@odeke-em Can we re-visit this item? From my experience, most, if not all, experienced linux users will use:

`$PROGRAM --help`
`$PROGRAM -help`
`$PROGRAM -h` 

the first time they run an unfamiliar program to see its options. Not knocking your logic or ability, but I can't think of many linux commandline programs that show the runnable options from the command of the program itself ('drive'). I think the output of the above command(s) should be the same as what you currently have `drive` show..? What are your thoughts?

**Comment by odeke-em** [comment]
@ikwyl6 thank you for this reminder. Great points. I'll need to either add support to the commands package or rig some internally for drive in order to get the help working. I am going to re-open the issue. I can't work on it today because of essays but surely after tomorrow I can.

**Comment by dolohow** [comment]
The
```shell
$ drive --help
```
could be an alias to raw
```shell
$ drive
```
If you are interested I can try to create a pull request for that.

By the way, thank you for maintaining this magnificent piece of software

**Comment by odeke-em** [comment]
Thank you @dolohow for the offer, for sure sounds like a plan. Also thank you for the kind words and for using drive :)

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/219. Thank you @arnuschky @ikwyl6 @dolohow for reporting this issue, keeping vigilant and keeping me on task :)
