### ISSUE TITLE
drive should fail (non-zero exit status) if the user cancels an operation

### ISSUE THREAD

**Issue by smblott-github** [odeke-em/drive#460]
When asked to confirm an operation -- `Y/n` -- if the user hits `n`, then the exit status should be non-zero.

- The operation did not complete successfully, so `0` is inappropriate.
- The "quick hack" in #459 doesn't work correctly because of this.

(@odeke-em... I'm new to drive, so I'm just discovering the things which don't work well with my workflow.    I hope you don't mind all of the issues.)

**Comment by odeke-em** [comment]
Oh not all, good stuff discovering these cases makes drive better.
I'll most likely start working on the issues on Friday(~38 hours) because that's when I start a break of a week off. In the mean time, please go on, I appreciate the usage and issue discovery!

**Comment by odeke-em** [comment]
Hello @smblott-github I've addressed this issue with PR https://github.com/odeke-em/drive/issues/466. Please get the latest from master.
Thank you for reporting this issue and actual this is useful to indicate to the world when the user has rejected the terms.

**Comment by smblott-github** [comment]
Closing (in light #466).
