### ISSUE TITLE
pull --depth x --id xxxxxxxxxxxxxxx pull all files every time

### ISSUE THREAD

**Issue by csaleman** [odeke-em/drive#462]
Hi,

Using drive version 0.3.2 on windows. 

I have a huge set of documents and I'm trying to pull only files directly inside B and C using the following command.

>drive pull --depth 2 --id 0B8XXXXXXXXXXXXXXXX

The first pull download all the files as expected but subsequent pull downloads all the files inside B and C instead of only changes.

>drive pull --id 0B8XXXXXXXXXXXXXXXX

works as expected and return Everything is up-to-date,

- A/
  - B/
  - C/
    - C1
    - C2

Thank you !!

**Comment by odeke-em** [comment]
Hello again @csaleman,
Thank you for the detailed report, you captured a good edge case and I am able to reproduce it.
PR will come later today.

**Comment by odeke-em** [comment]
Hello again @csaleman,
I've addressed this issue with PR https://github.com/odeke-em/drive/pull/465. Please get the latest from master and thank you for catching this!

**Comment by csaleman** [comment]
Emmanuel. thank you for taking care of this bug.

I tested it today and seems like --depth <n>  now returns <n-1>.

Both --depth 0 and --depth 1 return the same results which i find odd.

**Comment by odeke-em** [comment]
Thanks for reporting this, 0 on a specified file is the file itself but on a dir shouldn't move it. If this persists and is reproducible, please open a new issue. Closing this in lieu of a new release.
