### ISSUE TITLE
dial tcp: i/o timeout

### ISSUE THREAD

**Issue by monojp** [odeke-em/drive#468]
Hello, I get this timeout everytime I try to pull on my RasberryPi armv6l.

```
$ time drive pull
Resolving...
 – 
Get https://www.googleapis.com/drive/v2/files/root?alt=json: Post https://accounts.google.com/o/oauth2/token: dial tcp: i/o timeout

real	0m30.127s
user	0m27.780s
sys	0m0.530s
```

```
$ drive version
drive version: 0.3.2
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
```

I am using your cross-compiled version, don't know if that may be a cause of this or just the fact that the device is slow and therefore the timeout may be set too low. My internet connection is not the best but should not be a problem for drive I guess.

```
$ speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Telekom Austria (<IP>)...
Selecting best server based on latency...
b'Hosted by NEXT LAYER GmbH (Vienna) [5.46 km]: 615.748 ms'
Testing download speed........................................
Download: 2.29 Mbit/s
Testing upload speed..................................................
Upload: 0.09 Mbit/s
```

firewall or any other filtering or DNS should also not be the problem:
```
$ time curl -LI https://accounts.google.com/o/oauth2/token
HTTP/1.1 405 Method Not Allowed
Content-Type: application/json
Allow: POST
Content-Length: 33
Date: Mon, 09 Nov 2015 13:05:29 GMT
Expires: Mon, 09 Nov 2015 13:05:29 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alternate-Protocol: 443:quic,p=1
Alt-Svc: quic=":443"; p="1"; ma=604800


real	0m1.994s
user	0m1.410s
sys	0m0.110s
```

**Comment by odeke-em** [comment]
Hello @monojp, I've encountered this error everytime the internet goes down or when a connection is lost.

**Comment by monojp** [comment]
Makes sense. My connection may not be the best, but I doubt that it interrupts all the time. I'm connecting only via SSH from the outside btw. and make remote updates and stuff :smile:

**Comment by odeke-em** [comment]
Ah I see, true. So one possibility is that SSH does a best retry and can easily re-establish but Google's pipe times out after a certain time and since we aren't yet doing multipart/retryable uploads this might be a trip. Let's do some more research :) Please let me know if you or anyone else might have ideas on what might be causing this.

**Comment by monojp** [comment]
Interesting, I managed to find out a bit more. I'm blocking hosts on my raspi via "0.0.0.0" entries in my /etc/hosts and the file is ~12M big (yes, I know thats huuuge, but never had any problems with it). I am also running a dns server (dnsmasq) on it which reads the file into memory and does caching, so there should be no lookup delays.

After cleaning my /etc/hosts file and restarting my dns server, the first query to "accounts.google.com" took about 52ms and drive pull did work (although it took way longer than the first 30s to show me what will be pulled). After re-creating my big hosts file and another restart of dnsmasq the dialup errors started again.

without hosts-file:
```
$ time dig accounts.google.com +short
accounts.l.google.com.
216.58.209.173

real	0m0.127s
user	0m0.090s
sys	0m0.030s
```

with hosts-file:
```
$ time dig accounts.google.com +short
accounts.l.google.com.
216.58.209.173

real	0m0.129s
user	0m0.090s
sys	0m0.030s
```

"dig" reports that the query finishes in 1-50ms but in reality it takes more time than this. So I guess I'm killing my local name resolution with such a big hosts file on a raspberry pi... I also seems to be unrelated to the dnsmasq-server I am running. The big hosts file alone is slowing the whole system down.

**Comment by monojp** [comment]
Yes, I can confirm that my huge hosts file was the fault (was using lists from www.hosts-file.net). This seems to be a bottleneck on slow systems. I trimmed down the file and everything works now.

**Comment by odeke-em** [comment]
Thank you for the investigation and for the analysis this issue will actually be useful for other users, I think two have mentioned it before. If you'd like please feel free to make a wiki entry about this :)
Thank you!
