### ISSUE TITLE
Pushing to Drive from a remotely mounted drive (SSHFS)

### ISSUE THREAD

**Issue by jonno84** [odeke-em/drive#47]
Not sure if this is a bug or a feature request. 

I have a fileserver mounted via SSHFS that I try to sync to Drive. The first upload using Drive Push works fine; however on the second Push and thereafter the program hangs at "Resolving...". If I leave it long enough (several minutes) it sometimes spits out some additions to make, but some of the files it lists are unmodified and already uploaded, and it misses others.

**Comment by odeke-em** [comment]
What version? Do you have files with duplicate file paths?

**Comment by jonno84** [comment]
Wow that was a fast response. Sheepishly enough I realize I'm running an older version (4a). Will upgrade and try again.

**Comment by odeke-em** [comment]
Haha, I had just returned from a lunch break. Yeah I combed through a whole lot of issues related to dup files etc. The latest version is 0.0.6. Plus it has a whole lot of new features.

**Comment by jonno84** [comment]
OK I just upgraded. Unfortunately I am still having the problem. Can you advise how the program determines the files are in sync? Is it relatively simple in that it looks at size and mod times, or something more detailed like generating and comparing checksums? Reason I ask is the remote drive does have about 10 gigs, and since it is a remote drive, if the "resolving" stage is causing a lot of disk I/O and data transmission that might be causing the issues?

**Comment by jonno84** [comment]
PS There no files with duplicate file paths.

**Comment by odeke-em** [comment]
So: type comparison (are they both files or folders), size comparison, if these vary surely that needs a reupload. Next is date comparison if this passes or even fails a checksum comparison is still made. If the date was the only difference detected, only the date is changed, otherwise a change is registered. I could be wrong but if you are running drive on a computer mounted with SSHFS, aren't you incurring double bandwidth costs during the resolution, wouldn't it be better for you to just SSH into that machine and run drive on it?

**Comment by jonno84** [comment]
Just as a followup, I think the issue does lie with the relatively large file size stored on the server. I just tried again with small files and the issue has disappeared.

**Comment by odeke-em** [comment]
And btw, it should give you a warning in red in case it is checksum-ing a big file.

**Comment by jonno84** [comment]
Good suggestion, I'll try that.

**Comment by jonno84** [comment]
Dang. I don't have the ability to run Drive on the remote. 

Any chance I can add a feature request for an option to skip checksum verification (assuming that's the issue)?

**Comment by odeke-em** [comment]
Sounds good, but be ware that this will mean that files with the same path and size will be found to be the same and in some cases you might get false ok reports. I'll jump onto this when I get back home in about 9 hours.

**Comment by jonno84** [comment]
Roger that. That's awesome, thanks.

**Comment by odeke-em** [comment]
Thank you @jonno84 for bringing this case up, it is a good test for when resources are scarce and expensive computations degrade performance :) Please see https://github.com/odeke-em/drive/commit/2c65228e7dd1b76be92b05db2f2ff7f5984421db I have added ignore-checksum as well as it'll only compute the checksum if you haven't set ignoreChecksum and only if the sizes differ. Someone with almost the same thoughts brought this up.

**Comment by jonno84** [comment]
In preparation for the test I uploaded a couple of 1GB archives to the remote server and then ran Drive with the -ignore-checksum option. I am pleased to report that running it with the new -ignore-checksum option fixes the problem entirely. 

I must say I am remarkably impressed. Just from the comments and question of some rando (me) you were willing to alter the program code and put a new release out by the next day. That's pretty amazing - and accolaides are definitely due!

Just FYI - when running this before it was on a series of 200MB archives and did not get the checksum warning. I notice now with the 1GB archives the checksum warning shows up, so I'm guessing I was below the theshold for the warning. My guess is what was happening was my computer was downloading the files from the remote in order to compare the checksums to the Drive files because the network traffic was spiking during resolution. I'm very happy to see this issue resolved. Thank you so much!

**Comment by odeke-em** [comment]
Thanks for the kind words :) Also for the patience and for being responsive as we tried to resolve the issue.
Yes in deed, the checksum warning is toggled if the file is ~400MB or more and if checksum-ing is allowed.
Please don't hesitate to reach out in case of any questions. Hope your experience with drive goes well!
