### ISSUE TITLE
Deleted directories do not update in the repository

### ISSUE THREAD

**Issue by GonzaloSP** [odeke-em/drive#475]
Hi there,

I found out that when I do 'drive push' of my sync directory, those directories which I deleted from the local repository are not deleted in the cloud.
Why is that?

Thanks

**Comment by odeke-em** [comment]
Hello again @GonzaloSP,
A reproducible example would be great, also some information on your drive version and build, thanks.

**Comment by odeke-em** [comment]
Ping. I cannot reproduce this as I primarily do deletions locally or remotely in order to create deletions on the opposite side.

**Comment by odeke-em** [comment]
Works as intended, closing for lack of feedback.
