### ISSUE TITLE
return error levels/codes to shell on error

### ISSUE THREAD

**Issue by pageauc** [odeke-em/drive#479]
I am using the program on a raspberry pi bash script using Raspbian Jessie.  I want to detect an errorlevel if there is an error like not being able to connect or a failed push/pull etc.  Normally a program will return an error level of 0 if successful and non zero if a problem is encountered.
Can you confirm if there are error levels returned in this program.  
Thanks Claude ...

**Comment by odeke-em** [comment]
Hello again @pageauc,
Good question, so in Go an os.Exit(error) produces a non zero error code while os.Exit(nil) produces a zero error code and that's what drive does depending on if the operation flow encounters an error or not. 
So far, contributors have raised issues where errors haven't been properly raised and those issues have been addressed. Is there a case that failed to work for you? If you notice anything peculiar, please feel free to raise an issue and I'll work on it.

**Comment by ikwyl6** [comment]
I think what the user may be looking for (correct me if I'm wrong) is a list of different error codes for different exit status situations. This helps tremendously when someone wants to use your drive script in their script and notify the user of why an error was thrown. You have already included text descriptions with your script but the user may want to do it a different way. Otherwise if you don't assign exit codes to different errors, they only know that drive threw an "exit 1" (as an example) but there is no explanation why (if the user wants to suppress your output). 

Usually in C programming there can be an "errors.h" file or something similar that lists all error types. For example:

- exit 1: user enters wrong credentials
- exit 2: drive was cancelled by user (CTRL-c)
- exit 3: drive was disconnected from server. 

And so on. This list could be big.  This makes the error situations very manageable when someone wants to cleanly notify the user of why the script ended without a 0 exit code.

**Comment by pageauc** [comment]
Yes that is exactly what I am trying to do with my bash script.  I am automating recording and uploading video files in a round robin sequence.  If a process fails (record, upload, etc) then I want to take appropriate action like retry upload, record etc.  I also have to check to make sure that if multiple instances of the script are run, that the current state is not crashed eg tries to duplicate something that is already in progress.  I need to report meaningful status, warning or error message(s) to the users(s),  It is nice to have self correcting code but in some cases users might need to resolve a problem.  A list of exit codes would be great since one process can communicate to another like a record failing so don't upload it.  If problem persists then issue appropriate message.

I seem to be having problems if there is no internet connection and upload does not take place.
 if [ $? - ne 0 ]; then

Thanks Claude ...

**Comment by odeke-em** [comment]
Thank you @ikwyl6 for the clarification, that makes sense. @pageauc so no there isn't a list of exit codes, currently the only exit code is `1`
![img_20151111_134737](https://cloud.githubusercontent.com/assets/4898263/11102648/031d33da-887b-11e5-927f-94a6ed4b0466.png)

**Comment by ikwyl6** [comment]
Hi @odeke-em so do you think you can implement these error codes?

**Comment by odeke-em** [comment]
I don't know about now as I don't have much free time. In the next two months or so, sure, given the number of unfixed bugs plus my school commitments. Otherwise if anyone would like they can submit a PR and I'll definitely review it.

**Comment by odeke-em** [comment]
Hello @ikwyl6 and @pageauc did you have an idea of the different error codes or would you like me to add them in in running number form ie 1 counting upwards, and then you'll look them up?

**Comment by pageauc** [comment]
Ok.  These are my suggestions but not sure if you have appropriate points
in the program to trap these types of errors.  Some of these I can check
with another program prior to launching a sync. Eg No Connection.  It would
be nicer to have this done within a returned errorlevel.
Claude ...

0 - Sync Successful
1 - Sync Incomplete - Lost Connection due to Local Network or Internet
Problem
2 - Sync Incomplete - File Permission, Space, Etc Problem
3 - Sync Failed -.Authentication with Server Failed
4 - Sync Failed - Server or API Service Not Found Problem
5 - No Connection - Local Network or Internet Problem.

On Fri, Nov 27, 2015 at 10:06 AM, Emmanuel T Odeke <notifications@github.com
> wrote:

> Hello @ikwyl6 <https://github.com/ikwyl6> and @pageauc
> <https://github.com/pageauc> did you have an idea of the different error
> codes or would you like me to add them in in running number form ie 1
> counting upwards, and then you'll look them up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odeke-em/drive/issues/479#issuecomment-160167394>.
>



-- 
See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by HontoNoRoger** [comment]
+1 for that

**Comment by ManuCart** [comment]
I need it too after spent files with a pull/push script with non possiblity to read status code 504 & 505

**Comment by odeke-em** [comment]
Hey folks. My apologies for the long wait, I have been very busy for the last few months. However, this evening I got some time and whipped up a PR https://github.com/odeke-em/drive/pull/608. It has a couple of status/return codes and you can always see the reference in src/errors.go. I'll merge it in and we'll keep updating it as we go.
Thank y'all.

**Comment by odeke-em** [comment]
Auto closed by PR #608, please re-open if persists.

**Comment by ManuCart** [comment]
Thanks a lot I try it now
