### ISSUE TITLE
unshare: 'Permission not found'

### ISSUE THREAD

**Issue by bdlow** [odeke-em/drive#484]
Attempting to remove sharing from a file, by ID, returns a 'permission not found' error:

```
% drive stat -id 1yX...Rw   

1yX...Rw
Filename                  Name of file
FileId                    1yX...Rw
Bytes                     0                             
Size                      0.00B                         
DirType                   file                          
VersionNumber             1825593                       
MimeType                  application/vnd.google-apps.document
Etag                      "fbe...5NA"
ModTime                   2015-11-20 03:06:43 +0000 UTC 
LastViewedByMe            2015-11-20 02:55:18 +0000 UTC 
Shared                    true                          
Owners                    My Name                  
LastModifyingUsername     My Name                  
OriginalFilename                                        
Md5Checksum                                             
Copyable                  true                          
Starred                   false                         
Viewed                    true                          
Trashed                   false                         
ViewersCanDownload        false                         

*
Name: My Name <me@myappsdomain.net>
Role                 owner                         
AccountType          user                          
*

*
Name: Someone Else <other@gmail.com>
Role                 reader                        
AccountType          user                          
*

*
Name: myappsdomain.net <>
Role                 reader                        
AccountType          domain                        
*

% drive unshare -id 1yX...Rw                                
Revoke access for accountType: user for file(s):
+  Name of file

Proceed with the changes? [Y/n]:
Name of file: googleapi: Error 404: Permission not found: user, notFound

```

(This is for files on an Apps domain, if that makes a difference.)

Trying the various -type options has the same result. Isn't unshare missing an -emails flag?

**Comment by odeke-em** [comment]
Hello @bdlow thanks for reporting this and welcome to drive. I'll take a look at it and investigate more over the weekend. I agree unshare might be trippy, I've found it awkward too.

**Comment by odeke-em** [comment]
Thanks for reporting this issue, addressed by PR #486.
Closing it in lieu of a new release, please reopen if it persists.

**Comment by bdlow** [comment]
Thanks @odeke-em ; seems to work well for --type user.

I've had no success with --type domain (stat show an empty email address for domain); neither of the following works: (file is the same as in the OP, now with the other@gmail.com user removed):
```
% drive unshare --emails 'example.net' --type domain -id 1yX..Rw
no matches found! 
% drive unshare --emails '' --type domain -id 1yX..Rw
no matches found! 
```

**Comment by odeke-em** [comment]
Hey @bdlow you can only unshare permissions that are already set which is why you get the "no matches found" notice, however I think I have an idea of what is tripping out.
Would you mind showing me a stat sample and I'll take it from here, I think I have a hunch on what is happening. However, I'll be able to look at it maybe at the week's end as am trying to clear out the last assignments before the semester ends, plus other commitments.
Thanks.

**Comment by odeke-em** [comment]
@bdlow thank you for the patience, please get the latest from master. I created an issue that was a follow up of your comments and addressed it with PR https://github.com/odeke-em/drive/pull/504.

**Comment by bdlow** [comment]
Excellent, it's working well now!

Thanks,
Ben
