### ISSUE TITLE
drive command is now drive-google?

### ISSUE THREAD

**Issue by donders** [odeke-em/drive#487]
I installed drive on another machine today. After running the go get command there is no 'drive' binary in the gopath bin folder, but rather a 'drive-google' command. Is this intended? If so, can someone update the README?

**Comment by odeke-em** [comment]
Hello again @donders!
No that isn't the case, that's just an alias that got added in to appease issues https://github.com/odeke-em/drive/issues/271 and  https://github.com/odeke-em/drive/issues/277. Also the README already talks about this at https://github.com/odeke-em/drive#installation.
That's quite odd that you run your own `go get` successfully but it installed `drive-google`. If you are sure the command was meant for drive and it ran successfully, please repeat it with a `-v` flag.

**Comment by donders** [comment]
Ahh there you have it, I copied the 'wrong' command, as you might've guessed. Problem solved!

**Comment by odeke-em** [comment]
Cool.
