### ISSUE TITLE
Failure to return --match *

### ISSUE THREAD

**Issue by mitote** [odeke-em/drive#490]
works correctly in push pull  but...

Fails to return correct matches when attempting to list/stat files of a given type.
command:
    drive list gdrive/.../folder --match VOB
returns:
    "/../--matches" cannot be found remotely
    "/../VOB" cannot be found remotely
   /.../all_files_in_folder

list still works, but does not match.

**Comment by odeke-em** [comment]
Hello @mitote thanks for reporting this and welcome to drive!

So Go's command line parser accepts options first before arguments therefore to make your command work, please pass in the arguments with "--" before the arguments like this:
```diff
- drive list gdrive/.../folder --match VOB
+ drive list --match VOB gdrive/.../folder
```

**Comment by mitote** [comment]
Hi @odeke-em and thanks for supporting this awesome program.
I should have waited a little to report the bug.
I have tried every combination of syntax I could think of without success including the above syntax.

Attempted Syntax:
    `drive list gdrive/.../folder --match VOB`
    `drive list gdrive/.../folder -match VOB`
    `drive list gdrive/.../folder match VOB`
   ` variations with quotation marks`
All return 
    `"/../--matches" cannot be found remotely`
    `"/../VOB" cannot be found remotely`
    `...`
Attempted Syntax:
    `drive list  --match VOB gdrive/.../folder`
    `...all previous variations with this syntax and more`
All return
     `no drive context found; run `drive init` or go into one of the directories (sub directories) that you performed `drive init` `
      Definitely already initialized and functioning correctly.

I will attempt the following:  
- Updating to go-1.5.1
- Testing on another machine (when I can get to it) and/or OS
- shake my fists at the screen

I've written a work around in the mean time but if it helps I'll keep this thread up to date on my problem.

**Comment by odeke-em** [comment]
Please go into gdrive and repeat the syntax with what I had suggested, that's what the issue is.
See drive works in contexts, that is if you run a directory either it is a sub directory or the main directory that you ran `drive init` in and has a `.gd` directory.

**Comment by mitote** [comment]
So simple yet far down on my list of things to try.  
I will re-evaluate my approach.

Yes this works.  Many Thanks.

**Comment by odeke-em** [comment]
No worries, am glad I could be of help and thanks for checking out drive plus for the patience.
