### ISSUE TITLE
drive push creating empty files

### ISSUE THREAD

**Issue by Riaz1** [odeke-em/drive#491]
I've run various drive push commands, the last run was:
drive push -no-prompt -no-clobber --ignore-name-clashes --verbose

From the screenshot attached, you can see that files are being pushed to google drive, but some files have 0 size. On linux those files are not empty and have the same permissions as files that were uploaded properly.
![screenshot from 2015-11-25 07 45 58](https://cloud.githubusercontent.com/assets/15997971/11389471/c956ac06-9349-11e5-9617-b59cfd8e80ed.png)

**Comment by odeke-em** [comment]
Hello @Riaz1, thanks for this report and welcome to drive!

So would you mind taking  a look at closed issue https://github.com/odeke-em/drive/issues/365.

Also you haven't mentioned what version of drive you are using, what OS you are on(am going to assume this is Ubuntu Linux). Usually you can get drive's information by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by Riaz1** [comment]
Hi,

I will attempt some of the suggestions in #365 and get back to you in about a week. 
Ubuntu 14.04.3 LTS.

**Comment by odeke-em** [comment]
Hey @Riaz1 let's move this issue to #365 since it is older and has more discussions there.
