### ISSUE TITLE
Drive corrupts zip files

### ISSUE THREAD

**Issue by mw55309** [odeke-em/drive#492]
I have a Google Drive full of large zip files (3Gb to 50Gb).

I can download one of the smaller Zip files (8Gb) through Chrome, open it and see that it is correct, it opens, no problems.

If I pull the same file using drive, I get an error:

Archive:  SynthMetagenome/S elong 17ii15 FAA25973_run1.zip
warning [SynthMetagenome/S elong 17ii15 FAA25973_run1.zip]:  3985502558 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [SynthMetagenome/S elong 17ii15 FAA25973_run1.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

If I run drive diff there are no listed differences

If I run drive pull again it says "Everything is up-to-date".

I'm running on Scientific Linux version 6

**Comment by ikwyl6** [comment]
Has this been solved by yourself or did you hit the "comment and close" button?

**Comment by mw55309** [comment]
Sorry, I checked the md5sums, it wasn't a drive bug.

Currently still investigating but I suspect this has nothing to do with drive.
