### ISSUE TITLE
what are name-clashes

### ISSUE THREAD

**Issue by bellera** [odeke-em/drive#493]
I have one @gmail.com account that it is impossible to pull the contents.

I pulled other users and the only difference I can see it's that the user has a dot character in his @gmail.com username.

Like this:

name.surname@gmail.com

I got (name files are obfuscated for privacy)

drive pull
Resolving...
These paths clash
X /2014-2015/Treball de... ...
X /2014-2015/Treball de Recerca... ...
X /2014-2015/Treball de Recerca-RUMORS... ...
X /2014-2015/Treball de Recerca-RU... ...

drive about
Name: XXXXXXX YYYYYYYY
Account type:	LIMITED
Bytes Used:	499236859            (476.11MB)
Bytes Free:	15606890501          (14.54GB)
Bytes InTrash:	11952436             (11.40MB)
Total Bytes:	16106127360          (15.00GB)

* Space used by Google Services *
Service                              Bytes                               
DRIVE                                468.93MB                            
GMAIL                                5.32GB                              
PHOTOS                               0.00B                               
Space used by all Google Apps        5.79GB                              

* Maximum upload sizes per file type *
FileType                                           Size                
application/vnd.google-apps.document               10.00MB             
application/vnd.google-apps.spreadsheet            100.00MB            
application/vnd.google-apps.presentation           100.00MB            
application/vnd.google-apps.drawing                2.00MB              
application/pdf                                    4.77TB              
*                                                  4.77TB              

Feature                        Request limit (queries/second)
ocr                            0.000000                      
translation                    2.000000

**Comment by odeke-em** [comment]
Hello again @bellera. Thanks for reporting this.

So there is nothing wrong with email.extra@domain.com, I have been using such for long.
The issue here is
`
Resolving...
These paths clash
X /2014-2015/Treball de... ...
X /2014-2015/Treball de Recerca... ...
X /2014-2015/Treball de Recerca-RUMORS... ...
X /2014-2015/Treball de Recerca-RU... ...
`
which drive warned you about. It even provides a remedy if you read through the error.
Please pass in `--fix-clashes` or as mentioned take a look at the error it produced for how to fix this.
Let me know what happens.

**Comment by bellera** [comment]
@odeke-em,

Local folder is empty. So, I don't understand why drive is claiming for clashes.

I forgot to say that I tried *--fix-clashes* before opening this issue.

In fact, it seems like a kind of loop...

ls -l
total 0

drive pull --fix-clashes
Resolving...
Some clashes found, we can fix them by following renames:
/2014-2015/Treball de Rec... ... 
/2014-2015/Treball... ... 
Proceed with the changes [Y/N] ? Y
Renaming /2014-2015/Treball de Rec... ... 
Renaming /2014-2015/Treball... ... 
Clashes were fixed, try pushing again.

drive pull --fix-clashes
Resolving...
Some clashes found, we can fix them by following renames:
/2014-2015/CURS 14%2F15/Guió... ... 
Proceed with the changes [Y/N] ? Y
Renaming /2014-2015/CURS 14%2F15/Guió... ... 
Clashes were fixed, try pushing again.

drive pull --fix-clashes
Resolving...
Some clashes found, we can fix them by following renames:
/cursos/TXT/curs TxT/Activitat 3... ... 
Proceed with the changes [Y/N] ? Y
Renaming /cursos/TXT/curs TxT/Activitat 3... ... 
Clashes were fixed, try pushing again.

drive pull --fix-clashes
Resolving...
Some clashes found, we can fix them by following renames:
/2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BARCELONA... ... 
Proceed with the changes [Y/N] ? Y
Renaming /2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BARCELONA... ... 
Clashes were fixed, try pushing again.

drive pull --fix-clashes
Resolving...
Some clashes found, we can fix them by following renames:
/2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BANC... ... 
/2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BANC ACTIVITATS... ... 
/2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BANC ACTIVITATS EMOCIONS... ... 
Proceed with the changes [Y/N] ? Y
Renaming /2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BANC... ... 
Renaming /2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BANC ACTIVITATS... ... 
Renaming /2015-2016/Sem coord Proj. Singulars/CURS 15%2F16/BANC ACTIVITATS EMOCIONS... ... 
Clashes were fixed, try pushing again.

ls -l
total 0

Tried also *drive deinit* (erasing only db file)

I made also *drive index*

Finally I decided to make *drive pull --ignore-name-clashes* and now it's downloading everything (?).

Addition count 1287 src: 565.02MB
Proceed with the changes? [Y/n]:Y

I thought that *clashes* were conflicts between local and remote names. In this case I had anything on the local side. So, it seems that I don't understand what are *clashes*.

Could you clarify me this?

Thanks,

Josep

**Comment by odeke-em** [comment]
A name conflict exists when you have more than one file with the same path in the same dir.
Google Drive remotely allows for you to have multiple paths https://github.com/odeke-em/drive#known-issues. If you don't resolve them, files will be overwritten because your file system ordinarily doesn't allow for multiple files same path, but as mentioned Google Drive allows for that. It is just a precaution to avoid losing your data.
Also fetching all the name clashes isn't yet complete but nonetheless it is there to protect your data from being overwritten.

**Comment by odeke-em** [comment]
Also what version of drive, it is useful to give the information of what you are using this way I can trace back to commits etc.

**Comment by bellera** [comment]
Ubuntu 12.04 LTS Server 64 bit
drive  0.3.1

OK, many thanks! Finally, I think I well understood what are the *clashes*.

I did many times:

*drive pull -fix-clashes -no-prompt*

until not more receiving more clashes warnings to arrange the problem.

Now, I'm having problems connecting to *oauth2* service:

*drive pull -fix-clashes -no-prompt*
Resolving...
Get https://www.googleapis.com/drive/v2/files/root?alt=json: Post https://accounts.google.com/o/oauth2/token: dial tcp 216.58.210.237:443: i/o timeout

*drive about*
Get https://www.googleapis.com/drive/v2/about?alt=json: Post https://accounts.google.com/o/oauth2/token: dial tcp 216.58.210.173:443: i/o timeout

I will try to continue later. Or the Google service is falling or they control the number of accesses per account. I tried it using different connections to the internet.

**Comment by bellera** [comment]
I arrived to the end!

*Resolving...*
*Everything is up-to-date.*

Now, I want to ensure that the local copy has all documents. So, I have to export the documents that are using Google Drive formats. I did:

*drive pull --export doc,xls,ppt,png --explicitly-export --fix-clashes --no-prompt*

But each time that I use this command the documents are exported a new time.

And if I do:

*drive pull --export doc,xls,ppt,png --fix-clashes --no-prompt*

local exported copies are erased.

What syntax to use for *pull* & *export* and have up-to-date ?

**Comment by odeke-em** [comment]
```
And if I do:

drive pull --export doc,xls,ppt,png --fix-clashes --no-prompt

local exported copies are erased.
What syntax to use for pull & export and have up-to-date ?
```

For one you can ignore the exports dir by adding entry "_exports$" to your .driveignore
e.g
```shell
$ cd myDrive
$ cat < ! >> .driveignore
> _exports
> !
```
.driveignore is detailed in the README here https://github.com/odeke-em/drive#driveignore

Another thing you can do is skip mime types or even exclude operations.

**Comment by bellera** [comment]
Ok, thanks!

**Comment by odeke-em** [comment]
BTW @bellera you can decide to export to a different directory out of your drive e.g
```shell
$ drive pull -export pdf,rtf,docx,txt -export-dir ~/Desktop/exports
```

* For a bonus you can even define a default exports dir into the .driverc file in that drive
```shell
$ cd myDrive
$ cat < ! >> .driverc
> export-dir=/home/user/backups/exports
> !
```
Please note that you can define a .driverc for each directory, sub directory, or globally it is documented here https://github.com/odeke-em/drive#driverc

**Comment by odeke-em** [comment]
Ping!

**Comment by bellera** [comment]
Ok, thanks a new time!

Finally I didn't finish the work using export.

Instead than pulling with export I used Google TakeOut to backup the old account.

https://myaccount.google.com/privacy?pli=1#takeout

And drive to push the content downloaded with Google TakeOut to the new account.

I'm sorry!

**Comment by odeke-em** [comment]
Ah I see, oh it is no biggie glad to know you got that solved. Cheers! I'll close this issue then.
