### ISSUE TITLE
diff: switch to create unified diff

### ISSUE THREAD

**Issue by monojp** [odeke-em/drive#494]
Hi, sorry if this has already been mentioned before, I didn't find it although it may be related or a addition to #122.

What I think would be a nice feature is a unified diff output. Just like calling "diff" with the -u parameter which should create a diff that could also been used as input for "patch". Could this possibly be implemented by specifying another argument together with "drive diff"? I think this would make the diff output of drive more exchangeable (e.g. I am syncing config files and sometimes it would help to be able to create simple patches from drive).
On the other handy I just prefer reading diffs in the unified format, so it may be a nice additional output feature for some users.

**Comment by odeke-em** [comment]
Hello again @monojp. Thank you for reporting this, I can see the utility for this. So actually drive's diff executes an external shell command so definitely we can easily add this option.
This class is kinda boring so I might whip it out real quick :)

**Comment by odeke-em** [comment]
Done please see https://github.com/odeke-em/drive/pull/495. Please get the latest from master.
Thank you for requesting this!

**Comment by monojp** [comment]
Nice, looks good! Thanks for building this so fast. Should have requested it earlier :)

**Comment by odeke-em** [comment]
Cheers. Yeah this is a quick one and usually if I have say a boring class, then it is open season. Enjoy!

**Comment by monojp** [comment]
Hey, another idea: What do you think about inverse diff? Currently the local copy is diffed against the remote, right? In my case I'm mostly interested in the opposite case to find out what got removed / added on the local copy (like git,svn,..).
Another approach would be an intelligent diff that always diffs the old against the new change. If something changed remote it will diff local against remote, if something changed locally it will diff remote against local.

**Comment by odeke-em** [comment]
Hello again @monojp, aha you read my mind. I was thinking of making the base diff switchable so you could decide whether to use remote or to use local as the base, that same day that I added in your first request. However, after that class session that morning, the day got busier and I wasn't able to use my computer.
Would you mind creating a new issue for this?

**Comment by monojp** [comment]
Sure, no problem. Will do that when I get home. Thx for looking into it.

**Comment by odeke-em** [comment]
Hello @monojp, I got some free time and spun out the feature in PR https://github.com/odeke-em/drive/pull/507, please get the latest from master.
