### ISSUE TITLE
Can't pull last modified files with export option

### ISSUE THREAD

**Issue by antton** [odeke-em/drive#496]
Hi, 

As I see 'drive pull' check for the new and modified files everytime and only donwload the changes but It would be nice to give a possibility of export at the same time (only modified files)

Maybe it's possible and I don't know how, but I didn't find the opcion or convination to do it.

Thanks!

**Comment by odeke-em** [comment]
Hello @antton thanks for the reporting this and welcome to drive!

So you are looking for flag `--explicitly-export`.

**Comment by odeke-em** [comment]
```shell
$ drive pull --help 2>&1 | grep export
  -explicitly-export # <--- this is what you are looking for
    	explicitly pull exports
  -export string
    	comma separated list of formats to export your docs + sheets files
  -exports-dir string
    	directory to place exports
```

**Comment by antton** [comment]
Hi @odeke-em 

I will test it again and let you know! Thanks! ;)

**Comment by antton** [comment]
Hi, 

This is what I try 
 drive pull --export doc,xls,ppt,png --explicitly-export -verbose

but it export everyfile again an again every now and then, even the file has not been modified in Google Drive.

;)

**Comment by odeke-em** [comment]
Why don't you specify the paths?

**Comment by antton** [comment]
Hi @odeke-em 

Maybe I didn't explain exactly what I want to do.

I would like to syncronized all google drive files (gdocs, gsheet and gslides) exporting into their corresponding extension but  everytime I detect any kind of change on this files I would make the same proccess but only with changed files.

If I specify the path as you said, I need to explicitly to give a path to download the changed files, but it downloads all of them again and convert, It have to be another way to detect changes, download them and convert only this files.

I don't know If i'm explaining but If we have more than 500 google type files we can't be downloading and converting all of them everytime we pull from the source.

Thanks!

**Comment by odeke-em** [comment]
So if you are pulling only modified files that shouldn't be a problem at all.
Please give me a sample of the command you are using, it might just be misplacement of flags.

**Comment by odeke-em** [comment]
Before I suggested `--explicitly-export`

**Comment by odeke-em** [comment]
If you wanted only to pull and export at the same time, I probably misunderstood your question since it is it is documented here in the README.
```shell
$ drive pull --export pdf,png,xls,ppt --verbose
```

Also you didn't give me your drive version and other information to try to reproduce this :)

**Comment by antton** [comment]
Hi again, 

My version 0.3.3 on Ubuntu 14.04 

If I write your command 
```$ drive pull --export pdf,png,xls,ppt --verbose```
All files converted previously are removed.

the only way to pull and export at the same time was with:
```$ drive pull --export doc,xls,ppt,png --explicitly-export```

But I think everytime I use this last command drive is downloading all (gdocs, gsheet and gslides) files and convert all of them again.

Thank you for your time and consideration!

**Comment by odeke-em** [comment]
Ah I see, thanks for that clarification @antton.
So now that you are using that command without --explicitly-export, that's expected as any new clutter in your drive should be removed. To get around the deletions however, I just answered a question exactly like yours and provided some remedies here https://github.com/odeke-em/drive/issues/493#issuecomment-160444731 and https://github.com/odeke-em/drive/issues/493#issuecomment-160551639.

**Comment by xezpeleta** [comment]
Hi @odeke-em ,

Same problem here. After reading all your answers, I can't get it to work:

First, I create `.driverc` and `.driveignore` files
```yaml
# .driverc file
export-dir=/home/myuser/gdrive-exports
```
```yaml
# .driveignore file
_exports$
```
Then, I create a "test" folder on my Google Drive with the following content:
- file1: Google Doc
- file2: Google Spreadsheet
- file3: Google Slide

Now, I try to "pull and export" all my documents.

```sh
$ drive pull --export doc,xls,ppt,png -no-prompt -verbose
Pull::Started /test/file2
Pull::Started /test/file1 
Pull::Started /test/file3 
Pull::Done /test/file3 
Exported '/home/myuser/gdrive/test/file2' to '/home/myuser/gdrive/test/file2_exports/file2.xls'
Pull::Done /test/file2 
Exported '/home/myuser/gdrive/test/file1' to '/home/myuser/gdrive/test/file1_exports/file1.doc'
Pull::Done /test/file1
```

Well, apparently first time works quite well, even if it has ignored my exported directory configuration from `.driverc` file.

Now, I modify my files online and I try to pull again:

```sh
$ drive pull --export doc,xls,ppt,png -no-prompt -verbose
Resolving...
M /test/file3
M /test/file2
M /test/file1
Modification count 3
Pull::Started /test/file1 
Pull::Started /test/file3 
Pull::Started /test/file2 
Pull::Done /test/file1 
Pull::Done /test/file3 
Pull::Done /test/file2
```

As you can see, it pulls the modified files, but **without export** them. So now, my exported documents on my computer are outdated.

If I add `--explicitly-export` parameter, it exports all the google apps documents correctly, but it pulls and exports everything; included not modified documents:

```sh
$ drive pull --export doc,xls,ppt,png -no-prompt -explicitly-export -verbose
Resolving...
+ /test/file3
+ /test/file2
+ /test/file1
Addition count 3
Pull::Started /test/file1 
Pull::Started /test/file3 
Pull::Started /test/file2 
Pull::Done /test/file3 
Exported '/home/xezpeleta/gdrive/test/file1' to '/home/xezpeleta/gdrive/test/file1_exports/file1.doc'
Pull::Done /test/file1 
Exported '/home/xezpeleta/gdrive/test/file2' to '/home/xezpeleta/gdrive/test/file2_exports/file2.xls'
Pull::Done /test/file2 
xezpeleta@PC-018-01:~/gdrive$ 
xezpeleta@PC-018-01:~/gdrive$ 
xezpeleta@PC-018-01:~/gdrive$ 
xezpeleta@PC-018-01:~/gdrive$ drive pull --export doc,xls,ppt,png -no-prompt -verbose test
Resolving...
Everything is up-to-date.
xezpeleta@PC-018-01:~/gdrive$ 
xezpeleta@PC-018-01:~/gdrive$ 
xezpeleta@PC-018-01:~/gdrive$ drive pull --export doc,xls,ppt,png -no-prompt -verbose test
Resolving...
M /test/file2
M /test/file1
Modification count 2
Pull::Started /test/file1 
Pull::Started /test/file2 
Pull::Done /test/file1 
Pull::Done /test/file2
```

Is that the expected behaviour? Is there anyway to pull and export only my modified documents?

Thanks

**Comment by odeke-em** [comment]
Hello folks, I guess I made a typo when I was typing that out last night,
```diff
- export-dir
+ exports-dir
```

Hope you don't mind repeating that operation with the typo fixed.
Thanks.

**Comment by xezpeleta** [comment]
I start again. I create a `test` folder on my Google Drive and I pull it:

```sh
$ drive pull --export doc,xls,ppt,png -no-prompt -verbose test
Resolving...
+ /test
+ /test/file2
+ /test/file1
+ /test/file3
Addition count 4
Pull::Started /test/file3 
Pull::Started /test/file2 
Pull::Started /test/file1 
Pull::Started /test 
Pull::Done /test 
Pull::Done /test/file3 
Exported '/home/myuser/gdrive/test/file1' to '/home/myuser/gdrive-exports/file1_exports/file1.doc'
Exported '/home/myuser/gdrive/test/file2' to '/home/myuser/gdrive-exports/file2_exports/file2.xls'
Pull::Done /test/file1 
Pull::Done /test/file2 
```

Great, first time it works like a charm. I modify my files online and I run the command again:

```sh
$ drive pull --export doc,xls,ppt,png -no-prompt -verbose test
Resolving...
M /test/file3
M /test/file2
M /test/file1
Modification count 3
Pull::Started /test/file1 
Pull::Started /test/file3 
Pull::Started /test/file2 
Pull::Done /test/file1 
Pull::Done /test/file2 
Pull::Done /test/file3 
```

Apparently it detects that the files are changed, but it doesn't export them.

As before, if I do add `-explicitly-export` parameter, it pulls&exports everything. Even the not modified data.

**Comment by odeke-em** [comment]
@xezpeleta please pass in the paths you want explicitly exported.

**Comment by odeke-em** [comment]
So in the code there is a close that avoids downloading when the content hasn't changed.
Am going to modify it so that when exports are requested if a file is modified, this goes through.

**Comment by odeke-em** [comment]
Okay I think I finally understood the problem after trying to reproduce it. I've created a PR #509 to fix this.
Please get the latest from master.

**Comment by odeke-em** [comment]
The issue got autoclosed in the commit when I merged into master, please reopen if it isn't fixed.

**Comment by xezpeleta** [comment]
I've just tried it and now yes it works very well. Thanks for your quick answer @odeke-em.

**Comment by odeke-em** [comment]
Awesome, thanks for the patience and my apologies for misunderstanding the bug, lack of sleep didn't let me think clear :) I should have solved it earlier.

**Comment by antton** [comment]
Great!
