### ISSUE TITLE
--match-mime parameter wih list/pull

### ISSUE THREAD

**Issue by xezpeleta** [odeke-em/drive#498]
Hi, I'm trying to list and download Google Docs documents:

In the documentation (README) I see that the next command should work:

```
drive list --match-mime xls,docx
```

Running this command only shows the help, so apparently it doesn't recognize the parameter. Something similar occurs with PULL.

I saw that with `-matches` works well, but only with standard mimetypes like pdf, png, etc... But if I try to filter with Google Apps documents format it doesn't work.

Is there any way to do this?

Thanks!

**Comment by odeke-em** [comment]
Hello @xezpeleta, thank you for reporting this issue and welcome to drive!

You are right, for some reason "--match-mime" is "--exact-mime"
<img width="452" alt="screen shot 2015-11-27 at 9 04 43 am" src="https://cloud.githubusercontent.com/assets/4898263/11445022/f818245a-94e5-11e5-8c19-edb7c16bafda.png">

PR coming up in a second.

**Comment by odeke-em** [comment]
Hello @xezpeleta, list has always advertised that it supports `--match-mime`, pull has never done so. This issue is more related to the previous typo so if you want match-mime for pull, please make a separate PR for pull. Please get the latest from master. It should be fixed.

**Comment by xezpeleta** [comment]
Thanks @odeke-em, I'll try to do that

**Comment by odeke-em** [comment]
Closing this issue since it the bug is fixed for `--match-mime` and pull has never had `--match-mime` so please make that a separate pull request.
