### ISSUE TITLE
<nil> remote path doesn't exist

### ISSUE THREAD

**Issue by guruthree** [odeke-em/drive#50]
I occasionally get this error when pushing a directory with subdirectories that have to be created. At least, that seems to be in common. I'm not sure if anything bad actually happens as a result as I'm doing uploads with lots of files and there's no indicator of what remote path doesn't exist. Maybe something is slow at taking note of a newly created directory at times?

Great software, very useful!

**Comment by odeke-em** [comment]
What version of drive?

**Comment by odeke-em** [comment]
An issue that I could guess that is related to it is here: https://github.com/odeke-em/drive/issues/46

**Comment by guruthree** [comment]
I'm currently using 0.0.7, but I've seen this as well with 0.0.6. I'm currently doing `drive push directory`, which contains subdirectories, with subdirectories, and then files. You can see from the output below that it sort of happens sporadically. I think it would be useful if instead of just remote path doesn't exist it showed what path that was actually. In the files I'm uploading there are broken symlinks. Could this potentially have something to do with it? I'm a little unclear with drive is trying to do with them, other than the net effect that they don't get uploaded.

```
546 / 1709 [===============>---------------------------------] 31.95 % 10h54m23s
<nil> remote path doesn't exist
<nil> remote path doesn't exist
<nil> remote path doesn't exist
<nil> remote path doesn't exist
<nil> remote path doesn't exist
<nil> remote path doesn't exist
553 / 1709 [===============>---------------------------------] 32.36 % 10h42m17s
<nil> remote path doesn't exist
<nil> remote path doesn't exist
<nil> remote path doesn't exist
556 / 1709 [===============>---------------------------------] 32.53 % 10h37m10s
<nil> remote path doesn't exist
557 / 1709 [===============>---------------------------------] 32.59 % 10h35m30s
<nil> remote path doesn't exist
558 / 1709 [===============>---------------------------------] 32.65 % 10h33m50s
<nil> remote path doesn't exist
559 / 1709 [================>--------------------------------] 32.71 % 10h32m11s
<nil> remote path doesn't exist
560 / 1709 [================>--------------------------------] 32.77 % 10h30m32s
<nil> remote path doesn't exist
561 / 1709 [================>--------------------------------] 32.83 % 10h28m53s
<nil> remote path doesn't exist
562 / 1709 [================>--------------------------------] 32.88 % 10h27m14s
<nil> remote path doesn't exist
563 / 1709 [================>--------------------------------] 32.94 % 10h25m36s
<nil> remote path doesn't exist
564 / 1709 [================>--------------------------------] 33.00 % 10h23m59s
<nil> remote path doesn't exist
565 / 1709 [================>--------------------------------] 33.06 % 10h22m21s
<nil> remote path doesn't exist
566 / 1709 [================>--------------------------------] 33.12 % 10h20m44s
<nil> remote path doesn't exist
567 / 1709 [================>---------------------------------] 33.18 % 10h19m8s
<nil> remote path doesn't exist
1527 / 1709 [===========================================>-----] 89.35 % 1h29m56s
```

**Comment by odeke-em** [comment]
Thank you for reporting this. While doing a regression test I also noticed it. I am working on it right now. Watch this space :)

**Comment by odeke-em** [comment]
@guruthree thanks for the patience, would you mind testing out 482add9c699a5dadd5ef39b202a71b53a13d2b9b to see if this fixes it for you?

**Comment by guruthree** [comment]
I can test it, but I'm not sure how. My knowledge of go extends to `go get -u github.com/odeke-em/drive/cmd/drive` and I'm not sure how to adapt that to a branch.

**Comment by odeke-em** [comment]
No biggie,  please checkout PR #51 I have put up the instructions on how to get to it.

**Comment by guruthree** [comment]
Thanks. It seems to be working so far. When I tried doing `drive push -ignore-checksum=true` it still tried to checksum files, but with the usual `drive push -no-prompt=true -ignore-checksum=true` that I've been it did not (as expected).

**Comment by odeke-em** [comment]
Hmm, I'll try to investigate that separately? Otherwise, it solves the initial, `remote not existant problem`? Would you mind providing the feedback on the PR page for the sake of record keeping in relation to the original problem? Thank you.

**Comment by guruthree** [comment]
Looks like the initial problem is solved. I don't know about the checksum thing as it's only happened the one time. I'll start a new issue if it happens again.

**Comment by dbesancon** [comment]
Version 0.0.7
Same Problem with <nil> remote path doesn't exist
Applied patch (#51) and no longer getting error message about regarding remote path.
I am now getting googleapi: Error 400:: Parent is not a folder:  ...

Thank you for you time in this!

**Comment by odeke-em** [comment]
@dbesancon weirdly it was working until today mid afternoon. I did all things possible even rolled back to ages ago. I kept checking and testing for about one hour and a half, so I suspect an infrastructure problem(I could totally be wrong). I logged a heads up so will wait for them to get back
https://twitter.com/odeke_et/status/559441879733788673

**Comment by odeke-em** [comment]
@dbesancon I have found that it was an update by the google golang api https://github.com/google/google-api-go-client/commit/8a098771176331fd2afc6d135240402617dc0f5e that caused the code to break. If you would like to test out the code, go to the last change before it started breaking by:
```shell
$ cd $GOPATH/src/google.golang.org/api
$ git reset --hard 3f7dcd0e7a9cbcc8199def5ec2b0be34261ff67c
$
$ cd $GOPATH/src/github.com/google/google-api-go-client/
$ git reset --hard 3f7dcd0e7a9cbcc8199def5ec2b0be34261ff67c
```
In the meantime while I dig through the Google API and find out more about what tripped things out.

**Comment by odeke-em** [comment]
Fixed it by migrating to a curated and stable repo of the Google go client that I know won't be rapidly changing and breaking changes here. You can repeat the patch steps and should be able to test things out.
