### ISSUE TITLE
-quiet should prevent all logging but errors

### ISSUE THREAD

**Issue by chevillet** [odeke-em/drive#502]
Hello,

The command:

> drive pull -quiet -export docx,xlsx -explicitly-export -ignore-conflict

Outputs the following:

> Resolving... [First output]
> Exported 'SOME_PATH' to 'SOME_PATH' [For every exported doc]

And sometimes even download progress:

> 0 / 12139859 0.00 %
> 8038112 / 12139859  66.21 % 0
> [...]

Since these are clearly not errors, shoudn't these messages be excluded from logs when the **-quiet** option is used?

Thanks and regards,

Seb.

**Comment by odeke-em** [comment]
Hello @chevillet! Thanks for reporting this issue and welcome to drive.

Good catch, I haven't used --quiet more than 3 times myself so I hadn't checked in on it, I'll get this fixed.

**Comment by chevillet** [comment]
OK, great!
Thanks a lot!

**Comment by odeke-em** [comment]
Hello @chevillet thank you for the patience. I've addressed this issue in PR #522. Please get the latest from master.
Closing this issue, please re-open if it persists.

**Comment by chevillet** [comment]
@odeke-em Thank you for your help on this and your amazing work on drive!
The -quiet option now works perfectly!

Just a few words for Ubuntu users who might run into the same issue...
Ubuntu go packages are so outdated you won't be able to install drive from the latest source using:

> go get -u github.com/odeke-em/drive/cmd/drive

You need to get a newer version of go first , which can also be a little tricky!
Luckily, there is a great tool to manage go versions: https://github.com/moovweb/gvm
Using gvm, you can install a recent go version and then install drive from the latest source in just a few seconds:

> bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
> gvm install go1.4
> gvm use go1.4
> gvm install go1.5.2
> gvm use go1.5.2 --default

And then:

> go get -u github.com/odeke-em/drive/cmd/drive

Hope this helps.

**Comment by odeke-em** [comment]
Thank you for the kind words @chevillet!
Just a note to the installation you have there, please use
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
instead of
```shell
$ go get -u github.com/odeke-em/drive/cmd/drive
```
the first style will help bundle commit information and version info so that when reporting an issue, getting that should be as simple as `drive version`.

also I use Ubuntu occasionally and I've never had a problem installing Go from source it is a 5 step process and it is reliable and just works, for me.

Thank you for the notes @chevillet.

**Comment by chevillet** [comment]
OK, I just fixed the drive install command.

Regarding Ubuntu, I should have mentioned I'm using a 14.04 LTS server version...
The default go packaged version was 1.2 even if I'm upgrading and updating everything but the distribution everyday.

I guess the problem doesn't occur on more recent Ubuntu versions.

**Comment by odeke-em** [comment]
Awesome!

**Comment by chevillet** [comment]
Hi,

It's been working fine for a few weeks regarding the "Resolving" and "Exported" but there are still some progress messages using "-quiet", for example:

> 0 / 179592 0.00 %
> 4096 / 179592  2.28 % 8s
> 8192 / 179592  4.56 % 25s
> 17520 / 179592  9.76 % 18s
> 21616 / 179592  12.04 % 21s
> 46736 / 179592  26.02 % 11s
> 50832 / 179592  28.30 % 12s
> 58189 / 179592  32.40 % 12s
> 62285 / 179592  34.68 % 13s
> 68897 / 179592  38.36 % 12s
> 72993 / 179592  40.64 % 13s
> 78267 / 179592  43.58 % 12s
> 82363 / 179592  45.86 % 12s
> 94104 / 179592  52.40 % 10s
> 98200 / 179592  54.68 % 10s
> 103090 / 179592  57.40 % 10s
> 107186 / 179592  59.68 % 10s
> 112144 / 179592  62.44 % 9s
> 116240 / 179592  64.72 % 9s
> 120853 / 179592  67.29 % 8s
> 124949 / 179592  69.57 % 8s
> 129738 / 179592  72.24 % 7s
> 136295 / 179592  75.89 % 6s
> 141486 / 179592  78.78 % 5s
> 158600 / 179592  88.31 % 3s
> 162696 / 179592  90.59 % 2s
> 166792 / 179592  92.87 % 1s
> 281681 / 179592  156.84 % -10s
> 346384 / 179592  192.87 % -14s
> 346384 / 179592  192.87 % 41s

I was not able to figure out exactly when this happens since I'm pulling my entire drive folder everyday (and it's really not changing much) and the progress is only output sometimes.

**Comment by pefoley2** [comment]
I also have this issue.
