### ISSUE TITLE
Reduce CPU usage?

### ISSUE THREAD

**Issue by mayli** [odeke-em/drive#511]
Pushing files will cause 100% usage on a single core "Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz" vps. And the speed is around 5MB/s to 7MB/s. It takes 14 minutes computing to push 6.6G files. Is there anything we can do to reduce the cpu usage of pushing?

```
real    19m20.937s
user    14m6.116s
sys     2m0.748s
```

**Comment by odeke-em** [comment]
Hello @mayli, thanks for creating this issue and welcome to drive!

So that's some great push speed about as fast as my school offers(which I find fast).
So single core running a highly parallelized application. Did you try setting `DRIVE_GOMAXPROCS` as shown here 
```shell
$ DRIVE_GOMAXPROCS=2 drive push
```

https://github.com/odeke-em/drive/wiki#env-variables

**Comment by mayli** [comment]
@odeke-em Thanks, I've also tested pushing on a better machine(20 Cores).
I got a speed of 30MB/s ~ 50 MB/s,

```
# time ./gdrive/bin/drive_x86_64 push -ignore-checksum test/10G.bin                                                                          
Resolving...                                                                    
+ /test/10G.bin                                                                 
Addition count 1 src: 10.00GB                                                   
Proceed with the changes? [Y/n]:y                                               
10737418240 / 10737418240 [=====================================] 100.00 % 4m22s
                                                                                
real    4m25.342s                                                               
user    3m0.905s                                                                
sys     1m8.194s    
```

On the single core system:
```
 time DRIVE_GOMAXPROCS=1 ~/gdrive/bin/drive_i686 push -ignore-checksum -verbose test/1G.single.bin                
Resolving...
+ /test/1G.single.bin
Addition count 1 src: 1.00GB
Proceed with the changes? [Y/n]:y
Push::Done /test/1G.single.bin 
1073741824 / 1073741824 [=============================] 100.00 % 2m5s
real    2m7.802s
user    1m36.212s
sys     0m12.272s
```

It's still 100% cpu usage and around 10MB/s.

**Comment by odeke-em** [comment]
That actually doesn't help since reading for one file irrespective of the number of cores. The cause for CPU activity is the file being read and transmitted to Google Drive's backend, nothing else goes on in that goroutine while the reading is proceeding. Dayyyyumnnn 2 minutes to upload 1GB?? -- are you at Skynet central? That's my dream speed.

**Comment by mayli** [comment]
@odeke-em I mean, transferring at the speed of 30MB/s should be a easy task for an single core system.
The single core system can achieve this number in HTTP and ssh with about 30% cpu usage.
The mulit-core can also achieve ~30MB/s, which is saying the Google didn't limit the connection.
I think the current implementation might have some heavy computation somewhere in pulling/pushing. 

```
$ wget -O /dev/null http://speedtest.c1.lax1.dediserve.com/1GB.test
--2015-12-01 18:10:41--  http://speedtest.c1.lax1.dediserve.com/1GB.test
Resolving speedtest.c1.lax1.dediserve.com (speedtest.c1.lax1.dediserve.com)... 192.227.239.227
Connecting to speedtest.c1.lax1.dediserve.com (speedtest.c1.lax1.dediserve.com)|192.227.239.227|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1073741824 (1.0G) [text/plain]
Saving to: `/dev/null'

100%[==============================>] 1,073,741,824 31.9M/s   in 32s     

2015-12-01 18:11:13 (31.7 MB/s) - `/dev/null' saved [1073741824/1073741824]
```

**Comment by odeke-em** [comment]
Ah gotcha. Yeah but with --ignore-checksum and pushing one single file there isn't any extra computation involved.

**Comment by mayli** [comment]
Even scp gives a 30MB/s, let me see if I can profile it and blame golang :/

```
# scp -c arcfour 1g.bin xxx@xxx.com:                
xxx@xxx.com's password:                                                
1g.bin                                        100% 1024MB  29.3MB/s   00:35    
```

**Comment by odeke-em** [comment]
Actually there is something else that I could do to shave off CPU work but it will me writing a patch but I have an exam in about 12 hours that I haven't studied for :( However when am done with the exam I can write the patch and ping you, if you can wait, if you can't wait here is the pointer,
you can take out the middleman github.com/odeke-em/statos and replace the bytesTransferredAcker with a small channel that you can pass into the Golang Google Drive API

**Comment by mayli** [comment]
@odeke-em Thanks for the hints, I will look at it. Good luck with your exam :)

**Comment by odeke-em** [comment]
Thank you @mayli, catch you in a bit!

**Comment by odeke-em** [comment]
Hello again @mayli, actually cutting out the middle man won't yet work well with the Google Drive v2 API unless it is with resumeable media uploads yet we are always doing multipart uploads.
So anyways, I can't see any other thing that could hold up the CPU this intensively. As mentioned, please go ahead with the system profiling.

**Comment by mayli** [comment]
@odeke-em Oh I see, the multipart uploads will encode binary into base64, and I think that consumed tons of CPU cycles. I me benchmark the resume-able media uploads and see if it performs better.

**Comment by ikwyl6** [comment]
Not sure if it would work - but you could try 'nice' to minimize CPU...?

**Comment by mayli** [comment]
Tested three google drive clients, drive seems to be the fastest, I will assume it's already using the resumable upload API .Closing this issue as it's fixed in the latest release. Thanks!

rclone
```
# time ./rclone copy ../1g.zero.bin drive:1g.zero.rclone.bin
real    0m33.680s
user    0m18.260s
sys     0m12.760s
```

drive
```
time ./drive_linux-6cf9c721576fcb777bfd70da766b3729 push --destination 1g.zero.drive.bin 1g.zero.bin
real    0m32.409s
user    0m7.130s
sys     0m8.320s
```

my home make python script
```
root@paris:~/tmp# time python pydrive_upload.py 1g.zero.bin
real    1m12.505s
user    0m19.070s
sys     0m6.300s
```
