### ISSUE TITLE
Create standalone binary?

### ISSUE THREAD

**Issue by ewleonardspock** [odeke-em/drive#512]
Is there any way to create (or download) a standalone binary?  I would like to use this with my web host, which uses 64bit linux, but I can't install anything on the server, I can only run precompiled binaries in my directory.  I tried compiling on a different Linux machine, but when I copied the file it generated in /usr/bin/ to the web server, it wouldn't run.

**Comment by aerth** [comment]
Standalone binary works if you have permission to make things executable (chmod +x)

**Comment by odeke-em** [comment]
Thanks @aerth for getting this resolved!

**Comment by aerth** [comment]
;D
