### ISSUE TITLE
push without delete?

### ISSUE THREAD

**Issue by gauteh** [odeke-em/drive#514]
hi, not sure if there is a mailing list or irc channel where I could ask this, but it is it possible to push a directory without syncing it completely? That is, if I dont want to keep a complete copy of my files locally, but I want to push new files. 

So, a push without delete.

**Comment by odeke-em** [comment]
Hello again @gauteh!

`
hi, not sure if there is a mailing list or irc channel where I could ask this,
`

Unfortunately managing a mailing list or even an IRC is a lot of work as I am a student with lots of commitments so that would be hard for me :( However if anyone else wanted to sure, they can go ahead and create a mailing list or IRC.

`
but it is it possible to push a directory without syncing it completely? That is, if I dont want to keep a complete copy of my files locally, but I want to push new files.

So, a push without delete.
`
Oh yes definitely, there are a bunch of options
1) push with the exact files specified
```shell
$ drive push m1 m2.txt
````
I use this option quite a lot because drive's motivation is to selectively pull or push or perform any actions on specified files. I use this mostly for school folders where I'll have the same folder across lots of computers and depending on where am editing from, or space constraints I'll just want to deal with a single file.

2) use `--exclude-ops`
```shell
$ drive push --exclude-ops delete [paths...]
```

3) use `--no-clobber`
```
$ drive push --no-clobber [paths...] # Will only perform additions
```

All these options are also detailed in the README.md file :)
Please let me know if this helps and I can provide you with other examples.

**Comment by gauteh** [comment]
Thanks! I think --no-clobber should do it.

Yeah.. I know what it is like. But, I think it might make it easier to
contribute when there is a channel like that, perhaps gitter.im could be
an option? It is pretty easy to get started with and people can also
connect with IRC if that is their preference (also, it is not the end
of the world if you need to change to something else later).

Emmanuel T Odeke writes on December 7, 2015 10:27:

**Comment by odeke-em** [comment]
Aye aye, gotcha. We have a wiki too, interestingly you are the first person that has brought up IRC :)

**Comment by odeke-em** [comment]
I personally have never used IRC nor mailing lists, I mostly rely on issues and emails but sure if lots of people would like to use it and someone can manage it, sounds like a plan.

**Comment by gauteh** [comment]
Emmanuel T Odeke writes on December 7, 2015 10:45:
> Aye aye, gotcha. We have a wiki too, interestingly you are the first person that has brought up IRC :)
> 

Whatever works :) I found the wiki, but could not find my use-case
(yet..).

**Comment by gauteh** [comment]
Emmanuel T Odeke writes on December 7, 2015 10:47:
> I personally have never used IRC nor mailing lists, I mostly rely on issues and emails but sure if lots of people would like to use it and someone can manage it, sounds like a plan.

Ok, I will have to see how persistent of a user I will become. 

gitter.im has to be set up by the repository owner, I would recommend
adding a badge to the readme as well so that people easily can find it.

Another question; does the --no-clobber option update files that already
exist or do I have to use the exclude=delete option for that?

**Comment by odeke-em** [comment]
For the gitter.im I need to find some questions first, like will the information shared there be present to everyone? Could it be looked up by search engines(which is the preference)? Could you create an issue requesting the creation of a gitter.im link? Thanks.

**Comment by gauteh** [comment]
is it possible to specify the destination path? so that I don't need to
have exactly the same directory structure locally as on drive? then I
can push from several directories into the same drive directory.

**Comment by gauteh** [comment]
it seems my question is already answered in #35!

Gaute Hope writes on December 21, 2015 19:02:
> is it possible to specify the destination path? so that I don't need to
> have exactly the same directory structure locally as on drive? then I
> can push from several directories into the same drive directory.
> 
>

**Comment by gauteh** [comment]
hm, it seems that this works by creating symlinks? so that if I have
sub-dirs that are present in both they cannot be merged, is there a way
around that?


Gaute Hope writes on December 21, 2015 19:10:
> it seems my question is already answered in #35!
> 
> Gaute Hope writes on December 21, 2015 19:02:
>> is it possible to specify the destination path? so that I don't need to
>> have exactly the same directory structure locally as on drive? then I
>> can push from several directories into the same drive directory.
>> 
>> 
>

**Comment by gauteh** [comment]
Gaute Hope writes on December 21, 2015 21:02:
> hm, it seems that this works by creating symlinks? so that if I have
> sub-dirs that are present in both they cannot be merged, is there a way
> around that?
> 

I can get around this by initing my gdrive to a fresh dir, then creating
an empty top-level dir and use `-m` to mirror the whole struture there.

This feels fairly backwards, is it possible to specify the remote path
so that when pushing it translates the local path to the destination
path for all checks and pushes? Does this mean that the drivedb have to
be ignored?

**Comment by odeke-em** [comment]
My apologies, but I don't seem to understand your concern -- have you actually tried this out and it failed? Symlink following is already in.

```
I can get around this by initing my gdrive to a fresh dir, then creating
an empty top-level dir and use `-m` to mirror the whole struture there.

This feels fairly backwards, is it possible to specify the remote path
so that when pushing it translates the local path to the destination
path for all checks and pushes? Does this mean that the drivedb have to
be ignored?
```
Please give me an example of what you mean because unfortunately I don't follow what you are saying.

**Comment by gauteh** [comment]
Emmanuel T Odeke writes on December 22, 2015 10:01:
> My apologies, but I don't seem to understand your concern -- have you actually tried this out and it failed? Symlink following is already in.
>
> ```
> I can get around this by initing my gdrive to a fresh dir, then creating
> an empty top-level dir and use `-m` to mirror the whole struture there.
>
> This feels fairly backwards, is it possible to specify the remote path
> so that when pushing it translates the local path to the destination
> path for all checks and pushes? Does this mean that the drivedb have to
> be ignored?
> ```
> Please give me an example of what you mean because unfortunately I don't follow what you are saying.
>

I have two local folders that I want to push to the same folder on
drive:

  ~/A and ~/tmp/mnt/A

they should both be pushed to A on drive. The folders contain image
archives sorted by year so there are a bunch of folders like 2009, 2010,
2011 in _both_, however only some of the sub-folders like:
~/A/2009/2009-01-01 are present in both.

~/A is already pushed and is fully synced to drive, now I want to push
the rest of the stuff from ~/tmp/mnt/A and I tried to do (case 1)

```
cd ~
drive push -m -no-clobber ~/tmp/mnt/A/* A
```

this results in all top-level sub-dirs, like 2007, 2008 etc that are not
already present in ~/A are mirrored (via symlinks). However, there is
already a folder called 2009 so there is no room for a new symlink. The
changes from ~/tmp/mnt/A is therefore ignored. I imagine the same would
happen if I had conflicting files.

In order to avoid this I set up a fresh empty local copy of A
(equivalent of 'content' in the other issue) (case 2):

```
cd ~
drive deinit
cd tmp
mkdir gd
cd gd
drive init
mkdir A
drive push -no-clobber A
drive push -m -no-clobber ~/tmp/mnt/A/* A
```

this seems to work.

I would expect to be able to do:
```
drive push -m -no-clobber ~/tmp/mnt/A A # with no trailing '/*' on the source
```

in both cases.

so that the ~/tmp/mnt/A dir could be pushed to drive:A as if it was
located at the root of drive. If I wished to push ~/tmp/mnt/A to
drive:tmp/mnt/A I should just do it without the '-m' flag.

regards, Gaute

**Comment by odeke-em** [comment]
Have you tried this?
```shell
$ drive push -m -no-clobber ~/tmp/mnt/A .
```

**Comment by odeke-em** [comment]
The syntax for this command could maybe be better explained.
The head of each mounted path is used as the remote anchor point to the specified single remote directory
e.g
```shell
$ drive push -m ~/tmp/mnt/A/* A
```
translates to
push sub-children of ~/tmp/mnt/A/* as sub-children of A(whose current location relative to root "/" is /A -- it could be anywhere)
so if ~/tmp/mnt/A/* ==> ~/tmp/mnt/A/B ~/tmp/mnt/A/C ~/tmp/mnt/A/D
the remote anchor points created will be /A/B /A/C /A/D

The reason why the difficulty arose is because the usage of "." hadn't been mentioned. "." in drive will translate to the current working directory which will then be resolved relative to root
so
```shell
$ drive push -m -no-clobber ~/tmp/mnt/A .
```

will be pouring the contents of A into /A
so that'll give you /A/B /A/C /A/D and this should then achieve your goal.

Please let me know if this makes sense. Your use case could be a great entry into the wiki to show other users how to use `--m`

**Comment by gauteh** [comment]
Emmanuel T Odeke writes on December 22, 2015 10:19:
> Have you tried this?
> ```shell
> $ drive push -m -no-clobber ~/tmp/mnt/A .
> ```

From ~, this does not work because there is already a directory named ~/A (with fragments of the data).

(note ~/tmp/mnt/A is a mounted network drive, but it could also be a USB
drive).

**Comment by odeke-em** [comment]
Actually you have to run the command inside the path you'd like.
x := ~/tmp/mnt/A could be anything, it could be ~/Desktop/A/B/C/D/F. You choose what directory it should be and that directory or file should exist but overall the above command should accomplish your goal.

**Comment by odeke-em** [comment]
Please don't run drive commands outside of your mounted directory. The behavior is always intended for paths relative to root, otherwise results could be undefined.

**Comment by gauteh** [comment]
It is inside the root. If I run it from inside ~/A it just create a new symlink: ~/A/A and tries to push everything there.

**Comment by odeke-em** [comment]
Are you saying that the existance of a path 'A' if 'A' is the destination fails to push?
`
It is inside the root. If I run it from inside ~/A it just create a new symlink: ~/A/A and tries to push everything there.
`
If you are trying to push everything to the top level of ~/A, please do it at the level above, don't do it within A otherwise you are repeating what your previous commands, but now instead of above A ie ~/, you are re-doing them inside ~/A.

How about let's just start afresh?
```
$ cd <your_mounted_path/whatever_relative_to_it> # e.g cd ~/school_account/tests/A
$ drive push -m <not_in_root_paths> . # e.g drive push -m ~/Desktop/photos ~/tmp/mnt/A ~/tmp/mnt/B .
```

**Comment by gauteh** [comment]
My drive was initialized to `~` so `~/tmp/mnt/A` was inside before, is this a problem?

This is starting to go pretty slow, so testing takes a little longer, would not your above commands just create the sub-dirs:
~/school_account/tests/A/{photos,A,B} ? and if they already exist it would not work (since symlinks can't be created)?

**Comment by odeke-em** [comment]
The whole of ~ ?, nesting symlinks within symlinks is not a great thing and in fact at some points even during an ls, you will get an error like "traversing too many levels" of symlinks.


`drive init` takes an argument for the path on the file system to "mount" your root "/". If none is passed, it will use the current working directory.

Next time you can actually choose where to init from e.g
```shell
$ drive init ~/Desktop/GoogleDrive/educationAccounts/uniDrive
```
or even
```shell
$ drive init ~/myDrives/jack.bauer@gmail.com
```

**Comment by gauteh** [comment]
I am not pushing the whole ~, only parts of it. But I have a folder ~/A locally that I have already pushed, and now I have mounted a network drive with the rest of the stuff that would have been there if I had lots of disk space locally. I want to push it into drive/A.

It would probably have worked if not some of the sub-dirs in A exists both places, so when both 2009 exists in ~/A and ~/tmp/mnt/A drive fails to create the symlink ~/A/2009 since there is already a regular 2009 directory there. The content of ~/A/2009 and  ~/tmp/mnt/A/2009 is not the same.

I have initied to a different directory now, with a blank A folder. None of the sources are below this mount path. This seems to work since the symlinks are removed between the pushes (I do them sequentially).

**Comment by gauteh** [comment]
Last paragraph; if the init directory is empty I can do something similar to your command:

```
mkdir -p tmp/gd
cd tmp/gd
drive init
# A already exists remotely
drive push -m -no-clobber  ~/tmp/mnt/A .
drive push -m -no-clobber ~/A .
```

**Comment by odeke-em** [comment]
So this resolves your issue?

**Comment by gauteh** [comment]
Yes, it is a work-around, but in particular the use of symlinks to 'merge' sources to one drive is confusing. Since if a sub-dir already exists it will silently not push anything from the second source.

**Comment by odeke-em** [comment]
Ah I see. I however, don't think that's a problem at all because it boils down to how drive works -- no need to push anything that doesn't need a push. In the future you could manually do the symlink or manual data copy to that directory and use a plain `drive push`, also nesting symlinks could get ugly really easily :)

**Comment by gauteh** [comment]
Yes, it does need a push though, because the contents of the sub-dir are not the same, there are more sub-sub-folders that need to be pushed (or there might be a newer/better version of a file).

I am not really advocating nesting symlinks, the best would probably be to do the translation in drive without symlinking at all. :)

**Comment by odeke-em** [comment]
Sounds like a plan, we are always open to new ideas. Please feel free to make a PR or a proposal explaining how it would work. If this has confused one user, most likely it will confuse another user in the future at some point so I have no objection to changing how things work as long as it is well explained and understood.
