### ISSUE TITLE
context.go:250: function ends without a return statement

### ISSUE THREAD

**Issue by orena1** [odeke-em/drive#52]
Hi ,
I am trying to "install" drive, but I get this error...
```
root@debian-amd64:/home/user# go get -u github.com/odeke-em/drive/cmd/drive
# golang.org/x/net/context
/usr/lib/go/src/pkg/golang.org/x/net/context/context.go:250: function ends without a return statement
```

**Comment by odeke-em** [comment]
Sure you are running at least go1.2?

**Comment by orena1** [comment]
Hi,
Sorry my bad.. I was using an old version. ( the one that you get from apt-get install golang)
I compiled it from source and it is now working...

**Comment by odeke-em** [comment]
No worries, good to know it is working.
