### ISSUE TITLE
Add Md5sum to -long list output

### ISSUE THREAD

**Issue by ganpati** [odeke-em/drive#520]
It was very slow to do a 'drive stat' on the output of the 'drive list -long' output (awk $9) to obtain the md5 checksums...I saw in list.go that the Md5Checksum is readily available to print, and added it to the output of the pretty() function. It might be a useful addition with a suitable fmt command line option to maintain backward compatibility.

Quick hacky diff below:

diff --git a/src/list.go b/src/list.go
index 1970980..82b2c2f 100644
--- a/src/list.go
+++ b/src/list.go
@@ -337,7 +337,7 @@ func (f *File) pretty(logy *log.Logger, opt attribute) {
        }

        if !opt.minimal {
-               logy.Logf(" %-10s\t%-10s\t\t%-20s\t%-50s\n", prettyBytes(f.Size), f.Id, f.ModTime, fmtdPath)
+               logy.Logf(" %-10s\t%-10s\t%32s\t%-20s\t%-50s\n", prettyBytes(f.Size), f.Id, f.Md5Checksum, f.ModTime, fmtdPath)
        } else {
                logy.Logln()
        }

**Comment by odeke-em** [comment]
Hello @ganpati thanks for reporting this and welcome to drive.

There already exists a command for this.
```shell
$ drive md5sum
```
which is documented in the README here https://github.com/odeke-em/drive#retrieving-md5-checksums

**Comment by odeke-em** [comment]
Please pass in depth -1(to traverse as deep) or something greater than 1 to get results, so
```shell
$ drive md5sum --depth 2 vines
94dfc22698b03c804f79f3651dbcad3b  01077DE7891216242798157029376_320b17c44c9.3.3.16169349501424709165 (4).mp4
b73283934e0f00c67da1cc8bf7438d9c  01077DE7891216242798157029376_320b17c44c9.3.3.16169349501424709165.mp4
fa795a18a8abaf856b806bad9f7bd4fa  0A6B18AF271236879747691458560_30fb27b3999.4.3.10466620851656897150.mp4
9c6e1633c5d1316ef4cf76cf9fc4a52a  11676578_948334911876726_1747435426_n.mp4
bbab3d888a93a6c67887aec69f5b13c1  11719644_864235483656598_1573980006_n.mp4
90daed5e8c626eac859b0f0c9986de60  11766384_863683177050240_1872236128_n.mp4
911f607d317da580f28cdf4b45d71069  11785418_111175192564754_375509053_n.mp4
```

**Comment by odeke-em** [comment]
Your request already exists. Closing this issue. Thanks for reporting it.
