### ISSUE TITLE
Multiple account support

### ISSUE THREAD

**Issue by powerunlimited** [odeke-em/drive#521]
It would be useful if a user had multiple accounts, say work/personal and would like to transfer files between each other

**Comment by odeke-em** [comment]
Hello again @powerunlimited. A user once requested this, please take a look at this https://github.com/odeke-em/drive/issues/362. Unfortunately an exam swamped and can't explain a lot, but that issue should have the remedy. Thanks.

**Comment by powerunlimited** [comment]
Oops my bad. Should haved searched more about this
Yes, the bash script should work perfectly, sorry for wasting your time.
Closing this now

**Comment by odeke-em** [comment]
Oh it is no biggie. I'll actually later on make a reference to it in the README since almost everyone asks for it.
