### ISSUE TITLE
Add a retry-count flag for push/pull failures

### ISSUE THREAD

**Issue by canpolat** [odeke-em/drive#529]
drive may fail during a push/pull operation (API error is a typical example as observed in #519). In such cases, it would be **nice to have** the option to set number of retries. This way, the user would have better control over failure conditions when scripting.

**Note:** This is a low priority feature request (for me at least).

**Comment by odeke-em** [comment]
Thanks!

**Comment by odeke-em** [comment]
Thank you @canpolat for this feature request. Implemented by https://github.com/odeke-em/drive/pull/634. Please get the latest from master.
