### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by onetigr** [odeke-em/drive#531]
root@srv0:~# go get -u github.com/odeke-em/drive/cmd/drive
\# github.com/odeke-em/semalim
gopath/src/github.com/odeke-em/semalim/semalim.go:84: syntax error: unexpected range, expecting {
gopath/src/github.com/odeke-em/semalim/semalim.go:92: syntax error: unexpected (, expecting semicolon or newline
gopath/src/github.com/odeke-em/semalim/semalim.go:94: non-declaration statement outside function body
gopath/src/github.com/odeke-em/semalim/semalim.go:95: syntax error: unexpected }
root@srv0:~#

**Comment by odeke-em** [comment]
Hello there @onetigr, thanks for reporting this and welcome to drive!

Would you mind mentioning what OS you are on, go version and other information that could be useful to reproduce this?

**Comment by onetigr** [comment]
debian 8.2

**Comment by odeke-em** [comment]
Go version? `uname -a`?

**Comment by onetigr** [comment]
root@srv0:~# go version
go version go1.3.3 linux/amd64
root@srv0:~# uname -a
Linux srv0 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
root@srv0:~#

**Comment by odeke-em** [comment]
Please re-run the `go get -u`, I've fixed this in an external package with commit https://github.com/odeke-em/semalim/commit/637f9719b4ca40f719b12c40fbec72e95021e3e3.

**Comment by onetigr** [comment]
now it compiled well.
Thank you very much for your help, and for your tool at all!

**Comment by odeke-em** [comment]
Awesome! Thank you for the kind words and for reporting this. Have a good one and enjoy, cheers!
