### ISSUE TITLE
provide a command for just getting fileId

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/drive#533]
In relation to @canoplat's comment here https://github.com/odeke-em/drive/issues/530#issuecomment-167234978 where he had to link to StackOverflow and use the Google Drie UI, it might be beneficial for drive to have a command to just solely list fileIds outside of stat or list calls.
```shell
$ drive list --long [paths...]
```
can already cut the deal but by the time a frequent user hasn't discovered this shows that there is a need to make this a more visible command so that users won't have to stress opening and copying fileIds.

**Comment by canpolat** [comment]
@odeke-em, thank you for the feature.

I'm a frequent (daily) user, but I cannot say I use (or even know) many features of `drive`. I basically have a working flow where all `drive` commands are hidden in scripts, and I only occasionally use `drive` manually. So, please don't consider me as a power user for `drive` :)

I have been thinking about contributing to the documentation recently, but unfortunately could not find the time. Maybe doing so will help me use more advanced features and provide better support when I stumble upon questions here ;) It's in my TODO list. But we will see when I can have a look at it.

**Comment by odeke-em** [comment]
Thank you thank you @canpolat. No worries, that power usage is gonna come through soon. I appreciate the contributions  and ideas👏🏾.
Aha I know why it showed up in your inbox, when making release notes for @canpolat last Sunday, I fixed a mis-spelling of your Github handle in an issue so I guess that's when Github pinged you.
