### ISSUE TITLE
release tags are confusing me

### ISSUE THREAD

**Issue by l3iggs** [odeke-em/drive#54]
I see that c281591 was tagged as 0.0.7 (10 days ago), after which 6649a6c was tagged as 0.0.7-rc.1 (5 days ago), after which daa0e17 was tagged as 0.0.7-rc.2 (2 days ago). How can the 0.0.7 release come before its release candidates?

Maybe 0.0.7-rc.1 and 0.0.7-rc.2 should have been tagged as release candidates for 0.0.8?

**Comment by odeke-em** [comment]
@l3iggs thank you for bringing that to my attention, in deed that was me just making releases without thought and naming discipline. This will be corrected in a few hours when I get back home.

**Comment by l3iggs** [comment]
Awesome, thanks!
