### ISSUE TITLE
drive version reports 3.2 when built from external AUR package

### ISSUE THREAD

**Issue by colinkeenan** [odeke-em/drive#547]
I built drive from Arch AUR which currently downloads and builds from `https://github.com/odeke-em/drive/archive/v0.3.4.tar.gz`. The Arch package manager, pacman, reports drive version as 3.4, but `drive version` reports 3.2.

**Comment by odeke-em** [comment]
I don't maintain anything outside of this repo and the third party providers might be using stale versions. If you look at that file it was edited 18 days ago with commit https://github.com/odeke-em/drive/commit/d466c2b0fba63d95ba0ec950cd91f43d8013841d and even examining the content from the archive shows v0.3.4
<img width="765" alt="screen shot 2016-01-07 at 11 20 42 am" src="https://cloud.githubusercontent.com/assets/4898263/12178814/bd66965a-b530-11e5-9d00-dead581a02d8.png">

 so probably contact the third party builders, or build from source.

**Comment by colinkeenan** [comment]
The AUR just provides a PKGBUILD script which tells `makepkg` where to get the source and how to build it. In other words, this was built from the source. It was built from this file: 

`https://github.com/odeke-em/drive/archive/v0.3.4.tar.gz`

Which is the latest release. It is the release that you maintain here on github.com. I did not use `yaourt`. I built the package from source using `makepkg`.

Which file in `v0.3.4.tar.gz` would have the version info you show above?

**Comment by odeke-em** [comment]
Could it be a bug in the script? That is because the archive here on Github has had that code in for 18 days so unless the code is intercepted somehow I don't see how the version could change when using the latest release.
The file that always has the version is src/about.go.

**Comment by colinkeenan** [comment]
My `about.go` has the correct version listed same as you show above: 3.4. Nevertheless, what gets built from that reports itself as 3.2.

**Comment by colinkeenan** [comment]
OK. I figured out the problem. 

`which drive` reports `/home/colin/gopath/bin/drive` but of course, I want to run `/usr/bin/drive`. I'm not sure where the gopath version came from.

**Comment by colinkeenan** [comment]
`/usr/bin/drive version` correctly reports 3.4. I'll get this worked out. Thanks - not a bug.
