### ISSUE TITLE
Segfault when attempting to authorize Google account

### ISSUE THREAD

**Issue by shaansheikh** [odeke-em/drive#55]
When I attempt to run "drive init," the program Segmentation Faults

**Comment by odeke-em** [comment]
What version of drive? What OS? Any output?

**Comment by shaansheikh** [comment]
ok, so I managed to get the init command to work by running it several more times, but now "drive pull" is segfaulting.

drive version 0.0.7
Ubuntu 14.10 64-bit
It just says "Segmentation fault (core dumped)"
Installed by running "go get -u github.com/odeke-em/drive/cmd/drive"

**Comment by odeke-em** [comment]
I have been building drive both on a 32 and 64bit Ubuntu 14.10 machines for the last month using stable go releases. However, I have seen such behaviour when using my own go unstable/development version.
This is quite unusual, but let us try to debug this. What version of go are you using? Did you install from source?

**Comment by shaansheikh** [comment]
The "go version" command returns "go version xgcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1 linux/amd64"

I installed by running the "sudo apt-get install gccgo-go". While googling the issue, I discovered there are other compilers as well. Should I have used one of them instead?

**Comment by odeke-em** [comment]
Yap I'd recommend installing the versions provided by the official Golang downloads by following the instructions here https://golang.org/doc/install.

Once you've downloaded the version you want, it should be about a four step walkthrough e.g as seen in this screenshot from 
![screen shot 2015-01-31 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/4898263/5989949/6e2f7d30-a957-11e4-9590-148a4eb03e62.png)

**Comment by shaansheikh** [comment]
ok, so I installed [this](https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz) version of go. I am either getting a segfault, or the following crazy error

    unexpected fault address 0x7f33a5e0ecd4
    fatal error: fault
    [signal 0xb code=0x2 addr=0x7f33a5e0ecd4]
    
    goroutine 4 [running]:
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    	:0
    
    goroutine 1 [select]:
    code_google_com_p_goauth2_oauth.updateToken.pN41_code_google_com_p_goauth2_oauth.Transport
    	/home/shaan/go/src/code.google.com/p/goauth2/oauth/oauth.go:419
    code_google_com_p_goauth2_oauth.Refresh.pN41_code_google_com_p_goauth2_oauth.Transport
    	/home/shaan/go/src/code.google.com/p/goauth2/oauth/oauth.go:355
    code_google_com_p_goauth2_oauth.getAccessToken.pN41_code_google_com_p_goauth2_oauth.Transport
    	/home/shaan/go/src/code.google.com/p/goauth2/oauth/oauth.go:319
    code_google_com_p_goauth2_oauth.RoundTrip.pN41_code_google_com_p_goauth2_oauth.Transport
    	/home/shaan/go/src/code.google.com/p/goauth2/oauth/oauth.go:285
    github_com_odeke_em_google_api_go_client_drive_v2.Do.pN62_github_com_odeke_em_google_api_go_client_drive_v2.FilesGetCall
    	/home/shaan/go/src/github.com/odeke-em/google-api-go-client/drive/v2/drive-gen.go:3572
    github_com_odeke_em_drive_src.FindById.pN36_github_com_odeke_em_drive_src.Remote
    	/home/shaan/go/src/github.com/odeke-em/drive/src/remote.go:183
    github_com_odeke_em_drive_src.findByPath.pN36_github_com_odeke_em_drive_src.Remote
    	/home/shaan/go/src/github.com/odeke-em/drive/src/remote.go:191
    github_com_odeke_em_drive_src.FindByPath.pN36_github_com_odeke_em_drive_src.Remote
    	/home/shaan/go/src/github.com/odeke-em/drive/src/remote.go:202
    github_com_odeke_em_drive_src.changeListResolve.pN38_github_com_odeke_em_drive_src.Commands
    	/home/shaan/go/src/github.com/odeke-em/drive/src/changes.go:86
    github_com_odeke_em_drive_src.Pull.pN38_github_com_odeke_em_drive_src.Commands
    	/home/shaan/go/src/github.com/odeke-em/drive/src/pull.go:39
    main.Run.pN12_main.pullCmd
    	/home/shaan/go/src/github.com/odeke-em/drive/cmd/drive/main.go:273
    github_com_rakyll_command.Run
    	/home/shaan/go/src/github.com/rakyll/command/command.go:155
    github_com_rakyll_command.ParseAndRun
    	/home/shaan/go/src/github.com/rakyll/command/command.go:162
    main.main
    	/home/shaan/go/src/github.com/odeke-em/drive/cmd/drive/main.go:62
    
    goroutine 3 [syscall]:
    	goroutine in C code; stack unavailable

**Comment by odeke-em** [comment]
Use go1.3.X which is more stable, it should be on the same downloads page.

**Comment by odeke-em** [comment]
Any progress on this?

**Comment by shaansheikh** [comment]
using 1.3.X didn't help. I gave up and just switched to grive instead :(. I'll try again next weekend if I have some free time

**Comment by odeke-em** [comment]
That sucks, too bad to hear about this. Your case is an outlier as I and a couple of other people have been able to install on their machines successfully multiple times: as mentioned I am able to build drive on various machines. If you think this might be an architecture bug, I'd recommend filling a bug with the go project. Hope you can get this resolved.

**Comment by odeke-em** [comment]
This is a Go installation problem hence closing it.
