### ISSUE TITLE
Export native google presentations at ppt and pptx dont work

### ISSUE THREAD

**Issue by mirohe** [odeke-em/drive#551]
Hello again,

I tried export an original "presentation document" of google at ppt or pptx with flag --export and doesn't work. This Create the folder but don't create the file.
Other native documents of google that's ok, such as doc, docx (for google document), xlsx, xls (for google spreadsheet) and pdf, jpg, also.

I am to use drive version 0.3.4

Best regards

**Comment by odeke-em** [comment]
Hello @mirohe thanks for reporting this. I am luckily at my computer on a break and can patch this real quick. Looks to me like a bad mimeType is in for pptx. PR coming up in a few.

**Comment by odeke-em** [comment]
Please get the latest from master, addressed by https://github.com/odeke-em/drive/pull/559.
Thanks for reporting this issue!

**Comment by mirohe** [comment]
Hello Odeke,

I tried install the last version with:

> go get -u github.com/odeke-em/drive/cmd/drive

but the generated binary "drive" has the same version 0.3.4 that l have now.
however the binary isn't the same (check with "diff").
I checked in me local files that the file "misc.go"and has the changes maked.

I don't know that I am making bad.
Could you help me?

**Comment by odeke-em** [comment]
For sure, instead please run
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
It is also detailed here why you should run the drive-gen https://github.com/odeke-em/drive#installation under "Otherwise..."

**Comment by mirohe** [comment]
Hello

That's ok, but there is a problem. if export in ppt the native file google drive don't work never, and if export in pptx any "presentation", one times export correctly and others times not.
This doesn't happen in other document types. (docx document always work ok).
Here you go a real example:

$ miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
Exported '/home/miguel.rodriguez/google_drive/hola caracola' to '/home/miguel.rodriguez/google_drive/hola caracola_exports/hola caracola.pptx'
EXPORT DOCUMENT OK

$miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
FAILURE TO EXPORT DOCUMENT

$ miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
FAILURE TO EXPORT DOCUMENT

$ miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
Exported '/home/miguel.rodriguez/google_drive/hola caracola' to '/home/miguel.rodriguez/google_drive/hola caracola_exports/hola caracola.pptx'
EXPORT DOCUMENT OK

$ miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
FAILURE TO EXPORT DOCUMENT

$ miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
Exported '/home/miguel.rodriguez/google_drive/hola caracola' to '/home/miguel.rodriguez/google_drive/hola caracola_exports/hola caracola.pptx'
EXPORT DOCUMENT OK
 
 This is very rare

Best regard

**Comment by odeke-em** [comment]
Thanks for the report @mirohe, that's a curious case. So for starters, you don't have to always `--force`, you can `--explicitly-export`. Please see https://github.com/odeke-em/drive#exporting-docs.

**Comment by mirohe** [comment]
I always use --force but i needed to see the result in screen. 
Use --force or not, the result is the same.
I have tried with --exports-dir and --explicitly-export and have same problem but only with pptx.
This problem is specific of ppt's. I don't understand. This is very rare rare rare.

If I can help you something ..... you tell me.
