### ISSUE TITLE
Pushing a lot of files results in "too many open files"

### ISSUE THREAD

**Issue by anthem** [odeke-em/drive#552]
I tried to push a large set of files (photos) all at once (over 25,000). After uploading about 30MB, I got an unending list of "too many open files" errors.

**Comment by Catofes** [comment]
Same bug here. 
https://paste.catofes.com/index.php/3e38T/

Seems it was caused by fd limit.

**Comment by odeke-em** [comment]
Hello @anthem and @Catofes, thank you both for the report and welcome to drive!

Yes this is a common problem that happens for many programs. I guess the best that drive could do would be to semaphore limit the number of files that can be open. However, that's quite a bit of specialized work that I haven't yet seen in other programs. It can be done but I can't make promises as am quite low on time for now. However, I'll accept PRs.

**Comment by odeke-em** [comment]
Unfortunately this is a problem out of our control unless we did a lot of work for tracking the number of open files, but that creates a lot of complexity. You can always change your ulimit quota http://tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/x4733.html.
