### ISSUE TITLE
"drive ls" show names with a space in the end

### ISSUE THREAD

**Issue by darthcoli** [odeke-em/drive#557]
Hello. When run "drive ls" all results have an space at the end of the string. Its a minor bug, but is very dificult to parse/treat them. 

My version is the 0.3.4

**Comment by odeke-em** [comment]
Hello @darthcoli, thank you for reporting this. I can confirm that your report is correct.

**Comment by odeke-em** [comment]
Also my apologies for the really late reply, I have been swamped.
