### ISSUE TITLE
Can't disable notification mail

### ISSUE THREAD

**Issue by HontoNoRoger** [odeke-em/drive#558]
I'm trying to change a file's owner without notifying the new owner of the change.

`drive share -emails user@example.com -notify -role owner -type user 'important_file.txt'`

The help says:
```
  -notify
    	toggle whether to notify recipients about share (default true)
```

So am I guessing right, that adding `-notify` should DISABLE the notification mail and removing it should re-enable the notification mail?
I've tried with and without the parameter, the notification mail is sent every time. I even tried `-notify no` and `-notify false` without success. Adding an argument to the parameter just causes drive to share the file with default options i.e. role = reader and type = user.

**Comment by odeke-em** [comment]
Hey there @HontoNoRoger, welcome to drive and thanks for the question.

To disable it, use `notify=false`.

**Comment by HontoNoRoger** [comment]
Ahhh thanks, sorry for filing that an issue. Wasn't familiar with Go's boolean parameter stuff.

**Comment by odeke-em** [comment]
It is no biggie at all, I too at first thought passing in the non-default would turn it off :) Someday in the future, maybe Go will have this.
