### ISSUE TITLE
Push creating a new copy of the file and folders each time I push

### ISSUE THREAD

**Issue by graemerobb** [odeke-em/drive#56]
Tested against 0.0.8rc2
$ cat hello_world > a file
$ drive push a_file
(pushes)
$ drive push a_file
(everythign is up to date

However, do the same with a Jpg in a different directory

$ drive push head.jpg
(pushes)
$ drive push head.jpg
(pushes again)

![image](https://cloud.githubusercontent.com/assets/5207236/6055104/cb55442e-ad4c-11e4-8ec6-caf49263c410.png)

UPDATE
multple copies of the folder structure and file have been created in the drive

**Comment by odeke-em** [comment]
Hello, thanks for the detailed report. For starts so far I cannot reproduce that, please see below
![screen shot 2015-02-04 at 9 42 19 pm](https://cloud.githubusercontent.com/assets/4898263/6055156/d0294db0-acb6-11e4-89da-90953ba2ef48.png)
However I will give you credit for finding an edge case that I have encountered before in which Google Drive for some reason kept changing the modified times ( I could be wrong but I did an investigation of it and it seemed that the file was undergoing conversion during the period right after upload or so, plus it was open for some reason).
To further investigate this would you mind stating the file before and after upload like this
```shell
$ drive stat head2.jpg
```
Thank you.

**Comment by odeke-em** [comment]
Just the ModTime and MimeType after stat-ing are sufficient.

**Comment by graemerobb** [comment]
Hi, I have modified the title to be more accurate. Doing some more testing and the issue seems to be that each time I push it creates a new copy.

**Comment by graemerobb** [comment]
Screenshots below.
Summary
push (pushes)
stat (says doesnt exist, but it does, under a new copy of the whole folder structure)
push (pushes and creates a 2nd copy)


![image](https://cloud.githubusercontent.com/assets/5207236/6055309/839cb960-ad50-11e4-9a10-587471e7c819.png)

![image](https://cloud.githubusercontent.com/assets/5207236/6055315/979f1d22-ad50-11e4-8fbb-bd20d7e9d266.png)

**Comment by odeke-em** [comment]
Sorry Graeme but I have tried an alternative way of pushing which would be a multi nested directory that has never been pushed up and then pushing from inside it but still cannot reproduce it. 
![screen shot 2015-02-04 at 10 02 19 pm](https://cloud.githubusercontent.com/assets/4898263/6055323/df6b6576-acb9-11e4-96dc-fb8b5e361cd4.png)

Off the top of my head I cannot speculate why but let's try something a little different:
Just make sure that your Google Golang API client is upto date by:
```shell
$ cd $GOPATH/src/github.com/odeke-em/google-api-go-client
$ git pull origin master
```
Get the latest
```shell
$ go get -u github.com/odeke-em/drive/cmd/drive
```
And let me know what the output is.

**Comment by odeke-em** [comment]
Another thing off the top of my head that might be related to the original path, would you mind recreating a test directory that isn't shared and repeating that test in there? If you can't reproduce you then I have a start off point for investigation.

**Comment by graemerobb** [comment]
Is it because I have a push already running in a parallel process?

**Comment by odeke-em** [comment]
Quite plausible but did you try the last three remedies I recommended? That is just so that we can eliminate variables.

**Comment by graemerobb** [comment]
Software was up to date.
Create a new folder "TestPhotoSync"
drive push TestPhotoSync/ProfilePics/head2.jpg
(pushed, created two TestPhotoSync folders, the new one containing the new file)
drive stat TestPhotoSync/ProfilePics/head2.jpg
/TestPhotoSync/ProfilePics/head2.jpg: remote path doesn't exist

**Comment by odeke-em** [comment]
So not running almost equivalent parallel uploads and your drive version is at v0.0.8a and this persists, right? If it possible and not a private one, please send me the subject file so that I can try investigating.

**Comment by graemerobb** [comment]
the parallel process will finish soon and I will retest. Feeling confident that it is the issue.

**Comment by odeke-em** [comment]
Cool. A parallel upload in the worst case would mean that the folder is not found at the exact time by more than one uploader and then created by each worker at the same instant. This would be the equivalent of someone/people creating the files/folders with the same names and repeating the working. If it is the parallel upload, I think this issue https://github.com/odeke-em/drive/issues/2 also mentioned in the README might be relevant.

**Comment by graemerobb** [comment]
Re-tested without the parallel upload. Problem still exists.
before:
![image](https://cloud.githubusercontent.com/assets/5207236/6070297/75fb21cc-addf-11e4-9241-11413d2e6097.png)
(TestPhotoSync is empty)

pushed a file into that directory
![image](https://cloud.githubusercontent.com/assets/5207236/6070330/a4f2bf44-addf-11e4-8bcd-744d400acf45.png)

result is now 2 TestPhotoSync folders
![image](https://cloud.githubusercontent.com/assets/5207236/6070346/be02522e-addf-11e4-9a24-2829beac08e6.png)

**Comment by odeke-em** [comment]
Thank you Graeme for your patience and kuddos for the walk through. This finally got me to find out the cause of the problem, and I'll probably implement the solution over the weekend.

**Comment by graemerobb** [comment]
Great! What did you have to change at your end to reproduce it?

**Comment by odeke-em** [comment]
So I had to toggle a resource race since files are uploaded concurrently. Basically make a local dir, then inside it, make a couple of levels deep of nesting, and throw in two files in divergent paths eg. example/p1/p2/p3/here.txt and example/p1/p2/p4/there
txt where example doesn't exist on the cloud yet. The remedy for this is to make sure the common dir exists before each parallel upload tries to create the entire path. I had to further speed things up in order to reproduce it.

**Comment by tomtor** [comment]
I have a related issue with 0.0.9:

```
Modification count 6299 src: 3.15GB dest: 3.15GB
y\ ceed with the changes? [Y/n]:  – 
1834 / 6299 [==============>----------------------------------] 29.12 % 2h16m33s/scans/1994-Kos/crop0086.jpg: googleapi: Error 401: Invalid Credentials, authError
1835 / 6299 [==============>----------------------------------] 29.13 % 2h16m29s/scans/1994-Kos/crop0022.jpg: googleapi: Error 401: Invalid Credentials, authErr1836 / 6299 [==============>----------------------------------] 29.15 % 2h16m24s/scans/1994-Kos/crop0134.jpg: googleapi: Error 401: Invalid Credentials, authErr1837 / 6299 [==============>----------------------------------] 29.16 % 2h16m18s3044 / 6299 [=======================>-------------------------] 48.33 % 1h49m49s^Ctom@swan:/media/scratch/backup/gdrive$
```

Each error results in a minimal duplicated folder structure:

scan/1994-Kos/afile.jpg

scan/1994-Kos/anotherfile.jpg

**Comment by odeke-em** [comment]
@graemerobb @tomtor please see PR #67

**Comment by tomtor** [comment]
@odeke-em I did a large push and this problem is fixed for me! Thanks!

No big issue for me, but #38 is still present.
