### ISSUE TITLE
Push filtering

### ISSUE THREAD

**Issue by wernight** [odeke-em/drive#561]
drive seems very useful to perform back-ups.

For that, having the option to include/exclude files by either regex or kind of `.gitignore` (`rsync` has that too) is a must-have.

**Comment by odeke-em** [comment]
Hello @wernight thanks for reporting this and welcome to drive.

drive already has this in please see the README https://github.com/odeke-em/drive/blob/master/README.md#driveignore.

**Comment by wernight** [comment]
Ah nice! I missed that completely. May be a link to that section from commands that use it (e.g. [from `push`](https://github.com/odeke-em/drive/blob/master/README.md#pushing))

**Comment by odeke-em** [comment]
Well it applies to pull, push and other commands. Feel free to make a PR and we'll see.

**Comment by odeke-em** [comment]
Fixed by https://github.com/odeke-em/drive/pull/576. Thank you for the PR as well as for raising this.
