### ISSUE TITLE
How do I reconnect gdrive to my account if I disconnected it once?

### ISSUE THREAD

**Issue by elitecoder** [odeke-em/drive#569]
I was having some issues with sharing my uploaded directories. So I tried disconnecting and reconnect.
Unfortunately, after disconnecting, drive is just failing with 

```
Mukul-Sharma-MBP15:Downloads msharma1$ ./drive list
googleapi: Error 401: Invalid Credentials, authError
```

Is there any way to wipe all settings are reconnect?

**Comment by odeke-em** [comment]
Hello @elitecoder! Thanks for the question and welcome to drive.

My apologies for the late reply.

So you can `drive deinit` https://github.com/odeke-em/drive#de-initializing and then `drive init` https://github.com/odeke-em/drive#initializing, or anytime you wanna remove an account association, you can just go into the root of the mounted directory and remove .gd so `rm -rf .gd`. Also for better security, don't forget to revoke unwanted access to your account https://github.com/odeke-em/drive#revoking-account-access.

Hope this helps.

**Comment by elitecoder** [comment]
Thanks Emmanuel!! Although I am using a binary for v1.9.0 and de-init isn't an available option.

Although, deleting my drive binary and installing a new one apparently reset the creds and I was able to connect again.

FYI: I am running Mac OSX 10.11

You can close this case since I was able to connect again, I'll open a separate issue for the original problem which got me on this road.

**Comment by odeke-em** [comment]
Ah I see. I'd recommend getting the latest though v1.9.0 was 8 months ago and a lot changed.

**Comment by elitecoder** [comment]
I did try. I ran `go get -u github.com/odeke-em/drive/cmd/drive` as well as `go get -u github.com/odeke-em/drive/drive-google`

Both of these commands finished correctly without any errors, but I have no idea where they install `drive` if at all.

**Comment by elitecoder** [comment]
Never mind, did a find / -name drive and found it in my $GOPATH.

Would be useful to add this info to the README section for newbs like me. :-)
