### ISSUE TITLE
What Addition/Modification/Deletion count means

### ISSUE THREAD

**Issue by chfakht** [odeke-em/drive#574]
Hi , this is the first time i'm using drive with ubuntu
I have a folder called DriveStorage located on another partition and i have 4 Gb of data on it
So I have enter to this directory and run drive init (so it's not an empty directory , it have been synchronized from windows 7)
And when i run drive pull : i get those changes 
```
Addition count 17 src: 3.58MB
Modification count 1287 src: 928.84MB dest: 928.78MB
Deletion count 141 dest: 15.68MB
Proceed with the changes? [Y/n]:
```

 Can someone tell me what every line means ?
Also is it possible to synchronize an non empty folder ? (like in my case : what i have already describe) 
Thanks a lot.

**Comment by canpolat** [comment]
>Addition count 17 src: 3.58MB

Number of files (and their total size) that is available on your local folder but not on Google Drive. These will be uploaded to Google Drive.

>Modification count 1287 src: 928.84MB dest: 928.78MB

Number of files (and their total size) that are on your local folder that matches some files on Google Drive but are not identical (modified). These files will replace (overwrite) the files that are already in Google Drive.

>Deletion count 141 dest: 15.68MB

Number of files (and their total size) that are on Google Drive but not on your local folder. These files will be DELETED from Google Drive.

> Also is it possible to synchronize an non empty folder?

It is possible to sync non-empty folders. In this example you are already doing it. But apparently your local folder and Google Drive are not 100% in sync.

**Comment by chfakht** [comment]
@canpolat Thanks a lot but waiit:

> These files will replace (overwrite) the files that are already in Google Drive.

You are seing that the files will be replaced not synchronized ? right ? , so a manual upload of the new files will be much easier.

**Comment by canpolat** [comment]
@chfakht actually I don't know if it uploads the whole file or the diff. If you mean a two way synchronization, yes, there is a difference: `push` will only send the files from the local directory to Google Drive and `pull` will only fetch the files from Google Drive to local directory. So, you, as the user should decide which way you want to sync, **drive** will not do it for you.

**Comment by canpolat** [comment]
By the way: I just noticed that in my explanation of the lines above, I explained it as if you used the command `push`, but I see that you actually used `pull`. So let me correct it:

> Addition count 17 src: 3.58MB

Number of files (and their total size) that are on Google Drive but not on your local folder. These will be downloaded from Google Drive and added to your local directory.

> Modification count 1287 src: 928.84MB dest: 928.78MB

Number of files (and their total size) that are on your local folder that matches some files on Google Drive but are not identical (modified). The files in Google Drive will REPLACE (overwrite) the files in your local directory.

>  Deletion count 141 dest: 15.68MB

Number of files (and their total size) that is available on your local folder but not on Google Drive. These files will be DELETED from your local directory.

**Comment by chfakht** [comment]
Ok that's make sense i think that i will just run drive push wherever i want to upload my files ... the other commands are a lttle bit risky :+1:

**Comment by odeke-em** [comment]
Thank you @canpolat for getting that clarified, thank you @chfakht for the question. I'll close this issue since it seems resolved.

**Comment by meta-coder** [comment]
Why does it show remote file as modified even if the MD5 checksums of the remote file and local file match?
If I do 
$ drive push file1.pdf
$ drive pub file1.pdf
$ drive pull
It shows remote file1.pdf as modified.
(drive version: 0.3.9, drive_linux binary)
