### ISSUE TITLE
Files starting with a dot not taken into account

### ISSUE THREAD

**Issue by flawyte** [odeke-em/drive#575]
Hi,

I have a folder on Google Drive with files named like `.<XXX>`, but there files aren't pulled when I run `drive pull`, and neither they are pushed when running `drive push .` when the current dir contains for example files like `.bashrc`.

How can I achieve that ? Is there some option that I've missed ?

Thanks

**Comment by odeke-em** [comment]
Hello @flawyte thank you for the question and welcome to drive!
So hidden files by default are ignored, though you can allow for them to be recognized by using flag `--hidden` e.g `drive push --hidden myFiles`
You can also find this out by running `drive push -h`

**Comment by flawyte** [comment]
It works! Thank you very much :)
