### ISSUE TITLE
Push/pull folders with different name/path on host?

### ISSUE THREAD

**Issue by aph3rson** [odeke-em/drive#579]
Let's say I have a folder on my local filesystem, `~/Documents/ABC 123/`, and a folder on Google Drive, `/Introduction to Spelling (ABC 123)/`.

Without renaming either folder, is there a way to push/pull between these two files? Right now, when trying to use drive on my local filesystem, I can only push to `/ABC 123`, which would be a new directory (and renaming the newly-pushed directory doesn't help).

**Comment by odeke-em** [comment]
Hello @aph3rson, thanks for the question and welcome to drive!

So for now there isn't a direct way of doing it, but:
a) I think making a symlink on your local file system could work.
## symlink solution -- I haven't tested this out
```shell
$ cd ~/myDrive
$ ln -s "Introduction to Spelling (ABC 123)" ~/Documents/ABC\ 123
$ cd "Introduction to Spelling (ABC 123)"
$ drive pull # To pull
$ drive push # To push
```
b) If you are talking about individual files, you can use `--piped` with drive pull/push

## pull piped only for files.
```shell
$ drive pull --piped "Introduction to Spelling (ABC 123)/consonants" > ~/Documents/ABC\ 123/lesson1.txt
```

## push piped only for files.
```shell
$ cat ~/Documents/ABC\ 123/lesson2.txt | drive push --piped --force "Introduction to Spelling (ABC 123)/vowels"
```

Please let me know if this helps. Also other folks please feel free to chime in with ideas.

**Comment by odeke-em** [comment]
This isn't supported by default unless by the hacks mentioned above. Closing this.

**Comment by wphsieh** [comment]
Hi @odeke-em 
Since I also need to push some folder to a folder with a specific name in google drive, the folder name is dynamic and generated using SHA1 or other encoding.
According to your response, is it because of the google api or we just need to find out where to modify.
thanks.
