### ISSUE TITLE
help! drive stopped showing file names in the terminal output...

### ISSUE THREAD

**Issue by Sadi58** [odeke-em/drive#581]
I've begun experimenting with this new google drive client.
Yesterday it was working as expected, displaying results like this:
```
Resolving...
- /File1.docx
- /File2.odt
+ /File3.xlsx
+ /File4.odt
Deletion count 2 dest: 41.56KB
Addition count 2 src: 224.77KB
272719 / 230163 [==================================================] 118.49 % 5s
```
But today it has stopped displaying names of files changed, displaying instead something like this:
```
Resolving...
0 / 43641 [------------------------------------------------------------------] 0.00 % 
43641 / 43641 [===========================================================] 100.00 % 0
43641 / 43641 [==========================================================] 100.00 % 1s
```
I wonder what's caused this...
Maybe somebody got fed up with my clumsy experiments trying to write a basic app indicator for ease of use ; -)

**Comment by canpolat** [comment]
Google API is quite unstable today, it could be due to that. I would suggest repeating the command manually to see if the problem persists.

**Comment by Sadi58** [comment]
@canpolat
Thanks, it looks OK today.

**Comment by Sadi58** [comment]
Damn, it's gone again; it seems I'll have to live without the list of changes in my log : -(

**Comment by canpolat** [comment]
Normally it's not this unstable. But be aware of the following issues to avoid surprises: #519 #480 #549

**Comment by Sadi58** [comment]
Hmmm, I might well be experiencing such issues as I'm also trying some script instead of a single one-liner command.

I've ended up using these two commands to minimize errors (and increase risks ; -) 

`drive push -no-prompt -ignore-name-clashes -ignore-conflict -ignore-checksum &> "$HOME/.config/indicator-drive/remote.log"`
`drive pull -no-prompt -ignore-name-clashes -ignore-conflict -ignore-checksum &> "$HOME/.config/indicator-drive/local.log"`

I think I'll wait for a while keep the present setup of [my amateur app indicator](https://github.com/odeke-em/drive/issues/582) (without getting a list of files change locally/remotely) and see how it goes...
