### ISSUE TITLE
Export native google presentations at ppt and pptx not work

### ISSUE THREAD

**Issue by mirohe** [odeke-em/drive#583]
I tried export an original "presentation document" of google at ppt or pptx with flag --export and --force and doesn't work correctly. one times export in pptx correctly and others times not. 
And ppt never export.

here you are one example that one times well an others not consecutively.

$ miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
Exported '/home/miguel.rodriguez/google_drive/hola caracola' to '/home/miguel.rodriguez/google_drive/hola caracola_exports/hola caracola.pptx'
EXPORT DOCUMENT OK

$miguel.rodriguez@portatil52:~/google_drive$ drive pull --force --export pptx "hola caracola"
Resolving...
/hola caracola
Addition count 1
Proceed with the changes? [Y/n]:
FAILURE TO EXPORT DOCUMENT

And the next time could export well or not.

Best regards

**Comment by canpolat** [comment]
Reported and fixed earlier: #551 

Have you updated your drive? If so, could you provide the version and build hash?

    go get -u github.com/odeke-em/drive/drive-gen && drive-gen

**Comment by mirohe** [comment]
Hello canpolat,

I have updated the my drive, but the problem persists as describe above.
This is the reason that reopen this thread.
one times the pptx is exported well and other times not, and the ppt export not work never.

**Comment by odeke-em** [comment]
Hello again @mirohe, would you mind providing the `drive version and build hash` just as @canpolat had requested? This is really helpful for debugging purposes.
@canpolat thank you!

**Comment by mirohe** [comment]
Hello @odeke-em here you are drive version and hash

> drive version
> drive version: 0.3.4
> Commit Hash: '263f0d5b48f90c22f0c0bddaf61cc845ee007162'
> Go Version: go1.4.2
> OS: linux/386
> BuildTime: 2016-02-11 14:06:58.148082274 +0100 CET

And if I run md5sum I get

> md5sum drive
> c310e4c5b105d88630ec493a77abdd08  drive

I hope this can help you

**Comment by odeke-em** [comment]
Thank you very much @mirohe for the patience. I can confirm that this is a bug. I have diagnosed the problem and the PR is coming up real quick. My apologies for closing the previous issue, next time please feel free to re-open the starting issue this way.

**Comment by odeke-em** [comment]
@mirohe the issue was auto-closed from a PR but I'll re-open and let you have the last say on it once your issue is closed. Thank you again! Also tip of the hat to @canpolat!

**Comment by mirohe** [comment]
Hello @odeke-em .
Thank you very very much.
Now pull export pptx always works. Congratulations and thanks. 
Only pull export ppt never works.
I don't know, but could be problem of google that not convert in ppt only?
I can work prefectly with pptx, but I mention the problem of ppt by if others users need.

Great work

**Comment by odeke-em** [comment]
Awesome, glad to know that that works :) Thank you for the kind words too.

So for ppt vs pptx, here are the mimeType listings
```json
    "ppt":    "application/vnd.ms-powerpoint",
    "pptx":   "application/vnd.openxmlformats-officedocument.presentationml.presentation"
```
as you'll see pptx is the only version exportable for now as the mimeType matches that in the ExportLinks for a presentation. Good point though, I'll keep an eye out and try to make a test for ppt and see if Google Sheets can convert it, if so then we'll see about adding a clause to match both ppt and pptx as the same. If you'd like, please feel free to make a wiki entry for this for now.

**Comment by mirohe** [comment]
Hello @odeke-em 
aahhhhh ok . I understand.
For my part all right.
If you need a beta tester I'm here XD
thank you very much again.

**Comment by odeke-em** [comment]
Dope! Good to know it works alright on your side. I'll go ahead then and close this issue. Please feel free to reopen if it persists.
