### ISSUE TITLE
adding "-ignore-contents" option to "drive diff"?

### ISSUE THREAD

**Issue by Sadi58** [odeke-em/drive#585]
Currently I see that the command `drive diff`compares the **contents** of files which are present on both sides but have different time stamps. It even displays the differences between text files.

However, I think it could be very useful for (at least some) users if we could choose **comparing time stamps only**, for example by adding another option like `-ignore-contents`.

**Comment by odeke-em** [comment]
Hello @Sadi58, thanks for this request and welcome to drive, if I hadn't yet welcomed you.
So I see, you are suggesting some sort of short mode, right?

**Comment by odeke-em** [comment]
@Sadi58 thank you again for the feature request, addressed by PR https://github.com/odeke-em/drive/pull/587. Please get the latest from master, if you might not already know, it can be done by
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
Please re-open if the problem persists.

**Comment by Sadi58** [comment]
Thanks a million!!!
I'm currently using the latest version at http://ppa.launchpad.net/twodopeshaggy/drive/ but will try this new feature as soon as I can switch to the git version or the ppa gets updated ( whichever comes first ;-)

**Comment by Sadi58** [comment]
Now that PPA has been updated I'm glad to report **_gratefully_** that this works like a charm! :-)
