### ISSUE TITLE
[Help&Support] Unsuccessful attempt at manual installation

### ISSUE THREAD

**Issue by Sadi58** [odeke-em/drive#589]
Having installed this Drive client from via its deb package, I tried the manual installation method today in order to try and use the latest version at github, but I wonder why I had the following error messages (under a Live session of Linux Mint 17 with gccgo package version 4.xx installed):

```
~ $ go get -u github.com/odeke-em/drive/cmd/drive
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory
~ $ go get github.com/odeke-em/drive/drive-gen && drive-gen
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory
~ $ go get -u github.com/odeke-em/drive/drive-google
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory
~ $ go get -u github.com/odeke-em/drive/drive-gen && drive-gen drive-google
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory

```

**Comment by aerth** [comment]
Try ``` go get -v -u github.com/odeke-em/drive/cmd/drive```

It looks like your $GOROOT is not set correctly. How did you install go?

**Comment by Sadi58** [comment]
I installed gccgo via Synaptic Package Manager. I set the &GOPATH but had nothing to do with $GOROOT (it should have been set during installation I guess).

**Comment by aerth** [comment]
Okay, I dont think drive uses gccgo at all though, that may have messed things up. I recommend re-installing Go, [1.6 just came out](https://blog.golang.org/go1.6). Not from package manager.

**Comment by Sadi58** [comment]
OK, thanks a lot; wrong installation of go seems to be the cause of this problem. I'll close as soon as I can confirm this.

**Comment by Sadi58** [comment]
@aerth I've downloaded and installed the latest go, but now I've got this error message:
```
~ $  go get -u github.com/odeke-em/drive/cmd/drive
# github.com/odeke-em/drive/src
.local/share/go/src/github.com/odeke-em/drive/src/tty.go:20:21: fatal error: termios.h: No such file or directory
 #include <termios.h>
                     ^
compilation terminated.
```
I think I'll give up on manual installation and wait for the deb package to be upgraded.

**Comment by chevillet** [comment]
I had strange issues with Go under Ubuntu (not far from Mint so) a couple months ago.
I ended up installing Go this way:

> bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
> gvm install go1.4
> gvm use go1.4
> gvm install go1.5.2
> gvm use go1.5.2 --default

More details on #502 if you want to give a shot.

**Comment by shaggytwodope** [comment]
@Sadi58 You say .deb file, do you mean the ppa package? (Maintainer for ppa)

I've been busy lately, but if there is any major commits here https://github.com/odeke-em/drive/compare/v0.3.4...master that address any big issues I can update the ppa if need be. Otherwise it reflects current stable release decided by @odeke-em.

**Comment by Sadi58** [comment]
@chevillet Thanks a lot. I like trying and learning new things, but I just don't have enough time and energy for this bumpy path of manual installation right now.

@shaggytwodope Thank you so much in deed. Yes, I mean the ppa package. I was just eager to test the new `drive diff --skip-content-check` feature which was kindly implemented upon my suggestion very recently. But nothing urgent, I can wait.

**Comment by odeke-em** [comment]
Thank you very much @Sadi58 for the question and everyone for helping resolve this. 
![goodstuff](https://cloud.githubusercontent.com/assets/4898263/13157802/b4b5fa1c-d63e-11e5-94ce-3f7e4b7ffbfa.gif)

Yap gccgo is trippy with go programs as mentioned by @aerth and by @chevillet building it is probably the best option
