### ISSUE TITLE
Broken all firefox into same jitsimeet session room

### ISSUE THREAD

**Issue by mirohe** [odeke-em/drive#590]
Hello,

The other day I was doing tests in a session jitsi meet with 15 users. Some used firefox and others used chromium or chrome.
In a few minutes all users that used chrome or chromium they had no problem, but all users that used firefox broke and suddenly it closed.
All times that this users used firefox in the session, it closes.

The enviroment of tests was:

Server used -> https://meet.jit.si/
Users desktops:
Ubuntu 14.04
Graphical Environement is Unity
Firefox -> 44.0
chrome -> between 44.0 to 48.0
chromium -> between 44.0 to 48.0

If someone needs that I do more tests, We are available. 
It is important for us.

Best regards

**Comment by chevillet** [comment]
Hi,
You should open an issue under a @jitsi repository: https://github.com/jitsi/
This one is related to drive.

**Comment by mirohe** [comment]
hello,

jajajajaja sorry. Someone can clear this?

thanks

**Comment by odeke-em** [comment]
Haha no worries, it happens. Closing this issue since it is irrelevant to drive.
