### ISSUE TITLE
Push file to different folder

### ISSUE THREAD

**Issue by Belingar** [odeke-em/drive#593]
Is it possible to push or copy file from machine to Google Drive to a different folder? Suppose I need to copy file which is stored in /home/data/test.txt to Cloud with folder name device1/testing/. I am only interested in copying files to cloud, not to sync between cloud and machine.

**Comment by odeke-em** [comment]
Hello @Belingar, thank you for the question and welcome to drive.

Oh yes, you can push a file to a different folder without it having to exist in that folder. There is an option `-m` which I call `mounted push`.
So for your use case
```shell
$ cd ~/myDrive
$ drive push -m $HOME/data/test.txt device1/testing
```
You can even do
```shell
$ drive push -m ~/Desktop/Photos ~/.bash* ~/Downloads/papers/2016 mountedCollection
```
I use it quite a lot myself.

Hope this helps.

**Comment by Belingar** [comment]
Thanks for the answer. I did what you suggested. When i upload terminal says "everything is up to date", but file was not uploaded.

**Comment by Belingar** [comment]
Looks like there is some other problem. If I run script as user it works, but if I run as root, it doesn't. How can I menage this to work with root?

**Comment by odeke-em** [comment]
Please run the program with the same permissions instead of root or please set the appropriate permissions and $GOPATH for root. Closing since original issue works as intended.
