### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by canpolat** [odeke-em/drive#594]
Hi @odeke-em,

I know there aren't many changes since the last release but do you think we could get a release anytime soon (within a couple of weeks)?

**Comment by odeke-em** [comment]
Hello @canpolat, thank you for the reminder. My apologies :) I will make a release as soon as I get back home in about 8 hours. Yeah there have been a couple of changes that other users have wanted. New release coming out of the oven in T-8.

**Comment by canpolat** [comment]
@odeke-em no need to apologize :) You are doing a great job maintaining **drive**, and we can always use the latest from master.

**Comment by shaggytwodope** [comment]
Commenting to remind myself to update packages when Lord @odeke-em does release. Can be hard to remember lol.

**Comment by odeke-em** [comment]
Hahaha @Lord. You guys are the real MVPs, thanks for helping out with resolving issues, fixing bugs and for advice.
Github won't let me embed the iframe but here y'all go https://gifs.com/gif/73nJ7O

**Comment by odeke-em** [comment]
Hey y'all am away from my computer for a couple of hours but I just wanted to let y'all know that I made a release right before running out of the house as I was late for an event. Cheers!

**Comment by shaggytwodope** [comment]
Long post here lol, ok so aur package updated: https://aur.archlinux.org/packages/drive/

I need some response from arm users if possible. (maybe @odeke-em lol) ... arm builds are working now for the ppa package. https://launchpadlibrarian.net/242686736/buildlog_ubuntu-wily-armhf.drive_0.3.5-0_BUILDING.txt.gz

As of posting only built for wily, going to do the rest soon enough. @canpolat expect update asap.

**Comment by shaggytwodope** [comment]
@odeke-em I'm going to hit you lol, version wasnt bumped mate in this release. No biggie ofc, but worth mentioning. 

https://launchpad.net/~twodopeshaggy/+archive/ubuntu/drive/+packages All the builds should be ready to go for folks that use the ppa. Love to hear feedback for arm users. This took a bit of effort to get working lol. 

@canpolat and @Sadi58, The ppa should be ready to go. Sorry for any delay in that updating on my end.

**Comment by odeke-em** [comment]
Hahaha my bad @shaggytwodope . Let me bump it up. Yeah I was running out for an event real quick. I'll update it in the next couple of hours as am travelling for the next 18 hours.

**Comment by odeke-em** [comment]
@shaggytwodope please refresh here is the latest mixtape https://github.com/odeke-em/drive/releases/tag/v0.3.5

**Comment by shaggytwodope** [comment]
Updated aur, in process of doing ppa rebuilds.

**Comment by Sadi58** [comment]
@odeke-em , @shaggytwodope 
Thank you so much for the new release and deb package including the new `drive diff -skip-content-check`

**Comment by odeke-em** [comment]
Cool, good to know the release had the features working.
Thanks y'all. Closing this issue since it was resolved with a release.

![](https://j.gifs.com/82B72j.gif)
