### ISSUE TITLE
[feature request] return hash of file stored in drive

### ISSUE THREAD

**Issue by l3iggs** [odeke-em/drive#60]
I'm interested in verifying the integrity of a file on my Google Drive. Is there some way to ask the server to return a hash (sha256, md5 or whatever)? If not, can this feature be added to drive?

I see that `drive stat` shows a FileId. Can I somehow use that to verify the integrity of the remote file?

**Comment by odeke-em** [comment]
Oh yes there is. I can get this in asap.

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/commit/a2d1b6bcf6f07398b8a8f09b644b2096aa81fa97 please pull the latest and test.

**Comment by l3iggs** [comment]
Works! __Awesome.__
