### ISSUE TITLE
Server connectoin

### ISSUE THREAD

**Issue by ms512** [odeke-em/drive#600]
Hi.
Is it possible to copy a file from a server to Google Drive like SCP command enabling copying files from a server to a server by [scp user1@host1.com:/home/user1/file.txt user2@hos2t.com:/home/user2/?

**Comment by odeke-em** [comment]
Hello @ms512. Thanks for the question and welcome to drive!

drive doesn't obey the SSH/SCP protocol so you cannot use scp to copy files directly.
Also the way it was written doesn't make this easy, drive just copies to directories that are children of the mounted(init-ed) directory.
To answer your question, no you cannot do this, you cannot specify an arbitrary deposit location. However you can achieve something similar to this by:
a) Using symlinks that are children to the mounted root.
b) `--piped` which as you'd guess deals with pipes, but only for files and it works one file at time
```shell
$ drive pull --piped information/a1/zp.txt > ~/Desktop/archives
$ scp user@host1.com:/home/user/file.txt /dev/stdout | drive push--piped filings/T1/2015.
```

Hope this helps. Let me know what you think.

**Comment by odeke-em** [comment]
Closing this issue since drive doesn't speak SSH/SCP.
