### ISSUE TITLE
Pull and Push without delete

### ISSUE THREAD

**Issue by MauroMombelli** [odeke-em/drive#602]
Hi,

i have some misaligned folder, on the Drive there are some file (hundred of them) that are missing on the target machine, witch also has hundred of file missing on Drive's folder. This folder is big 10GB and the not-aligned files are about 1-2GB, so pulling ALL the driver folder somewhere else is not a great option.

How can i pull all those file from Drive to my machine without deleting local ones?

**Comment by barracks510** [comment]
A solution to this problem would be nice. If only Google Drive were more like Git....

**Comment by odeke-em** [comment]
Hello @MauroMombelli and @barracks510, thanks for reporting this and welcome to drive.

You can already do this and it is mentioned in the README https://github.com/odeke-em/drive#note
For example
```shell
$ drive pull --exclude-ops "delete,update" vines
$ drive push --exclude-ops "create" sensitive_files
```
The examples above show how that you can exclude CRUD operations using `--exclude-ops`.

You can also use `--no-clobber`
```shell
$ drive pull --no-clobber myfiles
```
This will only pull those files.

Also you can just pull files selectively
```shell
$ drive pull a1 a2/ax/b1/b2 others Pictures/2016
```

Hope this helps. Please let me know if this works for you.

**Comment by barracks510** [comment]
AH. I knew there was some functionality like that. Thanks, this helps significantly.

**Comment by MauroMombelli** [comment]
Thank you!

Whan i run the help in the command line it just say:

    -exclude-ops string
        exclude operations

this is quite cryptic and also does not tell you the operation, and because you have to correctly spell them is quite error prone.

As user i can tell you i looked at "drive pull -h" for something like --no-delete switch.

Also in the readme those operation are quite hidden as they does not appear in the push an pull guide, but a bit after like.

I must say i was expecting no delete and no update by default, luckily things ended up in trash (as i could not get the list of thing to delete, i redirected the output to file, and the program decided to proceed without asking).

I think maybe a little example on how to start without risking collateral damages may help a lot.

i know maybe i'm a bit stupid but i got really scared util i found out everything was in the trash, phew

**Comment by odeke-em** [comment]
@MauroMombelli my apologies for the lack of examples. I agree we should have this in. If you'd like to, please feel free to make a PR with sample examples to the README, if you are unable to, don't worry this can be added in later. No it has nothing to do with you, I just hadn't properly documented. If it confuses one person I'd bet you there are a lot more people who will get confused to.
Glad to know that you were able to sort this out though.
