### ISSUE TITLE
question: option for limiting concurrent pulls

### ISSUE THREAD

**Issue by basdfvawfawef** [odeke-em/drive#604]
Hello,

I use drive in an SD card.
Every time it pulls files, it pulls 4 file in a time, and this make my SD card slow enough to do nothing.
Can you add a parameter to allow download a file in the same time?

Thank you.

**Comment by odeke-em** [comment]
Hello there @basdfvawfawef, thank you for reporting this and welcome to drive. 
There is an env flag that you can set before a pull or push
```shell
$ DRIVE_GOMAXPROCS=2 drive pull myContent Pictures/2013
```
So the caveat is that right now it does a minimum of 2 files concurrently per operation but otherwise you can vary the number of concurrent file pulls/pushes.

**Comment by basdfvawfawef** [comment]
Thank you for replying.
I'll try it.
