### ISSUE TITLE
How to use "fix-clashes"

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#606]
How is this flag '-fix-clashes' supposed to be used on the command line? I've tried:

`drive push -fix-clashes 2012\ Tax\ Year/`
` drive push --fix-clashes 2012\ Tax\ Year/`
and the error is:

```
Resolving...
 – 
clashes detected. Use `ignore-name-clashes` to override this behavior or `fix-clashes` to try fixing this
```
The only 'fix-clashes' I find in the README/Main Page is on the "Pushing" header:

https://github.com/odeke-em/drive#pushing but it shows no actual usage on how to use this flag.

```
$ drive version
drive version: 0.3.5
Commit Hash: 'cd62d0afcf2ee48965f903857a5a7058427b30fe'
Go Version: go1.4
OS: linux/386
BuildTime: 2016-03-06 13:51:00.74023531 -0400 AST
```

**Comment by odeke-em** [comment]
Hello again @ikwyl6, thanks for reporting this.
So in the README there is talk of a different command https://github.com/odeke-em/drive#clashes
```shell
$ drive clashes [--depth n] [paths...]
$ drive clashes --list [--depth n] [paths...] # To be more explicit
$ drive clashes --fix [--depth n] [paths...]
```

Also it could be that drive isn't return all the present clashes, but that's an issue that was reported and is yet to be fixed.
Please give that a try and let me know what transpires.

**Comment by ikwyl6** [comment]
Ok thanks for the info. Can I suggest you add a reference in the section of '--fix-clashes' (https://github.com/odeke-em/drive#pushing) to this "Clashes" link in the file.

**Comment by odeke-em** [comment]
@ikwyl6 could you help me with pointers as what we could add specifically, any wording for it? Thanks.

**Comment by staszek-arsdata** [comment]
The message on the console does not correspond with drive command line. I've got:

clashes detected. Use `ignore-name-clashes` to override this behavior or `fix-clashes` to try fixing this

So i try:
$ drive fix-clashes

but there's no such command. I think the message should be:

clashes detected. Use `ignore-name-clashes` to override this behavior or `clashes --fix` to try fixing this

This way the drive cmd line is auto documenting itself.

**Comment by draeath** [comment]
So, this is still a problem.

**Comment by Spark010** [comment]
using "drive clashes --fix" seams to have fixed the clashes .... that should be in the documentation

**Comment by rmdes** [comment]
Still exist..drive version: 0.3.9.1
