### ISSUE TITLE
OAuth2 Invalid Scope

### ISSUE THREAD

**Issue by Guymer** [odeke-em/drive#609]
When attempting to initialize my drive for the first time the URL that is printed on the command line fails (see [attachment](https://cloud.githubusercontent.com/assets/4899102/14042187/7bac26ae-f26f-11e5-8196-b1d8d352a4c3.png)). I managed to side-step that issue by modifying the printed URL so that the scope URL parameter was all lower case. Google then printed me an authorization code. Unfortunately, this authorization code failed when I pasted it into the command line with the following printout:
`oauth2: cannot fetch token: 400 Bad Request Response: {
  "error" : "invalid_scope",
  "error_description" : "Some requested scopes were invalid. {invalid=[https://www.GoogleAPIs.com/auth/drive]}",
  "error_uri" : "http://code.google.com/apis/accounts/docs/OAuth2.html" }`.

Perhaps this is a simple fix of changing the source URL to be lower case? I don't know, I don't deal with OAuth at all.

Thanks

**Comment by odeke-em** [comment]
Hello there @Guymer, thanks for reporting this and welcome to drive.
Yes in deed, this is bug that I accidentally just introduced when by introducing a search and replace in https://github.com/odeke-em/drive/pull/608  https://github.com/odeke-em/drive/pull/608/files#diff-96a204b8073f24b6b3a57d5bf6fcec6aR43.

Am pushing a PR to fix it up asap. Thank you for the catch.

**Comment by odeke-em** [comment]
Fixed by PR #610. Good catch. Please reopen if persists.

**Comment by Guymer** [comment]
That works great now, thanks @odeke-em
