### ISSUE TITLE
Is there a way to push/copy a single local file to specific remote directory?

### ISSUE THREAD

**Issue by kevjonesin** [odeke-em/drive#612]
Is there a way to push/copy a single local file to specific remote directory? I didn't find any way in "help" docs to specify a remote path or otherwise change remote target directory with "drive push" commands for a single file. And "drive cp" appears to be just for copying remote files to ... well, the "help" docs don't actually specify, but I'm presuming a local path ... or is it to make additional copies within remote directories? I was able to push a file from my local "~/gdrive" directory to my Google Drive's root directory ('My Drive') with "drive push file.txt" and then use "drive mv file.txt Foo/Directory/" to relocate it, but I'm left wondering if there is a way to place a local file of choice in remote directory of choice with a single command? At present, I'm just looking to manually move occasional files to and from my Google Drive via command line, rather than fully syncing remote and local directories.

[BTW, thanks for maintaining and developing "drive"; it's nice to have some GDrive access when I don't have a GUI at hand.]

**Comment by odeke-em** [comment]
Hello @kevjonesin. Thank you for the question and welcome to drive! My apologies for the late reply.

So to push a single file to a specific path is a bit awkward for now, yes in deed. A copy then move doesn't suffice. No one had needed this functionality in the past so I never thought of it. But this is def a good feature to add that will make it easy to move things as opposed to push by relocating to the exact directory structure.

To answer some questions:
1. `drive copy` only copies remote paths(files and directories) to the last specified path or if a single path is passed to `drive copy`, it will find the remote equivalent of the current working directory.
Yes in deed, the documentation could definitely be improved.

However for now, you'd have to recreate the directory structure of the target path so
```shell
$ cp content a1/b2/c3
$ drive push a1/b2/c3 # Or cd a1/b2/c3 && drive push
```
But as you already noticed that quickly becomes unuseable and too much hacking. Thanks for the request, PR coming soon!

**Comment by kevjonesin** [comment]
@odeke-em, Thanks for your response and consideration. :  }

p.s.— I might be able to find time (at some point) to help with documentation. Perhaps expand upon current "help" entries and migrate them to a traditional "man" page and/or "info" page. Would be an interesting way to learn 'man page' format and syntax. win/win

**Comment by odeke-em** [comment]
Solid plan!

 Am very busy mostly but I see a big need for this and I'll try to get this in pretty soon, and I'd be very happy to review documentation PRs. Thank you.
![](https://cloud.githubusercontent.com/assets/4898263/11171846/caa8f26a-8bb7-11e5-8b94-e84d63f3d92d.gif)

**Comment by odeke-em** [comment]
Hello @kevjonesin thanks for the patience. This issue was auto-closed from a PR commit. Please feel free to reopen it if the problem persists.
But basically now you can say
```shell
$ drive push --destination a1/few/ones allSources/b2/b3/b5 b8n/logs content/locks/bz9
```
where the arguments after you've specified the push destination should exist relative to the root of the mounted root dir.
Let me know how it goes.
