### ISSUE TITLE
Drive skipping ~5% of files when there is a large folder

### ISSUE THREAD

**Issue by sselph** [odeke-em/drive#613]
Hi,

drive version: 0.3.5
Commit Hash: 814d5f741328a2011714cd881f1984cfb7ece01e
Go Version: go1.6 linux/amd64

This has been going on for a while, sorry for not filing a bug earlier. I have folders in drive with 900 jpeg files in them ranging from 100-300kB. If I cd to the folder and do a push or pull and the receiving end has an empty folder it will only see and prompt to transfer ~850 of the files. If I say yes, they transfer. Then if I run it again, it will usually find the remaining and transfer them. Occasionally, I have to do it a third time to get 1-2 files that were missed.

I haven't had a chance to look more closely. If there is some verbose logging or anything else I can do to help troubleshoot let me know.

**Comment by odeke-em** [comment]
Hello again @sselph. Thank you for the report. Ah I see. Next time you can try it out with flag `--verbose` e.g
```shell
$ drive push --verbose files
```
However that's going to produce lots of noise since that logs even successful jobs as well as failed jobs but it will tell you why it failed. I think we could add improvements to make debugging such easier.

**Comment by sselph** [comment]
Thanks but that doesn't seem to increase logging in the portion of affected code. This happens in the portion that is doing the diff. 
```
$ ls | wc -l
900
$ drive ls
$ drive push --verbose
Resolving...
...
Addition count 843 src: 153.87MB^C
$ drive push --verbose
Resolving...
...
Addition count 849 src: 154.80MB
```

**Comment by odeke-em** [comment]
Ah I see, thanks for the repro.

**Comment by feuerbach** [comment]
Ran into this too. @odeke-em any idea what may be causing this?

**Comment by odeke-em** [comment]
Hello @feuerbach, unfortunately I haven't had time to investigate that but my hunch would be some code to do with local file discovery might be incorrect. Thanks for the reminder.

**Comment by feuerbach** [comment]
Thank you. If you could point me into the direction you have in mind, I could take a look.

**Comment by odeke-em** [comment]
For sure, thank you for this. The relevant code for local listing is here https://github.com/odeke-em/drive/blob/837fdaaf01f2a5288ae7ea541ddaaa3ae00277b6/src/misc.go#L937-L1009, somewhere there might be the elusive bug.

**Comment by sselph** [comment]
The other day I ran this on another system and every thing worked fine. The difference was this machine was single a single core machine. So out of curiosity I changed DefaultMaxProcs to 1 and everything worked.
https://github.com/odeke-em/drive/blob/837fdaaf01f2a5288ae7ea541ddaaa3ae00277b6/src/misc.go#L64

**Comment by sselph** [comment]
Found the issue. I'll clean up my fix and get a pull request sent out soon.

**Comment by sselph** [comment]
Sent https://github.com/odeke-em/drive/pull/639 which I think solves this particular issue.

**Comment by odeke-em** [comment]
Awesome, thank you @sselph!

**Comment by odeke-em** [comment]
Fixed by @sselph in PR https://github.com/odeke-em/drive/pull/639. I'll let y'all close it when it is working after you get the latest from master.
