### ISSUE TITLE
Problem fresh build...

### ISSUE THREAD

**Issue by docbill** [odeke-em/drive#614]
I'm trying to build a fresh build inside a docker container...   However, I keep running into a dependency problem:

```
[briemers@briemers2 ~]$ sudo docker run -t -i fedora /bin/bash -i
[root@b3d8c3964229 ~]# dnf install git go godep
[root@b3d8c3964229 ~]# cat <<\+ > ~/.profile
export GOPATH="$HOME/work-go"
if [ -n "${PATH#*/work-go*}" ]
then
  export PATH="$PATH:$HOME/work-go"
fi
+
[root@b3d8c3964229 ~]# . ~/.profile
[root@b3d8c3964229 ~]# go get github.com/tools/godep
[root@b3d8c3964229 ~]# go install github.com/tools/godep
[root@b3d8c3964229 ~]# go get github.com/odeke-em/drive/drive-gen
[root@b3d8c3964229 ~]# cd work-go/src/github.com/odeke-em/drive/drive-gen/
[root@b3d8c3964229 drive-gen]# godep save
godep: cannot save google.golang.org/api/drive/v2 at revision 43c645d4bcf9251ced36c823a93b6d198764aae4: already have google.golang.org/api/googleapi at revision 0a735f7ec81c85ce7ec31bf7a67e125ef62266ec.
Run `godep update google.golang.org/api/googleapi' first.
[root@b3d8c3964229 drive-gen]# godep update google.golang.org/api/googleapi
godep: cannot find package "github.com/google/google-api-go-client/drive/v2" in any of:
	/usr/lib/golang/src/github.com/google/google-api-go-client/drive/v2 (from $GOROOT)
	/root/work-go/src/github.com/google/google-api-go-client/drive/v2 (from $GOPATH)
godep: cannot find package "github.com/odeke-em/xon/pkger/src" in any of:
	/usr/lib/golang/src/github.com/odeke-em/xon/pkger/src (from $GOROOT)
	/root/work-go/src/github.com/odeke-em/xon/pkger/src (from $GOPATH)
godep: error loading dependencies
[root@b3d8c3964229 ~]# go get github.com/google/google-api-go-client/drive/v2
package github.com/google/google-api-go-client/drive/v2: code in directory /root/work-go/src/github.com/google/google-api-go-client/drive/v2 expects import "google.golang.org/api/drive/v2"

```
I'm stuck here...
I could probably copy the installation I already have in my real fedora installation, but that does not seem like a very good idea.

**Comment by odeke-em** [comment]
Hello @docbill, sorry about that. I think I may not have updated godeps in a very long time. Would it be possible for you to remove drive-gen/Godeps? And then try again with the godep save?

**Comment by docbill** [comment]
[root@c3a658ef04b8 /]# cd ~/work-go/src/github.com/odeke-em/drive/drive-gen/
[root@c3a658ef04b8 drive-gen]# ls
Godeps  LICENSE  README.md  build.go
[root@c3a658ef04b8 drive-gen]# rm -rf Godeps
[root@c3a658ef04b8 drive-gen]# godep save
godep: dirty working tree (please commit changes): /root/work-go/src/github.com/odeke-em/drive/config
godep: dirty working tree (please commit changes): /root/work-go/src/github.com/odeke-em/drive/src
godep: error loading dependencies

**Comment by docbill** [comment]
Looks like instead I should do:
# git rm -rf Godeps
# git commit -a
# godep save

Then it works.   It is strange needing to commit changes before testing they work.   But it works.

**Comment by docbill** [comment]
Success:  https://hub.docker.com/r/docbill/docker-drive/

Thanks,

Bill

**Comment by odeke-em** [comment]
Solid! That's cool. Please feel free to list your steps and or docker build in the wiki :)
