### ISSUE TITLE
drive did not install

### ISSUE THREAD

**Issue by wmbbarnett** [odeke-em/drive#617]
Attached is the console display for the install.
[drive.txt](https://github.com/odeke-em/drive/files/209412/drive.txt)
 
verified go install was correct. 
 
install was on a beaglebone black running debian 7.9.

**Comment by odeke-em** [comment]
Hello there @wmbbarnett thanks for reporting this and welcome to drive.
Perhaps you are using a version of Go less than 1.3? This is because you have an error 'work/src/golang.org/x/net/context/pre_go17.go:109: function ends without a return'.
Please use preferrably go1.4 and greater.

**Comment by wmbbarnett** [comment]
will do.
 
thank you.
