### ISSUE TITLE
[feature request] push from stdin and pull to stdout

### ISSUE THREAD

**Issue by l3iggs** [odeke-em/drive#62]
It would be really great to be able to `drive push` a data stream read from stdin. 

I hope this could work like this:
```bash
echo "testing123" > test.txt
cat test.txt | drive push --stdin stdinTest.txt
```
Then you'd have a file in your Google Drive called stdinTest.txt which contains the string "testing123"

What do you think?

**Comment by odeke-em** [comment]
Yap, sounds like a plan. I'll get it in a couple of hours or so when I get home.

**Comment by l3iggs** [comment]
Great!
I guess it should probably come with a pull to stdout compliment, if it's not too much trouble, i.e. 
```
drive pull --stdout stdinTest.txt
```
Should send "testing123" to stdout.

And please imagine me doing these things with > 1 TB files, 'cause that's what I'm planning ;-)

**Comment by odeke-em** [comment]
Yeah I had considered it's pull equivalent, actually someone had requested this from Burcu's repo. Haha, no biggie, hope it will be able to handle this.

**Comment by l3iggs** [comment]
> Haha, no biggie, hope it will be able to handle this.

Hopefully if the solution you come up with here doesn't involve attempting to load the entire stream into RAM at any point, then it'll work fine with large/long streams. I don't have > 1 TB of RAM kicking around :-P

**Comment by odeke-em** [comment]
Come on. The current solutions don't even load everything into RAM. Google even patched up the API client to ensure that this doesn't happen.

**Comment by l3iggs** [comment]
Good news!

**Comment by l3iggs** [comment]
here's why I requested this feature:
https://github.com/odeke-em/drive/wiki/%5BUse-Case%5D-Backup-a-btrfs-volume-to-your-Google-Drive
I think it's a killer feature

**Comment by odeke-em** [comment]
Woot woot, thank you @l3iggs! I think so too.

**Comment by l3iggs** [comment]
I haven't done any new benchmarks since testing this branch. That testing showed no speed difference when moving data through the pipes vs file based pushing/pulling. I haven't noticed any changes while using this in 0.1.0.

**Comment by odeke-em** [comment]
Gotcha, although I noticed that in your first demo, 100MB was transferred in about 40seconds or so,  I could be wrong. Any idea of what it took before?

**Comment by l3iggs** [comment]
Oh, no, I never explicitly compared it to the speed I got with release 0.0.9. It'll be a few hours before I can get back home and test 0.0.9. I'll report back here.

**Comment by odeke-em** [comment]
Thank you.

**Comment by l3iggs** [comment]
I've just tested 0.0.9 vs 0.1.0
I see no statistically significant speed difference for up/downloads of 100MB files.

**Comment by odeke-em** [comment]
Roger that, thank you for the test.
