### ISSUE TITLE
md5sum seems broken

### ISSUE THREAD

**Issue by RezaRob** [odeke-em/drive#624]
Other things work just fine, such as 
drive ls -long
but 
drive md5sum
produces an empty (totally blank) result set without reporting any errors.

Thank you.

**Comment by odeke-em** [comment]
Hello there @RezaRob, thanks for the issue and welcome to drive!

Would you mind sending the context of the issue? `drive version`? Some output?
As for starting to dig through this, `md5Sum` works only for files and not folders. Also not for Google Docs or Sheets. Please check the type of the files. The mentioned types don't have md5sums.

**Comment by RezaRob** [comment]
Hi odeke-em,
here is some output:

<linux version>
Linux version 3.13.0-85-generic ... (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) 

<go version>
$ go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

<drive version>
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ drive version
drive version: 0.3.5
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 

<drive ls>
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ drive ls
/backups/20151229.1/backup.20151229.1.tar.list.gpg
/backups/20151229.1/backup.20151229.1.tar.gpg-0000

<local ls>
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ ls -a
.  ..
<i.e.  local folder is empty>

<drive md5sum>
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ drive md5sum 
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ 
<again, result is completely empty>

I should note that during installation I got some sort of go error about "Cancel" not being defined or something.  Sorry I forget the exact line.  If I must, I'll reinstall.  
But again, strangely, everything else actually works,  except md5sum.

**Comment by RezaRob** [comment]
I'm sorry, please wait until I reinstall!  I'm having several installation errors while attempting a reinstall.
My apologies.  I'll get back later.

**Comment by odeke-em** [comment]
No rush @RezaRob, take your time. I'll take a look at it when I get back home in a few hours or over the weekend.

**Comment by RezaRob** [comment]
Thank you odeke-em.

I removed gccgo from my system (not at all sure what the issue was in the first place.)
I installed golang-1.6-go (ubuntu 14.04)
Now I get,
\<go version>
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ go version
go version go1.6 linux/amd64

which I hope is sufficient.

I installed drive again.  No errors.
I get,
\<drive version>
reza@reza-desktop:/backups/gdrive/backups/20151229.1$ drive version
drive version: 0.3.5
Commit Hash: \<CURRENT_COMMIT>
Go Version: \<GO_VERSION>
OS: \<OS_INFO>
BuildTime:

But the issue with drive md5sum is exactly as before.  Other things seem to work.

I'm really hoping I haven't made any mistakes.  Too many go versions was slightly confusing and I wasn't sure what the original install warning was.  This time it looked clean.  Of course, I'm using the original folder for gdrive.  In any case, since other things work, I strongly suspect it is related to the drive API/md5sum protocol.  

I hope it helps.  Many thanks.

**Comment by odeke-em** [comment]
Solid. Good to know it installed alright. Just one more step to compile the commit hash info into the binary
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
and then you can run
```shell
$ drive version
```

**Comment by odeke-em** [comment]
So to use md5sum, would you mind trying a depth greater than one or using flag `--recursive` e.g
```shell
$ drive md5sum --depth 3 videos
```
or 
```shell
$ drive md5sum --recursive content
```

**Comment by RezaRob** [comment]
Fantastic!  Thank you very much.  It's working now.  
May I ask what the commit hash does?

**Comment by odeke-em** [comment]
Dope, glad to know it is working for you now. The commit hash just helps in quick debugging to the source code version your binary was compiled against when you provide your  `drive version`.
For example mine
```shell
$ drive version
$ drive version
drive version: 0.3.5
Commit Hash: '3385bd27a98da1d9f27333b015b4e520cbd06f2a'
Go Version: devel +63ceeaf Fri Apr 22 05:27:51 2016 +0000
OS: darwin/amd64
BuildTime: 2016-04-22 20:47:30.092168624 -0700 PDT
```
This way we can easily go find out what's trippy with a commit or the changes in it.

What made it work though was `--depth` > 1 or `--recursive`.

**Comment by RezaRob** [comment]
Great, sure,

$ drive version
drive version: 0.3.5
Commit Hash: '3385bd27a98da1d9f27333b015b4e520cbd06f2a'
Go Version: go1.6
OS: linux/amd64
BuildTime: 2016-04-22 20:33:01.266572743 -0700 PDT

Thank you odeke-em.

**Comment by odeke-em** [comment]
Glad to know you were able to resolve it. Just for future reference, md5sum doesn't work on directories so a deeper depth will be needed to get these sums.
