### ISSUE TITLE
Easy way to Download root?

### ISSUE THREAD

**Issue by ctro** [odeke-em/drive#629]
I can't quite tell if there is an easy way to `sync download` my entire GoogleDrive easily.

I thought `gdrive sync download root .` might work but it doesn't.  
I get `Provided id is not a sync root directory`  Am I missing something?

**Comment by odeke-em** [comment]
Hello there @ctro. Thank you for the question and welcome to drive!

Are you sure this is the right project? drive doesn't have that syntax and the binary by default isn't called 'gdrive'. However, if you were looking for a drive solution, it is just a matter of first following these instructions https://github.com/odeke-em/drive#requirements and then

```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
$ drive init myDrive
$ cd myDrive
$ drive pull
```

## To pull the first level only, run $ drive
```shell
$ drive pull --depth 2
```

Please feel free to ask more questions or reach out in case of anything. Hope this helps.

**Comment by ctro** [comment]
Yep!  Wrong project. :facepalm:
I was actually trying to use this project but it doesn't build on a Pi.
I'll let you decide if it's worth adding an Issue for the Pi Build.
Thanks for getting back to me so quickly!

**Comment by odeke-em** [comment]
Ahah here is a distraction for the face palm ![](https://j.gifs.com/Kr79AJ.gif)

No worries @ctro when I get home in about 4, I can cross compile for you a binary.

**Comment by shaggytwodope** [comment]
@ctro You can open another issue I'm sure, but include what the error is when trying to build. It may be similar to issue #627 maybe?

@odeke-em I swear I need to figure how to build .deb package for rpi folks. Got a armhf build for ubuntu pacakges.

**Comment by odeke-em** [comment]
@shaggytwodope that would be a good plan right there ![](https://j.gifs.com/R6BJWR.gif)

**Comment by ctro** [comment]
Yep, dup of #627.  I'll follow along there.

On Tue, Apr 26, 2016 at 5:35 PM, Emmanuel T Odeke <notifications@github.com>
wrote:

> @shaggytwodope <https://github.com/shaggytwodope> that would be a good
> plan right there
> <https://camo.githubusercontent.com/d6c4a293ec25ad1abf10a51638594da1831c8ce2/68747470733a2f2f6a2e676966732e636f6d2f5236424a57522e676966>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/odeke-em/drive/issues/629#issuecomment-214919756>
>



-- 
Clint Troxel
18F Innovation Specialist
Jackson, WY  83001
