### ISSUE TITLE
All pulled documents are zero byte

### ISSUE THREAD

**Issue by monnand** [odeke-em/drive#63]
I just sync'ed my Drive on my local filesystem. All documents created on Google Drive are now zero byte on my local disk.  Is this a feature that has not been implemented?

I installed the program using ``go get``. Do I need to switch to some stable release version?

**Comment by odeke-em** [comment]
If they are Google Docs/Sheets, then as mentioned in the README and also by default, Google Docs and Sheets cannot be downloaded raw, only exported. If that isn't the case what kind of files are they?

**Comment by monnand** [comment]
@odeke-em Oops. Sorry about that. I did not read the README carefully. Thank you!

**Comment by odeke-em** [comment]
No biggie. Don't hesitate to reach out in case of any issues or questions.

**Comment by ikwyl6** [comment]
@odeke-em But it should be noted that you have an export feature for these files to PDF, txt, etc don't you?

**Comment by odeke-em** [comment]
That is right @ikwyl6. However, I'd bet that was discovered after they went through the README.
