### ISSUE TITLE
-quiet progress issue

### ISSUE THREAD

**Issue by chevillet** [odeke-em/drive#636]
Hi @odeke-em!

I didn't want to bring this up earlier because you seemed busy but since you're very active today and I guess you might have missed the updates in #502 because the issue was already closed, could you please check why the "progress" information is "randomly" displayed while using -quiet?

Thanks in advance!

**Edit**: See https://github.com/odeke-em/drive/issues/502#issuecomment-172208797

**Comment by odeke-em** [comment]
Hello again @chevillet, thank you for opening this issue. My apologies for the late reply, I've been swamped lately. I'll take a look at it when am free.

**Comment by chevillet** [comment]
No worries and you really don't need to apologize!
Your work on the project is awesome and everybody's glad you've taken it over last year!

**Comment by odeke-em** [comment]
Hello @chevillet thank you for the kind words and for the patience. I'll be pushing up a CL to fix this in a second.

**Comment by odeke-em** [comment]
@chevillet please get the latest from master `go get -u github.com/odeke-em/drive/drive-gen && drive-gen` and if it persists, please don't hesitate to reopen this issue as it was autoclosed by a  commit from PR https://github.com/odeke-em/drive/pull/642.

**Comment by chevillet** [comment]
Thanks a lot! 
Just updated my setup, I'll let you know if it happens again.
