### ISSUE TITLE
push-mounted: always puts entries in root

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/drive#641]
While testing out a new CL, I noticed that push-mounted ie `drive push -m` always puts entries in root and touches root too causing an error `googleapi: Error 403: File not mutable, Forbidden`
```shell
$ drive push --quiet -m ~/Desktop/openSrc/bugs/golang test-quiet
 4038 / 10087665 [>-------------------------------------------]   0.04% 2h55m31s: googleapi: Error 403: File not mutable, forbidden
 10087665 / 10087665 [===========================================] 100.00% 2m11s
push:  err: googleapi: Error 403: File not mutable, forbidden  
```
This bug is a result of PR https://github.com/odeke-em/drive/pull/616 in which the introduction of destination means that it works alright for a normal push but fails for a mounted push.

**Comment by odeke-em** [comment]
Postponed to v0.3.7 to pave way for the integration of the new end to end encryption package.

**Comment by Anmol-Singh-Jaggi** [comment]
When will this be solved?

**Comment by brandoncurtis** [comment]
@Anmol-Singh-Jaggi when you push @odeke-em some bitcoin :moneybag: :moneybag: :moneybag: :+1:

**Comment by Anmol-Singh-Jaggi** [comment]
I'd rather learn Go and do it myself. :laughing:

**Comment by odeke-em** [comment]
![outf](https://cloud.githubusercontent.com/assets/4898263/16215992/059283c2-371c-11e6-9c4c-f2ba7900b0d2.gif)

Thanks @brandoncurtis for having my back! @Anmol-Singh-Jaggi, am sure you already guessed from @brandoncurtis' comment: the work done here is all voluntary and on own time, so things do take a bit of time to get fixed, but that's all good.

As for the timeline to fix it, hopefully soon before the next release. I use `push-mounted` a lot, so I hope to fix it when I get time.
