### ISSUE TITLE
Pulling `shared-with-me` folder

### ISSUE THREAD

**Issue by nvanheuverzwijn** [odeke-em/drive#643]
Hi,

How can one pull _shared_ folders with `drive pull` without having to specify every id of the shared content ?

Regards,
Nic

**Comment by odeke-em** [comment]
Hello there @nvanheuverzwijn. Thank you for the question and welcome to drive.

So the last time I checked, you have to actually add the shared folder to your Google Drive and once it is part of yours, then you can pull it normally by name or by file-id e.g
```shell
$ drive pull assn3
```
Please see the screenshots below
<img width="863" alt="screen shot 2016-05-11 at 1 11 41 am" src="https://cloud.githubusercontent.com/assets/4898263/15174238/7a9a24d0-1715-11e6-8d96-ff052f9a56f2.png">
<img width="1226" alt="screen shot 2016-05-11 at 1 11 58 am" src="https://cloud.githubusercontent.com/assets/4898263/15174240/7aa11934-1715-11e6-9476-f71678455d0d.png">
<img width="624" alt="screen shot 2016-05-11 at 1 12 15 am" src="https://cloud.githubusercontent.com/assets/4898263/15174239/7a9efa00-1715-11e6-80cb-2c259cd04264.png">

**Comment by nvanheuverzwijn** [comment]
Ah, ok I see.

Thanks for your answer.

**Comment by theclue** [comment]
This is ok unless you're going to use a service account to push files in a no-prompt cronjob.

I'm stucked in the middle as I can push content but no way to share this to the owner of the shared drive..

**Comment by HorvathAkosPeter** [comment]
It does not work. Today, there is no such thing than "Add to my drive" option, there is only an "Add shortcut to my drive" option. It creates a link to the shared content.

The tool downloads the link as a zero-byte file and nothing can be done with it.
