### ISSUE TITLE
How to update drive

### ISSUE THREAD

**Issue by KristobalJunta** [odeke-em/drive#644]
How do I propely update the drive application to the latest version?

**Comment by shaggytwodope** [comment]
It's as trivial as running `go get -u github.com/odeke-em/drive/cmd/drive`, this should update drive accordingly. But it's important to note how you installed it previously.

**Comment by KristobalJunta** [comment]
I've installed it with exactly the same command, and running it now doesn't seem to have the desired effect. I'm on v0.2.8 and `go get -u github.com/odeke-em/drive/cmd/drive` doesn't update it.

**Comment by KristobalJunta** [comment]
Looks like the problem was in my go path
The $GOPATH was correct, but $GOBIN wasn't - so it installed newer drive to the wrong folder.

**Comment by shaggytwodope** [comment]
@KristobalJunta awesome you found the issue, it working now I assume? Remember for normal tagged releases there is a few packages for some distros.

**Comment by KristobalJunta** [comment]
As far as I can see, there are only source code and arm packages attached to github releases.
Anyway, yes, it worked and now I have v0.3.5. Just some .bashrc tweaking :)
Thank you for help.
