### ISSUE TITLE
drive command not found

### ISSUE THREAD

**Issue by nthakor** [odeke-em/drive#659]
I installed drive and pushed all my files properly. And it worked correctly. Once when I turned off my computer and turned on it says 
`No command 'drive' found, 
did you mean: Command 'derive' from package 'haskell-derive-utils' (universe)
drive: command not found
`

**Comment by shaggytwodope** [comment]
Is the go folder you install to in your $PATH?

**Comment by nthakor** [comment]
No, it wasn't. I added and worked. Thank you.

**Comment by MattB98** [comment]
In case anyone else hits this problem and has go in their $PATH....
The install ran with no errors, retruned to command prompt, typed 'drive' and got 'command not found'.  The binary was in ~/go/bin, so I need to execute 
`~/go/bin/drive `
to run drive
