### ISSUE TITLE
No longer possible to only pull update files

### ISSUE THREAD

**Issue by tkjacobsen** [odeke-em/drive#66]
I use drive to backup my google drive data. However, with recent changes, I can no longer pull only changed files as the -force option will re-download everything (>25 GB). It makes sense to not overwrite local files by default, so I guess a new flag would be required to explicitly allow overwriting local files but only download changes (as was the default up to version 0.0.7).

**Comment by tkjacobsen** [comment]
Alternative is to split -force in two:

-force: overwriting local files (but only changes)
-force-download: above + always download

**Comment by odeke-em** [comment]
Sorry for the late reply. I just got back home. Ah that sucks that the re-download trips you out. Before I get to implementing I just wanted to nail out a thing or two. Do you get a manifest of what conflicts exist? The reason you get the `-force` suggestion is because you have data that is modified on both ends.

**Comment by DenomZero** [comment]
I just started using drive and its almost exactly what I'm looking for. The mentioned issue is my only gripe but with uploading and downloading.  The perfect solution IMO would be to implement something like 'drive push -diff' like using just 'drive diff' and then syncing those changes.  Hopefully thats something not terribly hard to implement.  Keep up the good work and thanks for taking the time to read my comment.

**Comment by odeke-em** [comment]
Thanks @tkjacobsen @DenomZero for raising this issue, great suggestions and soon I'll be pushing up a PR with a flag to solve this. Watch this space.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/72
