### ISSUE TITLE
export: allow unloading to a single directory instead of each sub-directory per export

### ISSUE THREAD

**Issue by AtcR** [odeke-em/drive#660]
I'm trying to pull and export some docs files to pdf (app 900) without make a lot of directories.

`drive pull -force -export pdf -exports-dir /home/xxxxxx/gdrive/PDF/ -id xxxxxxx`

But each export make his own folder into PDF.
How can i insert each exported file into only one directorie/folder?

I know my English is not perfect and I will really appreciate if you could give me a hand on this problem.

**Comment by odeke-em** [comment]
Hello there @AtcR, thanks for the issue and welcome to drive.

Yes in deed, currently it creates a directory per file but that's because you can export to multiple formats(e.g pdf, txt, rtf, png etc) and also to avoid cluttering one directory. A feature request could be to allow dumping exports into a common directory.

**Comment by chevillet** [comment]
I'd love to have the ability to export files in the original directory even it clutters it.
Also, it would be great to be able to skip the ".desktop" file when it was exported.

Of course, it shouldn't be the default behaviour and I can live without it but I'd love these options.

**Comment by odeke-em** [comment]
@chevillet thanks for chiming in, actually would you mind filing a separate issue about skipping the creation of *.desktop files?
Otherwise I have a CL coming up in a second to implement this request in this issue.

**Comment by chevillet** [comment]
Hi @odeke-em!
Thanks a lot for this new feature, it's really cool.
And sorry about the *.desktop request, I should have created a different issue in the first place, my bad.

**Comment by odeke-em** [comment]
No worries at all. I see you've created the issue, I am going to get started working on it as we speak 🙏🏾
