### ISSUE TITLE
prebuilt binaries similar to gdrive?  <feature request>

### ISSUE THREAD

**Issue by minektur** [odeke-em/drive#662]
Any chance of getting pre-built statically linked binaries, like done with [gdrive](https://github.com/prasmussen/gdrive) to make it significantly easier to install?  I dont know what is involved in packaging up go binaries at all so... easy?  hard?  My target is an x86_64 linux system with really really limited system utilities, where it might be "very difficult" to get go working.  the gdrive binary "just works", and was hoping I could find a google-drive binary that was similar.  edit:  target is x86-64 chromeos in dev mode...

**Comment by odeke-em** [comment]
Hello there @minektur, thank you for the issue and welcome to drive.

In releases, I've always tried to make binaries too. For example for the last release https://github.com/odeke-em/drive/releases/tag/v0.3.6
![screen shot 2016-06-05 at 8 02 12 pm](https://cloud.githubusercontent.com/assets/4898263/15810958/907c169e-2b58-11e6-89d2-6bdfa835bace.png)

As far as using `go get`, I'd recommend installing at least go1.5 which is about a 5 step process https://golang.org/doc/install and then `go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen`. If the last release's binary doesn't work for you, please let me know and I can recompile for you one. Hope this helps.
Thanks.

**Comment by odeke-em** [comment]
Closing this as it the binaries are in and there is Makefile to generate binaries. Please reopen if it persists.
