### ISSUE TITLE
Ability to see Google Photos

### ISSUE THREAD

**Issue by mrmattwilkins** [odeke-em/drive#663]
Hi,
When I am in google drive web view, ie "https://drive.google.com/drive/u/0/my-drive", there is a link on the left "https://drive.google.com/drive/u/0/photos" called  "Google Photos".  Would it be possible for drive to be able to work with that directory/folder also?
Thanks
Matt

**Comment by odeke-em** [comment]
Hello there @mrmattwilkins thank you for the question and welcome to drive.

Yes you can work with "Google Photos" folder as detailed in this issue https://github.com/odeke-em/drive/issues/301#issuecomment-125758506
To quote it
```
jonbrock commented on Jul 28, 2015
You can create a Google Photos folder in your Google Drive now, and then use drive to manipulate the photos. To set it up, go to drive.google.com, open settings, scroll down and enable the "Create a 
Google Photos folder" option. Once it's created you can rename the folder (if you want) and it 
continues to work.
```
and then you refer to that folder by the name "Google Photos".

**Comment by mrmattwilkins** [comment]
Thank you!  Silly me actually read that before, but just made the folder
which of course didn't work.  Ticked it in the settings and it works like a
charm.
Cheers
Matt

**Comment by odeke-em** [comment]
Dope. Please feel free to make a wiki entry if you'd like or even a PR if you might be interested so that later on other folks can take a look at it too. Otherwise, please don't hesitate to reach out in case of any questions and hope you enjoy using drive. Cheers.
