### ISSUE TITLE
`drive pull` 503 errors trigger future erroneous conflicts

### ISSUE THREAD

**Issue by brandoncurtis** [odeke-em/drive#668]
On a fresh install of `drive` version 0.3.7, the initial pull of the account's gDrive root encounters some 503 errors that suggest some files didn't download correctly.  These files **did** download correctly (their size is exactly as expected), but subsequent `drive pull` are prevented by conflicts with these totally-fine files.

<pre>
$ drive pull
Addition count 1903 src: 8.57GB
Proceed with the changes? [Y/n]:y
 4490448141 / 9198293954 [===================================================================================>---------------------------------------------------------------------------------------]  48.82% 8m4spull: /!CLARKLAB/Multimedia/Lab Personnel/MelindaClark2.jpg err: download: failed for url "https://googledrive.com/host/0B_cTARztpNAJNXlucWV3S3NhZjA". StatusCode: 503
 4502050946 / 9198293954 [===================================================================================>--------------------------------------------------------------------------------------]  48.94% 8m17spull: /!CLARKLAB/Multimedia/Lab Personnel/CongTrinh1.jpg err: download: failed for url "https://googledrive.com/host/0B_cTARztpNAJN1NHQkQ2bldJalU". StatusCode: 503
 4503686097 / 9198293954 [===================================================================================>--------------------------------------------------------------------------------------]  48.96% 8m22spull: /!CLARKLAB/Multimedia/Lab Personnel/ross_eppler_0.jpg err: download: failed for url "https://googledrive.com/host/0B_cTARztpNAJeGJycjl0ZlJKZFk". StatusCode: 503
 4504100302 / 9198293954 [===================================================================================>--------------------------------------------------------------------------------------]  48.97% 8m22spull: /!CLARKLAB/Multimedia/Lab Personnel/CarlyAnderson1.jpg err: download: failed for url "https://googledrive.com/host/0B_cTARztpNAJVTlXaXY5ZGJkaHc". StatusCode: 503
 5561078658 / 9198293954 [=======================================================================================================>-------------------------------------------------------------------]  60.46% 7m1spull: /Presentations/2014 Group Meetings/Recruiting Summary/Brandon.pptx err: download: failed for url "https://googledrive.com/host/0B7dlTo75514jc09VZ0FacnA3SnM". StatusCode: 503
 5681028943 / 9198293954 [========================================================================================================>-----------------------------------------------------------------]  61.76% 6m44spull: /Presentations/2014 Group Meetings/Recruiting Summary/Brian.pptx err: download: failed for url "https://googledrive.com/host/0B7dlTo75514jU2JaaTFJNmhDakE". StatusCode: 503
 8065191602 / 9198293954 [=====================================================================================================================================================>---------------------]  87.68% 2m2spull: /Multimedia/2015 - Yosemite/Meera/DSC00742.jpg err: download: failed for url "https://googledrive.com/host/0B7dlTo75514jN1hkU2VzazFhWkE". StatusCode: 503
 9177000467 / 9198293954 [==============================================================================================================================================]  99.77% 18m13s

$ drive pull
Resolving...
These 7 file(s) would be overwritten. Use -ignore-conflict to override this behaviour
X /!CLARKLAB/Multimedia/Lab Personnel/MelindaClark2.jpg 0B_cTARztpNAJNXlucWV3S3NhZjA
X /!CLARKLAB/Multimedia/Lab Personnel/CongTrinh1.jpg 0B_cTARztpNAJN1NHQkQ2bldJalU
X /!CLARKLAB/Multimedia/Lab Personnel/CarlyAnderson1.jpg 0B_cTARztpNAJVTlXaXY5ZGJkaHc
X /!CLARKLAB/Multimedia/Lab Personnel/ross_eppler_0.jpg 0B_cTARztpNAJeGJycjl0ZlJKZFk
X /Presentations/2014 Group Meetings/Recruiting Summary/Brandon.pptx 0B7dlTo75514jc09VZ0FacnA3SnM
X /Presentations/2014 Group Meetings/Recruiting Summary/Brian.pptx 0B7dlTo75514jU2JaaTFJNmhDakE
X /Multimedia/2015 - Yosemite/Meera/DSC00742.jpg 0B7dlTo75514jN1hkU2VzazFhWkE
conflicts have prevented a pull operation 
</pre>

This is a bad situation.  I can run -ignore-conflict and obliterate the 'duplicate' files from the first attempt, but I don't *really* know what I'm doing without checking each of these files for real conflicts.

**Comment by odeke-em** [comment]
Hello again @brandoncurtis, thanks for creating this issue.

Oh oh, this highlights the need for some sort of rollback mode for the state of files when pulled or pushed because this situation seems like the state registered to the local DB was that as if the files were successfully pulled. I agree, this is a tricky situation. What did you end up doing?

**Comment by brandoncurtis** [comment]
Agreed, the situation appears to be:
- according to `drive`, the files encountered a 503 error while downloading
- `drive` assumes this means they failed to download, so it writes to the database that they are not present
- the next `drive pull` tries to pull down the files the database says are missing, but... they're not missing, and they're in the way!
- `drive` doesn't check to see if the incoming file and the current file are the same, so it registers a conflict and gives me the option of obliterating the local files or aborting
  - if I choose to abort, the database never gets updated and I'll have exactly the same problem with every subsequent pull
  - if I choose to obliterate the local files, the database is updated and subsequent pulls work as expected

In this case I was pulling a directory for the first time and I knew that there had not been any local changes, so I obliterated the local files.

If I was _not_ pulling for the first time, I would be confused.  If the pulled files affected by this bug were very large, it could cost a lot of bandwidth to re-download them.

**Comment by odeke-em** [comment]
Hello again @brandoncurtis, thank you very much for the patience and for the bug report.
I finally fixed this behavior, by https://github.com/odeke-em/drive/pull/741.

Please get the latest from master.
