### ISSUE TITLE
Progress bar over 100%

### ISSUE THREAD

**Issue by vankessel** [odeke-em/drive#669]
The bar appears to be calculated by:

( amount_added + amount_deleted ) / total_to_be_added

So if there is an equal amount of additions and deletions it will go to around 200%

**Comment by odeke-em** [comment]
Hello there @vankessel, thanks for creating this issue and welcome to drive.

I think this issue is a duplicate of https://github.com/odeke-em/drive/issues/177. Let's move the discussion there.

**Comment by odeke-em** [comment]
Migrated to https://github.com/odeke-em/drive/issues/177.

**Comment by odeke-em** [comment]
Thanks for the patience, fixed by PR https://github.com/odeke-em/drive/pull/784.

Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
