### ISSUE TITLE
Pull folders only

### ISSUE THREAD

**Issue by brandoncurtis** [odeke-em/drive#670]
I have a Google Drive with a huge, deeply-nested file structure.  It is not feasible to store the contents of the Drive locally, and the folder structure is too complicated to keep in my head.

I would like to use `drive pull` to recreate the entire folder structure locally; then I could navigate the structure in the terminal and pull down individual folders when I need them.  Is this possible with the current version of `drive`?

**Comment by odeke-em** [comment]
Roger that. We could have a flag to just pull directories kind of the way you can specify only files with `find . -type f` or only directories with `find . -type d`. This is a useful feature. In fact I think we have it enabled for `drive list --files` to only list files.

**Comment by odeke-em** [comment]
Hello there @brandoncurtis, thank you for this request.
Please get the latest code and then you'll be able to do
```shell
$ drive push --directories a1/m1
$ drive pull --files tf1/tf2
```
Please see PR https://github.com/odeke-em/drive/pull/673.

If there are any issues, feel free to reopen this issue.

**Comment by brandoncurtis** [comment]
Brilliant.  Works great!  Thanks @odeke-em!

**Comment by odeke-em** [comment]
Thanks for checking it out @brandoncurtis and for the kind words :). Good morning!
