### ISSUE TITLE
"file does not exist" when pushing/pulling

### ISSUE THREAD

**Issue by dconathan** [odeke-em/drive#677]
Sorry if I'm missing something obvious, but I can't get `drive push` and `drive pull` to work.  I can `drive rename`, `drive mv`, `drive stat` files and see the changes reflect on my google drive, but any command involving `push` or `pull` gives me an `file does not exist` error. e.g.

```
$ cd ~/drive
$ echo "hello" > hello.txt
$ drive push
file does not exist 
$ drive pull
file does not exist 
```

**Comment by odeke-em** [comment]
Hello there @dconathan, thank you for the report and welcome to drive.

What does `drive version` say?

**Comment by odeke-em** [comment]
@dconathan I think I identified what went wrong, I screwed something up early this morning in this CL https://github.com/odeke-em/drive/commit/2a5875f5e0ff464c5ca244a023b79417d3e7ef53. Fixing it right now :)

**Comment by dconathan** [comment]
Oh yeah, should've mentioned I'm using the [Arch build from the AUR](https://aur.archlinux.org/packages/drive/), though I was getting the same behavior when building using `go get` as per the readme...
```
$ drive version
drive version: 0.3.7
Commit Hash: '2a5875f5e0ff464c5ca244a023b79417d3e7ef53'
Go Version: go1.6.2
OS: linux/amd64
BuildTime: 2016-07-03 12:34:48.238438849 -0500 CDT
```

**Comment by odeke-em** [comment]
Thank you very much @dconathan for reporting this issue. I fixed it with PR https://github.com/odeke-em/drive/pull/678. Please get the latest code and the problem should be gone.

**Comment by dconathan** [comment]
Indeed fixed.  Thanks @odeke-em keep up the good work :+1:

**Comment by odeke-em** [comment]
Thank you 🙏🏾! Please don't hesitate to reach out in case of any issues or questions.
