### ISSUE TITLE
Crash on drive push (uninitialized filters?)

### ISSUE THREAD

**Issue by Sjlver** [odeke-em/drive#681]
Running `drive push -m /path/to/some/file path/in/drive` results in the following crash:

```
panic(0x902ca0, 0xc82000e0c0)
	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc820019380, 0xc82007b698, 0x0, 0x0, 0x0, 0xe67be8, 0x0, 0x0, 0x0, 0x0)
	/home/dslab/gopath/src/github.com/odeke-em/drive/src/changes.go:351 +0x6ea
github.com/odeke-em/drive/src.lonePush(0xc820019380, 0xc820154020, 0x12, 0xc8200191c0, 0x3e, 0xc82012b220, 0x50, 0x0, 0x0, 0x0, ...)
	/home/dslab/gopath/src/github.com/odeke-em/drive/src/push.go:348 +0x24e
github.com/odeke-em/drive/src.(*Commands).Push(0xc820019380, 0x0, 0x0)
	/home/dslab/gopath/src/github.com/odeke-em/drive/src/push.go:100 +0xd47
main.(*pushCmd).pushMounted(0xc820102240, 0xc82000a080, 0x2, 0x2, 0xc820115740, 0x0, 0x0)
	/home/dslab/gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:1077 +0x582
main.(*pushCmd).Run(0xc820102240, 0xc82000a080, 0x2, 0x2, 0xc820115740)
	/home/dslab/gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:837 +0x71
github.com/odeke-em/command.Run()
	/home/dslab/gopath/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/home/dslab/gopath/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/dslab/gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:125 +0x22c7
```

Might be related to this recent commit: https://github.com/odeke-em/drive/commit/2ff98bafeaee12ef3a609b0c8857feb6b0e873a1

**Comment by odeke-em** [comment]
Hello there @Sjlver, thank you for the report and welcome to drive!

Yes in deed, the crash seems related to that commit. Currently `push -m` is already broken https://github.com/odeke-em/drive/issues/641 but I'll file a quick PR to ensure that it doesn't crash at least. Am currently going out for some 4th of July celebrations but I'll dig into this when I get back in a couple of hours.

**Comment by odeke-em** [comment]
@Sjlver, please get the latest from master, fixed by https://github.com/odeke-em/drive/pull/682. Please reopen if it persists. As mentioned, `drive push -m`  is broken on its own. That CL is just a duct tape solution to fix it until I get back home. Thank you.

**Comment by Sjlver** [comment]
Wow, that was fast. Thanks a lot!
