### ISSUE TITLE
.driverc doesn't seem to honor encryption-password

### ISSUE THREAD

**Issue by quisar** [odeke-em/drive#683]
I have the following driverc:

hidden=true
encryption-password=*********

When I push a file drive, the file is not encrypted. On the other end, hidden file are pushed.

Am I missing something obvious?

**Comment by odeke-em** [comment]
Hello there @quisar, thank you for reporting this issue and welcome to drive!

Let me dig through this and get back to you. Thanks!

**Comment by odeke-em** [comment]
Yap, now I recall, I hadn't registered encryption and decryption keys in the resource configuration mapper function here https://github.com/odeke-em/drive/blob/master/src/rc.go#L82-L115 and in particular add their respective keys right before this line here https://github.com/odeke-em/drive/blob/master/src/rc.go#L108.

**Comment by odeke-em** [comment]
Thank you again @quisar for reporting this issue. Closed by PR https://github.com/odeke-em/drive/pull/684, please get the latest code and it should be able to work properly. Please reopen if the problem persists.
