### ISSUE TITLE
confusing help message for push -no-clobber

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#685]
```
$ drive index -h 2>&1 | grep -A1 clobber
-no-clobber
        prevents overwriting of old content
$ drive pull -h 2>&1 | grep -A1 clobber
-no-clobber
        prevents overwriting of old content
$ drive push -h 2>&1 | grep -A1 clobber
-no-clobber
        allows overwriting of old content
```
The description for push -no-clobber seems reversed.

**Comment by odeke-em** [comment]
Hello @kcwu, welcome back to drive! It's been a very long time since you were here. Good to see you are still using drive :)

Thanks for raising this issue. Please feel free to send a patch, or let me know and I can submit one.

**Comment by kcwu** [comment]
Please go ahead fix it. I am too busy to fix it by myself now.

**Comment by odeke-em** [comment]
Please get the latest code. Fixed by https://github.com/odeke-em/drive/issues/688. Thank you for raising this!
