### ISSUE TITLE
Unrecognized import path when trying to install the latest source

### ISSUE THREAD

**Issue by jmohsenm** [odeke-em/drive#694]
I get `package golang.org/x/crypto/scrypt: unrecognized import path "golang.org/x/crypto/scrypt" (parsing golang.org/x/crypto/scrypt: XML syntax error on line 9: expected /> in element)` and some similar errors when trying to install from the latest source by `go get -u github.com/odeke-em/drive/cmd/drive`.

Same thing happens when using other commands in the installation part.

**Comment by odeke-em** [comment]
Hello there @jmohsenm, thank you for the issue and welcome to drive.

So for starters, what version of go are you using?

**Comment by jmohsenm** [comment]
Hello!
I'm using go version go1.6.1 linux/amd64 on opensuse leap 42.1.

**Comment by odeke-em** [comment]
Would it be possible for you to remove or rename `golang.org/x/crypto/scrypt` then try again?

**Comment by jmohsenm** [comment]
I couldn't do that.
But I guess I've found what the problem really is. I guess as google does not allow its go service in my country (Iran), I'm not able to get the dependent packages. And therefor, I get these errors.

**Comment by odeke-em** [comment]
Ah, gotcha. I see. In that case, worry not, when releasing drive, I usually compile binaries https://github.com/odeke-em/drive/releases/tag/v0.3.7. Please confirm checksums in case you are to download them.

**Comment by jmohsenm** [comment]
Thanks for your help!

**Comment by odeke-em** [comment]
Alright, I'll mark this bug as `censored-by-country-policy` and then close it. In releases you can always find binaries compiled along. If you've got a special OS, please let us know and we can add that to the list here https://github.com/odeke-em/drive/blob/master/Makefile.
Thank you for using drive!
