### ISSUE TITLE
`list --trashed` gets stuck and returns no information

### ISSUE THREAD

**Issue by njbbaer** [odeke-em/drive#695]
`list --trashed` does not list trashed items in any directory, and must be force stopped `Ctrl-C`.

> $ drive list --trashed
> ---More---
> ---More---
> ---More---

**Comment by odeke-em** [comment]
Hello there @njbbaer, thank you for reporting this issue and welcome to drive!

I've noticed this bug in list. Would you mind passing in `--no-prompt` to the command for starters?
```shell
$ drive list --no-prompt --trashed
```

Also please note that that command lists trashed objects in the folder mapping to the current working directory.

**Comment by njbbaer** [comment]
I tried adding `--no-prompt` which removed the pagination messages but still gets stuck and returns nothing. Here are my steps to reproduce this issue:
```
$ drive init
$ mkdir test
$ cd test
$ touch test.txt
$ drive push
$ drive trash test.txt
$ drive list --no-prompt --trashed
```
However `drive untrash test.txt` works fine.

**Comment by njbbaer** [comment]
I've been poking around and I have some more details. It seems there are multiple problems going on here.

For starters, the pagination prompts print before the list itself. This occurs for all `drive list` not just trashed. I took a look through the source to see if I could fix this. It appears `func breadthFirst` of `list.go` iterates over `reqDoPage` to put the files into a collection, which triggers the prompts early. Only afterwards is the collection sorted and finally printed.

So `drive list --trashed --no-prompt` actually works but only in the root directory and prints all files in trash. If you have many items in trash like I do it will appear stuck for a while.

If I attempt to list trashed files inside a directory I get ```"/foo" cannot be found remotely```. If I then `drive trash foo` and `drive list --trashed foo` it prints all trashed files like root, not just those in the specified directory.

Ultimately I'd like to submit a pull request to fix these issues. So let me know if you have any input and I'll try to make the changes.

**Comment by odeke-em** [comment]
@njbbaer  thanks for debugging this, yeah I too noticed it in list but haven't worked on it. My apologies if this has taken a lot of your time. Please feel free to send the PR, looking forward to it! Thanks!

**Comment by njbbaer** [comment]
No worries, happy to help! I'm trying to build experience contributing to open source projects.

#700 fixes the major issue that was breaking `list -trashed` which should now return all trashed items in the current working directory.

I'd also like to fix the premature pagination prompts which are trigged when iterating over `reqDoPage` to create a collection. However, in order to sort the results the collection must still be created before it is printed.
