### ISSUE TITLE
Add an option to skip *.desktop files creation

### ISSUE THREAD

**Issue by chevillet** [odeke-em/drive#697]
See: https://github.com/odeke-em/drive/issues/660#issuecomment-224118945

Thanks in advance.

**Comment by odeke-em** [comment]
🙏🏾 thanks for creating this, working on it now.

**Comment by odeke-em** [comment]
@chevillet all done with PR https://github.com/odeke-em/drive/pull/698. Please get the latest code. FYI you can set this flag in your .driverc file in the root of your project e.g
```shell
$ cat << ! >> .driverc
> desktop-links=false
> !
```

**Comment by chevillet** [comment]
Sounds great, thanks a lot!

**Comment by odeke-em** [comment]
Let me know how it goes. Please don't hesitate to reopen this issue if things aren't working as expected.

**Comment by chevillet** [comment]
Sure, I will, thanks again for your work on drive!
