### ISSUE TITLE
undefined error on Raspberry Pi 

### ISSUE THREAD

**Issue by hubaskidoo** [odeke-em/drive#704]
I'm not a go developer. I'm attempting to install the Drive command so I can stream video to my Google drive account from the camera on my Raspberry Pi.

I'm not sure if the error is mine or if I've come across an incompatibility between Drive and Raspberry PI.

This is what I've done:
I installed go using
>sudo apt-get install golang git mercurial
>mkdir go

Verified go directory was in my $HOME path.
I then typed:
>export GOPATH=$HOME/go
>export $PATH=$PATH:$GOPATH/bin

Verified $GOPATH was set and then I typed
>go get -u github.com/odeke-em/drive/cmd/drive

Go went silent so I hit enter again to ensure I had hit enter. After a few minutes the following error messages spewed out:
>go/src/golang.org/x/oauth2/jws/jws.go:67: undefined: base64.RawURLEncoding
>go/src/golang.org/x/oauth2/jws/jws.go:85: undefined: base64.RawURLEncoding
>go/src/golang.org/x/oauth2/jws/jws.go:105: undefined: base64.RawURLEncoding
>go/src/golang.org/x/oauth2/jws/jws.go:116: undefined: base64.RawURLEncoding
>go/src/golang.org/x/oauth2/jws/jws.go:143: undefined: base64.RawURLEncoding
>go/src/golang.org/x/oauth2/jws/jws.go:166: undefined: base64.RawURLEncoding
> golang.org/x/net/context/ctxhttp
>go/src/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go:36: req.Cancel undefined (type *http.Request has no field or method Cancel)

I thought perhaps either I screwed up installing go or there is no base64 encoder for Raspberry pi but thought I'd ask before trying a different approach.

My apologies if I'm mis-using this Issues thread - I'm not a git user either.

**Comment by odeke-em** [comment]
Hello there @hubaskidoo, thank you for the report and welcome to drive.

I see, so it seems like apt-get is installing an outdated version of Go. Go no longer needs Mercurial. You can install Go by following the instructions at https://golang.org/doc/install/source.
Also I've been trying to make binaries for drive whenever I make a new release. Please see the latest binaries at https://github.com/odeke-em/drive/releases e.g https://github.com/odeke-em/drive/releases/tag/v0.3.7 under binaries section, drive-armv*. You'll need to see what arm version your Raspberry Pi is running.

**Comment by hubaskidoo** [comment]
Hi odeke-em, thanks for the reply.

It's a Raspberry 3 with a Cortex a53 processor. I don't see a53 as one of you binaries so I'll give compiling the source on the raspberry a shot after I re-install go.

**Comment by davecheney** [comment]
Use the arm build, not the arm64 build, as the raspberry pi runs in 32 bit arm mode

**Comment by davecheney** [comment]
Armv6 or armv7 will be fine, armv5 will also work.

**Comment by odeke-em** [comment]
Thank you @davecheney 🙏🏾

**Comment by odeke-em** [comment]
Closing this issue, following @davecheney's advice on how to build it for arm.

@hubaskidoo, if the issue persists, please ping back here. Thanks again @davecheney.
