### ISSUE TITLE
Can't install with Go1.6.2

### ISSUE THREAD

**Issue by ZhengZhaoHeng** [odeke-em/drive#705]
Hi, 

I tried to install drive with following instruction:

> go get -u github.com/odeke-em/drive/cmd/drive

But I got some error:

> [zhaohenz@flux-login1 ~]$ go get -u github.com/odeke-em/drive/cmd/drive
> # cd .; git clone https://go.googlesource.com/crypto /home/zhaohenz/gopath/src/golang.org/x/crypto
> Cloning into '/home/zhaohenz/gopath/src/golang.org/x/crypto'...
> fatal: https://go.googlesource.com/crypto/info/refs not valid: is this a git repository?
> package golang.org/x/crypto/scrypt: exit status 128
> # cd .; git clone https://go.googlesource.com/net /home/zhaohenz/gopath/src/golang.org/x/net
> Cloning into '/home/zhaohenz/gopath/src/golang.org/x/net'...
> fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
> package golang.org/x/net/context: exit status 128
> # cd .; git clone https://go.googlesource.com/oauth2 /home/zhaohenz/gopath/src/golang.org/x/oauth2
> Cloning into '/home/zhaohenz/gopath/src/golang.org/x/oauth2'...
> fatal: https://go.googlesource.com/oauth2/info/refs not valid: is this a git repository?
> package golang.org/x/oauth2: exit status 128
> package golang.org/x/oauth2/google: cannot find package "golang.org/x/oauth2/google" in any of:
>         /sw/lsa/centos7/go/1.6.2/src/golang.org/x/oauth2/google (from $GOROOT)
>         /home/zhaohenz/gopath/src/golang.org/x/oauth2/google (from $GOPATH)
> # cd .; git clone https://code.googlesource.com/google-api-go-client /home/zhaohenz/gopath/src/google.golang.org/api
> Cloning into '/home/zhaohenz/gopath/src/google.golang.org/api'...
> fatal: https://code.googlesource.com/google-api-go-client/info/refs not valid: is this a git repository?
> package google.golang.org/api/drive/v2: exit status 128
> package google.golang.org/api/googleapi: cannot find package "google.golang.org/api/googleapi" in any of:
>         /sw/lsa/centos7/go/1.6.2/src/google.golang.org/api/googleapi (from $GOROOT)
>         /home/zhaohenz/gopath/src/google.golang.org/api/googleapi (from $GOPATH)

How can I solve this problem?

**Comment by odeke-em** [comment]
Hello there @ZhengZhaoHeng, thanks for the question and welcome to drive.

Nothing jumps off the top of my head for what could be causing this problem except a suspicion of a not properly set up $GOPATH, so let's try a game of elimination.

For starters, would you mind doing
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
``` 
this way we can see which repos/packages have been properly installed and to where they are.
Also could you double check that your $GOPATH is properly installed, as described here https://golang.org/doc/code.html#GOPATH

**Comment by ZhengZhaoHeng** [comment]
Hi, @odeke-em, thanks for your reply.

As for my GOPATH, I have added following in my ~/.bashrc:
`export GOPATH=$HOME/gopath/
 export PATH=$GOPATH:$GOPATH/bin:$PATH
`
and ran the command:
`source ~/.bashrc`

And I also did:
`go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen`

The outputs are:
'
[zhaohenz@flux-login1 ~]$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
github.com/odeke-em/drive (download)
github.com/odeke-em/command (download)
github.com/boltdb/bolt (download)
github.com/cheggaaa/pb (download)
github.com/mattn/go-isatty (download)
github.com/odeke-em/cache (download)
github.com/odeke-em/cli-spinner (download)
github.com/odeke-em/go-utils (download)
github.com/odeke-em/go-uuid (download)
Fetching https://golang.org/x/crypto/scrypt?go-get=1
Parsing meta tags from https://golang.org/x/crypto/scrypt?go-get=1 (status code 200)
get "golang.org/x/crypto/scrypt": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/scrypt?go-get=1
get "golang.org/x/crypto/scrypt": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
# cd .; git clone https://go.googlesource.com/crypto /home/zhaohenz/gopath/src/golang.org/x/crypto
Cloning into '/home/zhaohenz/gopath/src/golang.org/x/crypto'...
fatal: https://go.googlesource.com/crypto/info/refs not valid: is this a git repository?
package golang.org/x/crypto/scrypt: exit status 128
github.com/odeke-em/exponential-backoff (download)
github.com/odeke-em/extractor (download)
github.com/odeke-em/log (download)
github.com/odeke-em/meddler (download)
github.com/odeke-em/pretty-words (download)
github.com/odeke-em/semalim (download)
github.com/odeke-em/statos (download)
github.com/skratchdot/open-golang (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
# cd .; git clone https://go.googlesource.com/net /home/zhaohenz/gopath/src/golang.org/x/net
Cloning into '/home/zhaohenz/gopath/src/golang.org/x/net'...
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
package golang.org/x/net/context: exit status 128
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
get "golang.org/x/oauth2": found meta tag main.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2?go-get=1
golang.org/x/oauth2 (download)
# cd .; git clone https://go.googlesource.com/oauth2 /home/zhaohenz/gopath/src/golang.org/x/oauth2
Cloning into '/home/zhaohenz/gopath/src/golang.org/x/oauth2'...
fatal: https://go.googlesource.com/oauth2/info/refs not valid: is this a git repository?
package golang.org/x/oauth2: exit status 128
Fetching https://golang.org/x/oauth2/google?go-get=1
Parsing meta tags from https://golang.org/x/oauth2/google?go-get=1 (status code 200)
get "golang.org/x/oauth2/google": found meta tag main.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2/google?go-get=1
get "golang.org/x/oauth2/google": verifying non-authoritative meta tag
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
package golang.org/x/oauth2/google: cannot find package "golang.org/x/oauth2/google" in any of:
        /sw/lsa/centos7/go/1.6.2/src/golang.org/x/oauth2/google (from $GOROOT)
        /home/zhaohenz/gopath/src/golang.org/x/oauth2/google (from $GOPATH)
Fetching https://google.golang.org/api/drive/v2?go-get=1
Parsing meta tags from https://google.golang.org/api/drive/v2?go-get=1 (status code 200)
get "google.golang.org/api/drive/v2": found meta tag main.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at https://google.golang.org/api/drive/v2?go-get=1
get "google.golang.org/api/drive/v2": verifying non-authoritative meta tag
Fetching https://google.golang.org/api?go-get=1
Parsing meta tags from https://google.golang.org/api?go-get=1 (status code 200)
google.golang.org/api (download)
# cd .; git clone https://code.googlesource.com/google-api-go-client /home/zhaohenz/gopath/src/google.golang.org/api
Cloning into '/home/zhaohenz/gopath/src/google.golang.org/api'...
fatal: https://code.googlesource.com/google-api-go-client/info/refs not valid: is this a git repository?
package google.golang.org/api/drive/v2: exit status 128
Fetching https://google.golang.org/api/googleapi?go-get=1
Parsing meta tags from https://google.golang.org/api/googleapi?go-get=1 (status code 200)
get "google.golang.org/api/googleapi": found meta tag main.metaImport{Prefix:"google.golang.org/api", VCS:"git", RepoRoot:"https://code.googlesource.com/google-api-go-client"} at https://google.golang.org/api/googleapi?go-get=1
get "google.golang.org/api/googleapi": verifying non-authoritative meta tag
package google.golang.org/api/googleapi: cannot find package "google.golang.org/api/googleapi" in any of:
        /sw/lsa/centos7/go/1.6.2/src/google.golang.org/api/googleapi (from $GOROOT)
        /home/zhaohenz/gopath/src/google.golang.org/api/googleapi (from $GOPATH)
github.com/odeke-em/ripper (download)
'
It seems that everything with golang goes wrong. Thanks again for your help.

**Comment by odeke-em** [comment]
Ah I see, meanwhile before we figure this out, please feel free to checkout the binaries from the last release that I made https://github.com/odeke-em/drive/releases.

### By hand mitigiation
Before we can figure out what is going on with go get -u failing to reach those repos:
One thing that you could do to get the code to download is manually go into the directories and perform git clones by copying the gitURL and matching the respective directory in this format
```shell
$ git clone <GIT_URL> <ABSOLUTE_PATH_THAT_WAS_COMPLAINED_ABOUT>
```

e.g for   OAuth2 and Google-API-GO-Client
```shell
$ git clone https://go.googlesource.com/oauth2 $GOPATH/src/golang.org/x/oauth2
$ git clone https://code.googlesource.com/google-api-go-client $GOPATH/src/google.golang.org/api
```
same for all the other URLs

**Comment by ZhengZhaoHeng** [comment]
The binary works perfectly!

I also tried to clone the repo myself by:
`git clone https://go.googlesource.com/oauth2 $GOPATH/src/golang.org/x/oauth2`

and I got this:
```
Cloning into '/home/zhaohenz/gopath//src/golang.org/x/oauth2'...
fatal: https://go.googlesource.com/oauth2/info/refs not valid: is this a git repository?
```
It is weird and I can't find any solution by searching this error on Google.

**Comment by odeke-em** [comment]
Perhaps you should try first
```shell
$ mkdir -p /home/zhaohenz/gopath/src/golang.org/x/oauth2
```
as I noticed the "Cloning into '/home/zhaohenz/gopath//src/golang.org/x/oauth2'..." has two slashes "//".

OR
To clone oauth2, please do
```shell
$ go get golang.org/x/oauth2
```

**Comment by odeke-em** [comment]
Please use the latest >= Go1.7. Timed out.

**Comment by daluu** [comment]
FYI, regarding `fatal: https://go.googlesource.com/oauth2/info/refs not valid: is this a git repository?`, I got that error as well doing standard git clone & go get.

Looking up the error, came across this: https://confluence.atlassian.com/bbkb/info-refs-not-valid-is-this-a-git-repository-313467635.html

maybe the oauth2 public source repo has been potentially corrupted? Or there's an access/usage limit issue at the moment?
