### ISSUE TITLE
Multiple/Single uploads

### ISSUE THREAD

**Issue by NablaMetal** [odeke-em/drive#709]
Firt of all, thank you for this project, it is very useful to me.

However when pushing large files online there is a high probability of failure (internet connection, system freeze...) I have noticed files are uploaded like 3 at a time.

Is there a way to limit the push to one file at a time ? The transfer would be safer for cases with large files/low bandwidth)

Thank you,

NablaMetal
drive version: 0.3.7

**Comment by odeke-em** [comment]
Hello there @NablaMetal, thank you for the question and welcome to drive!

Yes, you can limit the number of files being pushed by setting environment variable `DRIVE_GOMAXPROCS`. My apologies, as it is not documented in the README, but it is in the wiki https://github.com/odeke-em/drive/wiki#env-variables.
You can set it like this
```shell
$ DRIVE_GOMAXPROCS drive push fileA fileB dirA....
```
or in your environment like this
```shell
$ cat << ! >> ~/.bashrc
> export DRIVE_GOMAXPROCS=8
> !
$ source ~/.bashrc
```

Although, it should really be a variable option set on the commandline.

**Comment by NablaMetal** [comment]
Thank you very much. Sorry I forgot to read the wiki page !

Best regards,

NablaMetal
