### ISSUE TITLE
Feature: Multiple accounts/credential support?

### ISSUE THREAD

**Issue by fourjay** [odeke-em/drive#71]
I have a work (edu) GAE account and a personal account. It would be nice to have access to both of them on the same machine. :-)

**Comment by odeke-em** [comment]
I actually have about 5 different accounts on my machine. All you have to do is run `drive init` in different directories for each othem, and authorize for the respective accounts.
e.g
```shell
$ drive init jackbauer.drive
$ drive init chloeobrien.drive
$ drive init tonyalmeida.drive
```
And authorize the respective accounts.

**Comment by fourjay** [comment]
Thanks!
