### ISSUE TITLE
push: prevent deletion of files from remote directory, that have been removed locally

### ISSUE THREAD

**Issue by slystone** [odeke-em/drive#718]
I'm using drive to backup docs, periodically I'd like to save space from local drive but if I remove files from local dir,  the same will happen remotely. 

Is it possible to prevent PUSH from deleting extraneous files from remote directory?

**Comment by odeke-em** [comment]
Hello there @slystone, thank you for the question and welcome to drive.

Yes, you can prevent deletions by using push option `--exclude-ops` https://github.com/odeke-em/drive#note e.g
```shell
$ drive push --exclude-ops delete myBackups
```
and that will prevent deletions.
--exclude-ops takes CRUD options create, read, update, delete.

You can also use, `--no-clobber` https://github.com/odeke-em/drive#pushing
```shell
$ drive push --no-clobber
```
and that should only allow additions.

Hope this helps.

**Comment by odeke-em** [comment]
Also btw, there is `untrash` https://github.com/odeke-em/drive#trashing-and-untrashing which you can use to restore on remote, items that have been trashed remotely.

**Comment by tsoernes** [comment]
Can you add no-clobber to the `drive push -h`documentation in CLI? I assume it works for pull as well. For such an important feature it's strangely absent.

Thanks

**Comment by slystone** [comment]
Sorry for the delay: perfect, thank you very much!
