### ISSUE TITLE
proxy blocks tcp://drive.google.com:443 so pull fails with expired x509 cert; init, ls and push work fine

### ISSUE THREAD

**Issue by mvdbos** [odeke-em/drive#719]
This is the error I get on each file that is being fetched from the remote with `drive pull`. 

`Get https://googledrive.com/host/xxxxxxxxxxxxxxxxxx: x509: certificate has expired or is not yet valid`.

As mentioned in the subject, `init`, `ls` and `push` work fine. I also checked if my system clock is current as mentioned in #152. It is fine.

Any ideas?

**Comment by mvdbos** [comment]
Hmm, it seems this only happens when I am behind our corporate proxy. This proxy blocks tcp://drive.google.com:443. 

Why are some drive commands begin blocked and others not? Do they connect to different endpoints?

**Comment by odeke-em** [comment]
Hello there @mvdbos, thank you for the question and welcome to drive!

Aha, I got a similar problem in June https://twitter.com/odeke_et/status/748422470840029184 and I discovered later on that there was a MITM proxy that was trying me #conspiracy #whereAreBiggieAndPac #illuminati.

Anyways, yeah there isn't much we can do for this issue unless you get them to not block drive.google.com:443.
