### ISSUE TITLE
Paging doesn't work on OS X

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#724]
I've just installed latest version from github. Paging doesn't work. If you press enter at "--More--", you just get a blank line.

**Comment by odeke-em** [comment]
Hello there @bjohas, thanks for filing this issue.

Yeah the first `--More--` displayed is a bug, but if you pressed Enter the second time it should paginate. Gonna fix this.

**Comment by bjohas** [comment]
For me, I just get several --More--, i.e. I see 

```
(e.g. first page of files)
---More--- (press enter)
---More--- (press enter)
---More--- (press enter)
---More--- (press enter)
```

Thanks!

**Comment by odeke-em** [comment]
@bjohas please get the latest from master.

**Comment by bjohas** [comment]
Thanks!
