### ISSUE TITLE
Maximum items for -pagesize

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#725]
There seems to be a limit for -pagesize - what is it? It would be good if there wasn't a limit, so that the full drive can be listed.

Alternatively, there should be an error message if pagesize is set to more than the allowed limit.

Thanks!!

**Comment by odeke-em** [comment]
Hello there @bjohas, thanks for the question.

Yes there is a default limit for the page size that you can get by doing
```shell
$ drive list -h
...
  -pagesize int
    	number of results per pagination (default 100)
...
```

Yes, you can turn off paging by using flag `--no-prompt`
```shell
$ drive list --no-prompt
```

**Comment by bjohas** [comment]
Right - thanks!! Turns out I just wasn't patient enough - the process stops at times, before more pages are displayed! Many thanks!
