### ISSUE TITLE
explicitly setting the mod time of a file on drive

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#726]
It is possible to use drive to set the mod time of a file on drive?

Thanks!

**Comment by odeke-em** [comment]
Hello there @bjohas, thank you for the question and welcome to drive.

So let me try to understand your question:
`Can drive set the mod time of a file on Google Drive?` 
1. Did you mean change it to the current time, as in touch it? If so, yes:
```shell
$ drive touch after.png before.png doc1.7.png 
/codereview-screenshots/before.png: 2016-09-10 21:27:34 +0000 UTC
/codereview-screenshots/doc1.7.png: 2016-09-10 21:27:34 +0000 UTC
/codereview-screenshots/after.png: 2016-09-10 21:27:34 +0000 UTC
```

2. Did you mean match the modTime as with a local file? If so, yes:
```shell
$ drive touch after.png 
/codereview-screenshots/after.png: 2016-09-10 21:38:07 +0000 UTC
$ drive diff after.png 
File: /codereview-screenshots/after.png
* local:          2016-09-10T20:35:46.000Z                
* remote:         2016-09-10T21:38:07.000Z                
$ drive push after.png 
Resolving...
M /codereview-screenshots/after.png
Modification count 1 src: 253.62KB dest: 253.62KB
Proceed with the changes? [Y/n]:y
 259707 / 259707 [=============================================================================================================================] 100.00% 0s
$ drive diff after.png && echo "They are the same"
They are the same
```

**Comment by bjohas** [comment]
Thanks,

The use case is that when moving photos / videos to SD card, Google drive
picked up the updated time stamps, so the pictures are no longer sorted by
date. There doesn't seem to be a way to adjust these with the web interface.

So it would be possible to pull these, adjust the time stamp on local disk,
and then push?

Because it's a lot of data, I was hoping that through the API you would be
able to set the date remotely say something like:

drive touch -t 201603040000 after.png

**Comment by odeke-em** [comment]
Oh okay, thanks for the clarification. I see, yeah, drive doesn't yet allow that.

However, I just woke up a few hours ago and won't get back up to sleep for a few more others so let me see if I can hack this up.

**Comment by odeke-em** [comment]
@bjohas please get the latest from master, I've addressed this with CL https://github.com/odeke-em/drive/pull/729 and added examples to the README.

Now you'll be able to set it, for example like this
```shell
$ drive touch --time 20120202120000 ComedyPunchlineDrumSound.mp3
/share-testing/ComedyPunchlineDrumSound.mp3: 2012-02-02 12:00:00 +0000 UTC
```

OR

```
$ drive touch --format "2006-01-02-15:04:05.0000Z" --time "2016-02-03-08:12:15.0070Z" outf.go
/share-testing/outf.go: 2016-02-03 08:12:15 +0000 UTC
```

OR

```shell
$ drive touch --duration -30h ComedyPunchlineDrumSound.mp3 outf.go
/share-testing/outf.go: 2016-09-10 08:06:39 +0000 UTC
/share-testing/ComedyPunchlineDrumSound.mp3: 2016-09-10 08:06:39 +0000 UTC
```

Thank you for filing the issue and hope this helps solve the problem for you.

**Comment by bjohas** [comment]
That's great many thanks - will try it!
