### ISSUE TITLE
Error 500?

### ISSUE THREAD

**Issue by creighto** [odeke-em/drive#738]
Hey @odeke-em, first of all, thank you so much for maintaining this invaluable Linux client! It has been working great for me for a couple of days now.

But as of today, it seems to have stopped working entirely. I only keep getting the 500 error, e.g.

    > drive ls
    googleapi: Error 500: Internal Error, internalError

When trying to pull, it actually wants to erase my entire local folder… 💥 

    > drive pull
    Resolving...
    googleapi: Error 500: Internal Error, internalError
    - {...long list...}
    Deletion count 6894 dest: 28.40GB
    Proceed with the changes? [Y/n]:

Is there an option to make the output more verbose to debug the situation? -- Thanks.

**Comment by odeke-em** [comment]
Hello there @creighto, thank you for the bug report and welcome to drive.

Yap, this is a nasty bug, but I got time this afternoon and am about to push up a fix.

**Comment by odeke-em** [comment]
Please get the latest from master, fixed by https://github.com/odeke-em/drive/pull/741.
