### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by shaggytwodope** [odeke-em/drive#743]
@odeke-em *cough* 0.3.8 missing on release made. Your so bad at version bump bro lol.

**Comment by odeke-em** [comment]
Hello there @shaggytwodope, thanks for the head up.

Ahaha, true that. My bad. Apologies for the late reply, I had gone out to grab dinner and then a movie.

I'll make the bump, then remake the release.

**Comment by odeke-em** [comment]
@shaggytwodope thanks for the reminder. Done and re-released https://github.com/odeke-em/drive/releases/tag/v0.3.8.

**Comment by shaggytwodope** [comment]
@odeke-em right on, fixed the aur release. I'll do the ppa and debian repo shortly before bed.
