### ISSUE TITLE
Source download from "downloads" section packages old incompatible version of github.com/odeke-em/command

### ISSUE THREAD

**Issue by vrusinov** [odeke-em/drive#749]
Steps to reproduce:

1. Download https://github.com/odeke-em/drive/archive/v0.3.8.tar.gz
2. installing non-bundled dependencies (do not install github.com/odeke-em/command/blob/master/command.go)
3. try to build with no network access

Build fails with:

```
cmd/drive/main.go:85:58: error: argument 3 has incompatible type (incompatible type for method 'Run' (different number of parameters))
  bindCommandWithAliases(drive.AboutKey, drive.DescAbout, &aboutCmd{}, []string{})
                                                          ^
cmd/drive/main.go:86:56: error: argument 3 has incompatible type (incompatible type for method 'Run' (different number of parameters))
  bindCommandWithAliases(drive.CopyKey, drive.DescCopy, &copyCmd{}, []string{})

```
(and more)

Looks like this is because https://github.com/odeke-em/drive/archive/v0.3.8.tar.gz has old version of `./drive-gen/Godeps/_workspace/src/github.com/odeke-em/command/command.go` which has

```go
type Cmd interface {
    Flags(*flag.FlagSet) *flag.FlagSet
    Run(args []string)
}
```

while `cmd/drive/main.go` has stuff like this:
```go
func (cmd *versionCmd) Run(args []string, definedFlags map[string]*flag.Flag)
```

It appears interface was changed in https://github.com/odeke-em/command/commit/91ca5ec5e9a1bc2668b1ccbe0967e04a349e3561 but bundled library was never updated for odeke-em/drive.

Please either update it (retrospectively?) or remove altogether.

Workaround is obvious: have newer version of github.com/odeke-em/command/commit in GOPATH before bundled one.

**Comment by odeke-em** [comment]
Thank you for reporting this issue.

I'll entirely remove my bundled packages because those can always be refreshed.

**Comment by odeke-em** [comment]
Done with https://github.com/odeke-em/drive/pull/753, I'll make a small point release so that you can re-download and build from the tar with less problems.

**Comment by odeke-em** [comment]
I've made for you a small point release at https://github.com/odeke-em/drive/releases/tag/v0.3.8.1 that shouldn't have this problem.

Thank you for reporting it!

**Comment by shaggytwodope** [comment]
@odeke-em from what I can tell this release doesnt change anything from already built packages. I might not version bump the ppa and stuff. That cool, or rather version match current release tag?

**Comment by odeke-em** [comment]
@shaggytwodope if you don't need to use the Godeps code, then no biggie but if the PPA stuff uses the Godeps code, perhaps you'll need to bump it too.

**Comment by shaggytwodope** [comment]
@odeke-em right on mate,. I've updated the aur package because it's no biggie for that. Just for reference if any users post issues etc the ppa isnt going to be updated til next release. As there is no need for it. (see I read changelogs lol) Much love, thanks for responding promptly as always.
