### ISSUE TITLE
Command for copying link

### ISSUE THREAD

**Issue by samogot** [odeke-em/drive#750]
When I use Google Drive web app, I can make symlinks by holdind Ctrl key either while drag&drop or while usind Move to dialog. To say correctly it isn't named 'symlinks', rather object has several parent folders (when i rename file/folders - it will rename in each of parent folders). 

![2016-09-29 18 44 31](https://cloud.githubusercontent.com/assets/11226228/18961197/ddbeec0c-8674-11e6-9bce-6115b050cf60.png)

is there way to achieve such result using this util? I expected that 'copy' command works like this (as there is no way to 'copy' throw web interface), but it creates new file instead of linking

**Comment by odeke-em** [comment]
Hello there @samogot, thanks for the report and welcome to drive!

So, for starters, drive doesn't have linking, so I'll consider this a feature request.
The problem though is with pulling and pushing to those "linked files", that's gonna be a tricky one.

**Comment by samogot** [comment]
I'm already using this feature using web interface (and other peoples can), so it's already "tricky". I maintain linux symlinks on my desktop by myself and don't use push from root dir. This is ok for me. 

As I can see, implementing this feature would be rather easy - just add a condition for running [this line](https://github.com/odeke-em/drive/blob/aa79e324a22a2073b68c61783f4015426b7dbe67/src/move.go#L150) of move command. for example as '--copy-link' cli parameter. I might try implement it myself, but i haven't experience in golang)) Is there any guide how to set up developer environment and run modified code?)
