### ISSUE TITLE
Make all options consistent

### ISSUE THREAD

**Issue by jean-christophe-manciot** [odeke-em/drive#772]
Hi there,

Some options begin with '--', others with '-'.
Is it possible to choose a single format?
Also, can we define any kind of option inside .driverc, i.e including those which do not require any '=' after the option name?

**Comment by sselph** [comment]
Go will allow you to do -- or - for any flag. It is probably just inconsistent documentation. The list of options you can pass via .driverc doesn't seem to be everything but the list seems to be here: 
https://github.com/odeke-em/drive/blob/9b9b7fd2ec0dea3c87aa032475fcec07bb8240e8/src/rc.go#L90-L113

Those are are the variables that can be looked up here to see the actual value

https://github.com/odeke-em/drive/blob/7222324775c88eda7115f3db828e6412f9182651/src/help.go#L28

Like `NoPromptKey` is `no-prompt`. @odeke-em might have better documentation somewhere. The bool options like this would be `no-prompt=true` in the file.

**Comment by jean-christophe-manciot** [comment]
Thanks for your answer.
Due to lack of comments, it's difficult to guess which group of constants qualifies as recognized options in .driverc:
- the [first one](https://github.com/odeke-em/drive/blob/7222324775c88eda7115f3db828e6412f9182651/src/help.go#L70)
- or the [second one](https://github.com/odeke-em/drive/blob/7222324775c88eda7115f3db828e6412f9182651/src/help.go#L209)
- or ... maybe both?

**Comment by jean-christophe-manciot** [comment]
It seems that only <key>=<value> lines are accepted in .driverc.

**Comment by odeke-em** [comment]
@jean-christophe-manciot thank you for posting the issue.

Yap, what @sselph said in https://github.com/odeke-em/drive/issues/772#issuecomment-255543808. Unfortunately Go isn't strict about -- and - for short and long options.

Yeah we should document this more, the weekend is coming up.

@jean-christophe-manciot, that's right .driverc is in the form of line by line key=value documented
here https://github.com/odeke-em/drive#driverc with examples as well.

**Comment by shaggytwodope** [comment]
@odeke-em what is the preference? I'd love to go over all the documentation and edit it accordingly. Need some pr's for hacktoberfest lol.

**Comment by jean-christophe-manciot** [comment]
@odeke-em Is it possible to enhance drive by adding the possibility to also declare some options in .driverc **which do not need a value**, i.e something like:
```
key1=vlaue1
key2 
key3=value3 
key4=value4 
key5
key6 
...
```
where only relevant keys for the current operation are read and others are dismissed without error.
Or if the former is to complex to parse, there's also the possibility to **structure .driverc** a little bit like this:
```
[global]
key1=value1
key2=value21

[command_1] # such as pull
key3=value31
key4
key5=value51

[command_2] # such as share
key3=value32
key2=value22
key5=value52
...
```
where the global keys apply until the same keys are overridden by more specific values in [command_n] sections.
```
The goal is to simplify drive's usage.

**Comment by odeke-em** [comment]
@shaggytwodope  `@odeke-em what is the preference? I'd love to go over all the documentation and edit it accordingly. Need some pr's for hacktoberfest lol.`
Awesome, that'd be dope! Please go ahead and happy HacktOberfest!

@jean-christophe-manciot sounds reasonable, thanks for the suggestions. Yap we can change that in https://github.com/odeke-em/drive/blob/master/src/rc.go#L165-L198 to make some options optional. Although the problem then becomes say the default for `long` is false, while the default for `owners` is true, we have to change up the truth values of those options.

Now I like the suggestion of structuring the .driverc commands in sections. For sure let's make this a feature request. Would you mind opening a separate issue for that? That way we won't lose track of that information.
