### ISSUE TITLE
Drive error

### ISSUE THREAD

**Issue by sku286** [odeke-em/drive#774]
My logs are getting put to bin by itself . two folders are getting created with same name also.So there is conflict issue when i try to push logs in the folders

**Comment by odeke-em** [comment]
Hello @sku286, thank you for filing the issue and welcome to drive.

For starters, would you mind giving some more context to your issue?
What does `drive version` say? What operating system are you on? What version of Go are you using? How did you install drive?

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Issue timed out, please get the latest and try again, then reopen if it reproducible.
