### ISSUE TITLE
Error while pushinfg

### ISSUE THREAD

**Issue by AmitLevin** [odeke-em/drive#777]
Hello,
I've been using drive for quite a while. 
lately I'm encountering the following error while running my back up script:  

`Get https://www.googleapis.com/drive/v2/files?alt=json&q=%22root%22+in+parents+and+title+%3D+%22.config%22+and+trashed%3Dfalse: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_grant"
}

Get https://www.googleapis.com/drive/v2/about?alt=json: oauth2: cannot fetch token: 400 Bad Request
Response: {   "error" : "invalid_grant" } 
`

**Comment by odeke-em** [comment]
Hello there @AmitLevin, thank you for filing the issue and welcome to drive!

For starters would you mind telling me your drive version?
Did you perhaps revoke OAuth access from your account?
If so, you can always re-initialize it by running
```shell
$ drive init .
```
at the root of your drive's parent directory and follow the steps printed out.

**Comment by AmitLevin** [comment]
Thank you for the fast response! 

Re-initing solved it. 

I was working on my backup script the other day and ran:
`drive init .`
On another directory. 

Any way it works again.

**Comment by odeke-em** [comment]
Aye aye, I'll close the issue then. Please reopen if it persists.
