### ISSUE TITLE
"Proceed with the changes" line malformed

### ISSUE THREAD

**Issue by gjalsem** [odeke-em/drive#78]
When I run ``drive push`` I get this prompt:

`` | ceed with the changes? [Y/n]:  – ``

The ``|`` you see there is from the ``Resolving...`` animation, so it can also be a `\` etc. So that doesn't look right, I guess it should be:

``Proceed with the changes? [Y/n]: Y``

(Yes being the default if you press enter is as intended?)

I'm using Ubuntu 14.04 with just a regular GNOME Terminal, and version 0.1.1 of drive.

**Comment by odeke-em** [comment]
Thank you for reporting this. In deed I shall pause the spinner, PR coming up soon.

**Comment by odeke-em** [comment]
It actually made me go back and revisit how I had set things up as well as the package that I had written for the spinner. To fix the spinner in its package, I had to ensure a full shutdown before return as seen here https://github.com/odeke-em/cli-spinner/commit/4fba755d512f08982d0d2cb654d84c1cc5974dee. To fix the spinner in drive I had to move the respective stop calls to pull and push as seen here https://github.com/odeke-em/drive/commit/2f83616eba1024fb5a6d06f34ecd9ed7bb304c6c
Please pull from master and try again then let me know if it is fixed.

Thank you very much for reporting this.

**Comment by gjalsem** [comment]
I tried compiling from master yesterday, but it didn't work on the first attempt and I didn't have time to look into it further. But today I got version 0.1.2 from the Ubuntu PPA and the problem is indeed fixed. Thanks!
