### ISSUE TITLE
drive md5sum --depth level must be incremented by 1 to have the desired effect

### ISSUE THREAD

**Issue by jean-christophe-manciot** [odeke-em/drive#783]
```
Google Drive/Missions/Innovations# drive list
/Missions/Innovations/Proposal for a DNS Secured BGP.pdf
/Missions/Innovations/Proposal for a DNS Secured BGP.docx
/Missions/Innovations/Proposal to Change the EIGRP Feasibility Condition to allow faster convergence.docx
/Missions/Innovations/Proposal to Change the EIGRP Feasibility Condition to allow faster convergence.pdf

Google Drive/Missions/Innovations# drive md5sum
Google Drive/Missions/Innovations# 
```

**Comment by odeke-em** [comment]
Hello there @jean-christophe-manciot, thanks for the report.

Yes in deed, this is an annoying bug that results from an off-by one error in the Md5sum code.
For now you can control the depth by setting it to +1 the value you expect. By default it is 1 as with `drive list`. Please use `-depth 2` to mirror `drive list -depth 1`.

**Comment by jean-christophe-manciot** [comment]
I've just discovered 2 other issues:
- the documentation talks about the -r flag, but it does not work as expected:
```
drive md5sum -r
flag provided but not defined: -r
Usage of md5sum:
  -depth int
    	max traversal depth (default 1)
  -h	
  -hidden
    	discover hidden paths
  -id
    	stat by id instead of path
  -quiet
    	if set, do not log anything but errors
  -recursive
    	recursively discover folders
```
- the -recursive flag has an effect but does not start from where the call is made:
```
Google Drive/Missions# drive md5sum -recursive
f83efad87af0af2ac45e619f7024cf54  Certifications/Cisco/CCDA/Certificate/9927656_certificate.pdf
483360399fd61dac7fc55e84404bd275  Certifications/Cisco/CCDA/Certificate/CCDA Score Report.jpg
...
```

**Comment by odeke-em** [comment]
Thank you thank you @jean-christophe-manciot, let me mark this as a bug and for the next release.

**Comment by jean-christophe-manciot** [comment]
My mistake about the second point which is not an issue.
Actually, it can be used as another workaround to first post:
```
Google Drive/Missions/Innovations# drive md5sum -recursive
a3ec8d8644b63a9cfff50fd8f102dffa  Proposal for a DNS Secured BGP.docx
36215eb1940f422d6d289c8ec042f86f  Proposal for a DNS Secured BGP.pdf
6b5be4ad070dbe3f7c0085013743bb75  Proposal to Change the EIGRP Feasibility Condition to allow faster convergence.docx
8c78373e08b590ef0dcaa5ac8a38f270  Proposal to Change the EIGRP Feasibility Condition to allow faster convergence.pdf
```

**Comment by odeke-em** [comment]
No worries, thing though is `-recursive` will traverse as deep as it can so if there were levels in that directory, it would hit the last point

**Comment by jean-christophe-manciot** [comment]
Yes indeed, we cannot control the recursive depth with --depth n, that's another issue or potential for improvement. As a summary on this point:
- ```drive md5sum --depth n``` has no result/effect
- ```drive md5sum -r ``` has no result/effect
- ```drive md5sum -recursive``` works fine but its depth cannot be controlled

**Comment by odeke-em** [comment]
@jean-christophe-manciot, please get the latest from master. Fixed by https://github.com/odeke-em/drive/pull/832. Thank you for reporting it and for the patience!
