### ISSUE TITLE
unshare err (path): no matches found! 

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#789]
I am still having issues with 'unshare', perhaps it's related to https://github.com/odeke-em/drive/issues/747 or another issue.

When I try
> drive unshare -id some_id -emails Abc@gmail.com

I get 
> Addressees:
> 	+ Anyone with the link
> ...
> unshare err (path): no matches found! 
> 

Presumably addressees should be abc@gmail.com? In any case, the file is not unshared.

Thanks!

**Comment by odeke-em** [comment]
I don't know if Google allows case insensitive emails so please confirm that that's the right email.

Maybe Gmail might accept it, but I don't think that would be in the scope for drive which just forwards along emails assuming the user entered them correctly.

**Comment by chevillet** [comment]
I confirm that Gmail doesn't allow uppercase letters in usernames.
I already tried to create such an address and uppercase letters are automatically converted to lowercase while creating the account.
Gmail automatically forwards emails: 
- with case "issues"
- with dots randomly addded between letters (this doesn't work for Google Apps accounts)
- with +something (or even +something+somthingelse) added at the end

But, I second @odeke-em, I don't think that should be handled in drive.

**Comment by odeke-em** [comment]
Cool, thank you @chevillet for the research!

Yeah, and also there is another thing, if their email provider allows lower case and
upper case distinct emails, trying to send to both by normalizing to one case would create
privacy and security holes in which someone can phish for emails if files are successfully
sent but also accidentally share with the wrong person their files.

I'll close this issue. If there is something else we can do, please feel free to raise it here and we
can reopen the issue.

**Comment by bjohas** [comment]
Hi all,

really sorry for the confusion - it was just a typo on my part. I can confirm that I'm using the emails in lower case, and exactly as they are on drive.

I am still having issues with 'unshare', perhaps it's related to https://github.com/odeke-em/drive/issues/747 or another issue.

When I try
> drive unshare -id some_id -emails abc@gmail.com

I get 
> Addressees:
> 	+ Anyone with the link
> ...
> unshare err (path): no matches found! 
> 

And the last point was then very subtle - not "presumably adressES should be abc@gmail.com, ie lowercase" but "presumably addressEES should be abc@gmail.com (rather than "anyone with the link")? 

In any case, the file is not unshared. Sorry again for that - any thoughts?

Thanks!

**Comment by chevillet** [comment]
My bad, I admit I never use this feature and I was just giving details about how Gmail and Google Apps handle email addresses because I already spent time testing almost everything I could think of (I wasted almost an hour before figuring out that the dot trick wasn't working on Google Apps).
I'll let @odeke-em give you an answer about the actual issue.

**Comment by odeke-em** [comment]
No worries @chevillet, your clarification helped me too and gave me a hunch on a suspicion I had about outside Gmail addresses.

@bjohas thanks for the update. Okay, so can you verify the email of the person that you want unshared from the file, then try to unshare it? If that fails, please report your `drive version`.

**Comment by bjohas** [comment]
I've figured this out:

> drive unshare -id some_id -emails abc@gmail.com

does NOT work, but

> drive unshare -emails abc@gmail.com -id some_id

DOES work. It would be good to fix this, so that the order of the arguments doesn't matter!

**Comment by odeke-em** [comment]
Okay the confusion here is the key `--id` is just a switch, irrespective of where you put it, it is just a boolean value
```shell
$ drive unshare --id --emails abc@gmail.com id1 id2 id3
```
instead of sharing by path
```shell
$ drive unshare --emails abc@gmail.com pathWithid1 pathWithid2 pathWithid3
```

There is an example in the README https://github.com/odeke-em/drive#unsharing

**Comment by bjohas** [comment]
AHA! OK, many thanks!!
