### ISSUE TITLE
use of drive share -notify - unable to stop notification?

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#791]
> drive share -h

gives 

> -notify
>    	toggle whether to notify receipients about share (default true)

However,

> drive share  -notify -role reader -emails abc@gmail.com -id ABC123

produces a notification, while 

> drive share  -notify false -role reader -emails abc@gmail.com -id ABC123

does not work (at least there's no user feedback). 

How do you disable notification?

**Comment by odeke-em** [comment]
What do you mean by `at least there's no user feedback`?

Notify is meant to not send the user an email. Working as intended IMO.

**Comment by bjohas** [comment]
I found that notifications are being sent when -notify is specified.

**Comment by odeke-em** [comment]
To turn it off, use `--notify=false`.

**Comment by odeke-em** [comment]
I guess I wasn't coherent in my statement in https://github.com/odeke-em/drive/issues/791#issuecomment-262846254

I mean to say, `--notify` is meant to control whether a notification goes out or not.

**Comment by bjohas** [comment]
AHH! OK, that works!! Thanks!
