### ISSUE TITLE
GOAWAY error when pulling many files

### ISSUE THREAD

**Issue by sauyon** [odeke-em/drive#798]
Presumably these should be retried instead of simply failing?

![2016-11-27-210008_1276x284_scrot](https://cloud.githubusercontent.com/assets/2347889/20651838/bbf14004-b4e4-11e6-8bb2-1b26f345c4f5.png)

**Comment by odeke-em** [comment]
We already have retries in code with exponential backoff, it doesn't print that out but if you use flag
`--verbose` when pulling or pushing you'll see the output.

I haven't examined the Google APIs servers to speculate about the GOAWAY errors but what
would be helpful would be information like your go version, drive version, OS information,
anything that would help in diagnosing the problem.

**Comment by sauyon** [comment]
Linux 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 GNU/Linux
(Arch)
drive version: 0.3.8.1
Commit Hash: '6ee868f762f5d2d17faa0a95c2e55f059bdf9f36'
Go Version: go1.7.3
OS: linux/amd64
BuildTime: 2016-11-27 18:56:22.88896884 +0000 GMT

**Comment by odeke-em** [comment]
Please get the latest Go. Looks similar to https://github.com/golang/go/issues/18112 which has been fixed by https://github.com/golang/net/commit/8dab9293431a241c65a8e8d46bbaa0492ec94849 CL https://go-review.googlesource.com/#/c/33971.

**Comment by odeke-em** [comment]
Ping! Please get the latest Go as well as update drive, and try again. If it persists, please reopen.

**Comment by sauyon** [comment]
Hey, sorry about the late comment - go-git is refusing to build on my machine at the moment and release go is still 1.7, so I'll report back when 1.8 actually releases.
