### ISSUE TITLE
Exit code 0 on stat failure

### ISSUE THREAD

**Issue by aueuaio** [odeke-em/drive#801]
Hi, i'm using drive v0.3.8 on arch linux, and whenever i `drive stat` some directory that does not exist remotely, the error message is correctly sent to stderr, but the program returns 0. For example, the command `drive stat some_path && echo 'success'` always prints 'success' at the end, whether `some_path` exists or not; also, this might be specific to the `drive stat` command since, even if i didn't try every other command, `drive push` and `drive pull` work as expected (returning non-0 on failure).

**Comment by odeke-em** [comment]
Hello there @aueuaio, thank you for the report and welcome to drive.

Yap this is definitely a bug.

**Comment by odeke-em** [comment]
@aueuaio fixed by PR https://github.com/odeke-em/drive/pull/804. Please updated and get the latest from master.
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
