### ISSUE TITLE
Windows Installation Fails

### ISSUE THREAD

**Issue by bosmanoglu** [odeke-em/drive#817]
Hi, 

I was just testing the windows installation. Followed Peter's guide and get the following error message:
```
PS C:\Users\batu> set CGO_ENABLED=0
PS C:\Users\batu> go get -u github.com/odeke-em/drive/cmd/drive
# github.com/odeke-em/drive/src
D:\codes\go\src\github.com\odeke-em\drive\src\tty.go:20:21: fatal error: termios.h: No such file or directory
 #include <termios.h>
                     ^
compilation terminated.
```
Any ideas what to do?

Best, 
batu.

**Comment by efkan** [comment]
I wonder, is there any reason to try this repository on Windows instead the official application of Google Drive?

If I know right, this repo is used for only Linux distributions.

The official site to download Google Drive for Windows: https://www.google.com/intl/us_ALL/drive/download/

Good luck..

**Comment by idvoretskyi** [comment]
@bosmanoglu AFAIK, only *nix systems are officially supported at the moment - https://github.com/odeke-em/drive/releases/tag/v0.3.8

**Comment by bosmanoglu** [comment]
Hi @efkan, @idvoretskyi:

Thanks for the answers. For some reason the CGO_ENABLED=0 was inactive. Adding it to the environment variables, restarting the command prompt, and re-running the 
`go get -u github.com/odeke-em/drive/cmd/drive`
solves the problem. 

Best, 
batu.

**Comment by idvoretskyi** [comment]
@bosmanoglu what about adding this information to the documentation? /cc @odeke-em

**Comment by bosmanoglu** [comment]
@idvoretskyi Done ;)

**Comment by odeke-em** [comment]
Thank you very much @bosmanoglu and @idvoretskyi. There was a similar issue opened here https://github.com/odeke-em/drive/issues/238 with a similar fix suggested by @pefoley2 here  https://github.com/odeke-em/drive/issues/238#issuecomment-136008753
