### ISSUE TITLE
gdignore

### ISSUE THREAD

**Issue by stormj** [odeke-em/drive#82]
It would be useful to be able to have a .gdignore file, where drive will ignore those files when pushing, pulling, and diffing, just like a gitignore.

**Comment by odeke-em** [comment]
Cool, interested in adding this in?

**Comment by odeke-em** [comment]
Never mind, I have already started on it with PR #84

**Comment by odeke-em** [comment]
Fixed by https://github.com/odeke-em/drive/commit/e02b3a20351018cc71513d7d9697c2cf47d5d356

**Comment by stormj** [comment]
I'm sorry, I don't know even Go

**Comment by odeke-em** [comment]
No biggie, that shouldn't stop us from working together :) Ideas, direction, requirements are all contributions. Please see the latest from master, and thank you for bringing this up.

**Comment by ikwyl6** [comment]
The user should be able to "ignore" files by filesize as well, not just a regular expression. This would be useful for users who have .img or .iso on their PC but do not want to upload to google drive.

**Comment by odeke-em** [comment]
How about ignore .img or .iso, then explicitly push them whenever you need to? For now I don't want to make the ignore grammar complex.

**Comment by odeke-em** [comment]
Actually, would you mind instead opening a feature request for ignoring by filesize, so that we do not forget about it?
