### ISSUE TITLE
drive behind proxy

### ISSUE THREAD

**Issue by alexandre1985** [odeke-em/drive#821]
My OS is Debian and I'm behind a proxy and when I do a `drive push file.txt` I get this error:

> Resolving...
>  – 
> Get https://www.googleapis.com/drive/v2/files?alt=json&q=%22root%22+in+parents+and+title+%3D+%22a%22+and+trashed%3Dfalse: Proxy Authentication Required

What should I to get `drive` to work behind a proxy?
Thanks

**Comment by odeke-em** [comment]
Hello there @alexandre1985, thank you for the issue and welcome to drive!

So I personally don't know how to get drive to work behind a proxy but perhaps we can hala at folks
who've reported doing it before in  https://github.com/odeke-em/drive/issues/638 so let's ask @ouwenxxing for some help.

**Comment by saptarshiguha** [comment]
I wish this could work. I too am on centos behind a proxy ...

**Comment by erdoking** [comment]
you can try to set proxy variable global in /etc/environment (or export in bash-script).

http_proxy=http://$USER$:$PASSWORD$@$SERVER$:$PORT$/
https_proxy=http://$USER$:$PASSWORD$@$SERVER$:$PORT$/

like:
http://proxyuser:mypassword@wwwproxy:8080/

You need to relogin after that. Check it with "env"

**Comment by alexandre1985** [comment]
Thank you.
The problem that I had was that my http_proxy, https_proxy and ftp_proxy were all lowercase.
They all have to be uppercase (HTTP_PROXY, HTTPS_PROXY and FTP_PROXY) so that drive can pick it up.
Thank you for the env tip @erdoking

**Comment by alexandre1985** [comment]
The problem was that I had HTTP_PROXY misconfigured and I was configuring the http_proxy variable. And drive was not picking up the http_proxy because there was an HTTP_PROXY.
So now I configured both and I have no problem
