### ISSUE TITLE
push of takeout zip archives

### ISSUE THREAD

**Issue by nick4me** [odeke-em/drive#83]
I tried to upload some google takeout zip archive files using the following command...

drive push -m /my/path/to/google-takeout/ -r backup/folder/a/

but it seems that google drive extracts the archive files. I see the content of the zip files in the respective google drive folder.

Is there any way to disable the feature and only upload the raw files?

**Comment by odeke-em** [comment]
Hello @nick4me unfortunately I have never used "Google Takeout" nor even have access to such files but for starters I can give you a tip to allow raw files to be uploaded.
```shell
$ cat your_zip_files | drive push --piped target_name
```

**Comment by odeke-em** [comment]
@nick4me ping!

**Comment by odeke-em** [comment]
Closing this issue. Please re-open if it persists.
