### ISSUE TITLE
[0.3.9] src/commands.go:142: cannot use c.log (type *"github.com/odeke-em/log".Logger) as type io.Writer in argument to FDebugPrintf:

### ISSUE THREAD

**Issue by jean-christophe-manciot** [odeke-em/drive#834]
Ubuntu 16.10 4.8
drive git sources tag v0.3.9 in master

```
        echo --------
        echo Cleaning
        echo --------
        cd drive
        sudo -u actionmystique -H git-reset-clean-pull-checkout.sh $branch $tag

        echo ---------
        echo Compiling
        echo ---------
        drive-gen
```
leads to:
```
# github.com/odeke-em/drive/src
src/commands.go:142: cannot use c.log (type *"github.com/odeke-em/log".Logger) as type io.Writer in argument to FDebugPrintf:
	*"github.com/odeke-em/log".Logger does not implement io.Writer (missing Write method)
exit status 2
```

**Comment by odeke-em** [comment]
@jean-christophe-manciot please run first
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
The update you need is from https://github.com/odeke-em/log.

**Comment by jean-christophe-manciot** [comment]
OK, I see that there are multiple go dependencies. 
Is there a simple command to make sure they are all updated before compiling?

**Comment by odeke-em** [comment]
Yeah if you do the command in https://github.com/odeke-em/drive/issues/834#issuecomment-271071080
I added flag `-v` to give output that can be used to give detailed bug reports if anything fails, otherwise if just want everything fully updated, do
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by jean-christophe-manciot** [comment]
Works like a charm ;)

**Comment by jean-christophe-manciot** [comment]
I would add ```master``` to ```git pull --ff-only``` in case someone has checked out a tag just before.

**Comment by jean-christophe-manciot** [comment]
Otherwise you'll get some error message like:
```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```
