### ISSUE TITLE
pushing child of non-existent remote directory fails

### ISSUE THREAD

**Issue by gauteh** [odeke-em/drive#848]
Hi, I tried to push a sub-directory of target A/B/C where A/B does not exist, but kept getting everything is up-to-date. Now, for some reason it detects the changes again. Is there some cache issue going on?

**Comment by odeke-em** [comment]
Hello there @gauteh, good to hear from you this year!

This is a bug that I've too noticed, that is a regression. If you push A/B then pushing A/B/C should correctly then push.

I'll mark it as a bug to be fixed for the next release. Thank you for the report.

**Comment by gauteh** [comment]
Ah allright.

I think i ended up not syncing some files, and consequently deleting them.
Could that be caused by the same bug?

man. 23. jan. 2017 kl. 03.59 skrev Emmanuel T Odeke <
notifications@github.com>:

**Comment by gauteh** [comment]
This just happened with a `.git` sub-dir, in a newly cloned repository.

**Comment by gauteh** [comment]
Huh, I cancelled the first push before starting, and when doing drive push again afterwards it finds the .git dir.

**Comment by odeke-em** [comment]
@gauteh please get the latest from master. In #1019 I was able to test out that non-existent directory creation works, even though that PR wasn't necessarily meant for this but that test case was used in #1016. Thank you for the patience and for using drive over these years!
