### ISSUE TITLE
Rename - Why the Remove and Add on Name Changes?

### ISSUE THREAD

**Issue by JohnnyBlocks** [odeke-em/drive#850]
I'm using this and it's working great....and maybe this is due to my not understanding...

I have files mirrored on my windows machine, google drive, and linux.  

When I performed a 'rename' of a folder, the process was to remove the existing folder and then download the new one.  The same happens at the file level if only a file is renamed.

When dealing with large file sizes, this can cause a lot of IO and bandwidth usage.

The drive app (on windows) somehow understands the change is a name and simply renames this in the cloud.  

Am I not understanding something or is this simply be design?   

Example
`Resolving...`
`+ /Work/Archive/HistologyEfficiency.zip`
`- /Work/Archive/HistologyEfficiecny.zip`
`Addition count 1 src: 4.37GB`
`Deletion count 1 dest: 4.37GB`

As consumer bandwidth is starting to be capped by ISPs, it would be ideal if this could just propagate the name changes instead of having the client value the files as add/removals.

Just my thoughts... That being said.. this is amazing and I cannot express my gratitude to everyone who has helped bring this codebase to life. <3

**Comment by odeke-em** [comment]
Hello @YoYo-Pete, thank you for the issue and welcome to drive!

Great suggestion to infer that information. Yes, we should infer from similarities in files that a rename is due when the checksum, size, name, path, fileId are the same.

However, `drive rename` should change that for you and it already does, it renames both locally and on the cloud by default, unless something turned it off
```shell
$ drive rename --help
Usage of rename:
  -force
    	coerce rename even if remote already exists
  -h	
  -id
    	unshare by id instead of path
  -local
    	rename local as well (default true)
  -quiet
    	if set, do not log anything but errors
  -remote
    	rename remote as well (default true)
```

Also please report your `drive version`, the latest that I have on my computer is
```shell
$ drive version
drive version: 0.3.9.1
Commit Hash: '93be68d4f6e771fb6e063db7e766f0a28e36e86d'
Go Version: devel +09bff04 Fri Jan 20 02:27:30 2017 -0700
OS: darwin/amd64
```

which I generated by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
