### ISSUE TITLE
syntax error: unexpected string literal, expecting comma or )

### ISSUE THREAD

**Issue by bhavesh1212310** [odeke-em/drive#852]
Trying to install drive but I'm getting this error

`gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )
`

**Comment by shaggytwodope** [comment]
As with most bug reports having to do with go, can you share your go version. Running `go version` and sharing the complete output. I can't reproduce this on go 1.7.4. Stands to reason this may be related to an older go release.

**Comment by bhavesh1212310** [comment]
Hey yes you are right, I had go version 1.6 installed

**Comment by trickv** [comment]
I've also just updated the wiki page which was wrong.
