### ISSUE TITLE
Update required version in README.md to 1.7.x

### ISSUE THREAD

**Issue by kjoller** [odeke-em/drive#853]
I had the same issue as #852, trying to use version 1.6.4.

I read the README, then tried 1.5.4. Did not work either.

Tried version 1.7.4, as suggested in #852, worked perfectly :-)

**Comment by odeke-em** [comment]
Hello there @kjoller, thank you for raising the issue and welcome to drive!

Roger that, let me make a quick patch of it since I am in front of my computer.

**Comment by odeke-em** [comment]
@kjoller thank you for the recommendation and report. Done with https://github.com/odeke-em/drive/issues/855!
