### ISSUE TITLE
"go get" fails with a syntax error

### ISSUE THREAD

**Issue by peter-kehl** [odeke-em/drive#854]
Hi Emmanuel,

Thank you for de-facto maintaining Drive. Especially since you contribute to many other projects, too.

Installing from source fails for me. Would you advise, please.

go get  -u github.com/odeke-em/drive/cmd/drive
# github.com/odeke-em/drive/cmd/drive
gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )

# Also:
go get github.com/odeke-em/drive/drive-gen
gopath/src/github.com/odeke-em/drive/drive-gen/build.go:24: syntax error: unexpected string literal, expecting comma or )

echo $GOPATH
/home/pkehl/gopath

Ubuntu 16.04.1 x32, up to date.
go version go1.6.2 linux/386

**Comment by odeke-em** [comment]
Hello @peter-kehl, thank you for raising the issue and welcome to drive!

Yes in deed, this issue has been reported by a few other folks as well lately.
This issue https://github.com/odeke-em/drive/issues/853 asks us to update the Go version to 1.7.

Am going to update the README in a few here.

**Comment by odeke-em** [comment]
@peter-kehl please use Go1.7 and above, I've updated the README to reflect that as well.
Thank you for the report.
