### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by fjhenigman** [odeke-em/drive#863]
Just tried to build on ubuntu 16.04.1 which has go 1.6.2.

% go get -u github.com/odeke-em/drive/drive-gen
...
gopath/src/github.com/odeke-em/drive/drive-gen/build.go:26: syntax error: unexpected string literal, expecting comma or )

**Comment by odeke-em** [comment]
Hello there @fjhenigman, thank you for reporting the issue and welcome to drive.

Please use Go1.7 and above or if you don't have Go1.7 you can pick one of the binaries here  https://github.com/odeke-em/drive/releases/tag/v0.3.9.

We updated the README to indicate this in https://github.com/odeke-em/drive/pull/855 which closed a couple of duplicate issues.
