### ISSUE TITLE
pub error: googleapi: Error 403: Insufficient permissions for this file, forbidden

### ISSUE THREAD

**Issue by nirajyadav** [odeke-em/drive#864]
Hello,

    Can you please help ?

I am able to create, new, delete, push everything successfully.

But when i do drive pub it throws this error. Thoughts ? 

googleapi: Error 403: Insufficient permissions for this file, forbidden

**Comment by odeke-em** [comment]
Hello there @nirajyadav, thank you for reporting the issue and welcome to drive!

For starters, what does your `drive version` say?

**Comment by nirajyadav** [comment]
Thanks @odeke-em I found issue. Its blocked by my comp. Pub is not allowed. Thanks.
