### ISSUE TITLE
Debian: dirmngr required

### ISSUE THREAD

**Issue by idvoretskyi** [odeke-em/drive#866]
Istallation using https://github.com/odeke-em/drive/blob/master/platform_packages.md#debian-or-debian-based-distros, fails:

```
(debian)idv@localhost:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7086E9CC7EC3233B
Executing: /tmp/apt-key-gpghome.lSBsHBKEj7/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7086E9CC7EC3233B
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.lSBsHBKEj7/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

Debian Sid, fresh minimal installation.

**Comment by odeke-em** [comment]
Hello again @idvoretskyi, thank you for creating the issue and the accompanying PR!

I don't know much about Debian installation but I'll ping our local PPA wizard @shaggytwodope
who made that documentation, to help me with the review.

Thank you.

**Comment by shaggytwodope** [comment]
@odeke-em LGTM, seems I install gnupg by default on my machines (which includes this package). I've overlooked this requirement.

**Comment by odeke-em** [comment]
@shaggytwodope please comment on the PR :)

**Comment by okinhk** [comment]
Still getting this error. May I have missed any update?
