### ISSUE TITLE
Handling of push -piped existing file

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#87]
If push -piped existing file, drive just silently ignore and return success.

```
$ echo 123 | drive push -piped test.txt && echo ok
ok
$ echo 456 | drive push -piped test.txt && echo ok
ok
$ drive pull -piped test.txt
123
```

Expected behavior:
 - either print error message and return error
 - or, overwrite file with new content
 and use option to switch to the other behavior.

**Comment by odeke-em** [comment]
Good point, --piped should behave normally and only get overridden when --force is passed in. I'll jump onto this in about 10 hours, or feel free to take a stab at it.

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/commit/765fdbb18a00c3c13be6935263d203e03924e1f4

**Comment by kcwu** [comment]
765fdbb is not enough.
Please see my reproduce steps. I expected that the result should be 456 if with --force

**Comment by kcwu** [comment]
BTW, according to the help text
 -force=false: forces a push even if no changes present
 -no-clobber=false: allows overwriting of old content
Looks like NoClobber is more suitable.

**Comment by odeke-em** [comment]
I think I'd rather use -force because in this case we aren't dealing with a mode for which an existant file is considered a conflict, which is not the normal case.

**Comment by kcwu** [comment]
Then maybe the flags need to be revised.

**Comment by odeke-em** [comment]
For sure, feel free to pitch in on how to improve. However, can you see why we'd rather use `--force` than `--no-clobber`? This new mode is basically in conflict if a file exists, ordinarily this would result in update.

**Comment by kcwu** [comment]
Understood. Personally I prefer the opposite way --  update by default and return error with extra flag. I'm okay to your change, just feel the help message become confusing.

**Comment by odeke-em** [comment]
Sorry for the late reply, I had gone out for a bit. See, usually I'd take your approach and I too would rather have it lax than as strict. However, I think trying to play it safe than sorry would be better. There was an issue https://github.com/odeke-em/drive/issues/57 in which a user was not happy because drive let them clobber their files, even though drive clears mentions that such will happen. We should try to mitigate such scenarios.

**Comment by kcwu** [comment]
I see. Would you reopen this issue? make sure `-force` really overwrite with new content. And return error if not `-force`

**Comment by odeke-em** [comment]
Definitely.

**Comment by odeke-em** [comment]
This is the latest from the code on PR #91:
![screen shot 2015-03-11 at 2 41 13 am](https://cloud.githubusercontent.com/assets/4898263/6592843/22e4c786-c798-11e4-9491-44b8d8fdf2a4.png)

**Comment by kcwu** [comment]
I am wondering should drive exit with non-zero value for the second command? I mean, it won't echo ok.

**Comment by odeke-em** [comment]
Very good point, in the function that does this, technically it can accept more than one file, kinda like when you would select your custom EOF as in 
```shell
$ cat << !
```
However, that is a secret feature and for now that I'll just gut it, by actually throwing the error.

**Comment by odeke-em** [comment]
@kcwu ping.

**Comment by kcwu** [comment]
It's fixed. Thanks

**Comment by odeke-em** [comment]
Thank you too. That was a great collaboration.
