### ISSUE TITLE
Appear to install successfully: Drive Not Found (Ubuntu 14.04)

### ISSUE THREAD

**Issue by kellevan** [odeke-em/drive#88]
$: drive help
No command 'drive' found, did you mean:
...

**Comment by odeke-em** [comment]
Take a look at https://github.com/odeke-em/drive/issues/81 please make sure you installed Go properly and set your gopath correctly, otherwise in that issue you'll see how.

**Comment by kellevan** [comment]
Of course, one must logout or open a new terminal in order to have their bash_rc changes settle in.

Thanks Odeke!

**Comment by odeke-em** [comment]
Anytime!
