### ISSUE TITLE
Panic; double free?

### ISSUE THREAD

**Issue by jazvw** [odeke-em/drive#886]
Hi,

Everytime I run drive on one particular account, it crashes repeatably. Stdout/stderr below. Let me know what info you need to further debug this. 

Thanks for creating Drive!

Cheers,
Jasper.

$ drive pull -ignore-conflict -ignore-name-clashes -no-prompt
Resolving...

<removed files for privacy>

Addition count 145 src: 386.75MB
Clashing modification count 102 src: 265.16MB dest: 220.50MB
 5830333 / 683579955 [>---------------------------------------------------------------------------------------]   0.85% 28m42spanic: page 219 already freed

goroutine 15 [running]:
panic(0x555bef517320, 0xc4206a0400)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*freelist).free(0xc42097bad0, 0xbe4, 0x7fc494325000)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/freelist.go:121 +0x2c0
github.com/boltdb/bolt.(*node).spill(0xc4201865b0, 0xc420cc5fe0, 0xc420cc5fe0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:363 +0x1dc
github.com/boltdb/bolt.(*node).spill(0xc420186540, 0xc42097bbf0, 0xc420c396c0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:350 +0xb7
github.com/boltdb/bolt.(*Bucket).spill(0xc420cc3400, 0xc42097bb00, 0xc420c39930)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/bucket.go:570 +0x43b
github.com/boltdb/bolt.(*Bucket).spill(0xc42036a1d8, 0x555b19282d6e, 0x555befa3e9e0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/bucket.go:537 +0x93b
github.com/boltdb/bolt.(*Tx).Commit(0xc42036a1c0, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc4206aa000, 0xc420c39b98, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/db.go:605 +0x10d
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc420078f80, 0xc42065b800, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:279 +0x1a8
github.com/odeke-em/drive/src.(*Commands).createIndex(0xc420079000, 0xc4207d5080, 0x555bef623d98, 0xc420c39c80)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/fetch.go:314 +0x138
github.com/odeke-em/drive/src.(*Commands).localMod.func1(0xc420c39d38, 0xc420cbae00, 0xc420079000)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:529 +0x5c
github.com/odeke-em/drive/src.(*Commands).localMod(0xc420079000, 0xc420cbae00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:567 +0x2d0
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.localMod)-fm(0xc420cbae00, 0x0, 0x0, 0x0, 0x3, 0xc4208d5860)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:1062 +0x52
github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc420cbae00, 0x555b00000001, 0x555b00000000)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:478 +0x53
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0xc42002f6c0, 0x555bef08a135, 0x555bef5127e0, 0xc420cb1e00)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:120 +0xb1
github.com/odeke-em/drive/src.jobSt.Do(0x1, 0xc420caa7a0, 0x555bef2713bf, 0x555bef5127e0, 0xc420cb1e00, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:100 +0x27
github.com/odeke-em/drive/src.(*jobSt).Do(0xc42036ca00, 0xc4204401c0, 0x0, 0x0, 0x0)
	<autogenerated>:6 +0x5b
github.com/odeke-em/semalim.Run.func4.1(0xc4202f6db0, 0xc420cb1d40, 0xc4202f6dc0, 0xc4202f6dd0, 0x555befa24820, 0xc42036ca00)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/semalim/semalim.go:71 +0x56
created by github.com/odeke-em/semalim.Run.func4
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/semalim/semalim.go:76 +0x141

**Comment by odeke-em** [comment]
Hello there @jazvw, thank you for the issue and welcome to drive.

So we've been plagued by these boltdb double frees and crashes since last year and there are
still a bunch of open issues that might be duplicates of this issue https://github.com/odeke-em/drive/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20panic%20in%3Atitle
for example https://github.com/odeke-em/drive/issues/862.

I had commented about this issue to the boltdb project but the supposed fix didn't fix it. I personally have never been able to reproduce it. Perhaps it is because am on OS X. It would be helpful if you could include the version of drive that you are running.

I'll close this issue in favor of the mentioned duplicate, but if the worst comes to the worst, please go into your .gd directory and remove `drivedb` then try again.

Please comment on the mentioned issue https://github.com/odeke-em/drive/issues/862 if you'd like.
