### ISSUE TITLE
drive doesn't work with crontab 

### ISSUE THREAD

**Issue by Selektion** [odeke-em/drive#890]
Hi,
I've read different similar issue but nothing...

I've a very simple backup.sh file:

#!/bin/bash
rm /BackUp/Files/*
cd /BackUp/Files
zip -r BackUp_$(date '+%d-%b-%Y_%T').zip /var/www 
/usr/local/bin/gdrive upload  /BackUp/Files/*

and i set crontab:

* * * * * sh /BackUp/backup.sh

the scripts run, create the zip correctly but don't upload the file, if I run it from terminal ' sudo sh /BackUp/backup.sh' all go correctly

Any ideas?

**Comment by canpolat** [comment]
Wrong drive client. Contact `gdrive` team (https://github.com/prasmussen/gdrive) instead.

PS: I would suspect file permissions, but I know nothing about `gdrive`.

**Comment by canpolat** [comment]
It looks like there already is an issue: https://github.com/prasmussen/gdrive/issues/268

I suggest closing this one.

**Comment by Selektion** [comment]
Thank you canpolat and sorry for the error,
Yes, it was a permissione error

**Comment by odeke-em** [comment]
As mentioned by @canpolat, wrong client, but thank you for checking on us and welcome to drive @Selektion!
