### ISSUE TITLE
drive push doesn't read destination from .driverc

### ISSUE THREAD

**Issue by cbestall** [odeke-em/drive#891]
According to README
> The entries for a .driverc file is in the form a key-value pair where the key is any of the arguments that you'd get from running drive push

I've tried `destination=/Dev` for example, but drive tries to sync to root.

**Comment by odeke-em** [comment]
Hello there @cbestall, thank you for the report and welcome to drive!

Good raise here, just an oversight for keys recognized by the .driverc parser.

I am going to fix it shortly!
