### ISSUE TITLE
Installation fails with error "unexpected string literal, expecting comma or )"

### ISSUE THREAD

**Issue by birgersp** [odeke-em/drive#900]
Ubuntu 16.04, installed go with command `sudo apt install golang` (if it matters). Added `.gopath` folder to home directory, set `GOPATH` to `$HOME/.gopath`, set `PATH` to `$GOPATH/bin:$PATH`.

Running the command to install, as instructed in the readme fails with an error message.

```
birger@desktop:~$ go get -u github.com/odeke-em/drive/cmd/drive
# github.com/odeke-em/drive/cmd/drive
.gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )
```

**Comment by shaggytwodope** [comment]
Please see issue https://github.com/odeke-em/drive/issues/889 basically the go version is a bit behind on ubuntu. There is a ppa package available to make installing far simpler [here](https://github.com/odeke-em/drive/blob/master/platform_packages.md#ubuntu-or-ubuntu-based-distros).

You could upgrade the go version, but this would require some potentially messy steps. The ppa is safe and strongly suggested.

**Comment by birgersp** [comment]
Thank you! Sorry I didn't see the issue that was already there.
