### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by coliss86** [odeke-em/drive#912]
I tried to compile the source but it failed. Here the complete log : 
```
~/temp $ export PATH=$GOPATH:$GOPATH/bin:$PATH
~/temp $ go get -u github.com/odeke-em/drive/drive-google
# golang.org/x/oauth2/jws
src/golang.org/x/oauth2/jws/jws.go:75: undefined: base64.RawURLEncoding
src/golang.org/x/oauth2/jws/jws.go:93: undefined: base64.RawURLEncoding
src/golang.org/x/oauth2/jws/jws.go:113: undefined: base64.RawURLEncoding
src/golang.org/x/oauth2/jws/jws.go:124: undefined: base64.RawURLEncoding
src/golang.org/x/oauth2/jws/jws.go:151: undefined: base64.RawURLEncoding
src/golang.org/x/oauth2/jws/jws.go:174: undefined: base64.RawURLEncoding
# golang.org/x/net/context/ctxhttp
src/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go:36: req.Cancel undefined (type *http.Request has no field or method Cancel)
# google.golang.org/api/googleapi
src/google.golang.org/api/googleapi/googleapi.go:289: u.RawPath undefined (type *url.URL has no field or method RawPath)
```
I'm using  the version `go1.4.2 linux/386` on a debian jessie (stable)

I also tried with `go get -u github.com/odeke-em/drive/cmd/drive` in a clean directory and same problem.

**Comment by shaggytwodope** [comment]
@coliss86 please see [requirements](https://github.com/odeke-em/drive#requirements)

Short of it is that debian and few other distros have a far older version of go then what is supported at this time. There is a debian repo setup if that meets your needs. If there are any issues using the repo let me know. Information of the repo can be found [here](https://github.com/odeke-em/drive/blob/master/platform_packages.md).

**Comment by coliss86** [comment]
Thx for the answer, I didn't read the first sentence of the documentation, my bad :'(

I upgraded to 1.7.4 and the compilation now works fine ✨
