### ISSUE TITLE
cannot compile using go1.5

### ISSUE THREAD

**Issue by geertvercamer** [odeke-em/drive#915]
Hi,

complete noob on pi, python, linux, ...

I have this error when launching 'go get -u github.com/odeke-em/drive/drive-gen && drive-gen':
.gvm/pkgsets/go1.5.2/global/src/github.com/odeke-em/drive/drive-gen/build.go:24: syntax error: unexpected string literal, expecting )

Thanks for helping me out!

**Comment by shaggytwodope** [comment]
@geertvercamer  please see [requirements](https://github.com/odeke-em/drive#requirements)

You are using an older version of go then what is supported at this time. You may want to see if your platform is listed [here](https://github.com/odeke-em/drive/blob/master/platform_packages.md). Using packages for your platform will be alot easier in most cases then compiling on your own.

**Comment by geertvercamer** [comment]
Thanks @shaggytwodope 

uname -a -> Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

Jessie, I guess? Debian based? But apt-add-repository gives 'command not found'

**Comment by shaggytwodope** [comment]
@geertvercamer So the command comes from the pacakge `software-properties-common`. Please take a look at the whole section and steps mentioned. 

Check out the [releases](https://github.com/odeke-em/drive/releases) page under the downloads section for pre-compiled binary's that can be run with ease should the steps not work for you above.

**Comment by redtux** [comment]
i am getting the same error when using the golang-go package in ubuntu xenial (v1.6-1ubuntu4). installing go1.4 and/or go1.5.2 through gvm as described in the wiki is also not working. (Failed to compile complaining for an "unknown relocation type 42; compiled without -fpic?".)

**Comment by shaggytwodope** [comment]
@redtux you need to be using go 1.7+. Is the wiki saying otherwise?

**Comment by redtux** [comment]
indeed, it does! :-D

> gvm install go1.4
gvm use go1.4
gvm install go1.5.2
gvm use go1.5.2 --default

See: https://github.com/odeke-em/drive/wiki#troubleshooting

**Comment by chevillet** [comment]
The `gvm` trick was working fine for older Ubuntu/Mint but I haven't used it for so long it might not be as useful as it was. Maybe we should remove it from the wiki unless anyone can confirm it's still working.

@redtux Regarding Raspberry Pis, it's supposed to work according to this link even if I don't have a Pi to test: https://github.com/tgogos/rpi_golang (there is also a how to without gvm)

**Comment by odeke-em** [comment]
Hello @geertvercamer thank you for the question and welcome to drive!

Thanks @shaggytwodope and @chevillet for answering the question.

@geertvercamer yap just like @shaggytwodope mentioned in https://github.com/odeke-em/drive/issues/915#issuecomment-304720047, the minimum Go version is listed there as Go1.7, and if that doesn't work as he also mentioned in https://github.com/odeke-em/drive/issues/915#issuecomment-304724157, there are precompiled binaries that you can use.
