### ISSUE TITLE
Quota error when downloading large number of files

### ISSUE THREAD

**Issue by mcspritz** [odeke-em/drive#922]
Hi,

I noticed that when downloading more than roughly 50 files with total size less than 2MB I get an error:

/last-file-to-be-downloaded err: googleapi: got HTTP response code 403 with body: {
 "error": {   "errors": [    {     "domain": "usageLimits",
    "reason": "quotaExceeded",
    "message": "The download quota for this file has been exceeded",
    "locationType": "other",     "location": "quota.download"    }   ],
  "code": 403,   "message": "The download quota for this file has been exceeded"
 } }   

Which creates an empty file. For now I just delete the empty file and pull again and it works.

I'm using:
drive version: 0.3.9.1
Commit Hash: '8c26f34b24e0e681acfaffee4149edbbd0aec6a2'
Go Version: go1.7.5
OS: linux/amd64
BuildTime: 2017-02-03 22:13:30.854342991 +0100 CET

on Manjaro Linux

Thanks

**Comment by odeke-em** [comment]
Hello again @mcspritz.

So if you haven't changed these keys to use your own configuration https://github.com/odeke-em/drive#api-keys, then your drive usage is competing with everyone else in the world who is using the default config ie a lot of people as seen here https://github.com/odeke-em/drive/issues/480, and also the bug for quotas hasn't yet been resolved by Google Drive's backend(at least no one has informed yet of its fixing)

To mitigate this, you can create your own drive API keys from https://console.developers.google.com/ and then set them in your environment like this
```
$ cat << ! >> ~/.bashrc && source ~/.bashrc
GOOGLE_API_CLIENT_ID=foo
GOOGLE_API_CLIENT_SECRET=bar
!
``` 
and from there you'll be able to have your own quota that might be sufficient.

Please try that and if symptoms persist, feel free to reopen this issue.
