### ISSUE TITLE
Question: Ignore "Google Photos" folder

### ISSUE THREAD

**Issue by mcushing** [odeke-em/drive#925]
Newb - in the ".driveignore" how would you define to ignore the "Google Photos" folder. I guess the space in the name is throwing me off.

**Comment by odeke-em** [comment]
Hello @mcushing, thank you for the question and welcome to drive!

Yes in deed, you can ignore the Google Photos Folder just by typing it out as is in the .driveignore file
```shell
Google Photos
``` 
If you feel a little paranoid about it, you can use the regex form of it e.g
```shell
Google\s+Photos
```

Hope that answers your question. Please reopen the issue in case of ambiguities.

**Comment by mcushing** [comment]
Thank you, that works!
