### ISSUE TITLE
Encrypted Container File Cannot Push Update

### ISSUE THREAD

**Issue by martyg77** [odeke-em/drive#930]
Hello.  I have a 100% reproducible issue with file corruption using the drive toolkit and VeraCrypt containers.  Any modification I make to my containers get mangled when uploading to the Google cloud.

Please tell me what I am doing wrong, I can't imagine an issue this serious existing without being able to find another bug report.

```
$ drive version
drive version: 0.3.9.1
Commit Hash: '1cb01ece65b6d9d39060da1ecf2a440a90b24954'
Go Version: go1.8.3
OS: linux/amd64
BuildTime: 2017-06-24 13:23:28.787814148 -0700 PDT

$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ pacman -Q veracrypt
veracrypt 1.19-2
```
Create encrypted file container, standard VeraCrypt volume using defaults, on local disk  size 50M, NTFS filesystem.
Mount the volume, quickly populate it with recognizable data, then dismount.
Push the container up to Google

```
$ md5sum Drive/drive-vc.hc 
f91535bbe56d07b8a13ff6a037f51b1f  Drive/drive-vc.hc

$ touch Drive/drive-vc.hc # VC leaves timestamp alone by default, tweak in options
$ drive push -verbose Drive/drive-vc.hc 
Resolving...
+ /drive-vc.hc
Addition count 1 src: 50.00MB
Proceed with the changes? [Y/n]:Y
```
and pull back into another tree, noting all is well with the world

```
$ drive pull -verbose Drive1/drive-vc.hc
Resolving...
+ /drive-vc.hc
Addition count 1 src: 50.00MB
Proceed with the changes? [Y/n]:y

$ md5sum Drive1/drive-vc.hc 
f91535bbe56d07b8a13ff6a037f51b1f  Drive1/drive-vc.hc
```

Now repoen the container in the source volume, make a trivial file addition, then dismount.
Push the change up to Google, note this update transmits much faster than original upload.
Then pull the update back down to the other side.
Observe the result.

```
$ md5sum Drive/drive-vc.hc 
aa2d5e207090ac2e6152acd39e213477  Drive/drive-vc.hc

$ touch Drive/drive-vc.hc
$ drive push -verbose Drive/drive-vc.hc 
Resolving...
M /drive-vc.hc
Modification count 1 src: 50.00MB dest: 50.00MB
Proceed with the changes? [Y/n]:y

$ drive pull -verbose Drive1/drive-vc.hc
Resolving...
M /drive-vc.hc
Modification count 1 src: 50.00MB dest: 50.00MB
Proceed with the changes? [Y/n]:y

$ md5sum Drive/drive-vc.hc Drive1/drive-vc.hc 
aa2d5e207090ac2e6152acd39e213477  Drive/drive-vc.hc
f91535bbe56d07b8a13ff6a037f51b1f  Drive1/drive-vc.hc

$ drive stat Drive/drive-vc.hc 
/drive-vc.hc
Filename                  drive-vc.hc                   
FileId                    0B-ImKPfo32eTdTBTc0lzTVZGSlE  
Bytes                     52428800                      
Size                      50.00MB                       
QuotaBytesUsed            52428800                      
DirType                   file                          
VersionNumber             538577                        
MimeType                  application/octet-stream      
Etag                      "dUcwyQ6hN8QZTeM4-DHEZmgLfsU/MTQ5ODY4MDE5MzAwMA"
ModTime                   2017-06-28 20:03:13 +0000 UTC 
LastViewedByMe            2017-06-28 20:11:09 +0000 UTC 
Shared                    false                         
Owners                    Martin Gallant                
LastModifyingUsername     Martin Gallant                
Md5Checksum               f91535bbe56d07b8a13ff6a037f51b1f
Copyable                  true                          
Starred                   false                         
Viewed                    true                          
Trashed                   false                         
ViewersCanDownload        false  
```                       

Note MD5 is for old version on the cloud and Drive1.
Though the MD5 on the Google side no longer matches my source, updates are now messed up.

```
$ drive diff Drive/drive-vc.hc
$ drive push -force -verbose Drive/drive-vc.hc 
Resolving...
Everything is up-to-date.
```

**Comment by martyg77** [comment]
To rephrase all of this,

1. Drive _appears_ to correctly update my VeraCrypt container changes, but in fact what resides in the cloud remains the old version.
2. I do not know of a way to make push to send up the new container, short of deleting and re-creating the file

**Comment by martyg77** [comment]
Was able to duplicate without VeraCrypt:
 
```
$ dd if=/dev/urandom of=Drive/drive-vc2.hc bs=1M count=50
$ md5sum Drive/drive-vc2.hc
$ drive push Drive/drive-vc2.hc

$ dd if=/dev/urandom of=Drive/drive-vc2.hc bs=1M count=50 # Overwrite original
$ md5sum Drive/drive-vc2.hc
$ drive push Drive/drive-vc2.hc
$ drive stat Drive/drive-vc2.hc
```

**Comment by CountryBumkin** [comment]
Try the -ignore-checksum option, more details here https://github.com/odeke-em/drive#verifying-checksums

Regards CB

**Comment by martyg77** [comment]
I read that part of the documentation a dozen times without seizing the big picture.
Now that I have been shown, I hang my head in shame.  :-)

Just a couple ideas to help along your next new user, now that I have my issue under control.
This program is a game-changer for me.  Thanks for maintaining it.

drive diff should perform checksumming no matter what, rationale being is this command is where users will gravitate to when they have problems.
Mortals should not have to know they need to turn on a flag for this purpose - If they don't, they get told files are the same when they are not.

When invoked with the -force option, drive push should always upload into the cloud, no matter what.
Current behavior suggests this is happening, when in fact it is not.  The documentation certainly suggests that it will.
