### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by FredyR4zox** [odeke-em/drive#931]
When i run "drive init" and paste the authorization, it gives me this error: "Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority"

**Comment by shaggytwodope** [comment]
The is a go problem it seems, and fixed in https://github.com/golang/go/issues/18688.

How did you install drive, and what go version are you using. Just typing `go version` will show you.

**Comment by FredyR4zox** [comment]
go version = go version go1.8.3 linux/amd64

I installed with the command: go get -u github.com/odeke-em/drive/cmd/drive

**Comment by FredyR4zox** [comment]
I still have this problem :/

**Comment by MrDini123** [comment]
Hi,

It is an easy fix issue. Just run a `wget -nv http://curl.haxx.se/ca/cacert.pem -O /etc/ssl/cert.pem` command to download the certificate. Or if your system looks for certifications in another folder, start the drive with strace, and extract the path from its output.
