### ISSUE TITLE
push inside non-existent directory doesn't seem to work

### ISSUE THREAD

**Issue by alexiou1977** [odeke-em/drive#933]
Hi,

I have done some changes to a folder of a locally-mounted remote path but these changes are not pushed to the remote directory. I am just getting the message that everything is up-to-date. What is happening?

Thanks

**Comment by CountryBumkin** [comment]
Try the -ignore-checksum option on Push and Pull commands, more details here https://github.com/odeke-em/drive#verifying-checksums

Regards CB

**Comment by alexiou1977** [comment]
Not working...

~/go/bin/drive push -ignore-checksum VCFs/

**Comment by CountryBumkin** [comment]
The logic is a bit perverse, try something like ....

~/go/bin/drive push -ignore-checksum=false VCFs/

**Comment by alexiou1977** [comment]
Still doesn't work! I don't understand what is happening. It used to work very smoothly up to 2 days ago.

Should I better reinstall el drive?

Thanks CB for your suggestions.

**Comment by CountryBumkin** [comment]
If the software was working and now fails is a different context. To ensure repeatable testing be sure to execute the drive commands from a command prompt in an interactive terminal window, not in a script file with re-directed output and errors to a log file.

If you are using Linux check the exit status after the drive command. eg
 $ drive push -ignore ....
 $ echo $?
0    ! this 0 indicates the previous command was correct,  numbers suggest various errors.

regards CB

**Comment by alexiou1977** [comment]
Yes. I am running the command always in the terminal. One interesting thing is that when I want to see the contents of the remote directory it's telling me that the specified path cannot be found remotely.

```
~/googleDrive/Local_Work$ pwd
/home/kalexiou/googleDrive/Local_Work

~/googleDrive/Local_Work$ /home/kalexiou/go/bin/drive ls
"/googleDrive/Local_Work" cannot be found remotely
```

**Comment by odeke-em** [comment]
Hello @alexiou1977, thank you for the issue and welcome to drive!

Let me try to reproduce this and investigate then fix if necessary.

**Comment by alexiou1977** [comment]
Hi odeke-em,

Any news about my issue?

Regards,
Kostas

**Comment by odeke-em** [comment]
Hello @alexiou1977 thanks for the reminder. My apologies for the late reply, I've been travelling around and also pushing out work related code. However, I was able to reproduce this and I think I have a hunch on what is going wrong. I'll try to work on this in the next 9 hours or better over the weekend.

**Comment by odeke-em** [comment]
@alexiou1977 thank you for the patience and for the advocacy to fix this issue. As promised, I've fixed it with PR https://github.com/odeke-em/drive/pull/941. Please get the latest by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```

Please reopen if symptoms persist!

**Comment by alexiou1977** [comment]
Muchas gracias odeke-em.

-- Konstantinos Alexiou, PhD
Bioinformatician

IRTA
Centre de Recerca en Agrigenòmica (CRAG) CSIC-IRTA-UAB
Campus UAB, Edifici CRAG
08193 Bellaterra (Cerdanyola del Vallès)
Tel: +34 93.563.66.00 ext. 3360

konstantinos.alexiou@cragenomica.es - konstantinos.alexiou@irta.cat

www.cragenomica.es - www.irta.cat


2017-07-24 8:01 GMT+02:00 Emmanuel T Odeke <notifications@github.com>:

**Comment by odeke-em** [comment]
🍻 anytime @alexiou1977, hope that solved your issue.
