### ISSUE TITLE
unexpected string literal, expecting comma or )

### ISSUE THREAD

**Issue by prbhtm** [odeke-em/drive#935]
odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )

**Comment by shaggytwodope** [comment]
Make sure you are running go 1.7 as mentioned in the [readme](https://github.com/odeke-em/drive#requirements). If that is not possible, consider some of the already compiled options. Such as the binary's on the release page. Or some of the packages made for some popular distros.

**Comment by odeke-em** [comment]
Hello there @prbhtm, thank you for the question and welcome to drive!

Yes, in deed, as mentioned by @shaggytwodope, we need at least go1.7 and it is already documented in the README.

Thank you @shaggytwodope.
