### ISSUE TITLE
no way to run the delete command quietly

### ISSUE THREAD

**Issue by ryansinn** [odeke-em/drive#938]
I'd like to run the delete command with a -no-prompt flag, but that is not available so I don't believe there is a way to run deletes (skipping the trash) via a script.

**Comment by ryansinn** [comment]
--quiet 

heh. it's there.

**Comment by odeke-em** [comment]
Hello @ryansinn thanks for the question and welcome to drive!

Cool that you solved it yourself, cheers!

**Comment by ryansinn** [comment]
Thanks for the response!

It would be helpful if the documentation stated what switches are supported for all the commands. 
Sorry, I didn't think to try it before I opened the ticket -- I was already deep into the _other_ ticket issue when I hit a snag with the prompts issued by the delete command when trying to create a solution that would allow the manipulation (specifically for me, the deletion (skipping the trash)) of files on google drive without having to sync the files to the local system (because in my case the files originated from the local system, so they're already there.   Trying to use Google Drives to store server data backups in the cloud -- might be using the wrong solution for the job ;)
