### ISSUE TITLE
pushing a file in a subdirectory goes  nowhere ?

### ISSUE THREAD

**Issue by juanluisbaptiste** [odeke-em/drive#94]
Hi,

I'm not sure if this is a bug or a misunderstanding of drive use, but I have noticed the following behavior:

Afer doing drive init on my home directory, if I push a file on it, it goes ok:

$ cd $HOME
$ drive init
$ drive push file.txt
Resolving...
+ /file.txt
Addition count 1 src: 3.05MB
Proceed with the changes? [Y/n]: y
1 / 1 [=================================================================================================================] 100.00 % 13s
$

If I try to add it again drive will say the file is up to date, perfect. Now this:

$ cd $HOME
$ drive push Documents/file.txt
Resolving...
+ /Documents/file.txt
Addition count 1 src: 3.05MB
Proceed with the changes? [Y/n]: y
1 / 1 [=================================================================================================================] 100.00 % 13s
$

drive list or going to my drive account do not show the uploaded file. Also drive will allow the execution of the previous command multiple times, as if the file wasn't uploaded. So, as there's no error message it seems as if the file was successfully uploaded, but it doesn't appear nowhere. So, where is it ??

If then I init Documents dir and push Documents/file.txt again, the file will be uploaded but to /, not /Documents, how can I make it to be uploaded to the same path or to one of my drive's subdirectories ?

**Comment by odeke-em** [comment]
In deed, you are pushing from two different paths. Think of everything as relative to your root.

**Comment by odeke-em** [comment]
Btw drive init should only be done once per account. From then on you can start organizing your folders and files relative to the root and hitting push or pull. To get you started, I'd implore you to check out the README file.

**Comment by odeke-em** [comment]
Please take a look at the README.md file on how to use drive. Basically, you only init once and then perform operations for files and directories nested inside the root that you ran init it. Otherwise, a fresh init everytime means initializing a new drive.
