### ISSUE TITLE
print error to stderr

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#95]
Sometimes the output is piped for processing. For example, 
$ drive list | grep | wc
$ drive pull -piped | md5

If the error messages are printed to stdout, users are unable to know there is an error.

**Comment by odeke-em** [comment]
Please look at PR #109

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/commit/b8652fe6cbb4efdc0def25d587c74a0afaff5c8c.
Reopen if persists.
