### ISSUE TITLE
excluding directories

### ISSUE THREAD

**Issue by tigerjack** [odeke-em/drive#950]
`foo/.*/git/`

In my drive ignore I'm using the regex above to exclude all the `git` directories inside the `foo` directory or any subdirectory.  The `git` directories should only be available offline

So, the offine directory structure should be something like
```
foo/
├── git
│   ├── drive
├── bar
```

while online I'd like to have something like

```
foo/
├── bar
```

However, whenever I try to push the whole `foo` directory, it tries to also push the `git` directory online. Obviously, it will not push any subdirectory (such as `drive`) or file inside the `git` directory, basically creating an empty `git` directory online.

The same applies when I want to push a directory which has subdirectories which should be only available online.  The problem in this case is even worse. Using the previous example, suppose instead that the `git` directory is only online, while I don't have any subidrectory named `git` inside `foo`.
When I try to execute `drive push foo`, it will ask me to delete any `git` directory online.

I haven't found any clear workaround so far. I've tried to modify the regex in many way: 

- `foo/.*/git`; however, in this case a lot of stuffs will be excluded also
- `foo/.*/git($|/.)`; however, in this case it will exclude every file named git.

To me, the only solution is to try to append a `/` to each directory identified by `drive`, but maybe I'm missing some obvious regex.

**Comment by odeke-em** [comment]
@tigerjack thank you for the question and welcome to drive! My apologies for the late reply, I've been swamped.

So there is something called a `.driveignore` file in which you can specify patterns to include or exclude, please see https://github.com/odeke-em/drive#excluding-and-including-objects. Each directory can have its own .driveignore file up until the root's .driveignore.

Hope this helps.

**Comment by odeke-em** [comment]
I'll close this issue, as I've answered it and there a bunch of more question based issues, but please feel free to reopen or reach out in case of questions or clarifications. Thank you for taking the time to ask the question and for using drive!
