### ISSUE TITLE
Duplicated folders when pushing

### ISSUE THREAD

**Issue by manugutito** [odeke-em/drive#957]
Hi,

I just installed drive 0.3.9.1 from the gentoo repository and it works quite nicely, so congrats! I started slowly with small folders and so on and it was working perfectly, but when I pushed a big folder (some 4G) with a lot of subfolders and small files in it, duplicated folders were created in Google side (up to 5 or 6 folders with the same name), the content of the original folder scattered all over them.

For now I erased it and I am doing the big initial upload through other means, and I guess when the changes are small this will not pop up anymore, but I think it is important anyway.

**Comment by camgoeswild** [comment]
I'm having the same issue (also with 0.3.9.1) on an Ubuntu Server machine.

**Comment by onionsbub** [comment]
I have the same issue (also on 0.3.9.1) on an Ubuntu Server machine. Although for me it happens with fairly small folders (less than 4G) as well.

**Comment by manugutito** [comment]
Yes, I forgot to add that it's been happening with every push since then, as long as there is a folder being pushed. I guess this is more of a problem because GDrive supports having folders/files with the same name in the first place (???).

**Comment by jhcsu** [comment]
I think this is a repeat of Issue #951.

The workaround mentioned in Issue #951 has worked consistently for me (using the ```-depth``` option). Unfortunately it is challenging to code the workaround programmatically.

**Comment by manugutito** [comment]
Hello NesbiDevelopment,

In my case that does not happen, the numbers are exactly the same.

**Comment by jh2858** [comment]
No special characters required for this to happen for me.  Here's a really simple way to demonstrate the problem.

```
> mkdir -p a
> mkdir -p a/b
> touch a/b/c.txt
> drive push a
Resolving...
+ /a
+ /a/b
+ /a/b/c.txt
Addition count 3
Proceed with the changes? [Y/n]:
```
All seems to go well, but then let's go to Google Drive and see what is in folder ```a```.  There are two copies of ```b```!  (Only the first copy contains ```c.txt```, by the way.)

![folder](https://user-images.githubusercontent.com/1117252/33898060-84c0c472-df24-11e7-956e-4bb7a8f7fcbe.png)

**Comment by oliva5** [comment]
I have the same problem. Every time I try to push a new folder, I get duplicated folders. Some of them are empty, others have individual files. I don't have any strange characters in their name. After that I am unable to pull the changes due to clashes and I have to fix them manually.

**Comment by odeke-em** [comment]
Hello there @manugutito, thank you for creating this issue. Welcome to drive, to you, @onionsbub, @jhcsu, @NesbiDevelopment, @jh2858 and @oliva5!

Firstly my apologies for the really late reply, I have been very swamped with work and life.

So there is a similar issue https://github.com/odeke-em/drive/issues/951 which was filed after this one, but perhaps might have more discussions on there, please feel free to migrate there.
