### ISSUE TITLE
How to init over SSH on an ubuntu server ?

### ISSUE THREAD

**Issue by bin31** [odeke-em/drive#963]
Hello,

I followed the wiki : drive init ~/gdrive but the script is waiting for the authorization code. 

1/ I don't know how to specify the account I want to access. Is it default to the user i am using in Ubuntu or else ?

2/ I think I should get a window and i don't for good reasons i ignore (i am not a software specialist). I am sharing the display of a XFCE desktop with vnc.

Any help appreciated.

**Comment by ryan-hallman** [comment]
The script gives you a link to paste into your browser. If you don't get that, you should check your firewall rules. If you do get it, paste it into the browser, sign in to the Google account that you want to use and then it'll create a code that you paste back into the terminal window.

**Comment by bin31** [comment]
I got in between but on a server, i would like to avoid that copy paste in the browser. Is there any way to make this by script ?

**Comment by chevillet** [comment]
Not to my knowledge but this has more to do with the way Google handles permissions (https://myaccount.google.com/permissions) than drive.
Of course, you could automate the whole process emulating browser interactions with Google to authorize drive on your account but it would not be easy.

**Comment by odeke-em** [comment]
Hello there @bin31, thank you for the question and welcome to drive! Also thank you @ryan-hallman and @chevillet for the answers. My apologies for the late reply, I've been swamped.

So @bin31, I've done this countless times and I don't think it should be hard or inconvenient:
a) you can authorize the code on any computer and move it to where, for example you can initialize it on your local computer with the GUI and then move the token to the remote server
b) or even simpler you can init on the remote server while SSH'd, copy the authorization URL to your local computer with the UI, authorize then just copy the code into the terminal of your remote server.

Please try it out. I'll close this question, please feel free to reopen if symptoms persist.
