### ISSUE TITLE
'drive list file' prints wrong name

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#97]
How to reproduce:
```
$ echo foo | drive push -piped a/b.txt
$ drive list a/b.txt
/a/b.txt/b.txt
```
`/a/b.txt` is expected

**Comment by odeke-em** [comment]
Yap I noticed that too.

**Comment by odeke-em** [comment]
Addressed by https://github.com/odeke-em/drive/commit/a1255dc850b05e6e41eecb709aa689977d19bb25. Reopen if persists.

**Comment by kcwu** [comment]
according to the drive_test.py
```
echo "foobar" | drive push -piped a/b/c.txt
drive list -no-prompt a/b/c.txt
[expected] ['/a/b/c.txt']
[actual] ['/c.txt']
failed
```

**Comment by odeke-em** [comment]
Reopening this.

**Comment by odeke-em** [comment]
Take a look at https://github.com/odeke-em/drive/commit/e667aa254efcbcd240c3341e558015ef5ffeb6ad
