### ISSUE TITLE
any plan to support team drive?

### ISSUE THREAD

**Issue by fordarm** [odeke-em/drive#971]
Hi,

thank you for your good utiliy.
Do you have plan to support google team drive function on drive?
Aactually rclone supports it but can't mount on system.
I would like to mount team drive on my system. 
Please support team drive.

**Comment by chevillet** [comment]
Hi! It's just a proposal for now but please see this feature request: https://github.com/odeke-em/drive/issues/913

**Comment by odeke-em** [comment]
Hello @fordarm, thank you for the request and welcome to drive! My apologies for the late reply, I hadn't seen this notification and I've been swamped.

Awesome, thank you @chevillet for reporting the duplicate, in deed it is.
