### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by nk932714** [odeke-em/drive#973]
Unable to deploy on heroku

**heroku Logs**

-----> Go app detected

-----> Fetching jq... done

 !!    

 !!    'GOVERSION' isn't set, defaulting to 'go1.9.2'

 !!    

 !!    Run 'heroku config:set GOVERSION=goX.Y' to set the Go version to use

 !!    for future builds

 !!    

-----> Installing go1.9.2

-----> Fetching go1.9.2.linux-amd64.tar.gz... done

-----> Fetching errors-0.8.0.tar.gz... done

-----> Fetching gb-0.4.4.tar.gz... done

-----> Installing GB v0.4.4... done

-----> Running: gb build -tags heroku

FATAL: command "build" failed: failed to resolve import path "dcrypto": import "github.com/odeke-em/drive/src/dcrypto/v1": not found: stat /tmp/build_5094bd3a1f7ea33568d12310d7041b92/nk932714-drive-0b501d3/src/github.com/odeke-em/drive/src/dcrypto/v1: no such file or directory

 !     Push rejected, failed to compile Go app.

 !     Push failed

**Comment by odeke-em** [comment]
Hello there @nk932714, thank you for the question and welcome to drive!

My biggest apologies for the really late reply, I have been swamped with work.

So to deploy to Heroku, one needs to vendor the dependencies, please take a look at https://devcenter.heroku.com/articles/deploying-go. An easier alternative though is to just deploy a Linux binary. Every release comes with binaries https://github.com/odeke-em/drive/releases
 and you can also build them on your own computer https://github.com/odeke-em/drive/blob/master/Makefile
```shell
make linux
```

I am going to close this question as the solutions seem to either be dependency addition or deployment of the binaries. Please feel free to reopen if there is something else that we can do.

**Comment by nk932714** [comment]
Thanks a lot for info @odeke-em
