### ISSUE TITLE
Way to push only a diff?

### ISSUE THREAD

**Issue by riley-martine** [odeke-em/drive#980]
I have a lot of small files and want to perform functions on them, like adding a line to the end of each or deleting the last character. Is there a way to do this that doesn't require downloading the file, editing, and pushing?

**Comment by odeke-em** [comment]
Hello @riley-martine, thank you for the question and welcome to drive!

Unfortunately the Google Drive API doesn't provide for a way to do this so unfortunately this isn't a feature that we can implement easily :(

**Comment by odeke-em** [comment]
I'll go ahead and close this as there isn't  away that the Drive API remotely will accept diffs.
