### ISSUE TITLE
Fix driveignore samples

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#99]
Since the pattern is matched using regex. Suggest to change the samples in readme and release note from something
```
.gd
.so
.swp
```
to
```
\.gd
\.so
\.swp
```
or even
```
^\.gd$
\.so$
\.swp$
```

Otherwise
```
touch awesome
drive push
```
has nothing to push

**Comment by odeke-em** [comment]
Ahaha, funny thing is I could have just copied my own .driveignore file. Did you want to submit a PR for master? I'll update the release notes.

**Comment by odeke-em** [comment]
Updated the release notes.

**Comment by kcwu** [comment]
Time to sleep for me. I can submit a PR tomorrow if you didn't.

**Comment by odeke-em** [comment]
Aye aye, I could add it but I'll wait for yours since I'd like to have you mentioned as a contributor in the graphs.
