### ISSUE TITLE
main.go:33: syntax error: unexpected string literal, expecting comma or )

### ISSUE THREAD

**Issue by iblacksand** [odeke-em/drive#991]
When running `go get -u github.com/odeke-em/drive/drive-google`, I encountered the error
```bash
go/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )
```
Was I doing something wrong or is the source broken?

**Comment by CaffeineDreams** [comment]
Yep I'm getting this too. The package in the shaggytwodope repo installs fine on Ubuntu, but this installs version 0.3.9.1, and I'd very much like 0.4 so I can use the service account feature. Unfortunately, I've never worked in golang so I have no idea where to start debugging. Looking at the build log, I'm wondering whether it's related to this behaviour: https://github.com/golang/dep/issues/1140

If so then the CI config needs updating to use a go version > 1.8, it's currently set to 1.7
