### ISSUE TITLE
SSH access

### ISSUE THREAD

**Issue by gavox** [odeke-em/drive#996]
Currently drive works by using https. Due to some strange configuration of the router of my office I am not able to connect. I get the answer: 

`Get https://www.googleapis.com/drive/v2/files?alt=json&q=%22root%22+in+parents+and+title+%3D+%2210_TEST%22+and+trashed%3Dfalse: Post https://accounts.google.com/o/oauth2/token: http: error connecting to proxy https://persefone.utadeo.edu.co:8080/: dial tcp 10.10.0.95:8080: getsockopt: connection refused`

I have a similar situation with connecting to bitbucket through mercurial. There I solved the issue using ssh. There my configuration file is something like: 

```
[paths]
default = ssh://gavox@bitbucket.org/gavox/modelosconflicto
```

Is there something similar here?

Thanks!

**Comment by idvoretskyi** [comment]
@gavox unfortunately, SSH protocol is not supported by Google Drive API, which is used by `drive`, therefore it's not possible.

cc @odeke-em

**Comment by gavox** [comment]
Thanks!

**Comment by odeke-em** [comment]
Hello @gavox, thank you for the question and welcome to drive! Thank you @idvoretskyi for answering the question.

In deed, what @idvoretskyi said. However, if you'd like to use drive on a server that you connect to via SSH, you'd still have to SSH onto your server, and then set up drive via the commandline e.g https://github.com/odeke-em/drive/issues/963#issuecomment-343334482.

I'll close this question as @idvoretskyi answered it. Thank you again.
